### ISSUE TITLE
"Copy image" intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1007]
This intent would find the "best" image on the page, and copy it. Probably the image that is visible in the viewport (50%) that has the largest area.

**Comment by JanviMahajan14** [comment]
i would like to work on this issue.

**Comment by ianb** [comment]
You got it! Setting up the intent will go in `clipboard.js`, but finding the image, selecting it, and copying it will happen in `extension/intents/clipboard/contentScript.js`

**Comment by JanviMahajan14** [comment]
@ianb Can you tell me how can i choose the best image from the page i am really struck here
This is the approach i am using in contentScript.js
```
  types.copyImageLink = function() {
    const img = document.querySelectorAll("img");
    const imgArr = Array.from(img);
    const url = imgArr.filter((e) => {
      const bounding = e.getBoundingClientRect();
      return bounding.height > 50;
    });
    copyImage(url[0].src);
  };
```
But it always fetches the first img on the page
