### ISSUE TITLE
Add docs/testplan.md

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#101]
This was something I found useful for a handful of Shield studies back in the day...
But if the engineering team can come up with a baseline number of manual tests that they want performed for the add-on to make sure the flows are tested (and helps QA quickly jump in and know what features need testing):

I did manage to extract these from the PI request:

- Ensure add-on loads properly.
- Mic activates when triggered (button press or keyboard shortcut)
- UX unfolds as designed.
  - Doorhanger/popup UI visualizes audio being captured, processing, and success or error states.
  - Spoken audio displayed within UI
  - Appropriate actions is executed (load new page, find tab, mute, etc)
- Pressing feedback buttons from last request sends ping to telemetry

But I don't know if there are any other features that need testing.

**Comment by ianb** [comment]
@alexandra-martin has [created one in TestRail](https://testrail.stage.mozaws.net/index.php?/suites/view/5678&group_by=cases:section_id&group_id=56036&group_order=asc) (note: only visible to Mozilla employees).
