### ISSUE TITLE
[Mobile] Transcription of utterance not displayed

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1017]
On the latest version the Mozilla Assistant app a transcription of the utterance is no longer displayed before switched to the Firefox browser. This used to be visible before processing to make it clear to the user what the app heard.

**Comment by awallin** [comment]
![Transcript](https://user-images.githubusercontent.com/428245/74859743-5df82080-52fc-11ea-9fee-2555c8cb8e59.jpg)

**Comment by espertus** [comment]
Fixed.

**Comment by alexandra-martin** [comment]
Verified on Android 10 with Mozilla Assistant version 1.0 and Add-on version 0.19.4034. 

![20200221_103418](https://user-images.githubusercontent.com/54401091/75018342-63d63900-5497-11ea-8ada-5cfe2ce7505d.gif)
