### ISSUE TITLE
Add cancel/nevermind intents

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#104]
If you just say "cancel" right now it searches for cancel.

* Cancel
* ~Stop~
* Nevermind

**Comment by awallin** [comment]
There may be conflicts around "stop" (maybe "cancel") when playing media. E.g. does the user mean "stop playing the audio" or asking the assistant to stop trying to fulfill the request.

**Comment by jcambre** [comment]
I'm also inclined to put this into the UI (e.g. cancelling upon ESC, clicking an X button, dismissing the popup)

**Comment by ianb** [comment]
Agreed, stop is problematic, and probably shouldn't be on this list. But searching for cancel is definitely the wrong thing! Searching for "this is a test" is also probably the wrong thing (since I've been doing that a lot too ;)

**Comment by ianb** [comment]
It would be nice if "cancel" could stop narration as well. Maybe we should add this to the intent API.
