### ISSUE TITLE
Provide a channel for general feedback

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#105]
We should have some way for people to provide general feedback, like an email address, Discourse forum, pointing them to GitHub issues...

**Comment by pdehaan** [comment]
+1 to a link GitHub repo/issues so we can capture as much as possible in one place.

Not sure the best way to capture feedback from _non-dev_ types which may not have a GitHub account (and would be less likely to register just to give a bug report; I know I've passed on filing bugs in the past if it required me to use GitLab or Jira or something I didn't already have an account for).
Maybe some sort of survey feedback URL is pretty low friction, and then somebody has to monitor that channel and manually move the issues into GitHub.

**Comment by awallin** [comment]
In the design I spec'd a feature to collect feedback on the most recent request with a smily/frown face (once clicked it would allow text input).

We may want a more general feedback mechanism. In this case I agree with @pdehaan a lower friction collection tool such as a survey will help non-technical users provide feedback. We could add a "Feedback" link to the settings panel with a link to a survey. Firefox Private VPN is doing that with their initial rollout.

<img width="321" alt="Screen Shot 2019-08-14 at 11 22 29 AM" src="https://user-images.githubusercontent.com/428245/63045789-ee553480-be85-11e9-9a1f-3b3a48810137.png">

**Comment by awallin** [comment]
Added mock ups for feedback to Abstract.
@harraton we should put together a survey to collect open ended feedback from pilot participants.

**Comment by harraton** [comment]
Will do. I was planning on emailing surveys out, but we should figure how
when we want to do that, and when we want people to go through the feedback
link.


Janice

**Comment by awallin** [comment]
This particular feature let's users submit feedback at any point. We should have a regular prompt for feedback (via email) but I think that's separate and probably only relevant for the initial small internal releases.

**Comment by harraton** [comment]
Created a survey to put in the Settings page for feedback:
https://qsurvey.mozilla.com/s3/firefoxvoice-feedback

**Comment by awallin** [comment]
Looks good @harraton. Closing the work to include a link in-product is part of #177.
