### ISSUE TITLE
Use URL cleaner for pageMetadata

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1059]
[Neat URL](https://github.com/Smile4ever/Neat-URL) is an extension, but presumably it has some bits of code (probably [this function](https://github.com/Smile4ever/Neat-URL/blob/master/background.js#L456-L590)) we can use to just to do cleaning. We could add that to pageMetadata.

**Comment by annlinros** [comment]
Hi @ianb I would like to work on this issue.

**Comment by ianb** [comment]
@annlinros Sure! I noticed the extension is based on [Lean URL](https://github.com/tugh/lean-url) which might be simpler to work from.
