### ISSUE TITLE
Settings page should try to acquire microphone

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1074]
Because the recorder page is gone, the settings page is now the way that we should expect people to change their microphone settings. But since we don't ask for microphone permission, you can remove but not add microphone permissions.

If we ask for the microphone (but don't record) it should put up a permission prompt.

**Comment by awallin** [comment]
Should we have a link in the settings page to change mic permissions which would open a new page that tried to acquire microphone permissions and displayed instructions? That way we don't need mic permissions every time settings is opened.

**Comment by ianb** [comment]
If they already given the permissions that are required then the settings page should be able to get the mic permission without any problem. It's only if they've removed the permission and reload that it will pop up the permission prompt.

**Comment by ianb** [comment]
We're going to make a link to the onboarding page from the settings page, and that should handle that. That redesign will come in a later bug.
