### ISSUE TITLE
Design onboarding microphone permission notices

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#108]
This is mostly just a placeholder, but it's really prominent and annoys me and I don't want it to be the placeholder anymore:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/44390/63047188-e99e7980-bea1-11e9-9f42-2203bfd876b8.png">

**Comment by pdehaan** [comment]
Related:
- #87; _"The close button in the success instruction box overlaps content at certain page widths"_
- #88; _"security-button.png extension img in success instruction block causes line breaks in UI"_

**Comment by ianb** [comment]
The states we have:

* Success (microphone acquired)
* Pending (we've asked for the microphone, the user hasn't said yes or no)
* Permission denied: we need to instruct the user on how to fix the permission
* Generic error: ? Something went wrong, probably the user should reload

**Comment by awallin** [comment]
Closing as duplicate as a design for permissions and errors is included in #505
