### ISSUE TITLE
Submit form intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1083]
The submit form intent might simulate an Enter key, or could try to find the most plausible form to submit and call `.submit()` (though Enter would be better).

Should match at least `submit (form |)`, but maybe there's other phrases too.

This would be a new intent in `forms.js`

**Comment by Manasa2850** [comment]
I want to work on this

**Comment by ianb** [comment]
You got it!

**Comment by Manasa2850** [comment]
@ianb how do I reproduce this in my browser?
I'm not quite sure how to view the form intent in my browser

**Comment by ianb** [comment]
I'd recommend finding a few forms on the web and testing them. The search form on github.com is one:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/44390/75892526-1642c000-5df7-11ea-928c-42b824174284.png">

This comment form might also be a good example, as Enter _won't_ work here.

You'll probably want to look at `document.activeElement` and then identify the form based on that (probably `document.activeElement.form` though you should probably fall back to looking through parentNodes, as not every active element will have that `.form` attribute)

**Comment by Manasa2850** [comment]
Ok. I'll try this out. Thanks!
