### ISSUE TITLE
Intent: Collect tabs

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1086]
Maybe the simplest form would be "collect these tabs" which would get all tabs from the same domain and cluster them around the current tab. E.g., if I ran it right now it would take every github.com tab and move it around here (since I'm on the last tab, they would all be immediately before my active tab).

An extended form would be "collect all [query] tabs" which would do a search for the query and cluster all the matching tabs similarly. If the current tab wasn't matching, then it would... choose the best tab and also focus it...?

Finally "collect all tabs" would just rearrange all tabs according to domain (maybe sort by URL?).

And finally-finally, "collect all tabs in all windows" (or anything "in all windows") would grab tabs regardless of window.

**Comment by ianb** [comment]
This is actually a good **second** issue, as it's a little more involved than some of the other good first issues.

This should go in `tabs.js`

**Comment by danielamormocea** [comment]
If it's up for grabs, i'll take it, please :)

**Comment by SaumyaSinghal** [comment]
Hello @ianb  , I'll like to take up this issue if no one is working on it.

**Comment by ianb** [comment]
I guess I'll assign this to @danielamormocea ... 

We're running out of first issues, so I'm going to start checking in and removing assignments from some of the other issues

**Comment by danielamormocea** [comment]
Hello @ianb. I have a question regarding 'collect [query] tabs in all windows'. So I understood that if the current active tab does not match the query I should focus on a tab that does match it. Now, what if the current window does not have any tab that matches the query? Should I change the window to a tab that matches it?

**Comment by danielamormocea** [comment]
I made a PR with changing the focus to a different window if there is no tab in the current window that satisfies the query, and there is one in the other window. I can change this if this is not the expected behavior.

**Comment by ianb** [comment]
@danielamormocea I hadn't thought particularly about how it should act in that case, but that sounds like a reasonable choice to me.
