### ISSUE TITLE
Open narration UI in read intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#110]
Right now we don't open the UI for the narration in Reader Mode, so it might not be obvious that there are controls there:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/44390/63048335-53b81e00-bea4-11e9-9d76-2e109b2c91a2.png">

**Comment by awallin** [comment]
Yea, I noticed this in user testing. The user has no context for where controls are. Opening the menu would be nice.
