### ISSUE TITLE
Intent: close selected tabs

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1101]
To trace my thought process: I imagined a query "close [query] tabs", e.g., "close github tabs". It would do a search, probably only against the URL and title (not content, i.e., not the same as find.js), and then close those tabs. But closing all those tabs probably requires confirmation, and we don't have a pattern for that – including how to present the action, or adjust it.

Instead we could use the concept of selected tabs (partially exposed in Firefox, but easier to access through an extension). We could use "select [query] tabs" (or maybe "collect" as in #1086), and then "close selected tabs". The concept for "collect" both selects the tabs and collects them for easier review (a selected tab that's not visible in the tab bar is hard to review).

**Comment by dave-ok** [comment]
@ianb Can I look into this?

**Comment by dave-ok** [comment]
@ianb I have created this intent in pull request #1183. Could you please review it?
