### ISSUE TITLE
Intent: combine all windows

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1103]
This would move all tabs from other windows into the current window.

Suggested phrase: 

```
combine all windows (into |) (one |) (window |)
combine tabs (into |) (one |) window
```

**Comment by km-js** [comment]
Being an outreachy aspirant, I would like to work on this.

**Comment by ianb** [comment]
@km-js Are you still working on this? If it's not working out I'd like to open this back up for other contributors

**Comment by fleur101** [comment]
Hello, @ianb. I am an Outreachy applicant, may I work on this issue if it is unassigned?
