### ISSUE TITLE
Intent: turn selection into link

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1109]
This would take the current selection and turn it into a link. If the selection is in a contenteditable then it will be a proper HTML link, otherwise a Markdown link.

The link would be calculated first by looking at the other open tabs, and then if nothing matched it would be a Google I'm Lucky search.

**Comment by JanviMahajan14** [comment]
@ianb I found this  issue really interesting. Can I give it a try?

**Comment by ianb** [comment]
@JanviMahajan14 Sure! This will be somewhat challenging, I'm not sure the best way to actually do all the steps, but here's what I think it will look like:

To try to resolve the link, I might suggest opening with `createTabGoogleLucky()` and hiding the tab (there's no option to hide the tab, so you'd have to change that function some (`openSearchTab()` in `search.js` is an example of hiding). Once you've fetched it you can use `pageMetadata` to get the URL and title. I'd put the URL and title in the popup so the user gets an idea what the link resolved to.

To both get the text and to edit the link in the page you'll use the [selection](https://developer.mozilla.org/en-US/docs/Web/API/Selection) APIs. If it's a `<textarea>` I think we can default to a Markdown link, but if it's inside `contenteditable` (which means some parent of the selection `.hasAttribute("contenteditable")`) then you'll need to replace the selection, maybe with [something like this](https://stackoverflow.com/a/3997896).

**Comment by JanviMahajan14** [comment]
@ianb i am not sure in which form i can check this implementation. Also I want to know as you suggested forms.js is a good place for the indent to live So are we restricting the implementation in forms only

**Comment by ianb** [comment]
@JanviMahajan14 It doesn't just have to be forms, I just thought this would be a good place to put the implementation. It has to be an editable field of some sort for this to work after all.

But I did expect for it to only work with `<textarea>` and `<* contenteditable=true>`

**Comment by JanviMahajan14** [comment]
Ok thanks ! Now I got it.

**Comment by JanviMahajan14** [comment]
@ianb i am not getting how can hide the tab . I am doing 
` const newTab = await context.createTabGoogleLucky(selection.text);
   const url = newTab.url;`
to get the required url that will turn the selection to link. But this always creates a new tab. Is there any way to resolve this.

**Comment by ianb** [comment]
@JanviMahajan14 For hiding the tab you'll have to make a change like:

```js
  async createTabGoogleLucky(query, options = {}) {
    const searchUrl = searching.googleSearchUrl(query, true);
    const tab = await this.createTab({ url: searchUrl });
    if (options.hide && !buildSettings.android) {
      await browser.tabs.hide(tab.id);
    }
```

You use use `pageMetadata.getMetadata` on the new tab, or you could just use `tab.url`. I think either is fine in this case – `getMetadata` sometimes gets a cleaner link, but with an I'm Lucky search you should get a clean link from Google anyway.
