### ISSUE TITLE
Intent: what's playing

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1111]
This would look at the tab currently making sound, and maybe give its title, or a screenshot, or... something.

Question: does Spotify and other services set the title based on the currently playing song? If not we might have to add something to the services framework to get the currently playing item. We should still fall back to title and/or screenshot.

You can use `browser.tabs.query()` to find the tab(s) that are making sound.

**Comment by AemieJ** [comment]
I have worked with extensions before and I know how to get the metadata of the current tab making sound and receiving the screenshot of the page as well, however I am having difficulty figuring out the structure. 

Could you tell me from which file to edit so I could try my best to make the changes?

**Comment by awuorm** [comment]
@ianb I am an outreachy applicant, can I have this issue assigned to me?

**Comment by ianb** [comment]
@AemieJ: I guess I'll assign this to you since you were first. 

This document should cover a bunch of it: https://github.com/mozilla/firefox-voice/blob/master/docs/writing-an-intent.md – this intent would go in `intents/music/music.js`

**Comment by annlinros** [comment]
I have made a PR #1177 
Is that ok?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-10).

![10](https://user-images.githubusercontent.com/54401091/76317927-9d0b0780-62e5-11ea-995b-102725d34f54.gif)
