### ISSUE TITLE
Intent: paste to notes

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1113]
This would go with the other note-taking intents, and would just paste whatever happened to be in the clipboard. Mostly it would just call `document.execCommand("paste")` once the field was focused.

**Comment by ianb** [comment]
For this you'll want to look in `notes.js` and create a new intent, very similar to the other intents.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-09).

![8](https://user-images.githubusercontent.com/54401091/76313540-cfb10200-62dd-11ea-9666-d3232e9b7fe9.gif)
