### ISSUE TITLE
Intent: start slideshow

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1115]
This would try to find images and/or videos on the page that would be suitable for a slideshow.

This extension might offer some inspiration: [Slideshow](https://addons.mozilla.org/en-US/firefox/addon/media-slideshow/)

**Comment by dave-ok** [comment]
@ianb I currently have 1 PR up for review, but can I be assigned to this task?

**Comment by ianb** [comment]
@dave-ok Sure. I honestly don't know how this should work, like how you'll decide on the contents of the slideshow given a page. So... give it a try, and if you can't figure something out report back.

**Comment by dave-ok** [comment]
Thanks. I will let you know how I plan to handle this before I proceed

**Comment by dave-ok** [comment]
@ianb Is it okay if I used a third party slideshow component (bootstrap/jquery)? I was thinking something like a lightbox gallery.

**Comment by ianb** [comment]
@dave-ok I'm reluctant to bring in something too big for this, though this could be a new directory in `extension/intents/slideshow/` to keep things separated. If there's something fairly small with a clear license, then yes, but all of Bootstrap seems like too much.

**Comment by dave-ok** [comment]
@ianb I have made a draft PR #1305 towards this. Please, do check it out. Though, I suspect the slideshow might need some further styling
