### ISSUE TITLE
[browser command] Add print intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#112]
It would open up the print dialog.

It's easy because [it's already an API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/print)

**Comment by awallin** [comment]
Be nice if you could say "Print" a second time to execute from the dialog box.

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. I will submit a PR ASAP.

**Comment by ianb** [comment]
Closed in #474
