### ISSUE TITLE
Link README to a demo video

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1124]
People who happen upon the github page might want to know how it works, and I think a demo video is the easiest way to show it.

@awallin: what's the best video right now?

**Comment by awallin** [comment]
Either the Berlin or Snow Trip videos.

* https://drive.google.com/open?id=1-OkvlRBQPBp4nQQrkBb_y8lSkzLefPzU
* https://www.youtube.com/watch?v=3sqKsfj8WRE&feature=emb_title
