### ISSUE TITLE
Minified tailwind.min.css file is 537KB

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#113]
```sh
$ git rev-parse --short HEAD # a6fc5c7
```

Spotted in #94. 

```
$ ls -lash extension/css/vendor/tailwind.min.css
537K    extension/css/vendor/tailwind.min.css
```

Looking through https://tailwindcss.com/docs/installation/, I spotted this gem (emphasis mine):

> Note that while the CDN build is large (27kb compressed, 348kb raw), it's not representative of the sizes you see when including Tailwind as part of your build process.
>
> Sites that follow our best practices are almost always under 10kb compressed. **For example, Firefox Send is built with Tailwind and their CSS is under 4kb compressed and minified.**

And here is the [**mozilla/send** tailwind.config.js](https://github.com/mozilla/send/blob/master/tailwind.config.js) file.

**Comment by ianb** [comment]
This has been removed
