### ISSUE TITLE
Bookmark intent sheet does not contain step to remove bookmark

### ISSUE THREAD

**Issue by GangaChatrvedi** [mozilla/firefox-voice#1132]
In addition to creation and opening of bookmark. Removing bookmark from current page will be good add-on feature.

**Comment by GangaChatrvedi** [comment]
I would like to work on this feature.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-09). 
Everything seems fine, but it can be good idea if both plural and singular form for "bookmark" can be added in the phrases, in case the command transcription is displaying examples like "remove bookmarks from page", "delete page from bookmark". 

![bookmark remove](https://user-images.githubusercontent.com/54401091/76309954-88734300-62d6-11ea-939f-15ec29443cef.png)

![bookmark remove 2](https://user-images.githubusercontent.com/54401091/76309958-8ad59d00-62d6-11ea-9f5a-2bd26b3cc109.png)

![4](https://user-images.githubusercontent.com/54401091/76309250-151d0180-62d5-11ea-8594-3f6a0839f66d.gif)

**Comment by alexandra-martin** [comment]
@GangaChatrvedi thanks for the follow-up.
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-11).

![12](https://user-images.githubusercontent.com/54401091/76507308-415f8c00-6455-11ea-9aa0-f1c0379cd060.gif)
