### ISSUE TITLE
[wakeword] investigate downsampler errors

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1135]
I'm getting errors like:

```
TypeError: can't access property "postMessage", downsampler is undefined 2 web_voice_processor.js:39:9
```

This appears to break the wakeword handling.

**Comment by Simpcyclassy** [comment]
@ianb Can I investigate this please?

**Comment by ianb** [comment]
@Simpcyclassy It looks like you have several issues now, so leaving this for now.

**Comment by Simpcyclassy** [comment]
OK, that's fine.

**Comment by ianb** [comment]
No longer applicable since we removed the underlying library.
