### ISSUE TITLE
Smile/Frown icon appears white on hover

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1140]
When hovering the smile or frown in feedback the icon appears white.

<img width="649" alt="Screen Shot 2020-03-02 at 1 49 48 PM" src="https://user-images.githubusercontent.com/428245/75721216-d8298d00-5c8c-11ea-800f-22e2d874421a.png">

**Comment by Emmanuella-Aninye** [comment]
Is this an open issue to be picked up?

**Comment by pachicodes** [comment]
@ianb can I have this? I am an Outreachy applicant!

**Comment by awallin** [comment]
@Emmanuella-Aninye @pachicodes Yes, this is an open issue if either of you would like to work on it?

**Comment by pachicodes** [comment]
@awallin I would like too

**Comment by awallin** [comment]
Go for it @pachicodes. I realize I provided @ianb with the wrong icons when he made the change in #779 so it's probably as simple as replacing the hover icons with the updates I've attached here.

[smile-icons.zip](https://github.com/mozilla/firefox-voice/files/4294197/smile-icons.zip)

**Comment by treasurechristain** [comment]
@awallin i would like to work on it also

**Comment by Vidwita** [comment]
Can I also work on this @awallin  ?

**Comment by lelouchB** [comment]
@awallin Please take a look at #1162

**Comment by ianb** [comment]
Sorry @Vidwita @treasurechristain @pachicodes – lots of activity here and I haven't been able to keep track of it.

Note though if you do fix a bug and it was already taken or closed, please submit a PR anyway, I'm happy to take account of any contributions even if they were duplicated.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-09).

![1](https://user-images.githubusercontent.com/54401091/76296671-3246d580-62bf-11ea-9ec4-d6dcef4de231.gif)
