### ISSUE TITLE
Make format linting part of tests

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1144]
With more PRs coming in, it might be nice to make these part of the tests.

`prettier --check` doesn't actually return with a non-zero code. There's [prettylint](https://github.com/ikatyang/prettylint).

One nuisance is that anything that's not in git shouldn't be linted. But .prettierignore has a couple files in source control that shouldn't be linted either. Maybe we should just add `// prettier-ignore` to those two files (voiceSchema.js and catcherAsyncSetup.js).

**Comment by lelouchB** [comment]
I want to work on this issue

**Comment by lelouchB** [comment]
@ianb I had a question, after integrating prettylint, what should be done with prettier??

**Comment by lelouchB** [comment]
@ianb I have made a PR #1161 
Please have a look
Also tell me if to fix the prettier linting during tests????

**Comment by dave-ok** [comment]
@ianb is it ok if I work on this I have been at it all day

**Comment by ianb** [comment]
@dave-ok Sure, I won't be able to merge both, but both PRs can count as part of your applications.

**Comment by lelouchB** [comment]
@ianb  Have done the necessary changes
Please Have a Look
