### ISSUE TITLE
Design what "play X on youtube" should do when the result is a channel

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#115]
For example, you might end up on [this channel page](https://www.youtube.com/channel/UCt9nYeSz90lnOnaVFjxFJzw) (in response to "play nick eh 30 on youtube"). The user has specifically asked to *play* something, so it seems like we should attempt to actually play something. What?

**Comment by awallin** [comment]
The ideal behavior would be to play the most recent uploaded video. Not sure if that's possible? Feels like that would be a users expected behavior for a musician, TV show, or other video channel.

**Comment by jofish** [comment]
Youtube provides for a “featured video” for any given channel, and I suspect that’s what we should autoplay.

**Comment by ianb** [comment]
Not every channel has a featured video, but maybe "play all" is a good fallback if it doesn't.

**Comment by ianb** [comment]
I think given our priorities, we can call the current functionality "good enough".
