### ISSUE TITLE
Document examples, npm run jest, phrase testing

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1158]
Using examples and `npm run jest` to test those examples is helpful for creating intents. But it's not documented! This could probably go in the Writing An Intent document.

**Comment by lelouchB** [comment]
HI I am an Outreachy Applicant
Can I work on this ???

**Comment by Apiyo4** [comment]
@ianb I would also love to work on the testing, I'm an Outreachy Applicant

**Comment by ianb** [comment]
@lelouchB You have some other tickets, so I'll assign this one to @Apiyo4

**Comment by lelouchB** [comment]
@ianb yeah it's totally fine
Good luck @Apiyo4

**Comment by ianb** [comment]
I think this has been done along the way.
