### ISSUE TITLE
Home page for Firefox Voice

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1166]
To date Firefox Voice has been using Open Innovation's campaign tools. As we expand the audience we'll need a more established home page for promotion that can highlight functionality, provide answers to common questions (which we get a lot of), and a link to download the add-on.

This will also be a location to display #643

**Comment by saucekode** [comment]
@awallin when this is ready. Please, I would love to work on it. Thank you.

**Comment by awallin** [comment]
Design for a new home page is ready. This new home page is focused on two audiences.

1. Existing [Common Voice](http://voice.mozilla.com) contributors. Our hope is they'll be excited to use Firefox Voice and be open to allowing their voice recordings to be saved and used as training data for Deep Speech’s SST model.

2. General public who discovers the extension through the add-on store, promotion in Firefox or other press/marketing.

Review the UX diagram for details on how the UI/flow change depending on referral source.

Details and specs for the design can be found here:
* Attached JPG mockups at various responsive breakpoints
* [HTML and CSS specs can be found on Abstract](https://share.goabstract.com/23673cdc-f2e3-405d-ae7a-70e0a286f278)
* [Content is available in this Google Doc](https://docs.google.com/document/d/17MnBTuO4Mxl7HZbYF6nxMVtni-MzuYLHkjtauvKiqxs/edit?usp=sharing)

From a technical perspective this site should be implemented using Mozilla's Protocal design system(https://protocol.mozilla.org/). @ianb can you add details about how/where the site/repo should be hosted?

![image](https://user-images.githubusercontent.com/428245/78063651-6acd5280-7345-11ea-85e3-46ef9c96cf48.png)

[FxVoice homepage.zip](https://github.com/mozilla/firefox-voice/files/4411010/FxVoice.homepage.zip)

**Comment by Simpcyclassy** [comment]
I believe these issues are same https://github.com/mozilla/firefox-voice/issues/126

**Comment by saucekode** [comment]
Yea sure. Still interested!

**Comment by jcambre** [comment]
@saucekode are you still working on this? I think we're hoping to have the new home page implemented pretty soon, so I'm happy to take it on if you don't have the time in the next few days.

**Comment by saucekode** [comment]
Hey dear, sure. I'm currently on a project. Can we kick off by say Monday?

**Comment by awallin** [comment]
Here's an InVision prototype for the homepage.
https://mozilla.invisionapp.com/share/9XWU20C2DVB#/413305292_Home_-_1056

**Comment by ianb** [comment]
Fixed in #1636
