### ISSUE TITLE
Support Windows development w/o WSL

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1172]
I've suggested using Windows Subsystem for Linux (WSL) for development, but it's been a challenge for many people to get setup.

While I've used more Linuxy things in other projects, I'm not sure how necessary it actually is in this project. All the important development scripts are Node scripts, and the build process is all Node.

Users will need to install git and Node. Maybe that's enough? Or if not, maybe it wouldn't be too hard to fix whatever problems there are. If someone could try to setup the project without WSL, document any problems, and hopefully find some solutions, that could be very helpful.

**Comment by dave-ok** [comment]
@ianb I agree. I couldn't use the WSL even if I wanted to because I use a windows 8 machine, and WSL is only available in certain versions of windows 10. So after a little tinkering I have been able to setup the project using just git and Node.

**Comment by dave-ok** [comment]
@ianb I am a current outreachy applicant. May I be assigned this issue?

**Comment by ianb** [comment]
You got it! This will probably be updates to the README, plus any changes that might come up in the code. 

There's a couple Python scripts used for release in `bin/` but don't worry about those, they aren't used for normal development.

**Comment by dave-ok** [comment]
Great! I'll get on it right away

**Comment by dave-ok** [comment]
@ianb I have made some updates to the README, however I left the original section detailing how to setup on windows with WSL. Please review my updates. in #1172
