### ISSUE TITLE
Reuse tabs in certain circumstances

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#118]
In some circumstances it seems like it would make sense to reuse an open tab instead of opening a new tab. Defining when may be tricky.

Specifically if the user is correcting an action by re-doing the action, it seems like we should reuse the tab. We might be able to detect this by seeing that a similar action is happening on a tab that was very recently created, or was created and not interacted with. 

To do this we would have to track when an intent creates a tab, the timestamp, and URL. We could then match that to see if the current tab is "reusable".

**Comment by awallin** [comment]
Agreed, there's cercumstances where opening in the existing tab would be nice. Might depend on the active tabs content (new tab, onboarding page, etc).  But, yea it's tricky to know when it's best to remain on the same page, we could consider a setting like "open requests in new tab".

**Comment by ianb** [comment]
I think #423 is a more actionable version of this issue.
