### ISSUE TITLE
Update readme with clearer instructions for linux.

### ISSUE THREAD

**Issue by LilyLME** [mozilla/firefox-voice#1182]
The developing part of the readme starts of well by asking that nodejs is downloaded then suddenly moves to **_"After downloading Firefox Nightly, change its name to FirefoxNightly (no space), otherwise the project wont be able to spawn the firefox."_**  That instruction is a little bit confusing we might want to restructure it by:

First asking the that the reader downloads Firefox nigtly from : https://www.mozilla.org/en-US/firefox/channel/desktop/

Next the instruction about  changing _**"its name"**_  is not clear, what is being renamed? The binary `fireforx`? that's not clear.

The ambiguous instruction can be found at :
https://github.com/mozilla/firefox-voice/blame/master/README.md#L36

I had a work around by applying these instructions from the WSL sections, otherwise I was quite lost.
https://github.com/mozilla/firefox-voice/blame/master/README.md#L80-L81

Hope I did not miss something :)

**Comment by av-00** [comment]
I've just completed setting up everything after a lot of support, @ianb can I work on it?

**Comment by ianb** [comment]
@av-00 Yes, that would be great, thanks!
