### ISSUE TITLE
Bug: Jest test failing locally on "music.pause" intent

### ISSUE THREAD

**Issue by dave-ok** [mozilla/firefox-voice#1184]
### Steps to Reproduce
Run "npm test" locally.

### Expected Result
All tests should pass

### Actual Result
Jest test fails when testing phrases for "music.pause" intent at "pause spotify" phrase

![Failing Test](https://user-images.githubusercontent.com/19638455/76188587-cc801e00-61d8-11ea-8983-88894b425fe6.png)

### Notes:
Tests still pass on CI because Jest tests have currently been disabled on CI

**Comment by naima-shk** [comment]
@ianb  Can i take this one please ? :)

**Comment by ianb** [comment]
@naima-shk I think @dave-ok was planning on fixing this as well as reporting it
