### ISSUE TITLE
Educate developers on type input feature

### ISSUE THREAD

**Issue by saucekode** [mozilla/firefox-voice#1188]

**Comment by Simpcyclassy** [comment]
Please, could this be assigned to me @ianb ?

I also need a little bit of clarification of this bug

**Comment by ianb** [comment]
@Simpcyclassy I'd like @awallin to come up with some design for this before implementation.

**Comment by Simpcyclassy** [comment]
Okay Lit.

**Comment by awallin** [comment]
@saucekode Could you describe the use case/problem further and what you envisioned as the solution?

**Comment by saucekode** [comment]
@awallin This happened when I first started using the extension. I was saying a particular word and it didn't recognize what I was saying, just kept getting the wrong output. So I looked for a button or something to prompt me to type the right word. The whole typing on the extension thing isn't obvious at the beginning.

So I suggest placing a button to prompt user input so they can type word if speaking fails

**Comment by ianb** [comment]
This has been a particular problem for people developing, and so far no one has figured out typing on their own, so at least for that use case it would be helpful. But maybe for others – we used to have people sometimes type intents, but now we get none at all, and that might just be because no one knows.

**Comment by awallin** [comment]
I propose these changes to make keyboard input more visible for developers.

In the settings menu educate users about the ability using the keyboard for typing input. See mockup.

Specifically for the developer build add messaging in the doorhanger which will appear on the first 5 triggers (matches current expansion behavior for new users). Clicking the link could either open the input box or link education text in settings.

![preferences-with-navigation](https://user-images.githubusercontent.com/428245/76473417-a368b480-63b5-11ea-8f03-624f6adfa9ce.jpg)

![keyboard-developer-tip](https://user-images.githubusercontent.com/428245/76473409-9c41a680-63b5-11ea-9d04-8508d24bc051.jpg)

**Comment by saucekode** [comment]
Okay! This works fine. Can I work on this when the design is ready? I opened the issue. Thank you

**Comment by Simpcyclassy** [comment]
Great feedback there @awalin! @ianb I await being assigned. Thank you

**Comment by ianb** [comment]
I believe @Simpcyclassy has been looking for a next bug for a while so I'd like to give this to her

**Comment by Simpcyclassy** [comment]
Thanks sir

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-15).
I will reopen this report, as the "Type Input" suggestion from the "Preferences" page should also be implemented like in the mock-up displayed above.

![Annotation 2020-04-15 175639](https://user-images.githubusercontent.com/54401091/79352786-f4cf0b00-7f42-11ea-9c6a-5acbf0d57afd.png)

**Comment by ianb** [comment]
I think this is fine as-is.
