### ISSUE TITLE
"Copy links" should work

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1190]
"Copy link" works right now, but if the system mishears you as saying "copy links" then you get a search result.

This will be a small change to `clipboard.toml`

**Comment by ajinkabeer** [comment]
Hey @ianb, I would like to take up this one if there aren't any other outreachy applicants who are looking for their first issue.

**Comment by saucekode** [comment]
Hello @ianb, I would like to work on this issue. Thanks

**Comment by ianb** [comment]
Assigning to @saucekode because we'd just talked about this ticket on the channel

**Comment by ajinkabeer** [comment]
Oh, totally fine. I'll look for other issues :)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-12).

![28](https://user-images.githubusercontent.com/54401091/76530163-03c22980-647c-11ea-8590-f66776c962a6.gif)
