### ISSUE TITLE
Make `npm run build:jsx` atomic

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1193]
Right now `npm run watch-rebuild` is run whenever certain changes are noticed (.jsx, .toml, and .ejs file changes). Unfortunately it updates all of these files, and can cause a bunch of reloads.

The toml and ejs files should actually be OK, because `bin/script-utils.js` should only write files that actually change. But `babel` writes all the jsx files, and it takes a while, so web-ext might even see when it's only half-completed the task.

To fix this I think we should have babel write out (with `--out-dir`) to some temporary location `./build/`) and then move all the files into place as one command (maybe moving only changed files).

This would be a new script in `bin/` that runs babel and then moves the files.

**Comment by IkkyOdufade** [comment]
Hi @ianb, can I have this?

**Comment by ianb** [comment]
@IkkyOdufade You got it!

**Comment by IkkyOdufade** [comment]
Hi Ian, I really dont know how to tackle this issue. Can you give me some pointers? Thank you.

**Comment by ianb** [comment]
@IkkyOdufade You're going to change `build:jsx` so it builds into a different directory (e.g., `build/`). Then after it's built files there, the simple thing would be to copy all the files at once, but the slightly better thing would be to create a script that copies the files only if they content has changed. `bin/script-utils.js` has an example of writing a file only if the content has changed, and that can serve as an example for copying.

**Comment by IkkyOdufade** [comment]
Hi Ian, I've been trying to create a pr with just the npm build corrections but I cant. The deezer files keep appearing. I tried the git checkout origin/branch -- file but it kept saying error: pathspec 'deezer.js' did not match any file(s) known to git. Please help. Thank you.

**Comment by IkkyOdufade** [comment]
Hi @ianb I would like to tell you how I have gone with this project since my pr is still not working properly. I changed the npm run build:js command, to create a new folder inside build, a lib folder. But the files being created are the ones inside eslintignore file. Is that how it is supposed to work?

**Comment by ianb** [comment]
@IkkyOdufade If things get really messy, sometimes I just check out a new copy of the repository, or do `git reset --hard origin/master` (after you copy all your changed files someplace safe!)

What have to changed `build:jsx` to be? It should probably be something like `babel --relative --out-dir build/ --ignore gh-pages '**/*.jsx'` and then there should be files like `build/extension/options/optionsView.js`

**Comment by IkkyOdufade** [comment]
Oh ok. I actually changed it to `babel --out-dir build/lib --copy-files --ignore gh-pages '**/*.jsx'  && node bin/build-jsx.js`. It compiled 9 files into the lib folder. Thank you for your help. Making git work like you want it to is hard sometimes. I have to improve my knowledge on git. 👍

**Comment by IkkyOdufade** [comment]
Hi @ianb . Do I still need to write a script to copy the files? After I changed the build:jsx, it compiles 9 files into a lib folder.
