### ISSUE TITLE
"google for X" should always open Google

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1194]
Right now the `search.searchPage` intent uses the default search provider. But one of the phrases it catches is `google for X`, which would presumably always means search Google, not the default search provider. 

To test this set your default search provider to be DuckDuckGo, and then try a phrase like "google for apples".

Fixing this might be a matter of adjusting the phrases for `search.searchPage` (maybe moving those Google-specific phrases into `navigation.bangSearch`), or separating out the Google phrases and using a parameter, and choosing between `performSearch()` and `browser.search.search()` based on that parameter (in the `search.searchPage` `run()` method).

**Comment by farhatcode** [comment]
Can I say the "Search for X" should always go to the default search provider and search.searchPage never catches the google phrase?
Because if query contains google, it can be handled in bang searches?

**Comment by farhatcode** [comment]
performSearch() is intended to perform google search and browser.search.search() is intended to search in the default search engine?
Right now according to my understanding of the code, performSearch() is called for (buildSettings.android) only in the run() method. 
and browser.search.search() is called for other cases.

**Comment by ianb** [comment]
@farhatcode Our other bang searches have different syntax than this because we don't use the search provider as a verb. For example, "amazon hats" doesn't open an amazon search, but "search amazon for hats" does. But we do want "google hats" to open a google search.

So... yes, this could mean adding google to the bang searches, plus adding some more google-specific phrases. Or it could mean changing `search.searchPage` to allow for an explicit Google search provider.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-25).

![3](https://user-images.githubusercontent.com/54401091/77548268-fe6ed100-6eb6-11ea-88df-45dc9f795ca0.gif)
