### ISSUE TITLE
Allow nicknames to be edited in options

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1197]
Right now we have a bunch of nicknames managed in `nicknames.js`. But you have to use voice commands, and it's hard to do that precisely or understand what you've saved.

I imagine a new section at the bottom of the settings page, looking roughly like:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/44390/76261739-a8e4c400-6228-11ea-85b5-881e30cf28cd.png">

The "Save" button might not be anything special, most of those fields in settings save when they are changed or unfocused. Delete of course deletes the one routine. I'm borrowing the name "routine" from Alexa, instead of calling them nicknames.

Note that you'll have to get the existing routines from `intentRunner.js` and then also save them there. This will require some additional messages being sent from `optionsController.jsx` to `main.js` through the `intentRunner.js`, both to fetch and save nicknames. 

The code currently distinguishes between a single alias, and a nickname that does several actions (`combined`), but the UI shouldn't show them differently.

@awallin might have some design notes, but I think the simple UI is enough to move forward with.

**Comment by danielamormocea** [comment]
@ianb. ready to take this :D

**Comment by awallin** [comment]
I can definitely make a higher fidelity UI design. My initial thought is this shouldn't be on the main settings page but instead linked from there. The settings page is getting long as is and it's unlikely this feature will be used by a majority of users.

**Comment by ianb** [comment]
@awallin Can we make a tabbed version of the settings page? Just in terms of code it seems nice to keep this stuff in one page.

**Comment by awallin** [comment]
@ianb Similar to the Firefox Preferences page which creates section for General, Home, Search, Privacy & Security, and Sync?

**Comment by danielamormocea** [comment]
@ianb @awallin So should I make a simple UI alongside the backend functionalities, then get feedback and improve the UI later?

**Comment by ianb** [comment]
@danielamormocea Yes, I generally like to focus on just having each step improve things. So as long as the UI flow seems right we can rearrange or restyle things in followups.

**Comment by awallin** [comment]
Here's a pass at the designs for routines including tabbed sidebar and layout for routines on a separate in-page tab. There's more to come for editing a specific routine and confirmations for delete.

Let me know if you have any questions?

![preferences-with-navigation](https://user-images.githubusercontent.com/428245/76449733-d301c780-6389-11ea-9d71-41b329d8b4db.jpg)

![preferences-routines](https://user-images.githubusercontent.com/428245/76449729-d006d700-6389-11ea-9bad-7cdf9e1092eb.jpg)

[icon-routine.svg.zip](https://github.com/mozilla/firefox-voice/files/4320015/icon-routine.svg.zip)

**Comment by ianb** [comment]
Oh, I remembered that in the mockup I gave there is room for more than one name/nickname for a routine, but the code doesn't actually allow for that currently. So for now each routine should just have one name, and we can add multiple names in a followup.
