### ISSUE TITLE
Sad emoticon not visible in the negative feedback display

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1202]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a command that shows the feedback section in the doorhanger, e.g. "Define voice", "Who created Breaking Bad".
3. Click on the sad emoticon from the "Did we get this right?" section from the doorhanger.

### Expected result:
The negative feedback section is displayed in the doorhanger without issues.

### Actual result:
The sad emoticon display is almost not visible in the doorhanger.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-09).
Mock-up for comparison:

![mock neg feed](https://user-images.githubusercontent.com/54401091/76307919-68da1b80-62d2-11ea-8876-9cd902008fd8.png)

Actual display:

![neg feed](https://user-images.githubusercontent.com/54401091/76308168-e00faf80-62d2-11ea-8ee6-a03ef75b46af.png)

![2](https://user-images.githubusercontent.com/54401091/76307977-87d8ad80-62d2-11ea-8dd0-8f67224cbacc.gif)

**Comment by fleur101** [comment]
Hello! Can I work on this bug?

**Comment by awallin** [comment]
@GangaChatrvedi Could you make a minor change to the color fill by using #0060DF to be consistent with the rest of the UI? Thanks.

**Comment by GangaChatrvedi** [comment]
Yes. I am creating new PR corresponding to this.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-11).

![3](https://user-images.githubusercontent.com/54401091/76425223-fd677b00-63b1-11ea-8247-40e3c21276ac.gif)
