### ISSUE TITLE
Specify minimum Node version in package.json

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1206]
I'm pretty sure there's a way to do this. I've been using v13.8.0, but i think v12 works too

**Comment by xlisachan** [comment]
@ianb can I work on this?

**Comment by naima-shk** [comment]
@ianb  Can i take this one please ? I m an Outreachy Applicant .

**Comment by ianb** [comment]
I think @naima-shk has been looking for a first issue for a bit, so assigning

**Comment by naima-shk** [comment]
@ianb  Thanks :)
