### ISSUE TITLE
Cursor should be pointer for smile/frown feedback

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1211]
The smile/frown icons should use a pointer (hand) when hovering on the smile/frown in the doorhanger. This indicates to a user they can click the icons.

**Comment by nuraynab** [comment]
Hi, can I have this?

**Comment by awallin** [comment]
Go for it @nuraynab

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-11).

![21](https://user-images.githubusercontent.com/54401091/76523590-54805500-6471-11ea-8051-c28a1c82660d.gif)
