### ISSUE TITLE
"Previous/Next results" commands only work with google search

### ISSUE THREAD

**Issue by JM-Mendez** [mozilla/firefox-voice#1213]
The commands `previous results` and `next results` are only able to fetch results from the google. This happens because the results are iterated over according to google's html structure, which doesn't match the other providers.

**Comment by JM-Mendez** [comment]
@ianb can you please assign this issue to me? It's a continuation of PR #1180, but was not within scope of the issue that PR was addressing.

**Comment by ianb** [comment]
@JM-Mendez Cool, you got it

**Comment by ianb** [comment]
QA note: if you change your default search engine to DuckDuckGo, and then run a search, and say "next result", it should go to the next result (like it does for Google)

**Comment by JM-Mendez** [comment]
> QA note: if you change your default search engine to DuckDuckGo, and then run a search, and say "next result", it should go to the next result (like it does for Google)

@ianb this should have been resolved when #1236 landed. Is this a regression I need to work on?

**Comment by ianb** [comment]
@JM-Mendez: @alexandra-martin wanted to verify the fix but wasn't clear what needed to be verified.

**Comment by 12people** [comment]
@ianb @JM-Mendez isn't working for me in the extension (version 0.21.0).
Is this a regression?
