### ISSUE TITLE
Customisable wakeword

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#1217]
I think that could be a good idea can choose a customisable wakeword, in addition to the list.
Just add a "textbox" and there you can write your wakeword.

**Comment by Akanksha1212** [comment]
Hi, I would like to work on this.

**Comment by awallin** [comment]
Closing this as it's a duplicate of this wakeword implementation.
https://github.com/mozilla/firefox-voice/issues/1037
