### ISSUE TITLE
"Hey Firefox" as wakeword

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#1218]
Could you add "Hey Firefox" as a default wakeword?

**Comment by av-00** [comment]
hi can i work on this?

**Comment by GangaChatrvedi** [comment]
@Sav22999 Creating a custom wake word with picovoice is possible but only with words which are available in their existing vocab. 

I could do it with **Hey Fire** and **Hey Fox**.

But **Hey Firefox** will need paid plan with picovoice.

**Comment by Sav22999** [comment]
@GangaChatrvedi I think "Hey Firefox" would be the most natural wakeword. But Also "Hey Fire" (or "Hey Fox") would be better than actual wakewords.

**Comment by Sav22999** [comment]
@GangaChatrvedi and "Hey Fire fox?" whould be a solution?

**Comment by GangaChatrvedi** [comment]
@Sav22999  Surely  **Hey Fire fox** will be possible. I am not sure about the sensitivity.

**Comment by Sav22999** [comment]
You should try it ;) anyway, I think you should add "hey fire", "hey fox" and maybe "hey fire fox"

**Comment by GangaChatrvedi** [comment]
Sure. I will work on it.

**Comment by Simpcyclassy** [comment]
@Sav22999 I think "Hey {user}" may give a better feel, what do you say @GangaChatrvedi ?

**Comment by KeenWarrior** [comment]
Hey {user} is not possible with pucovoice porcupine at present

**Comment by jofish** [comment]
I'd recommend holding off working on this one. We're talking to Picovoice right now, and we'll resolve this in other ways. There's lots of other bugs we'd really appreciate your help with!
