### ISSUE TITLE
Add "Play the video in this page"

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#1219]
If I am in a youtube page, for example, it should be a great thing can control the video.
"Play the video in this page"
"Pause the video in this page"
"Volume up in this page"
"Volume down in this page"
"Restart the video in this page"

**Comment by JanviMahajan14** [comment]
Can I work on this issue

**Comment by awuorm** [comment]
Hi @Sav22999 can I pick this task?

**Comment by Sav22999** [comment]
You have to ask to @ianb

**Comment by vandnakapoor19** [comment]
@ianb  I'd like to work at this point.
