### ISSUE TITLE
"Unmute this page" doesn't work

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#1220]
"Mute this page" work great, but "Unmute this page" doesn't! It opens "https://www.google.com/search?q=unmute+this+page&safe=active&voice" page

**Comment by OliviaRuyinZhang** [comment]
@ianb Can I give this item a try?

**Comment by OliviaRuyinZhang** [comment]
I already have a fixed for it. We need to add "page{s}" as one of the match for "unmute" under the metadata.js file.

**Comment by OliviaRuyinZhang** [comment]
I also noticed if we only typed "unmute", it wouldn't work. I added unmute as a match as well

**Comment by ianb** [comment]
@OliviaRuyinZhang Great, if you submit a PR I should be able to look at it tomorrow

**Comment by OliviaRuyinZhang** [comment]
Thanks!

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-12).
"Unmute this page" command works as intended.
"Unmute" command is an intermittent issue, as described in #1250.

![27](https://user-images.githubusercontent.com/54401091/76529539-17b95b80-647b-11ea-94b4-d61c6e4b695d.gif)

**Comment by alexandra-martin** [comment]
#1251 and #1253 seems to be related. 
These issues may be location depended.
