### ISSUE TITLE
Add "Search NAME on Firefox Add-ons"

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#1222]
Related to #977 
Add other keywords: "Search <NAME> on Firefox add-ons" and "Search <NAME> on Mozilla add-ons"

**Comment by Sav22999** [comment]
Can I work on this?

**Comment by Sav22999** [comment]
I think the solution is to add just `name = ["firefox add-ons", "mozilla add-ons"]` in `searchServices.toml`

**Comment by SaumyaSinghal** [comment]
I already worked on #977 so can i work on this?
