### ISSUE TITLE
[Preferences] Cleanup Data Collection section

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1238]
Two changes to clean up the design for the 'Firefox Voice Data Collection and Use' section.

* Reduce padding between first line 15px
* Replace checkboxes with toggle switches. Examples of these switches can be found in about:addons

![Preferences-data-collection](https://user-images.githubusercontent.com/428245/76450358-d9dd0a00-638a-11ea-9e05-7f0635028014.png)

**Comment by xlisachan** [comment]
@awalin, can I work on this?

**Comment by saucekode** [comment]
@awallin can I please work on this?

**Comment by nuraynab** [comment]
Can I have this? @awallin

**Comment by awallin** [comment]
Assigning to @xlisachan as she put in the first request.

**Comment by xlisachan** [comment]
@awallin thank you! I have made the requested changes in pull request #1242 (see above). Please review when you have a moment.
