### ISSUE TITLE
When there are two or more bookmarks with similar/same title, only the last saved bookmark gets opened

### ISSUE THREAD

**Issue by Simpcyclassy** [mozilla/firefox-voice#1243]

**Comment by saucekode** [comment]
@ianb can I work on this, please? Thank you.

**Comment by Simpcyclassy** [comment]
@ianb may I  will work on this

**Comment by ianb** [comment]
@Simpcyclassy Sure. What do you propose should happen in this case? (I'm not sure myself)

**Comment by Simpcyclassy** [comment]
So currently the most recently added bookmark opens when there are more than one good match, instead of sorting to open the latest, I can just sort and iterate through the array, and open each bookmark in a new tab. But then I also have to first do a check that the length of the array of bookmarks is less than a certain amount, so you don't end up opening like over 20 tabs😹Lemme see how this works, and create a PR.

**Comment by Simpcyclassy** [comment]
With the current implementation, it seems the most recently added bookmark opens when there is more than 1 good match. So instead of sorting and opening this way, I can just sort it and iterate through the array, and open each bookmark (element) in a new tab see. I guess I can first do a check that the length of the array of bookmarks is less than a certain amount so I don't end up opening over 50 tabs😹. Lemme work this out and see how it goes.
