### ISSUE TITLE
Convert test/test.js to async/await

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1257]
The example function in test/test.js from #1254 uses `.then()` and `.catch()`, but could use `await` instead

**Comment by Simpcyclassy** [comment]
@ianb I will like to take this task.

**Comment by saucekode** [comment]
@ianb currently, have my hands free. Would like to try this out

**Comment by naima-shk** [comment]
@ianb  Can i try this one please ?

**Comment by Simpcyclassy** [comment]
@ianb could you check [this](https://github.com/mozilla/firefox-voice/pull/1260) out please?

**Comment by ianb** [comment]
Fixed in #1260
