### ISSUE TITLE
[Intent] close window

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1258]
Based on telemetry users occasionally ask to "close all tabs" or "close this window" or "close window"

This should try to close the window but ensure the confirmation appears before actually closing the window.

**Comment by saucekode** [comment]
@awallin let me try this

**Comment by naima-shk** [comment]
@awallin  Can i take this one please  as i don't have any other issue ?

**Comment by awallin** [comment]
@saucekode go for it.
