### ISSUE TITLE
Add GitHub as bang search

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1259]
Users should be able to search for GitHub repos by saying "Search for <repo name> name on github" or "search GitHub for <repo name>"

This should leverage the existing bang search infrastructure.

**Comment by saucekode** [comment]
@awallin would really love to try this. Thanks

**Comment by liumichael** [comment]
I can work on this

**Comment by awallin** [comment]
Giving this to @liumichael as @saucekode just had a couple assigned to her.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 76.0a1 (2020-03-18).

![6](https://user-images.githubusercontent.com/54401091/76969594-42039100-6933-11ea-989a-f43c94419afe.gif)
