### ISSUE TITLE
Add alias for screenshot

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1261]
Add an alias for the existing screenshot feature when a user says "take a screenshot of the page"

**Comment by liumichael** [comment]
Hi @awallin, can I take a shot at this?

**Comment by awallin** [comment]
All yours @liumichael

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 76.0a1 (2020-03-18).

![3](https://user-images.githubusercontent.com/54401091/76961494-1af29280-6926-11ea-876d-a520601efb55.gif)
