### ISSUE TITLE
[Intent] Count my open tabs

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1267]
Based on telemetry we've seen people ask for the total number of their tabs by saying things like “count my open tabs” or “count how many tabs I have open” or “count my tabs”. I lean towards this being the total number of tabs on the current window but could be convinced it's total number of tabs on all windows?

The result should be displayed in the doorhanger matching attached mockups. Details to note:
* Font size for resulting number 92
* Education text is: Click mic and say ‘gather all Google tabs’

![open-tabs](https://user-images.githubusercontent.com/428245/76588866-71cf1680-64a5-11ea-9b5a-cdffcc509e06.jpg)

**Comment by xlisachan** [comment]
@awallin can I work on this?

**Comment by awallin** [comment]
Go for it @xlisachan

**Comment by awallin** [comment]
Made a few changes to the content and visual layout for this to establish a template for Q&A cards used in #1266 #1270 and #1269. Specs for these cards are as follows:

* 100x100 image with
* 25px of padding between Question Transcript and image
* 35px of padding between image and Answer text

**Comment by donalawa** [comment]
Can i also work on this?

**Comment by awallin** [comment]
@donalawa This is a straight forward issue. Keep an eye out for more 'good first issues' coming soon.

**Comment by xlisachan** [comment]
@awallin Please take a look at the updates and notes I included in the pull request mentioned above when you have a moment. Thank you!

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 76.0a1 (2020-03-18).

![1](https://user-images.githubusercontent.com/54401091/76960090-71aa9d00-6923-11ea-9a77-834314ed56a8.gif)
