### ISSUE TITLE
[Intent] Test

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1270]
People often say 'test' to Firefox Voice. We should do a simple test, provide feedback and a next step if there are any issues. See attached mockup.

![test](https://user-images.githubusercontent.com/428245/76588664-c756f380-64a4-11ea-9bdd-5e7756d13e79.jpg)

**Comment by melvin2016** [comment]
I would like to work on this.

**Comment by JanviMahajan14** [comment]
Hey @awallin Can i work on this issue ?

**Comment by awallin** [comment]
Go for it @JanviMahajan14

**Comment by awallin** [comment]
Made a few changes to the content and visual layout for this to establish a template for Q&A cards used in #1266 #1267 and #1269. Specs for these cards are as follows:
* 100x100 image with 
* 25px of padding between Question Transcript and image
* 35px of padding between image and Answer text

**Comment by JanviMahajan14** [comment]
thanks! one more what issues we need to check for this indent

**Comment by JanviMahajan14** [comment]
@awallin Can you tell me what needs we are supposed to check to perform this check successful

**Comment by awallin** [comment]
@JanviMahajan14 originally I was thinking we'd check for a internet connection and that the mic is getting audio (non zero reading) but if those are problems I don't think they user will even get to point where a card can be rendered. So, might as well just display the card without a check unless @ianb can think of anything?

**Comment by ianb** [comment]
I think just showing the card is enough. They are testing if the mic works, and if the intent runs then it must have worked.

I'd suggest it match `(this is | ) (test | testing) (test | testing |) (test | testing |)`

**Comment by JanviMahajan14** [comment]
@ianb Can you tell me where I am supposed to add the indent ?

**Comment by Simpcyclassy** [comment]
@JanviMahajan14  will you still love to work on this issue or may I take it up?

**Comment by Simpcyclassy** [comment]
@JanviMahajan14  will you still love to work on this issue or may I take it up? But if you still feel positive about it, this is a task for `extension/intents/self`
