### ISSUE TITLE
A typo on the README.md file.

### ISSUE THREAD

**Issue by Shulammite-Aso** [mozilla/firefox-voice#1282]
Here under *contributing* we have "To disclose potential a security vulnerability please see our security documentation":
![Screenshot from 2020-03-13 21-19-55](https://user-images.githubusercontent.com/48386390/76662668-8fb87c00-6576-11ea-989e-000b1479fd6e.png)

I'm thinking this should probably be "To disclose *a* potential security vulnerability please..." or "To disclose potential security vulnerability please..." 

please @ianb @awallin if this really needs correcting, i would like to quickly fix it and make pull request, as it will be my first contribution to this project.

**Comment by ianb** [comment]
Sure thing, PR away!

**Comment by Shulammite-Aso** [comment]
Thank ya. I have just made a PR
