### ISSUE TITLE
Create a master list of commands/requests handled for Firefox Voice

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#129]
Document the possible utterances and actions that can be requested on a web page that can be linked to from the add-on.

**Comment by ianb** [comment]
I think we should implement this as a Markdown document, and maintain it manually. We'll want to wrap the page in a nice template.

**Comment by awallin** [comment]
Based on Alpha participants transcripts and feedback we should open the lexicon page when users ask things like "What else can you do", "What can I say", "What can I ask you", etc.

**Comment by ianb** [comment]
We should review this list of commands: https://github.com/mozilla/firefox-voice/blob/master/extension/intents/self/self.js#L18-L20

Also the lexicon has to actually be filled out and styled. The text is in `bin/lexicon.md` and there are some instructions in that file for how to update it.

**Comment by ianb** [comment]
Well, we got something now.
