### ISSUE TITLE
Close active tab alias

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1298]
As reported by a user "close active tab" and "close the active tab" should work as an alias for "close tab"

**Comment by xlisachan** [comment]
@awallin can I work on this?

**Comment by saucekode** [comment]
Oh sorry @xlisachan , saw your comment after this, super sorry

**Comment by awallin** [comment]
@xlisachan there will likely be a similar alias issue again, I'll assign it to you.

**Comment by xlisachan** [comment]
@awallin no worries, I have a question about the issue though. I don't believe the word "active" is supported for the `tabs.close` intent, is it necessary? If so, I included it in my pull request. If not, I will remove it. Please let me know when you have a moment, thank you!

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 76.0a1 (2020-03-17) and the "Close active tab" and "Close the active tab" performs searches (either opens a Google card, or opens a stackoverflow [link](https://stackoverflow.com/questions/2076299/how-to-close-current-tab-in-a-browser-window) in a new tab).

![2](https://user-images.githubusercontent.com/54401091/76864509-d9041680-6869-11ea-9944-ee8c8f85f485.gif)

**Comment by xlisachan** [comment]
@alexandra-martin I think this issue can be closed again, there was a pull request that was just approved and merged. Can you please confirm?

**Comment by alexandra-martin** [comment]
@xlisachan thanks for the heads up. Yes, it seems that pull request solved the issue.
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 76.0a1 (2020-03-17).

![4](https://user-images.githubusercontent.com/54401091/76876577-cd6d1b80-687a-11ea-9769-50f237224b0c.gif)

**Comment by Simpcyclassy** [comment]
I think this issue is resolved and should be closed.
