### ISSUE TITLE
[Bang search] Linguee

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1299]
Based on a user feedback they would like to be able to Linguee by saying things like "search 'fox' with linguee."

There is a bang search for Linguee so it should be a straight forward implementation.
https://duckduckgo.com/bang?q=Linguee#

There's some more advanced implementations we could consider such as asking "say 'fox' on linguee" which would auto play the first audio file

**Comment by annlinros** [comment]
Hi @awallin  I would like to take up this issue..

**Comment by IkkyOdufade** [comment]
Hi @awallin can I work on this?

**Comment by naima-shk** [comment]
Hi @awallin  Can i take this one please ? :)

**Comment by awallin** [comment]
@annlinros give this a shot. The first part should be easy. I'll be curious what you think about adding an intent to auto play the audio with a search on Linguee.
