### ISSUE TITLE
"Copy image" command not copying pictures in Google Docs or other related tabs

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1327]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
A Google Docs tab is opened.
The tab that the user wants to copy the image from is made active.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Copy image" command.
3. Go to the Google Docs tab.
4. Use the paste keyboard shortcut (ctrl+V for Windows or cmd+V for Mac) ("Paste" command currently not working for this tab, see #1326).

### Expected result:
Image is copied in the Google Doc successfully.

### Actual result:
Other information is copied or nothing happens.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-18).
If the user right clicks with the mouse on the image and selects "Copy Image", then it is possible to copy the picture in the desired tab, e.g. Google Docs, Google Slides, Google Sheets, https://www.calmlywriter.com/online/. ("Paste" command works for calmlywriter or Google Sheets. For Google Docs and Google Slides, the paste keyboard command should be used)

![5](https://user-images.githubusercontent.com/54401091/76967190-bfc59d80-692f-11ea-9126-2f4bcc7a1fd0.gif)

**Comment by fleur101** [comment]
I was able to reproduce the bug. May I try to fix it?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-31).
"Paste" commands are not working in Google Docs and Google Slides, like in #1326, but image is copied with the paste keyboard shortcut.

![4](https://user-images.githubusercontent.com/54401091/78041390-4b501d00-7379-11ea-8a2d-a01bb1ab05a1.gif)
