### ISSUE TITLE
"General", "Routines" links and "Routines" page are bigger compared to the rest of the "Preferences" page 

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1328]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
The "Preferences" page is opened, by using the shortcut or clicking on the mic icon from the browser toolbar and selecting the "Settings" icon from the bottom left side of the doorhanger.

### STR:
1. Observe the "General" and "Routines" links from the left side of the page compared to the rest of the page.
2. Click the "Routines" link.
3. Observe the "Routines" page.

### Expected result:
"General", "Routines" links and "Routines" page don't have discrepancies from the rest of the "Preferences" page.

### Actual result:
"General", "Routines" links and "Routines" page are a little bit bigger compared to the "Preferences" page.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-16).
Style of the preferences page navigation links:
.category-name {
	font-size: 1.07em;
	line-height: 1.4em;
	padding-bottom: 2px;
	padding-inline-start: 9px;
	margin: 0;
	-moz-user-select: none;
}
See also #1197 for a mock-up example of a future "Preferences" page.

![8](https://user-images.githubusercontent.com/54401091/76977366-e559a380-693d-11ea-9cf3-9aca3e100dc3.gif)

**Comment by Shulammite-Aso** [comment]
@awallin if this is not how this should look, i can quickly work on it.

**Comment by Simpcyclassy** [comment]
I think [this](https://github.com/mozilla/firefox-voice/issues/1329) fixes this
