### ISSUE TITLE
Changes needed for the "Routines" page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1329]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
The "Preferences" page is opened, by using the shortcut or clicking on the mic icon from the browser toolbar and selecting the "Settings" icon from the bottom left side of the doorhanger.

### STR:
1. Click on the "Routines" link, from the left side of the "Preferences" page.
2. Observe the "Routines" page.

### Expected result:
"Routines" page doesn't have discrepancies compared to the mock-up from #1197.

### Actual result:
There are some discrepancies between the mock-up and the actual display.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-16).
The discrepancies between the mock-up and the actual display are as followed:
- “Create a custom phrase to execute one or more actions” text and “+ New routine” button should not be as bold text;
- “Create a custom phrase to execute one or more actions” text should have a "." at the end;
- “+ New routine” button should have the "+" a bit bigger, "routine" start with a capital letter and have a similiar size and outline to the button from the mock-up;
- line spacing between text from already made routines (e.g. between "news" and "Open nytimes.com") seems a bit bigger in the mock-up;
- when making a new routine (clicking on the "+ New routine" button), the "Save" button should change state (e.g. the color of the button) when it is possible to save the routine made (all fields are written);
- if no fields or some of the fields are not written, it should be visible that the routine can't be saved (e.g. maybe an error can appear inside the new routine box or the "Save" button can have some changes indicating that);
- "When you say this:" and "Do this:" text fields should have some similarities (they can be aligned, have the same length (but not necessarily the same height), have descriptions inside both the fields and be a similar font size with the rest of the text);
- “Edit” and “Remove” routine list options (clicking "..." from an available routine) should be similar to the one from the mock-up in terms of position, size and box outline, have a hover state when the mouse is hovering on an option;
- shadows of the already made routines or the create new routine boxes and the “Edit” and “Remove” routine list options seem darker than the mock-up;
- already made routine boxes should not have a hover state, because they can't be clicked;

Some of these can change, depending on the desired user experience. One example is the position of the "+ New Routine" button.

Mock-up:
![routines 2](https://user-images.githubusercontent.com/54401091/76985147-733a8c00-6948-11ea-8822-98b8ef14e6d2.jpg)

![9](https://user-images.githubusercontent.com/54401091/76985169-7a619a00-6948-11ea-9b1b-bd4b5ca22868.gif)

**Comment by Shulammite-Aso** [comment]
Hi @alexandra-martin I think Issue  #1328  Is a part of this,  or are they different? 
If they are the same and you intend to close the other, then I would like to work on this.

**Comment by Shulammite-Aso** [comment]
@ianb @awallin   I can start working on this after you give your thought on it.

**Comment by shreyaa-s** [comment]
Hey, can I work on this one? @ianb @awallin 
Thanks!

**Comment by alexandra-martin** [comment]
@Shulammite-Aso #1328 has a more general approach for the "Routines" page display (the page itself seems a bit zoomed in compared to other pages), while this report looks at more specific changes that need to be done. Hope that clarifies things.
