### ISSUE TITLE
Feedback link in doorhanger is not centered

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1331]
The feedback link at the bottom of the doorhanger should be center aligned to the width of the popup. See screenshot.

![feedback-not-aligned](https://user-images.githubusercontent.com/428245/76997903-5d5da480-6911-11ea-96c8-734e7be9f776.jpg)

**Comment by awallin** [comment]
@vandnakapoor19 this one is similar to #690 if you'd like to take a look at the same time?

**Comment by vandnakapoor19** [comment]
Sure! Thanks

**Comment by vandnakapoor19** [comment]
@awallin  I have made changes in the CSS file. Have a look once on your side and please confirm if it resolved the issue.

**Comment by awallin** [comment]
@vandnakapoor19 Can you submit the CSS changes as a PR so I can take a look?

**Comment by vandnakapoor19** [comment]
@awallin  Please check my last one titled "feedback is not centered" and please confirm if it resolved the issue.

Thanks

**Comment by vandnakapoor19** [comment]
@awallin @ianb Please let me know if there is you have merged the requestor if there is any issue with my pull request?

Thanks

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-10).

<img width="366" alt="Screenshot 2020-04-10 at 18 18 51" src="https://user-images.githubusercontent.com/54401091/79002068-5add1c00-7b58-11ea-88d7-fd8da1c62a6e.png">
