### ISSUE TITLE
"Play Green day" gives "Internal error: Error: No matching message handler" if made in a blank new tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1339]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
A Spotify account is logged in and autoplay is enabled.
A blank new tab is opened and made active.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar in the blank new tab.
2. Say or write the Spotify "Play" command, e.g. "Play Green Day".

### Expected result:
Spotify opens in a new tab and starts playing.

### Actual result:
"Internal error: Error: No matching message handler" is displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-19).

![11](https://user-images.githubusercontent.com/54401091/77080595-22876980-6a02-11ea-9883-b3506dd3b216.gif)

**Comment by GangaChatrvedi** [comment]
I would like to work on this issue

**Comment by LilyLME** [comment]
@ianb, @alexandra-martin I would be glad to work on this issue please

**Comment by awallin** [comment]
Go for it @GangaChatrvedi

**Comment by GangaChatrvedi** [comment]
Thanks. Working on it.

**Comment by GangaChatrvedi** [comment]
@ianb I am trying to console the result after this line and getting <unavailable>

https://github.com/mozilla/firefox-voice/blob/master/extension/content/helpers.js#L48

According to me, Array of DOM elements should have been printed but may be I'm getting it wrong.
can you please help me with this.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-09).

![7](https://user-images.githubusercontent.com/54401091/78912280-12f2c200-7a90-11ea-9f95-6f416416d3c5.gif)
