### ISSUE TITLE
Follow link failure

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1343]
There's a bug in following a link. It apparently parses the intent properly but doesn't execute the action. See console output.

<img width="896" alt="Screen Shot 2020-03-19 at 9 49 50 AM" src="https://user-images.githubusercontent.com/428245/77092702-41b4d580-69c7-11ea-9253-db0bf52682f5.png">

**Comment by IkkyOdufade** [comment]
Hi @awallin . Can I work on this?

**Comment by LilyLME** [comment]
@awallin let me have this please!

**Comment by awallin** [comment]
@IkkyOdufade you have a couple issue already. @LilyLME give this one a try.

**Comment by IkkyOdufade** [comment]
@awallin I don’t have any issues I’m working on right now. I’ve commented on a bunch of issues but I’m yet to be assigned to one.

**Comment by LilyLME** [comment]
Thanks @awallin, can you help me with the steps tot reproduce this?

**Comment by awallin** [comment]
@LilyLME It's not clear to me why it occurs on my machine but not others.

Basically, I'm opening any webpage with a link and then asking "Click on link for x" or "Follow link for x". I see a confirmation of the utterance but the action never occurs.

<img width="764" alt="Screen Shot 2020-03-24 at 9 52 47 AM" src="https://user-images.githubusercontent.com/428245/77454081-4efe0580-6db5-11ea-8d0c-252415debc83.png">
<img width="1202" alt="Screen Shot 2020-03-24 at 9 52 31 AM" src="https://user-images.githubusercontent.com/428245/77454084-4f969c00-6db5-11ea-92f6-b5675da55a63.png">
