### ISSUE TITLE
The query "open the new york times" fails on Android

### ISSUE THREAD

**Issue by espertus** [mozilla/firefox-voice#1349]
Do either of the following to reproduce:

- Paste this URL into Firefox for Android (fennec): https://mozilla.github.io/firefox-voice/assets/execute.html?text=open+the+New+York+Times
- Open Firefox Voice and say "open the new york times"

In neither case is a new page opened.

**Comment by LilyLME** [comment]
Hi @ianb, can I help you out with this one please :)
