### ISSUE TITLE
New routine doesn't complete all actions when made a second time

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1351]
### Prerequisites:
A fresh new Firefox profile is made and the extension is installed for the first time on the profile.
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
A routine is made that contains more than 1 action. (click mic icon next to the window's menu button, click the "Settings" button from the doorhanger, click "Routines" from the left side of the "Preferences" page, click "+ New routine" button, fill out the fields with the routine name and the actions that need to be done and click the "Save" button) 
Example of routine:
![Annotation 2020-03-20 154903](https://user-images.githubusercontent.com/54401091/77169544-55913200-6ac2-11ea-91ee-492e053b36da.png)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the newly made routine command, e.g. "News".
3. Repeat steps 1 and 2 after closing the new tabs that opened.

### Expected result:
New York Times, CNN and Vox are opened again in new tabs.

### Actual result:
Only Vox (the last action from the routine) opens in a new tab.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-20).
It seems when the "News" command is made a second time, it wants to start to open the New York Times tab, but it just jumps to open Vox instead.
Seems to apply for other new routines made in the new Firefox profile, but it may depend on the routine actions that need to be completed . ("books" routine - 2nd gif)

![5](https://user-images.githubusercontent.com/54401091/77170042-23340480-6ac3-11ea-8d42-2afecae727e2.gif)

![7](https://user-images.githubusercontent.com/54401091/77173542-50cf7c80-6ac8-11ea-9477-c32660376390.gif)

**Comment by LilyLME** [comment]
@alexandra-martin please can I have this :)

**Comment by alexandra-martin** [comment]
@LilyLME @ianb or @awallin can asign people.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-31).

![8](https://user-images.githubusercontent.com/54401091/78136427-3bdddc00-742c-11ea-9a48-7e40e7b96d6f.gif)
