### ISSUE TITLE
Commands that previously were displaying cards in doorhanger, now open new tabs

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1353]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write commands that should open cards in the doorhanger, e.g. "Who created Breaking Bad", "How deep is the Marianas Trench", "What's the temperature in London", "What's 10+10", "How long will it take to get to the airport".

### Expected result:
A card displaying the relevant answer is displayed in the doorhanger.

### Actual result:
A new tab opens that may be relevant to the command made.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-20).

![13](https://user-images.githubusercontent.com/54401091/77179050-a019ab00-6ad0-11ea-86d8-5f89f06164c1.gif)

**Comment by awallin** [comment]
Verified. We should fix this before the next release.

**Comment by GangaChatrvedi** [comment]
@awallin I would like to work on this issue

**Comment by awallin** [comment]
Go for it @GangaChatrvedi

**Comment by GangaChatrvedi** [comment]
Okay. On it.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-25).

![2](https://user-images.githubusercontent.com/54401091/77547006-4bea3e80-6eb5-11ea-94a4-11baaa0498a3.gif)
