### ISSUE TITLE
Add UI to view voice history

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1359]
With #1303 landed we have history being saved, but no way to view it.

For this, add a new tab to the options page, called "History". This should display history items most-recent-first. I believe a table with a formatted date and the utterance would be sufficient.

It would be okay to land this without pagination, but we'll definitely need pagination eventually. Ideally no history will be loaded unless you load the history tab.

@michael-mml would like to do this as a followup to the database work (comment here and I can assign you).

@awallin might have design notes.

**Comment by michael-mml** [comment]
Hi, @ianb , I'd like to take a shot at this.

**Comment by awallin** [comment]
@ianb we should probably allow the user to disable retention of voice history and clear. Are those features I should include in the design?

<img width="703" alt="Screen Shot 2020-03-24 at 9 46 18 AM" src="https://user-images.githubusercontent.com/428245/77453376-6be60900-6db4-11ea-920c-0f69893c547b.png">

**Comment by ianb** [comment]
@awallin Sure, though those could be part of the first PR or not.

We should probably have a note that this is just the local copy of the history. We don't have a way to delete the Telemetry history currently (the Telemetry team is still working on it I think), and if you've disabled Telemetry utterance saving then we might want to include something that says it is saved locally but not uploaded. The combinations are a bit complicated!

**Comment by michael-mml** [comment]
Hi @ianb and @awallin, I'm nearing completion for this feature and realize I will need an icon for the History tab. I don't believe one currently exists.

Also, I had to make a couple of changes to @OliviaRuyinZhang's PR, but we can discuss in the actual PR itself.

Thanks!

**Comment by awallin** [comment]
@michael-mml let's use the standard history icon for Firefox which I've attached.

[History.svg.zip](https://github.com/mozilla/firefox-voice/files/4429524/History.svg.zip)
