### ISSUE TITLE
[Alias] “read out content to me”

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1367]
Add “read out content to me” as an alias to read this page to me.

**Comment by saucekode** [comment]
@awallin please take a look at this. Thank you

**Comment by Simpcyclassy** [comment]
@saucekode You will need to add an `Alternative` matching intent to get this to work.

Line 4 `read.toml` may read something like 
`(can you |) read (me | ) (this | the |) (out content |)(article | articles | text |) (on this| )(tab | page |) (for me | to me |) (aloud |)`

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-10).
The command "Read out content to me" does a Google search for "out content".

![3](https://user-images.githubusercontent.com/54401091/79003822-0cca1780-7b5c-11ea-96f7-461189eaa967.gif)

**Comment by saucekode** [comment]
Will look into it and fix

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-13).

![6](https://user-images.githubusercontent.com/54401091/79220854-79475e00-7e5d-11ea-8cf1-6c896ce27652.gif)
