### ISSUE TITLE
"Create tab" should open a new tab

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1368]
This would be a small phrase match adjustment in `tabs.toml` – "open tab" works but not "create tab"

**Comment by saucekode** [comment]
@ianb please take a look at this. Thank you

**Comment by Simpcyclassy** [comment]
The same thing I mentioned in https://github.com/mozilla/firefox-voice/issues/1367 goes here

Line 87 will be

`(open | launch | create) (a | the |) (new | blank |) tab (for me|)`

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-10).

![4](https://user-images.githubusercontent.com/54401091/79004099-b6a9a400-7b5c-11ea-934a-10cbdcde1074.gif)
