### ISSUE TITLE
[Alias] "what should I do"

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1369]
Add an alias for "what should I do" to "help" which will open the Lexicon.

**Comment by Albaalah** [comment]
Hi @awallin can I work on this as my first issue?

**Comment by awallin** [comment]
Go for it @Albaalah

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-25).

![1](https://user-images.githubusercontent.com/54401091/77533582-cf993080-6e9f-11ea-9546-41009cdccaea.gif)
