### ISSUE TITLE
Another "Dictate" command can't be done before the initial "Dictate" command transcription

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1373]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
An online notepad tab is opened and made active, e.g. [calmlywriter](https://www.calmlywriter.com/online/) or [anotepad](https://anotepad.com/).

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Dictate" command, e.g. "Type don't forget to check emails".
3. Move the cursor before the transcribed text and pres "Enter" a few times.
4. Move cursor back to the top and repeat steps 1 and 2.

### Expected result:
The text is transcribed successfully in the tab.

### Actual result:
New text is added after the initial transcription.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-24).
Not reproduced if cursor is moved anywhere after the initial transcription.

![2](https://user-images.githubusercontent.com/54401091/77438127-1d556080-6dee-11ea-96a2-239f0e108db0.gif)

**Comment by dave-ok** [comment]
May I be assigned this issue? I am assuming the expected result is to dictate at the cursor position?

**Comment by ianb** [comment]
@dave-ok you got it. I probably put code in to specifically append when there wasn't a focused input element (and there wasn't a clear position to add the text), but if the element is focused then the text should go wherever the cursor is.

**Comment by dave-ok** [comment]
Thanks. I'm on it

**Comment by dave-ok** [comment]
I didn't place the "fixes #" properly. This should have closed after merge. @alexandra-martin @ianb Can you please close this issue if resolved. Thanks

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-27).
On notepads like [anotepad](anotepad.com), [rapidtables](www.rapidtables.com/tools/notepad.html) and [shrib](shrib.com) the issue is not reproduced anymore. But on notepads like [calmlywriter](www.calmlywriter.com/online/) and [memonotepad](https://www.memonotepad.com/) the issue is still reproducing.

![1](https://user-images.githubusercontent.com/54401091/77775821-c225a700-7055-11ea-8361-c10cfa05705e.gif)

![6](https://user-images.githubusercontent.com/54401091/77775830-c6ea5b00-7055-11ea-909d-35d8994fba41.gif)

**Comment by dave-ok** [comment]
@alexandra-martin Thanks for pointing this out. I will look into this right away

**Comment by dave-ok** [comment]
@alexandra-martin If you can could you please check out this PR #1405. It should fix the issues you just mentioned. Thanks

**Comment by alexandra-martin** [comment]
Thanks @dave-ok for the fix. Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-09).

![6](https://user-images.githubusercontent.com/54401091/78911422-f6a25580-7a8e-11ea-8cc3-1c81047d007a.gif)
