### ISSUE TITLE
[Timer] Use Chrono

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1379]
Followup to #1360:

Currently it gets the numbers explicitly from the phrases, but we could use [Chrono](https://github.com/wanasit/chrono) to parse times. It seems to handle many of the cases appropriate for this: time in the future, minutes, minutes and seconds, etc.

In the phrase we'd just capture an untyped `[time]` slot, and then use Chrono to parse that time, instead of having separate hours/minutes/seconds.

**Comment by danielamormocea** [comment]
@ianb  Could I work on this issue?

**Comment by ianb** [comment]
@danielamormocea You got it
