### ISSUE TITLE
Add "for internal use" to onboarding page

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#138]
For the first internal-only release we are going to collect more information than usual. We'll describe this in our internal communications, but just in case someone installs the add-on without seeing those communications we should put up some scary language on the onboarding page. 

Obviously we'd remove it for the external beta (closing this ticket should be accompanied with a ticket to revert the change).

**Comment by awallin** [comment]
I added the language to the latest mockup of the onboarding page directly on the logo.
https://share.goabstract.com/e41486eb-2b7d-4a91-b9ba-bcfb16cbff93?collectionLayerId=be49ec07-95c2-4823-9cc5-dddda3c4cc8b&mode=design

**Comment by ianb** [comment]
It's not perfect, but this is what I put in:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/44390/64718218-63b72380-d48b-11e9-95f9-8386fe399aec.png">

Since we don't even have a privacy statement, and the onboarding isn't that noticeable, I replaced the privacy statement in the popup with a warning:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/44390/64718420-c14b7000-d48b-11e9-9b91-f85410da5f6b.png">

Of course these should be removed when it's ready for public use.
