### ISSUE TITLE
Timer Follow up

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1392]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Timer" command, e.g. "Set timer for 20 seconds", "Timer for 10 seconds" and wait for the finished "Timer" display.

### Expected result:
The finished "Timer" display has no visual issues.

### Actual result:
"Did we get this right?" section is displayed.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-26).
If later on it's decided the feedback emoticons will remain in that display, they should be made to be able to be clicked.

Mock-up:
<img width="257" alt="Screenshot 2020-03-26 at 17 19 00" src="https://user-images.githubusercontent.com/54401091/77663663-f893f100-6f85-11ea-9022-86224a122d71.png">

![15](https://user-images.githubusercontent.com/54401091/77658014-c16e1180-6f7e-11ea-9032-0f5d265c8135.gif)

**Comment by danielamormocea** [comment]
@alexandra-martin  I've actually let this slide because it should be implemented after the follow-ups are implemented and merged. I am not sure if this should be a bug, but rather a further issue of the Timer..

**Comment by awallin** [comment]
The follow up commands are depend on #962. Let's use this ticket to implement the follow up when implemented,

**Comment by danielamormocea** [comment]
@awallin I'll start working on this, as the follow-ups are implemented;
