### ISSUE TITLE
Doorhanger with wrong result and a new tab with right result open at the same time when making a command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1397]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write commands that should open cards in the doorhanger, e.g. "lion".
3. Press the doorhanger "Back" button or close the doorhanger and open it again using the shortcut or mic icon from the browser toolbar.
4. Say or write the "56 diamonds" command.

### Expected result:
Result is either displayed in the doorhanger or a new tab opens with the result (Google or website).

### Actual result:
A new tab opens with a website while the doorhanger is displaying the result from the previous command with the title of the current command.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-27).
The issue was reproducing with other similar commands, but it was constantly changing. So the commands mentioned in the steps might not reproduce the issue after a while.

![3](https://user-images.githubusercontent.com/54401091/77772417-c7ccbe00-7050-11ea-8f3c-7d9baec050b0.gif)

**Comment by awallin** [comment]
We should preference displaying content in a doorhanger whenever possible. Meaning if a card is available in Google (or other search engine) we should display that in the doorhanger and not open a new page.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-06).
For the commands mentioned in the steps, the issue is not reproducing anymore. If other commands will reproduce the issue I will reopen the report, but for now it seems fine.

![2](https://user-images.githubusercontent.com/54401091/78667389-7ee2f800-78e1-11ea-9c56-1281a50d014d.gif)
