### ISSUE TITLE
"Play" or "Play music" does not work for the first time in audio music services

### ISSUE THREAD

**Issue by farhatcode** [mozilla/firefox-voice#1398]
**STR:**
1. Open soundcloud.com
2. Select any track by clicking its title (don't click the play button) so that it only get selected/opened, not played.
3. Say or write "Play" or "Play music" command.

**Expected result:**
The music should be played successfully.

**Actual result:**
Nothing happens.

**Note:** "Play" or "Play music" commands work for the paused music only, to unpause it. 
For the first time play music by clicking the play button and then pause it. Then saying these commands play music.

**Comment by amandhamija98** [comment]
@ianb may i please be assigned this

**Comment by farhatcode** [comment]
Actually this is not a bug. The implementation is done this way that the "Play" or "Play music" commands are catched by **music.unpause** intent. 
We need @ianb's suggestion about this, if this thing needs to stay same or we can do some phrase match adjustments about it.

**Comment by amandhamija98** [comment]
Aah ok , I had noticed this for YouTube as well. The first time one says play, it does not work

**Comment by farhatcode** [comment]
It only happens when the music is not auto-played. 
And during the implementation, may be it was considered to play the music from code, for the very first time when opening a track.

**Comment by amandhamija98** [comment]
Aah, perhaps so

**Comment by farhatcode** [comment]
As per this [comment](https://github.com/mozilla/firefox-voice/pull/1289#issuecomment-599734438) closing this issue for now.
