### ISSUE TITLE
"Play audio", "Pause audio" should work

### ISSUE THREAD

**Issue by farhatcode** [mozilla/firefox-voice#1399]
"Play audio" command should play the paused music as done by “play music”.
"Pause audio" command should pause the playing music as done by “pause music”.

This can be done by adding phrase matches in `music.toml`

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-08) for Spotify, Youtube and Soundcloud.

![8](https://user-images.githubusercontent.com/54401091/78797184-099a2480-79c0-11ea-8ca9-055f038ce3d8.gif)
