### ISSUE TITLE
"Play" command may display appropriate message for unsupported audio/video services

### ISSUE THREAD

**Issue by farhatcode** [mozilla/firefox-voice#1401]
The utterances **"play", "play music”, "play video"** which works fine for all supported audio/video services. May display some error message for unsupported music services.

**Prerequisites:**
This is reproduced if no soundcloud / youtube tabs are open. 
OR only one existing tab of soundcloud / youtube is opened.

I have tried this on primevideo.com

**STR:**
1. Open any video on primevideo.com
2. Say or write 
    "play"
    "play music"
    "play video"
commands one by one, when the video is paused. 

**Expected result:**
The commands may not respond or display appropriate message in doorhanger for unsupported video services.

**Actual result:**
**"play" and "play music”** commands create a new soundcloud tab (if no soundcloud tab exists) / play a paused track from an existing soundcloud tab.
**"play video"** command creates a new youtube tab (if no youtube tab exists) / play a paused video from an existing youtube tab.

and if a new tab is created, this new tab don’t get focused.

**Comment by farhatcode** [comment]
For unsupported music services, it was happening that when no service found from existing music services, service was being detected from history using `detectServiceFromHistory()` in `serviceList.js`. In my case `detectServiceFromHistory()` returned soundcloud (as I was working on soundcloud volume controls, so soundcloud was the mostly used service in my history), **detected service can vary for each user based on their history**
so when **"play"** and **"play music”** commands uttered on unsupported services, a new soundcloud tab got created or a paused track from existing soundcloud tab got played.

youtube is sent as a parameter when the **"play video"** command is uttered. so it always went to `explicitService` in `getService() ` in `music.js`. That is why **"play video"** created a new youtube tab or played a paused video from an existing youtube tab.

I have added error messages for these. Now a message is displayed in doorhanger when commands are uttered on unsupported music services.

**Comment by farhatcode** [comment]
It appears that using the player controls from the background is allowed.
So the only thing needs attention here is the creation of a new soundcloud or youtube tab, if not opened already.  Seems it is the only unintended part.

**Comment by farhatcode** [comment]
@ianb I was doing the fix for this issue in #1400 , which I didn't knew, is an intended feature to allow music player commands in the background. That is why it is making no sense to you. 
Then I also came to know, I was doing the wrong thing, blocking an intended behavior. 
Now I need your suggestions, how to fix the problem described in [the above comment](https://github.com/mozilla/firefox-voice/issues/1401#issuecomment-610007788).

**Comment by ianb** [comment]
Supporting control of background services is important for our product experience. In general voice has an advantage when you can talk about something you can't see, and in this case controlling a music service in the background is a good example of that. Also we always want to prefer doing something to giving an error message.

So while it's certainly possible that a user will try to control an unsupported service, and get unexpected background activity, we would want the product to err in the direction of action.
