### ISSUE TITLE
[browser command] minimize and zoom window

### ISSUE THREAD

**Issue by Simpcyclassy** [mozilla/firefox-voice#1409]
Let me fix this @ianb

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-09).

"Minimize window" is working properly, but I am not sure what "Zoom window" should do, as currently nothing happens. "Zoom in tab" and "Zoom out tab" are made for zooming tab information. If the command is meant to re-show the minimized window again, it should be possible only if more windows are opened and the user has access to the doorhanger (tried this and still nothing happens). Maybe re-showing a minimized window will be possible in the future, where the extension can be used in a more hands-free way.

![1](https://user-images.githubusercontent.com/54401091/78998178-b7d4d400-7b50-11ea-99a1-fb352f2b0957.gif)

**Comment by Simpcyclassy** [comment]
Just like the third (green) button on the top left of the browser window in your gif, it zooms in the window

**Comment by alexandra-martin** [comment]
Thank you @Simpcyclassy for the clarification. In this case the intents are working properly.
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-12).

![1](https://user-images.githubusercontent.com/54401091/79116349-f062f080-7d90-11ea-9f6f-bec34ffd48ef.gif)
