### ISSUE TITLE
Pocket commands give "Please login." even if account is logged in

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1410]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
A Pocket account is logged in.
A website that is to be saved in Pocket is opened and made active, e.g. https://en.wikipedia.org/wiki/Vincent_van_Gogh. 

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a Pocket command, e.g. "Save page to Pocket", "Pocket this", "Save this to pocket".

### Expected result:
Information is saved to Pocket successfully.

### Actual result:
An "Error saving" is displayed in the tab.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-30).

![1](https://user-images.githubusercontent.com/54401091/77915619-761a7280-72a0-11ea-89a7-22de136067de.gif)

**Comment by annlinros** [comment]
I will check it @alexandra-martin

**Comment by annlinros** [comment]
@ianb I checked into the issue and realised the bookmarklet function that I added will only work for my account.
It is such that, pocket provides distinct bookmarklet for each accounts. 
Is there any other work-around for it ?

https://help.getpocket.com/article/1061-bookmarklet-error-wrong-account

**Comment by alexandra-martin** [comment]
Commands tested again on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-11).
"Error saving" is not displayed anymore in the tab, but "Please login." is displayed instead, even if there is a Pocket account logged in. Also the page is not added to the Pocket account.

![2](https://user-images.githubusercontent.com/54401091/81698751-19010780-946f-11ea-8c4e-be7db22acd6e.gif)

**Comment by ianb** [comment]
I fixed this recently.
