### ISSUE TITLE
"Previous song" command not working in SoundCloud

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1417]
### Prerequisites:
Mic permissions and autoplay are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
A "Play" command is made in SoundCloud and a few songs are played or skipped. 

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Previous song" command.

### Expected result:
The previous song starts playing.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-30).

![4](https://user-images.githubusercontent.com/54401091/77936210-40cf4e00-72bb-11ea-9397-6f6ec2f0a08a.gif)

**Comment by melvin2016** [comment]
Let me look at it

**Comment by melvin2016** [comment]
@ianb @alexandra-martin Please verify.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-07).

![7](https://user-images.githubusercontent.com/54401091/78678571-cec9bb00-78f1-11ea-9f74-f82c606b6847.gif)
