### ISSUE TITLE
"Access To Website Blocked" when making a "Search Ticketmaster" command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1419]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search Ticketmaster" command, e.g. "Search Ticketmaster for design".

### Expected result:
Ticketmaster opens in a new tab and a search is made.

### Actual result:
"Access To Website Blocked" is displayed in the new opened tab.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-30).

![5](https://user-images.githubusercontent.com/54401091/77936808-1631c500-72bc-11ea-8e6a-ef3fcf806218.gif)

**Comment by dave-ok** [comment]
@alexandra-martin I am unable to reproduce the bug

![Search for page bug](https://user-images.githubusercontent.com/19638455/78039879-93197900-7366-11ea-8ee7-59b493b233eb.gif)

**Comment by annlinros** [comment]
@alexandra-martin I also failed to reproduce the bug and got the same results as @dave-ok

**Comment by alexandra-martin** [comment]
@dave-ok @annlinros Seems I might have been blocked intentionally, because Ticketmaster thought I was a bot :)). On forums people are saying that it should go away after 24 hours, but I am still not able to reach the website. I'm wondering if it has something to do with my location, as well.

**Comment by dave-ok** [comment]
@alexandra-martin Sorry you were locked out. Does this mean this issue can be closed?

**Comment by alexandra-martin** [comment]
@dave-ok yes, since it's only from my end. Will contact Ticketmaster to solve the issue.
