### ISSUE TITLE
 Add album/playlist search to Deezer

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1424]
#1293 added album and playlist support to Spotify and YouTube, it could also be added to Deezer

**Comment by melvin2016** [comment]
I would like to do this.

**Comment by awallin** [comment]
Go for it @melvin2016

**Comment by melvin2016** [comment]
@awallin I have added a PR :) .

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-14).
Commands work if made in the Deezer tab. If commands are made from other tabs, it acts like in #1340. 
Will verify the intent again after #1340 is fixed.

**Comment by melvin2016** [comment]
@alexandra-martin 

This was working till the [commit](7b5c1eec4f773083177b96bf4165139d548beb8f).

![Screen-Recording-2020-04-14-at-9](https://user-images.githubusercontent.com/22199666/79245489-ca734400-7e95-11ea-97e2-dde6f4fae712.gif)
