### ISSUE TITLE
"Search"/"Play" SoundCloud commands give various errors in doorhanger

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1431]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a SoundCloud command, e.g. "Search SoundCloud for Green Day", "Play Green Day on SoundCloud", "Search SoundCloud for Coldplay".

### Expected result:
SoundCloud opens in a new tab without issues.

### Actual result:
SoundCloud opens in a new tab and several errors are displayed in the doorhanger, depending on the commands made.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-30).
Reproduced when user is signed in or not signed in on SoundCloud.
Errors displayed in the doorhanger are as followed:
- "Internal error: Error: No matching message handler";
- "Internal error: Error: Missing host permission for the tab";

![1](https://user-images.githubusercontent.com/54401091/78022311-67de5c00-735d-11ea-9e83-1c36cf33bf63.gif)

**Comment by melvin2016** [comment]
This was shown to Spotify, Soundcloud when trying to open it from a `about:blank` page.

**Comment by melvin2016** [comment]
@alexandra-martin I can't seem to generate the issue might have been fixed I think.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22199666/78224315-f7af1200-74e5-11ea-9354-2c10846a3673.gif)

**Comment by melvin2016** [comment]
@alexandra-martin I can't seem to generate the issue. Might have been fixed along the way.
![Screen-Recording-2020-04-02-at-1](https://user-images.githubusercontent.com/22199666/78224646-858afd00-74e6-11ea-9a1c-8fcbc14e73a4.gif)

**Comment by alexandra-martin** [comment]
@melvin2016 yes seems like it, I am not getting the errors anymore. Will check on it tomorrow as well, in case of any changes. But if all is alright, I will close the issue.

**Comment by alexandra-martin** [comment]
Verified again on Mac 10.14 with Firefox Nightly 76.0a1 (2020-04-03) and the issue is not reproducing anymore. 
Will close the bug for now.

![4](https://user-images.githubusercontent.com/54401091/78359596-0c5ed900-75be-11ea-90c5-7a6b349425d7.gif)
