### ISSUE TITLE
Scrolling not working on Wikipedia and other pages

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1433]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)
Have an active Wikipedia tab opened.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Scroll" command, e.g. "Scroll down", "Scroll to top" (if page scroll bar is not at the top), "Scroll all the way down", "Scroll up".

### Expected result:
Page scrollbar acts accordingly to the command made.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-31).
Reproduced also on Instagram, Twitter.
Not reproduced on Youtube, Facebook, Bugzilla.

![2](https://user-images.githubusercontent.com/54401091/78037952-e397d300-7374-11ea-9791-afbaea49c1b2.gif)

**Comment by dave-ok** [comment]
@ianb Can I take a look at this?

**Comment by dave-ok** [comment]
@ianb I was thinking of solving this using a PageDown/Up event trigger. I don't know if there is any particular reason why it is not currently used. The keyboard event seems to be consistent across various sites. And it looks like the current scroll state is not returned or used anywhere else, hence, there may not be real need for it. So I was wondering maybe this direction might work? Please, when you can, could you let me know your thoughts on this? Thanks

**Comment by ianb** [comment]
@dave-ok Sure, but I don't know what exactly the fix for this will be. #1229 fixed some of this. I attempted to fix this with `runCommand("cmd_scrollPageDown")` in #1003 which didn't work. Maybe there's something else, or maybe one of these techniques just need to be tweaked for wikipedia, but... I'm not sure?

**Comment by dave-ok** [comment]
Thank you @ianb. I'll try a different approach and anticipate your thoughts on it

**Comment by dave-ok** [comment]
I have created a PR #1451 that should fix this issue

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-04-03).

![1](https://user-images.githubusercontent.com/54401091/78359842-80997c80-75be-11ea-90b9-f93eb559ad4d.gif)
