### ISSUE TITLE
Feedback border on timer

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1437]
When the timer is displayed there should not be a white boarder around the feedback section.

![timer-with-border](https://user-images.githubusercontent.com/428245/78053374-5d0fd100-7335-11ea-9921-cdaec7cec8b5.jpg)

![Confirm timer](https://user-images.githubusercontent.com/428245/78053368-5b460d80-7335-11ea-8caa-be6d8db196dc.jpg)

**Comment by noi5e** [comment]
I can work on this one today!

**Comment by awallin** [comment]
Go for it @noi5e

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-09).
#1504 has been made for follow-ups.

![3](https://user-images.githubusercontent.com/54401091/78897937-a4a40480-7a7b-11ea-88bf-2cfff6624831.gif)
