### ISSUE TITLE
Timer controls 'Cancel', 'pause', and 'reset'

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1439]
When a timer is in progress a tip appears next to the timer at the bottom of the doorhanger informing the user they can say 'cancel', 'pause' or 'reset'. Currently all those utterances must be followed by "timer". They should work even if "timer" is not part of the utterance.

<img width="403" alt="Screen Shot 2020-03-31 at 1 26 55 PM" src="https://user-images.githubusercontent.com/428245/78072240-9e16de00-7353-11ea-9a45-481c264d6eb0.png">

**Comment by Simpcyclassy** [comment]
This is a quick one,  I am taking it please

**Comment by Simpcyclassy** [comment]
Here are the constraints I found while working on this. `cancel` is already an inbuilt command that closes the doorhanger and so does not work for timer. `pause` is a command in `music.toml` so does not work on `timer`. `reset` works fine.


I went ahead to search for synonyms for `cancel` and `pause`, so I tried `exit` and `wait` respectively. Please, let me know if these are OK then I will go ahead and create a PR

**Comment by awallin** [comment]
Is it possible to preference control of the timer (when it's active) for `cancel` and `pause`?

**Comment by Simpcyclassy** [comment]
I will look into that and get back to you

**Comment by Simpcyclassy** [comment]
@ianb I will be needing your help here, please. May I know if there is a way I can set a preference for commands?

**Comment by ianb** [comment]
@Simpcyclassy There's no preference really, instead you'll have to add some code to "cancel" and "pause" to call the other intent if there's an active timer.

Probably the simplest way for now is to export a `canPause` and `canCancel` function from intents/timer/timer.js and use those in `self.cancelIntent` and `music.pause` to decide what it should do.

**Comment by Simpcyclassy** [comment]
OK thanks. It's a little tricky for me though, once I am able to work it through I will request your request your review.
