### ISSUE TITLE
Error when running the npm install command on Windows

### ISSUE THREAD

**Issue by madalincm** [mozilla/firefox-voice#144]
#### Description:
Currently there are errors displayed, and the install process is not completed, when the npm install command is run.

#### Notes:
Verified in Win7x64
Node version: 10.15.1
Logs for the `npm run postinstall` command (short version): [2019-08-27T15_13_17_350Z-debug.log](https://github.com/mozilla/firefox-voice/files/3546915/2019-08-27T15_13_17_350Z-debug.log)
Logs for the `npm install` command (full version): [2019-08-27T15_12_36_648Z-debug.log](https://github.com/mozilla/firefox-voice/files/3546933/2019-08-27T15_12_36_648Z-debug.log)

**Comment by alexandra-martin** [comment]
Verified in Win10x64
Node version: 10.16.3
Npm version: 6.9.0
The installation process is still displaying errors, and could not be completed, when the npm install command is being run. 
Logs for the npm run postinstall command (short version): [2019-08-28T08_19_57_132Z-debug.log](https://github.com/mozilla/firefox-voice/files/3549927/2019-08-28T08_19_57_132Z-debug.log)
Logs for the npm install command (full version): [2019-08-28T08_06_58_731Z-debug.log](https://github.com/mozilla/firefox-voice/files/3549921/2019-08-28T08_06_58_731Z-debug.log)

**Comment by madalincm** [comment]
Logs for all the commands:
`npm run build:changelog` - [changelog.log](https://github.com/mozilla/firefox-voice/files/3551948/changelog.log)
`npm run build:deps` - [deps.log](https://github.com/mozilla/firefox-voice/files/3551949/deps.log)
`npm run build:manifest` - [manifest.log](https://github.com/mozilla/firefox-voice/files/3551950/manifest.log)

**Comment by madalincm** [comment]
We found a workaround to install the add-on on all the needed platforms. Using [web-ext](https://www.npmjs.com/package/web-ext) we build the add-on on a Mac and we use that add-on to install it across all our operating systems.

**Comment by ianb** [comment]
For QA we'll have an automatically-created XPI soon, and that will mostly address your use cases. For developers we've recommend WSL in the README.
