### ISSUE TITLE
"Start presentation" Google Slides

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1440]
Similar to #1115 a user should be able to start the presentation of a Google Slide deck by saying things like.

* Start slideshow
* Present
* Start presentation
* Presenter view

**Comment by dave-ok** [comment]
Can I work on this @ianb

**Comment by awallin** [comment]
Go for it @dave-ok

**Comment by dave-ok** [comment]
Thanks @awallin I'm on it

**Comment by dave-ok** [comment]
@ianb Where do you suggest that I place this intent?

**Comment by dave-ok** [comment]
I have created a PR #1470 which should solve this. 
@awallin I created the match phrases you suggested but I skipped "Start slideshow" because slideshow is reserved for the "Slideshow" intent. I couldn't come up with more aliases right now

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-08).

![6](https://user-images.githubusercontent.com/54401091/78795278-7fe95780-79bd-11ea-8a66-5263411d62d8.gif)
