### ISSUE TITLE
[Alias] bookmarks and history intents

### ISSUE THREAD

**Issue by Simpcyclassy** [mozilla/firefox-voice#1443]
Creating aliases as suggested on my previous PR https://github.com/mozilla/firefox-voice/pull/1418

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-04-01).

![4](https://user-images.githubusercontent.com/54401091/78250061-fa1a6780-74f7-11ea-942e-af22b457f30d.gif)
