### ISSUE TITLE
Followup feature disables settings/feedback

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1473]
A regression from #1296 

If and only if I enable "keep the microphone on for follow up responses" the popup looks like this:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/44390/78392141-54c1cb00-75ad-11ea-81e1-3346d1d79aeb.png">

Note that the settings link and feedback link are gone. Turning off the pref restores them.

**Comment by JM-Mendez** [comment]
@ianb hi can you assign this to me. Already know where the fix is
