### ISSUE TITLE
Card display broken

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1474]
I believe this is a regression from #1296 

If I start the browser fresh, and say "weather in seattle" it does not show the card in the popup. Note that the followup preference doesn't effect this, but I did (I think) confirm it regressed specifically with #1296. I believe it's just the display of the card that is broken, as it otherwise acts like it would if there was a card (i.e., it doesn't open any page).

**Comment by amandhamija98** [comment]
hi, @ianb may I please be assigned this

**Comment by awallin** [comment]
I'm seeing this as well. The doorhanger with the transcript and confirmation remain in place but the card never appears. See attached.

We should fix before the next release.

<img width="1453" alt="Screen Shot 2020-04-16 at 1 57 35 PM" src="https://user-images.githubusercontent.com/428245/79506268-847bc480-7fea-11ea-9b25-b1f54f8aa3b4.png">
<img width="1453" alt="Screen Shot 2020-04-16 at 1 56 43 PM" src="https://user-images.githubusercontent.com/428245/79506269-85acf180-7fea-11ea-89f5-2fcc5a81962f.png">

**Comment by awallin** [comment]
@amandhamija98 you're welcome to take a look.

**Comment by amandhamija98** [comment]
Thank you, could you please point me where to look in the codebase, i believe i should look in popupView.js
