### ISSUE TITLE
Search page is reused for fallback searches

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1475]
I think this regressed with some of the recent search changes, but there's been too many for me to be certain where or when.

To reproduce:

1. Say "search for weather"
2. Say "weather in boston"

This *should* open a search page for 1, and then do a search in a hidden page for 2, and use the result in 2 to show a card. At this moment the card doesn't display, but that is tracked in #1474.

What *does* happen is that the search page opened in 1 is also used for the search in 2. When the card is displayed it's therefore superfluous, since the main search page also is displayed.

I'm assuming this is a problem with how `_searchTabId` is managed in `intents/search/search.js`

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-14).

![13](https://user-images.githubusercontent.com/54401091/79235182-f251b000-7e73-11ea-94bf-cbc323542503.gif)
