### ISSUE TITLE
Card Gives Internal Error while running same query multiple Times

### ISSUE THREAD

**Issue by maverick-27** [mozilla/firefox-voice#1478]
Steps to follow  to Reproduce:- 
Open the Fresh Browser .

1.Search for some query "Fastest Bullet"
2. Give the result 
3. Search again same query 

Actual Result : Internal Error : Error Communicate is not defined

**Comment by awuorm** [comment]
@maverick-27 @ianb  I am picking this task.

**Comment by awuorm** [comment]
@maverick-27 I am trying to reproduce this bug. Did you close the tab with the result when making the second search? Which OS and firefox nightly version are you on? I was able to do 4 searches on "fastest bullet" without getting the error. I am on windows 10, using firefox nightly 75.0a1 
![image](https://user-images.githubusercontent.com/53653844/78878998-f89ef100-7a5b-11ea-8972-4437889ac135.png)

**Comment by maverick-27** [comment]
Working Fine !!
