### ISSUE TITLE
Search "Close All Tabs" commands make a new Search

### ISSUE THREAD

**Issue by maverick-27** [mozilla/firefox-voice#1480]
Open The fresh Browser 
 Speak "Close All Tabs"

Actual Response : Makes a new Search

**Comment by awuorm** [comment]
@ianb can I pick this task?

**Comment by alexandra-martin** [comment]
@maverick-27, for me the command closes only the active tab, but it's not making a search.

![2](https://user-images.githubusercontent.com/54401091/78574920-5c92a100-7833-11ea-8570-059145a9884f.gif)

**Comment by awuorm** [comment]
Same here. It closed the current active tab without making a search. I am on windows 10 using Firefox Nightly Version 75.0a1
![image](https://user-images.githubusercontent.com/53653844/78581306-62d94b00-783c-11ea-85b5-e7903ec88bf7.png)

**Comment by vandnakapoor19** [comment]
I've also checked this issue. @alexandra-martin and @awuorm are correct. Right now it is just closing the active tab.

My concern is If we Speak/Write "Close All Tabs" it should close only the active tab or all the tabs?

As per my understanding, it should close all the tabs. Please let me know so I can implement the same.

**Comment by awuorm** [comment]
I have fixed this issue with pull #1495. Now the command close all tabs closes firefox instead of closing the active tab only.
