### ISSUE TITLE
Doorhanger result card disappears or error is displayed depending if command is vocal or written

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1482]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say a command that displays the result in the doorhanger, e.g. "Who created Breaking Bad".

### Expected result:
Result is displayed in the doorhanger without issues.

### Actual result:
Result is displayed for 1 second, then it disappears and the "Got it!" state is displayed with the command transcription. 

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 76.0a1 (2020-04-06).
Writing the command can give "Internal error: Error: communicate is not defined" in the doorhanger.
Doorhanger may change size when in the "Got it!" state, depending on the size of the result card.

![1](https://user-images.githubusercontent.com/54401091/78568256-81cee180-782a-11ea-836d-3fe21f491bb9.gif)

**Comment by vandnakapoor19** [comment]
@ianb I'd like to work on it.

**Comment by alexandra-martin** [comment]
Tested again today on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-04).
Vocal "Search" commands are currently not displaying Google cards.

![6](https://user-images.githubusercontent.com/54401091/81068245-b8128600-8ee8-11ea-91e9-28094ecb4cd7.gif)

Written commands are displaying the Google cards, but the "Internal error: Error: communicate is not defined" error is intermittently displayed in the doorhanger.

![7](https://user-images.githubusercontent.com/54401091/81068260-bea0fd80-8ee8-11ea-9140-8a536269a8a3.gif)

#1474 and #1569 relating this issue were closed, but will not be reopened, to not cause further duplicates.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-06).
Written commands are intermittently displaying the "Internal error: Error: communicate is not defined" error in the doorhanger.

![3](https://user-images.githubusercontent.com/54401091/81193258-d1d4cb80-8fc3-11ea-8629-68fb82fec917.gif)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-06).

![1](https://user-images.githubusercontent.com/54401091/81269373-e069c400-9051-11ea-8ff8-ec300890dfe6.gif)
