### ISSUE TITLE
Create registerPageName function in intentRunner

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1483]
This is a followup to #1302 (per this comment: https://github.com/mozilla/firefox-voice/pull/1302#discussion_r396027674)

Right now `navigation.js` is directly accessing `browser.storage`, but instead it should call functions in `intentRunner`. These new functions would use the same pattern as `intentRunner.registerNickname()`

**Comment by Simpcyclassy** [comment]
I will like to look into this
