### ISSUE TITLE
Add maximize support to Windows

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1488]
I'm pretty sure the "zoom window" command in #1434 is Mac-specific (at least my search in the code seemed to show that). We should find an equivalent way to do it on WIndows.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-15).

![3](https://user-images.githubusercontent.com/54401091/79351992-f9df8a80-7f41-11ea-8906-6957556d6698.gif)
