### ISSUE TITLE
Feedback emoticons not displayed properly in doorhanger

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1494]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar in the blank new tab.
2. Say or write a command that displays the result as a card in the doorhanger, e.g. "France".

### Expected result:
Doorhanger is displayed without issues.

### Actual result:
"Did we get this right?" emoticons are not displayed according to mock-ups.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-06).

Mock-up:
<img width="324" alt="Screenshot 2020-04-07 at 16 04 45" src="https://user-images.githubusercontent.com/54401091/78672934-0af91d80-78ea-11ea-8076-70d8b9f2b8f4.png">

![3](https://user-images.githubusercontent.com/54401091/78672963-151b1c00-78ea-11ea-9aa9-7e5be6a39d3e.gif)

**Comment by awallin** [comment]
Padding below smile icons should be 10px.

**Comment by vandnakapoor19** [comment]
@ianb I'd like to work on this. Please assign this task to me.

Please check PR https://github.com/mozilla/firefox-voice/pull/1502
@alexandra-martin I have made some changes in CSS for adjusting Feedback emoticons. Have a look once and let me know in case it is fine now.

Sample: 
![emotions_fix](https://user-images.githubusercontent.com/45131874/78724424-73042f80-78fb-11ea-9d40-f2c39e09983b.gif)

**Comment by awallin** [comment]
Go for it @vandnakapoor19

**Comment by vandnakapoor19** [comment]
@awallin Thanks for assigning me. I've already worked on this issue.
Please check pull request  https://github.com/mozilla/firefox-voice/pull/1502

Thanks

**Comment by vandnakapoor19** [comment]
@awallin If everything is working fine then please close this issue. Let me know in case I've to make any other changes?

**Comment by awallin** [comment]
Looks good closing.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-05).

![2](https://user-images.githubusercontent.com/54401091/81166910-fff2e500-8f9c-11ea-816d-8164de52afb8.gif)
