### ISSUE TITLE
Timer feedback display clean up

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1504]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar in the blank new tab.
2. Say or write a "Timer" command, e.g. "Set timer for 10 seconds".

### Expected result:
Doorhanger doesn't have display issues.

### Actual result:
There is a white line at the bottom of the black background from the doorhanger.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-06).
Also "Did we get this right?" needs to have a top padding of 15px to have a similar display like other commands (e.g. "Search voice").
The bottom white line is visible when doing other commands as well, like "Search lion".

![2](https://user-images.githubusercontent.com/54401091/78785566-07c86500-79b0-11ea-9670-82b724df69ae.gif)

<img width="1280" alt="Screenshot 2020-04-08 at 15 35 49" src="https://user-images.githubusercontent.com/54401091/78785585-10b93680-79b0-11ea-9784-62fcbb68ba8e.png">

**Comment by rohanharikr** [comment]
Would like to work on this!

**Comment by awallin** [comment]
Additionally there should be 10px of padding above "Did we get this right?" the visual of the feedback display for other utterances.

**Comment by awallin** [comment]
Go for it @rohanharikr

**Comment by rohanharikr** [comment]
@awallin Facing an issue. Stuck here:
<img width="387" alt="Screenshot 2020-04-09 at 2 05 52 AM" src="https://user-images.githubusercontent.com/12775813/78831072-a8497400-7a06-11ea-89bd-68c02851b787.png">

Firefox 76.0b2 (64-bit), Mac 10.15.3 (19D76)
Permission are enabled in browser and also under Privacy tab.

**Comment by awallin** [comment]
@rohanharikr are you unable to get any utterance to work? Does it not execute an action when you say something?

**Comment by rohanharikr** [comment]
This is happening in startup.

**Comment by awallin** [comment]
You might be encountering #860. @ianb any thoughts?

**Comment by rohanharikr** [comment]
@awallin I have made the padding fixes for the footer. 

I was not able to pinpoint where the white line was coming from in the css.
But on removing the first two .css imports from popup.css file,
/*@import url("../assets/css/inter.css");
@import url("../assets/css/gui.css");*/

the issue seems to be fixed.
<img width="440" alt="Screenshot 2020-04-10 at 2 59 57 AM" src="https://user-images.githubusercontent.com/12775813/78942581-9edc0c80-7ad7-11ea-9e04-6967966a7be0.png">

**Comment by alexandra-martin** [comment]
#### Update:
Additional display issue is observed:
- There is a white border on the right side of the black feedback background when doing a "Timer" command, which may cause the black background to not be centered in the doorhanger.

![8](https://user-images.githubusercontent.com/54401091/79229787-435da600-7e6c-11ea-9be1-22908c26371b.gif)

**Comment by rohanharikr** [comment]
@alexandra-martin I'm unable to reproduce the padding issue. 

<img width="1440" alt="Screenshot 2020-04-15 at 12 39 43 AM" src="https://user-images.githubusercontent.com/12775813/79264162-b9d0c700-7eb1-11ea-851f-a483165e4317.png">

**Comment by awallin** [comment]
I was able to reproduce using Version 0.19.5327.

<img width="1359" alt="Screen Shot 2020-04-14 at 12 49 51 PM" src="https://user-images.githubusercontent.com/428245/79267711-7729d300-7e4e-11ea-8efe-28b265df7a82.png">

**Comment by rohanharikr** [comment]
@awallin @alexandra-martin got the issue when taking a pull. working on the fix!

**Comment by rohanharikr** [comment]
Open another PR #1546 to fix this issue 

<img width="1440" alt="Screenshot 2020-04-15 at 12 39 43 AM" src="https://user-images.githubusercontent.com/12775813/79275608-205ee080-7ec4-11ea-95fa-4d1061b56afb.png">
