### ISSUE TITLE
Doorhanger display issue when doing a "Search" command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1505]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar in the blank new tab.
2. Say or write a "Search" command, e.g. "Search voice".
3. Place the mouse on the bottom part of the doorhanger and scroll horizontally using the bottom scroll bar.

### Expected result:
Doorhanger doesn't have display issues.

### Actual result:
There is a scrollbar present that shows a partial white border of the black background.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-08).

![3](https://user-images.githubusercontent.com/54401091/78788446-7efff800-79b4-11ea-9498-281430e13315.gif)

**Comment by vandnakapoor19** [comment]
@ianb @awallin I'd like to work on this.

**Comment by awallin** [comment]
Go for it @vandnakapoor19

**Comment by vandnakapoor19** [comment]
@alexandra-martin  I've made some CSS changes and tested on Local Machine.
Please have a look and confirm.
**System Configuration: -**
OS: Windows 10x64
Firefox Nightly: Version 75.0a1
Node: v12.16.1

![scroll_issue](https://user-images.githubusercontent.com/45131874/78839678-f0e13d00-79c6-11ea-851d-726483d7b8fe.gif)

**Comment by vandnakapoor19** [comment]
@awallin  If everything is working fine then please close this issue. Let me know in case I've to make any other changes?

**Comment by awallin** [comment]
Looks good. Closing.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-04).

![4](https://user-images.githubusercontent.com/54401091/81060384-002aac00-8edb-11ea-8c4a-cb0880f40133.gif)
