### ISSUE TITLE
[object Object] present in "Type Input" when "Developer tip" link is accessed from doorhanger

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1506]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar and wait a few seconds until the doorhanger extends.
2. Click the link under "Developer tip".

### Expected result:
"Type Input" doesn't have display issues.

### Actual result:
[object Object] is written in the "Type Input."

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-08).
Multiple tries may be needed for the doorhanger to successfully extend. Covering the mic may help.

![4](https://user-images.githubusercontent.com/54401091/78790425-2a11b100-79b7-11ea-9703-da72075bcb76.gif)

**Comment by Simpcyclassy** [comment]
I will like to fix this @ianb
