### ISSUE TITLE
"Go to"/ "Open" commands give error in doorhanger

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1507]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Go to New York Times" command.

### Expected result:
New York Times opens in a new tab.

### Actual result:
"Internal error: TypeError: can't access property "new york times", pageNames is undefined" is displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-08).

![5](https://user-images.githubusercontent.com/54401091/78793464-1f591b00-79bb-11ea-8621-5065bc72b6f3.gif)

**Comment by fleur101** [comment]
Oops. This is coming from my recent pull request, I'll fix it.

**Comment by fleur101** [comment]
So, the problem was that I missed an additional check when implementing a page naming feature. Now it is there. Could you please check it? @alexandra-martin

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-14).

![5](https://user-images.githubusercontent.com/54401091/79228962-f4634100-7e6a-11ea-9ac8-7aa70f003edf.gif)
