### ISSUE TITLE
Weather on Android App

### ISSUE THREAD

**Issue by jofish** [mozilla/firefox-voice#1511]
Bug: A query like "What's the weather in San Francisco" is interpreted as a request for directions to San Francisco. 

I don't know if there's a category for default weather apps on Android; this might be a good thing to just fire off directly into the browser, but we should handle this.

**Comment by espertus** [comment]
Thanks! It's a false positive for the phrase "What's the [something] in [place]", which we created for questions like "What's the best sushi in San Francisco?"
