### ISSUE TITLE
Inform users about required permissions before installing the extension

### ISSUE THREAD

**Issue by JM-Mendez** [mozilla/firefox-voice#1516]
A user in the chat room stated that it was a bit shocking seeing all the permissions that were requested on the first use of the extension. The suggestion they proffered was to link to the privacy policy on the page where a user installs the extension, so that a user can read it beforehand.

Not sure if others have had a similar experience, so I created this issue in their behalf to track it in case.

**Comment by ianb** [comment]
We'll put a section in the FAQ to describe what the permissions are for
