### ISSUE TITLE
Options page says data is "deleted after x months"

### ISSUE THREAD

**Issue by brianrhea** [mozilla/firefox-voice#1518]
The supporting copy under "Allow Firefox Voice to send anonymized transcripts of your audio request" on the Options page reads:

> Data is stored on Mozilla servers, never shared with other organizations and deleted after x months.

"x months" should be updated to reflect current storage policies.

**Comment by awallin** [comment]
Thanks for finding that @brianrhea. We'll get the correct x in there.

**Comment by ianb** [comment]
This has been fixed
