### ISSUE TITLE
Links to "Things you can say" and "Privacy" result in 404 after following the "How Mozilla Protects Your Voice Privacy" link on the Options page.

### ISSUE THREAD

**Issue by brianrhea** [mozilla/firefox-voice#1519]
**Steps to Reproduce:**
- Open the popup window by clicking the icon or with the keyboard shortcut
- Click the Settings gear icon in the bottom left of the popup window
- Scroll down and follow the "How Mozilla Protects Your Voice Privacy" link in the About section
- Click either of the "Things you can say" or "Privacy" links at the top of the page

**Expected Result:**
- "Things you can say" would load lexicon.html content
- "Privacy" would load privacy-policy.html content

**Actual Result:**
- Both pages result in 404s

**Suggested Fix:**
- Link "How Mozilla Protects Your Voice Privacy" to `/views/privacy-policy.html`

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-20).

![3](https://user-images.githubusercontent.com/54401091/79846788-874e2f00-83c7-11ea-9aa5-7e019ded7a32.gif)
