### ISSUE TITLE
Sorry, there was an issue' text recommendation for misheard commands

### ISSUE THREAD

**Issue by Githubuxer** [mozilla/firefox-voice#1524]
When Firefox Voice doesn't hear a proper audio command, it says 'Sorry, there was an issue' with a red exclamation mark below. Shouldn't it be something more casual like 'I did not hear that, please try again' or simply 'Please try again', or 'Can you repeat that'

The text 'Sorry, there was an issue' makes it seem like a technical issue vs just needing the user to repeat or speak a command.

**Comment by awallin** [comment]
@ianb The more causal and clear language of "I didn't hear that, please try again" is a good suggestion. Can we be confident when this error message is displayed the issue is garbled or no audio?

**Comment by ianb** [comment]
The error message itself isn't shown in the next release (it came from the speaktomeserver).

I guess technically the error gives us a distinction between noise that didn't parse into any text, and silence that was locally detected.

**Comment by ianb** [comment]
We'll fix it as described in #1673
