### ISSUE TITLE
Commands that need to go through "Redirect Notice" to open a page are not working properly

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1526]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Go to Goodreads" command.

### Expected result:
Goodreads opens in a new tab.

### Actual result:
The tab doesn't go through the "Redirect Notice" to display the actual page and the doorhanger remains in the "One second..." state.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-13).

![2](https://user-images.githubusercontent.com/54401091/79118883-b812e080-7d97-11ea-94e1-728046015cf6.gif)

**Comment by awallin** [comment]
@ianb We should solve this before the next release.

**Comment by vandnakapoor19** [comment]
@ianb @awallin I'd like to work on this.

**Comment by awallin** [comment]
Go for it @vandnakapoor19

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 77.0a1 (2020-05-03).

![1](https://user-images.githubusercontent.com/54401091/80966839-f68f3e80-8e1d-11ea-9673-012f970decea.gif)
