### ISSUE TITLE
Put history pagination controls at top and bottom

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1529]
I think in the History view (#1453) the pagination controls could be at the top and bottom. Especially if you increase the page size (e.g., show 100 items at a time) it's awkward at the bottom.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-22).

![3](https://user-images.githubusercontent.com/54401091/80118606-502b7980-8591-11ea-9ff9-a0e9e7d3c444.gif)
