### ISSUE TITLE
Change "utterance" label in history

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1531]
In the history added in #1453 it uses the term "utterance", which I think is an insider term that we shouldn't show to users:

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/44390/79139406-dff44b00-7d7b-11ea-82a1-cc8aee5d2366.png">

@awallin Label thoughts? I can imagine calling it "You said...", or "Your command"

**Comment by awallin** [comment]
Let's go with "You said..."
