### ISSUE TITLE
Visual clean up History

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1542]
These are visual specific fixes (and a couple minor functional tweaks) for the display of voice history in preferences. See attached mockup.

Separate issues are being added for larger functional additions. #1543 #1544 #1545 

* Remove drop shadow around table
* Remove hover state on rows
* Update row style & size. Height 38px, alternative background color of #F2F2F2
* Change order of columns. "You said..." should be first
* Unless there's a performance issue loading 50 rows by default let's remove the option to choose number of rows and simply have pagination move through 50 at a time. There's enough real estate to rely on scrolling.
* Clear history should be a button

![history](https://user-images.githubusercontent.com/428245/79274737-dd682300-7e59-11ea-874f-76e5d3e806e4.jpg)

**Comment by annlinros** [comment]
@awallin  I would really like to work on this!

**Comment by awallin** [comment]
All yours @annlinros

**Comment by annlinros** [comment]
Thanks :)
