### ISSUE TITLE
"Zoom window" gives "Internal error: Error: An unexpected error occurred" when made on Windows

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1548]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Zoom window" command.

### Expected result:
If the command is not supported on the used device, a message stating that is displayed in the doorhanger together with the correct command that needs to be used on that device.

### Actual result:
"Internal error: Error: An unexpected error occurred" is displayed in the doorhanger.

### Notes:
Reproduced on Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-15).
Not reproduced on Windows for the "Maximize window" command.
on Mac 10.14 both "Zoom window" and "Maximize window" are working as intended.

![2](https://user-images.githubusercontent.com/54401091/79354640-52fced80-7f45-11ea-8101-8007d9dbe6fc.gif)

**Comment by alexandra-martin** [comment]
@awallin what do you think that doorhanger message should be like?

**Comment by awallin** [comment]
Instead of an error message we should probably execute a similar command on Windows.

Can we not maximize the active window or zoom in on Windows?

**Comment by alexandra-martin** [comment]
@awallin from what I understood, on Windows "Maximize window" is the equivalent of "Zoom window" which was first implemented for Mac. Now I'm not sure about the code behind the commands, but on Mac I was able to use both commands correctly, while on Windows only "Maximize window" works, while "Zoom window" gives that error in the doorhanger.

**Comment by Simpcyclassy** [comment]
Please I will like to look into this

**Comment by Simpcyclassy** [comment]
> Instead of an error message we should probably execute a similar command on Windows.
> 
> Can we not maximize the active window or zoom in on Windows?

I  see that different commands handle the "zoom window" and "maximize window". The fix should be to make one command handle both utterances

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-20).

![1](https://user-images.githubusercontent.com/54401091/79845415-aea3fc80-83c5-11ea-9b13-83f743a7b7b0.gif)
