### ISSUE TITLE
When alarm finishes play audio twice

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1549]
Currently the audio for a completed alarm only plays once. As it's only a couple seconds we should play it twice heard even if the user is a few feet away from their computer.

**Comment by ianb** [comment]
To do this reliably we should probably just turn the file into the length we want.

**Comment by Simpcyclassy** [comment]
I try to set alarm I type "set alarm 2 minutes from now", it takes me to this [link](https://setalarmclock.net/set-timer-for-2-minutes) instead. I assume that is not the expected behaviour.

**Comment by awallin** [comment]
Looks like that is a bug. Phrases like "Set alarm for 2 minutes" should start that native timer.
