### ISSUE TITLE
Zap animation overlays parts of the text in the doorhanger

### ISSUE THREAD

**Issue by madalincm** [mozilla/firefox-voice#155]
### Steps to reproduce:
1. Click on the mic icon from the browser toolbar.
2. Start typing a command
3. Click the back button from the top-left of the doorhanger

### Expected result:
There are no display issues. 

### Actual result:
The Zap animation is displayed over other text displayed in the doorhanger

### Notes:
Reproduced on Win7x64 with Firefox Nightly 70.0a1 (64-bit)
Please view this screencast:
![zapDisplayIssue](https://user-images.githubusercontent.com/15685441/64028049-9d626300-cb4a-11e9-9f84-d2dc07398c7e.gif)

**Comment by ianb** [comment]
I think this is fixed, probably by #275 again

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![59](https://user-images.githubusercontent.com/54401091/65435632-83563080-de29-11e9-8305-a317ffc28ced.gif)
