### ISSUE TITLE
"View bookmarks sidebar" displays a card in doorhanger

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1552]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "View bookmarks sidebar" command.

### Expected result:
The bookmark sidebar is displayed in the window.

### Actual result:
A Google card is displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-16).
In case for "View bookmark sidebar" a new tab opens with a result.
"Bookmark sidebar", "Bookmarks sidebar", "Open bookmark sidebar" and "Open bookmarks sidebar" work as intended.  
Logged, as according to #373, the utterance was seen in telemetry.

![2](https://user-images.githubusercontent.com/54401091/79469503-e9461780-8008-11ea-97eb-83fea049e072.gif)

**Comment by Simpcyclassy** [comment]
I will fix this

**Comment by Simpcyclassy** [comment]
I will like to fix this

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 77.0a1 (2020-05-03).

![4](https://user-images.githubusercontent.com/54401091/80970302-9c917780-8e23-11ea-97b8-b8934e1e8ff2.gif)

**Comment by alexandra-martin** [comment]
@Simpcyclassy sorry, while looking closely, I think the changes were made in the command intent for opening the bookmark window, because the bookmark sidebar is not displaying anymore, since "(sidebar |)" from "browser.bookmark" probably blocks the intents from "sidebar.openSidebar". Will reopen this report again for the changes to be made in the corresponding command intent and for the "(sidebar |)" from "browser.bookmark" to be removed. I think you can leave "View" in the "browser.bookmark" intent , it isn't bad to have a consistency between the commands.

**Comment by Simpcyclassy** [comment]
Alright, will fix it. One of the commands has to go then since the both achieve the same thing. It will be an alias instead

**Comment by alexandra-martin** [comment]
Isn't it similar with how the history commands work? The only difference is having "sidebar" in a command to change what to open.

![5](https://user-images.githubusercontent.com/54401091/80974549-8c7c9680-8e29-11ea-85da-42fe031000c9.gif)

**Comment by Simpcyclassy** [comment]
Correct. It is
