### ISSUE TITLE
Keypress for Firefox Voice is overlapping with 1Password

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/firefox-voice#1554]
On Mac, when you use 1Password, you can use a combination of command + period to unlock the app so you can fill out your password. However, today I just realized that it overlaps with Firefox Voice keypress. So, when I  press command + period, it triggers Firefox Voice instead of unlocking 1Password. I have to disable Firefox Voice in order to continue using 1Password.

**Comment by awallin** [comment]
@kelimuttu Unfortunately there are a number of app with conflicting keyboard shortcuts. For both Firefox Voice and 1Password you can set a custom keyboard shortcut in the preferences section. Try changing the keyboard shortcut for either one of them and they'll happily co-exist.

**Comment by kelimuttu** [comment]
I didn't know if we're able to do that. Thanks, @awallin

**Comment by awallin** [comment]
@kelimuttu In Firefox Voice try these steps:

- Click the mic icon to trigger listening
- In the popup click the gear icon in the lower left
- In the preferences screen you should see a "Keyboard shortcut" section (see attached screenshot)
- Click in the input box and type a new keyboard shortcut of your choice

<img width="1298" alt="Screen Shot 2020-04-16 at 10 30 28 AM" src="https://user-images.githubusercontent.com/428245/79487779-98fd9400-7fcd-11ea-877e-20839735ea65.png">

**Comment by kelimuttu** [comment]
I've managed from the Manage Extension Shortcuts menu in Firefox. Thanks, though!
