### ISSUE TITLE
'Look up...' should return search result

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1556]
A phrase like `Lookup fish taco recipes` should return a result from the default search engine. At some point this was change to return the first result. @ianb we should correct this before the next release.

**Comment by vandnakapoor19** [comment]
@awallin @ianb I'd like to look on this issue.

**Comment by awuorm** [comment]
@awallin  I am trying to work on this issue, would this be a preferable scenario where the command `Lookup fish taco recipes on food network` returns the fish taco recipes on food network vs `Lookup fish taco recipes` should return the results from the search engine.

**Comment by awuorm** [comment]
I have opened a PR for this issue #1558. The results for the diferrent phrases now have these results
`Lookup for houses on pinterest`
![Screenshot (1881)](https://user-images.githubusercontent.com/53653844/79571625-29b69b80-80c4-11ea-818d-b89bc53e2645.png)
vs `Lookup for houses` 
![Screenshot (1882)](https://user-images.githubusercontent.com/53653844/79571706-510d6880-80c4-11ea-92e0-089d6beb4afc.png)

**Comment by awallin** [comment]
Looking good @awuorm. When I tested the PR I noticed not all modifier (e.g. "...on pinterest") resulted in a search on that site. Does it only use the modifier if there is a bang search available?

**Comment by awuorm** [comment]
Yes it looks like it only works if the bang search is available, I also tried `lookup fish taco recipes on delish" and it returned a google search page instead of opening the site.

**Comment by awallin** [comment]
Makes sense. Works great.

**Comment by ianb** [comment]
I believe this is fixed (at least "Lookup fish taco recipes" opens a search page).

**Comment by awuorm** [comment]
Glad I could help :)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 77.0a1 (2020-05-03).

![2](https://user-images.githubusercontent.com/54401091/80969470-54258a00-8e22-11ea-9ff6-39930a502c71.gif)
