### ISSUE TITLE
'show options' intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1559]
Based on telemetry users are saying 'show options' expecting to see a list of what they can say.

`show options` should be an alias for 'help' which opens the lexicon.

**Comment by Simpcyclassy** [comment]
I will like to fix this

**Comment by awallin** [comment]
Go for it @Simpcyclassy

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-20).

![2](https://user-images.githubusercontent.com/54401091/79846491-2f172d00-83c7-11ea-9dad-a35221ba5776.gif)
