### ISSUE TITLE
Clicking inside the doorhanger blocks the user from typing a command

### ISSUE THREAD

**Issue by madalincm** [mozilla/firefox-voice#156]
### Steps to reproduce:
1. Click on the mic icon from the browser toolbar.
2. Click inside the doorhanger (anywhere on the white space)
3. Start to write a command

### Expected result:
The user can write the command

### Actual result:
Anything that the user types does not appear in the doorhanger

### Notes:
Reproduced on Win7x64 with Firefox Nightly 70.0a1 (64-bit)
Please view this screencast:
![clickDoorhangerNoKeyboardInput](https://user-images.githubusercontent.com/15685441/64028615-a142b500-cb4b-11e9-9253-8ff1a84844b6.gif)

**Comment by ianb** [comment]
The fix is whenever the input element is unfocused (onblur), we just re-focus it again.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![1 done](https://user-images.githubusercontent.com/54401091/67551644-15e03d00-f712-11e9-8d21-68d0e581a469.gif)
