### ISSUE TITLE
'Sign in' and 'sign out' intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1560]
Sign in and sign out are common links/functionality on many websites. To make the process more efficient Firefox Voice could click the link for a user.

When a user says `Sign in` (or login, log me in, sign me in) Firefox Voice should look for a matching link/button on the page and click it taking the user to the appropriate page/form.

When a user says `Sign out` (or log out, log me out, sign me out) Firefox Voice should look for a matching link/button on the page and click it.

If these the appropriate link can't be found a message saying so should be displayed (see attached).

![sign-in-not-found](https://user-images.githubusercontent.com/428245/79609064-f0256680-80aa-11ea-9743-b56860ed7d8e.png)

**Comment by Simpcyclassy** [comment]
May I look at this?

**Comment by awallin** [comment]
Go for it @Simpcyclassy
