### ISSUE TITLE
Consecutive written commands should be treated individually

### ISSUE THREAD

**Issue by madalincm** [mozilla/firefox-voice#157]
### Steps to reproduce:
1. Click on the mic icon from the browser toolbar.
2. Enter a simple search term (I.e: Fox) and press the enter key
3. Enter a more complex command (I.e: Play United States Anthem)

### Expected result:
The commands are treated individual. The last command should open a video on youtube

### Actual result:
A search is performed for the "foxplay Unted States Anthem" keyword

### Notes:
Reproduced on Win7x64 with Firefox Nightly 70.0a1 (64-bit)
Please view this screencast:
![consecutiveCommandsIssue](https://user-images.githubusercontent.com/15685441/64029856-131bfe00-cb4e-11e9-9d35-5a1b220d3c72.gif)

**Comment by ianb** [comment]
Related to #170 and others

**Comment by ianb** [comment]
I believe this is fixed by text input changes.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![73](https://user-images.githubusercontent.com/54401091/65863094-30740000-e378-11e9-9914-f023db786052.gif)
