### ISSUE TITLE
"Bookmark has been removed"\ "Command cancelled" are displayed in doorhanger if new command is made right after a "Remove bookmark" follow up "Yes"\ "Cancel" command  

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1570]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)
"Keep the microphone on for follow up responses" from "Settings" page is enabled.
A page is bookmarked and that page is made active.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Remove bookmark" command.
3. While the doorhanger is still open say "Yes".
4. While the doorhanger is still open say another command, e.g. "Search cat".

### Expected result:
The new result is displayed and the doorhanger has no display issues.

### Actual result:
The new result is displayed, but "Bookmark has been removed" is still displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 77.0a1 (2020-04-20).
The message will disappear if doorhanger is closed and open again for new commands.
Reproduce also if "Cancel" is made in step 3. In this case, the "Command cancelled" message is displayed in the doorhanger.

![14](https://user-images.githubusercontent.com/54401091/79867218-aa3c0b80-83e6-11ea-89f2-0dcd3bdbc4a1.gif)

![15](https://user-images.githubusercontent.com/54401091/79867222-ad36fc00-83e6-11ea-9f9a-274f721b4838.gif)

**Comment by Simpcyclassy** [comment]
This also seems to be fixed cannot replicate
