### ISSUE TITLE
Command duplicates in "Lexicon"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1575]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Lexicon" command, e.g. "Help", "Show options".
3. Scroll down to "Browser control" section.

### Expected result:
There are no display issues in the "Lexicon" page.

### Actual result:
There are command duplicates for "Full screen" and "Clear history".

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 77.0a1 (2020-04-22).

![lexicon](https://user-images.githubusercontent.com/54401091/80003151-43435300-84c9-11ea-9498-63ad1006532d.png)

**Comment by awallin** [comment]
Fixed in #1577

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-22).

![new lexicon](https://user-images.githubusercontent.com/54401091/80118248-d1364100-8590-11ea-848b-186d5e05ee39.png)
