### ISSUE TITLE
Long unbroken string are displayed in the same line

### ISSUE THREAD

**Issue by madalincm** [mozilla/firefox-voice#158]
### Steps to reproduce:
1. Click on the mic icon from the browser toolbar.
2. Enter a a long unbroken string I.E: "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"

### Expected result:
There are no layout issues. The string is automatically broken and surplus of text goes to the second row. 

### Actual result:
Long strings are displayed in the same line and scroll bar is displayed

### Notes:
Reproduced on Win7x64 with Firefox Nightly 70.0a1 (64-bit)
Please view this screencast:
![longUnbroketStringIssue](https://user-images.githubusercontent.com/15685441/64032082-6728e180-cb52-11e9-975b-e7456b916eff.gif)

**Comment by alexandra-martin** [comment]
#### Update:
Currently, if a long unbroken string is written, there will be display issues when the transcription appears in the "Doorhanger", before the command result is displayed and when feedback needs to be given for the command.

![7](https://user-images.githubusercontent.com/54401091/70132668-5aee7c00-168d-11ea-9436-ae4270fbf90c.gif)

![8](https://user-images.githubusercontent.com/54401091/70132701-65107a80-168d-11ea-8c4d-a2a3c03a1758.gif)

**Comment by GangaChatrvedi** [comment]
I would like to work on this.

**Comment by JM-Mendez** [comment]
@GangaChatrvedi The mentor might not be subscribed to this issue, and I don't see him in the list of participants. 

It's best to tag him when you request an issue. This way you can be sure he's notified. 

I'll tag him now for you

@ianb

**Comment by GangaChatrvedi** [comment]
Thanks @JM-Mendez

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-12).

![1](https://user-images.githubusercontent.com/54401091/76620052-ff0d7c00-6534-11ea-8e37-f7dfc3b82158.gif)
