### ISSUE TITLE
Add bang search for video sites

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1588]
Based on user request (https://github.com/mozilla/firefox_voice_community/issues/388) we should add the ability to search the following sites using DuckDuckGo bang searches.

JustWatch.com > !justwatch 
reelgood.com > !reelgood

**Comment by virgilt** [comment]
@awallin May I work on this?

**Comment by creatorpiyush** [comment]
Can I take this issue if no one is working on it?
