### ISSUE TITLE
Update opt-in content

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1612]
Update the opt-in message for both transcripts and voice recordings with the latest content from the content doc.

https://docs.google.com/document/d/17MnBTuO4Mxl7HZbYF6nxMVtni-MzuYLHkjtauvKiqxs/edit?ts=5eac8bdc#heading=h.4gsalsu8d4c3

**Comment by alexandra-martin** [comment]
Verified "Opt-in Voice Transcripts" on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-07).

![Annotation 2020-05-08 114331](https://user-images.githubusercontent.com/54401091/81397053-3f513b00-912f-11ea-85e2-798555f30299.png)

**Comment by alexandra-martin** [comment]
Verified "Opt-in Voice Recordings" on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-12). Content doesn't seems to be updated.

Screencast if https://voice.mozilla.org/firefox-voice/?source=commonvoice "Home" page is accessed before first clicking the add-on mic icon.

![1](https://user-images.githubusercontent.com/54401091/81822727-246e3480-953c-11ea-8a49-5063cb535c34.gif)

Screencast if https://voice.mozilla.org/firefox-voice/?ask-audio=1 "Home" page is accessed before first clicking the add-on mic icon.

![2](https://user-images.githubusercontent.com/54401091/81822644-11f3fb00-953c-11ea-9c09-0fff2e6ba61e.gif)
