### ISSUE TITLE
Update Content for Data Collection and Use

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1613]
Within the preferences page a number of changes to the content in "Firefox Voice Data Collection and Use" have been made. The full text should be updated with copy and paste from this content doc.

https://docs.google.com/document/d/17MnBTuO4Mxl7HZbYF6nxMVtni-MzuYLHkjtauvKiqxs/edit?ts=5eb195d1#

![FxVoice-data](https://user-images.githubusercontent.com/428245/81093582-2e969000-8eb7-11ea-9719-f63e7839ae56.png)

**Comment by ianb** [comment]
With the PR it will look like this:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/44390/81345346-e7a6c700-907d-11ea-9ca9-67313dba38c3.png">

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-10).

![settings](https://user-images.githubusercontent.com/54401091/81560507-31ebb900-939a-11ea-83f0-97bb2766ea03.png)
