### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1622]
Never text and slight change to layout based on updates from legal. Content available for copy and paste here:
https://docs.google.com/document/d/17MnBTuO4Mxl7HZbYF6nxMVtni-MzuYLHkjtauvKiqxs/edit?ts=5eb33c11#

![privacy](https://user-images.githubusercontent.com/428245/81238668-7dc3ea00-8fb7-11ea-8612-ed3485cd43bb.jpg)

**Comment by ianb** [comment]
Note I've created #1630 to update the styling, since  #1629 updates the content but not styles.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-10).

![1](https://user-images.githubusercontent.com/54401091/81560581-61022a80-939a-11ea-83da-54f1189f1041.gif)
