### ISSUE TITLE
"Mute / Unmute music" gives "Internal error: Error: No handler for mute / unmute" in Spotify

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1625]
### Prerequisites:
Mic permissions and autoplay are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
A Spotify account is logged in, the Spotify tab is active and music is playing.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Mute music" or "Unmute music" (after player is muted) command.

### Expected result:
Volume is adjusted accordingly.

### Actual result:
"Internal error: Error: No handler for mute / unmute" is displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-06).

![7](https://user-images.githubusercontent.com/54401091/81302192-b5e42f00-9082-11ea-8296-9a4d5b80bb3e.gif)

**Comment by awallin** [comment]
@alexandra-martin can you confirm what platforms this occurs on? Is it only Spotify or does this bug affect other music services, YouTube or any tab playing audio?

**Comment by alexandra-martin** [comment]
I encountered the error messages only on Spotify for "Mute music" and "Unmute music". On other supported music services (Youtube, Soundcloud, Deezer) they work, except the "Unmute music" on Youtube (#1626). On other sites (Twitch, Google Play Music, Tune In) nothing happens for these commands, because I'm assuming they are not added specifically as music services.
When in narration mode, "Internal error: TypeError: service.mute is not a function" and "Internal error: TypeError: service.unmute is not a function" are displayed in doorhanger for "Mute music" and "Unmute music". I can add a bug for that, to display a more pleasant message. 
"Mute" only stops narration (#481) and "Unmute" sometimes doesn't work when tab is manually muted (#1250). Otherwise they work as intended on all mentioned sites or modes, because of the more general use of the commands that affect the tabs and not the players inside the tabs.

**Comment by Ishakikani9117** [comment]
@ianb  Can I work on this issue?

**Comment by Ishakikani9117** [comment]
@ianb  One more problem that I encountered while using youtube is when you use "mute" command for mutation then only "unmute" can be used for unmutation. Other matching commands like "unmute music" "unmute volume" doesn't work. If you consider this as a bug then please tell me, I can work on it.

**Comment by Ishakikani9117** [comment]
> @ianb One more problem that I encountered while using youtube is when you use "mute" command for mutation then only "unmute" can be used for unmutation. Other matching commands like "unmute music" "unmute volume" doesn't work. If you consider this as a bug then please tell me, I can work on it.

@awallin @ianb what's your opinion about this?

**Comment by awallin** [comment]
@Ishakikani9117 Yes, "unmute music" and "unmute volume" should function to unmute the audio.
