### ISSUE TITLE
"Minimize window" gives "Internal error: Error: An unexpected error occurred" on Windows

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1627]
### Prerequisites:
Mic permissions and autoplay are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Minimize window" command.

### Expected result:
Browser window is minimized.

### Actual result:
"Internal error: Error: An unexpected error occurred" is displayed in the doorhanger.

### Notes:
Reproduced on Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-06).
Not reproduced on Mac 10.14.

![15](https://user-images.githubusercontent.com/54401091/81312851-c8189a00-908f-11ea-8208-303b4959625f.gif)

**Comment by awuorm** [comment]
Hi @alexandra-martin I'd like to work on this bug
