### ISSUE TITLE
Fix Privacy Policy styling

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1630]
The privacy policy looks like this:

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/44390/81342202-757fb380-9078-11ea-8e4b-86be0364527f.png">

It's supposed to look like this:

![image](https://user-images.githubusercontent.com/44390/81342225-829ca280-9078-11ea-8c37-852501b3b9ba.png)

**Comment by Simpcyclassy** [comment]
@ianb may I get the colors used for the texts.

**Comment by awallin** [comment]
@Simpcyclassy dark text color is #20123A, link blue is #0060DF, purple text is #952BB9
