### ISSUE TITLE
"Things you can say" and "Privacy" not linked with corresponding pages if accessed through new "Home" pages

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1646]
### STR:
1. Open https://voice.mozilla.org/firefox-voice/?source=commonvoice or https://voice.mozilla.org/firefox-voice/?ask-audio=1.
2. Click on the “Everything you can say” link from the “Things you can do” section, or the “Privacy” link from Footer.
3. Click on the “Things you can say” or “Privacy” link from the top right corner of the page.

### Expected result:
The "Lexicon" or "Privacy" page is displayed without issues.

### Actual result:
404 File not found is displayed in the new page.

### Notes:
Reproduced on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-12).
Also "Install Now" button from the "Lexicon" or "Privacy" page is non-responsive.  

![404](https://user-images.githubusercontent.com/54401091/81819655-3e0d7d00-9538-11ea-8c15-5fe3446f879b.gif)

**Comment by awallin** [comment]
@ianb Let's fix this before the next release.

**Comment by locness3** [comment]
Also happens from mozilla.github.io/firefox-voice. This is bad, because we can't access the privacy policy without digging around :(
