### ISSUE TITLE
"Opt-in Voice Recordings" styling

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1647]
### Prerequisites:
New Firefox Nightly profile and new add-on installation is made (through about:debugging).

### STR:
1. Make a new Firefox Nightly profile and temporarily install the add-on, but don't click the mic icon.
2. Open https://voice.mozilla.org/firefox-voice/?source=commonvoice. 
3. Use the shortcut or click on the mic icon from the browser toolbar.

### Expected result:
"Opt-in Voice Recordings" doesn't have styling issues. 

### Actual result:
"Opt-in Voice Recordings" is not updated in terms of styling.

### Notes:
Reproduced on Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-12).
Content of opt-in is reviewed in #1612.

Screencast if https://voice.mozilla.org/firefox-voice/?source=commonvoice "Home" page is accessed before first clicking the add-on mic icon.

![1](https://user-images.githubusercontent.com/54401091/81822727-246e3480-953c-11ea-8a49-5063cb535c34.gif)

Mock-up:

![onboarding voice samples](https://user-images.githubusercontent.com/54401091/81829249-6058c800-9543-11ea-9b1c-291017053c1f.png)

**Comment by awallin** [comment]
Closing this as the design has changed

**Comment by awallin** [comment]
@ianb the design is out of date. Is there a reason you assigned it to me?

For design consistency purposes it'd be great to update the opt-in/out screens to use the elements (Zap, fonts, etc) available in protocol but not sure if that's possible?
