### ISSUE TITLE
Long vocal commands are cut off after a few seconds

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#165]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say a vocal command with a long string e.g. “Play a long song but not too long because in 10 minutes I need to go”.

### Expected result:
The result page is displayed after the vocal command is finished.

### Actual result:
Vocal command is cut off after around 9 seconds and a result page is displayed with only a part of the command, visible also as a transcript in the “Doorhanger”.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 70.0a1 (64-bit).

![voice 2](https://user-images.githubusercontent.com/54401091/64122252-b9b00b00-cda9-11e9-8247-d9460bb44d0d.gif)

**Comment by ianb** [comment]
I think for the commands we are targeting 9 seconds will be enough
