### ISSUE TITLE
Opt-in/out display in telemetry dashboard

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1650]
Currently we only display the number of users who opt-in or out of transcriptions. For the next release we should update to understand how many people are opt-in/out for storing voice recordings.

On telemetry dashboard display the number and percent of users who have:
-  opted-in vs opt-out to transcriptions during installation
-  opted-in vs opt-out to voice recordings during installation

**Comment by ianb** [comment]
On the dashboard: 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/44390/82482714-dce82b00-9a9c-11ea-8db8-7232d56771fe.png">
