### ISSUE TITLE
"Show search results" opens a Google page if a "Search" command that displays a search list is made

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1653]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
A "Search" command that displays a search list through the default search engine is made, e.g. "Search hiking in Denver". Then "Next" command is made.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Show search results" command.

### Expected result:
The search list previously shown is displayed or since the hidden search tab is not used for this kind of "Search" command, display a message in the doorhanger.

### Actual result:
Google opens in new tab with no search made.

### Notes:
Reproduced on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-14).
Reproduced also if other search engines are selected as default, like Bing or DuckDuckGo.
Reproduced also if just the "Search hiking in Denver" command is made and the "Show search results" command is made from another tab or after the search list tab is closed. 
Not reproduced if command is made after a "Search" command that opens a card or opens a website.

![5](https://user-images.githubusercontent.com/54401091/82054701-07666c80-96c8-11ea-9e8a-97d9fb888a83.gif)

**Comment by danielamormocea** [comment]
@ianb I'm not sure if the tab with the results should be reused or not; I fixed the issue (it was a typo issue) and now it reopens a new tab with the previous search results list. Is this the right behaviour? Should I change the logic and reuse the tab when possible? (e.g. it's still opened).
