### ISSUE TITLE
Visual cleanup opt-in

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1659]
Clean up the following visual elements on the new opt-in screens implementation during #1657.

Technical and interaction opt-in:
- [x] Add checkmark next to "Successfully installed"
- [ ] Add zap underline as seen in step 2.
- [x] Add yellow highlight behind `Data is stored securely...`

Voice transcript (and voice recording) opt-ins
- [x] `You’ll always be able to use Firefox Voice, even if you don’t allow collection.` should be part of the previous paragraph.
- [x] Add yellow highlight behind `The microphone is only active when triggered with a button press or keyboard shortcut.`

**Comment by ianb** [comment]
I've done most of these in #1659, but there might be some adjustments on the yellow box, and I'm not sure about the zap underline

**Comment by awallin** [comment]
For the zap you should be able to copy the horizontal line already implemented in step 2.
