### ISSUE TITLE
Transcripted vocal commands don’t start with a capital letter

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#166]
### Prerequisites:
Mic permissions enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say a “Search...” vocal command, e.g. “Search Game of Thrones”.
3. Observe the vocal command transcript from the “Doorhanger”.

### Expected result:
Transcripted vocal command is starting with a capital letter.

### Actual result:
Transcripted vocal command doesn’t start with a capital letter.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 70.0a1 (64-bit).
The bug seems to be reproduced with any kind of vocal command.

<img width="1280" alt="Screenshot 2019-09-02 at 13 44 43" src="https://user-images.githubusercontent.com/54401091/64123953-65f3f080-cdae-11e9-8f41-fd3d5df399cb.png">

**Comment by xlisachan** [comment]
@ianb, can I be assigned to this issue?

**Comment by ianb** [comment]
@xlisachan Sure! I think it will be fine to just always capitalize the first letter of the utterance. That could even happen in `popupController.jsx`

**Comment by xlisachan** [comment]
@ianb Thanks! Both vocal and text commands have been capitalized, please let me know if you have any feedback. #1200

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-11).

![13](https://user-images.githubusercontent.com/54401091/76507723-f09c6300-6455-11ea-880a-fbfc50c615c2.gif)
