### ISSUE TITLE
“Find tab” command doesn’t find all pages with similar names

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#167]
### Prerequisites:
Mic permissions are enabled.
Have several tabs open with similar names, e.g several Youtube tabs opened with “Best of...” titles.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say the vocal command “Find best of tab”, “Find best of Youtube tab”, “Find best tab” or “Find best Youtube tab” several times.

### Expected result:
All tabs within the vocal command terms are found one by one after each command.

### Actual result:
Not all tabs are found after saying the vocal command several times.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).

![voice 3](https://user-images.githubusercontent.com/54401091/64159568-21fefb00-ce43-11e9-8c1c-18a238ece4fd.gif)

**Comment by ianb** [comment]
One solution here might be that "find tab" shouldn't find the current tab (since why would you ask to find the tab you are looking at?)

**Comment by alexandra-martin** [comment]
I originally tried with 4 tabs with similar names and after each vocal command it was switching between 2, max 3 of the tabs, not all of them. The gif was to big to upload, so I downsized to fit.

**Comment by ianb** [comment]
The fix in #603 isn't perfect, but at least it handles the obvious problem that "find" shouldn't find the active tab.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Currently the "Find tab" command finds 2 tabs out of the 3 opened. 
If I start the command from the tab which was not previously found, it will find the other 2 tabs and will focus only on those. (2nd gif) 
The same thing happens if 3 different service tabs with similar names are opened and the "Find tab" command is made several times. (3rd gif)
@ianb if you think there will not be more than 2 similar name tabs opened at once, then the issue remains closed. Otherwise this issue should be opened again.

![1](https://user-images.githubusercontent.com/54401091/69415781-eecf5800-0d1d-11ea-8e52-13847e2c5c42.gif)

![2](https://user-images.githubusercontent.com/54401091/69415792-f262df00-0d1d-11ea-9c1d-2f5307408a7b.gif)

![5](https://user-images.githubusercontent.com/54401091/69417227-e88eab00-0d20-11ea-80c1-ef717ca58318.gif)
