### ISSUE TITLE
Put mic selector in preferences

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1672]
Using [enumerateDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) we can let people select their microphone without changing permissions.

It would be nice to have this in the options, near the top. A select box would be fine.

**Comment by awallin** [comment]
Adding mockup.

![mic-selection](https://user-images.githubusercontent.com/428245/82612184-1db47280-9b77-11ea-8458-513e8c3695df.png)
