### ISSUE TITLE
Consecutive written commands are considered as one command in a search

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#168]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Write a command, e.g. “search lion” and press “Enter”.
3. Click the “Back” button from the top left side of the “Doorhanger”.
4. Write a new command, e.g. “search armadillo” and press “Enter”.

### Expected result:
The commands are displayed separately.

### Actual result:
The two written commands are considered as one command in a search.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Also the following behaviours were observed after performing the above steps:

- The first written command is displayed, when going back;
- The “Zap” animation is placed at the bottom of the “Doorhanger”, when going back;
- The “Zap” checkmark is displayed in the “Doorhanger”, when going back;
- Both commands have there titles displayed and the previous command has information displayed in the "Doorhanger" after searching the second term;
- No new vocal command can be made;

To avoid this issue, deleting a written command is made sometimes by pressing “Backspace” and sometimes by pressing “fn + Backspace” (so checking both ways is recommended, because the cursor is either in front or at the back of the written terms).

![voice 4](https://user-images.githubusercontent.com/54401091/64167148-482b9780-ce51-11e9-9daa-cde25096c8ca.gif)

**Comment by ianb** [comment]
I believe this was fixed by #280 or maybe a previous commit.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![40](https://user-images.githubusercontent.com/54401091/65320928-a4115280-dbab-11e9-847f-535b1945b654.gif)
