### ISSUE TITLE
"Next" on previous search result doesn't work

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1682]
To reproduce:

1. Execute search, e.g., "search for casserole recipes"
2. Execute second search, "search for couches"
3. Close second search, focus first search tab
4. Say "next"

It _should_ give you the next casserole recipe. But instead it continues the couch search. Note that continuing the couch search would be correct _except_ when the casserole recipe search tab is the active tab.

This is probably a regression, and code to do this should be in `search.js`, but just isn't working correctly.

**Comment by danielamormocea** [comment]
I can't reproduce this. Works as intended for me
