### ISSUE TITLE
Written command is placed in a text box after clicking the “Back” button from a vocal command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#169]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say a vocal command, e.g. “Search armadillo”.
3. Click the “Back” button from the top left side of the “Doorhanger”.
4. Write a command, e.g. “Search giraffe”.
5. Observe “Doorhanger”.

### Expected result:
The “Doorhanger” doesn’t have display issues.

### Actual result:
The written command is placed in a text box.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Also the following behaviours were observed after performing the above steps:

- “Type your request” title and “GO” green button are displayed;
- Written command text box is placed in front of the “Back” button and “Type your request” title. 

The written command can be continued by either clicking on the "GO" green button or by pressing the "Enter" key.
The "Back" button is still functional.

![voice 5](https://user-images.githubusercontent.com/54401091/64168489-54652400-ce54-11e9-86a7-aa354f315cc2.gif)

**Comment by ianb** [comment]
I believe this is fixed, in #253, specifically the commit 794066a1eaf1d75bdb2226a95d73c7cd9805966f

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![37](https://user-images.githubusercontent.com/54401091/65313122-85578f80-db9c-11e9-9f44-c3662ecdd38a.gif)
