### ISSUE TITLE
Content tweak to opt-in for voice recordings

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1708]
To ensure we transcripts are mentioned in the opt-in replace the second paragraph of the opt-in message with the following.

"Can Firefox Voice store your voice recordings and associated transcript?"

**Comment by ianb** [comment]
OK, changing this:

> Can Firefox Voice store transcripts of your voice recordings? You’ll always be able to use Firefox Voice, even if you don’t allow collection.

To this:

>  Can Firefox Voice store your voice recordings and associated transcript? You’ll always be able to use Firefox Voice, even if you don’t allow collection.
