### ISSUE TITLE
Footer (Settings and Feedback links) don't display during "listening" mode when follow-ups are enabled 

### ISSUE THREAD

**Issue by jcambre** [mozilla/firefox-voice#1709]
<img width="661" alt="Screen Shot 2020-06-02 at 2 57 41 PM" src="https://user-images.githubusercontent.com/2432019/83558865-a7eac800-a4e1-11ea-8ce4-de3f91c96eff.png">

To reproduce, enable follow-ups mode and trigger the extension.

**Comment by danielamormocea** [comment]
I think this issue is also filed here: #1473

**Comment by ianb** [comment]
Not yet released, but fixed
