### ISSUE TITLE
Vocal and written command titles are displayed in the “Doorhanger”

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#171]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say a vocal command, e.g. “Search armadillo”.
3. Click the “Back” button from the top left side of the “Doorhanger”.
4. Write a command, e.g. “Search giraffe” and press “Enter”.
5. Observe “Doorhanger”.

### Expected result:
The “Doorhanger” doesn’t have display issues.

### Actual result:
Both the vocal and written command titles are displayed. 

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Reproduced within the bug is also the fact that the previous vocal command title is bolded.
Reproduced also when writing consecutive commands and not deleting the previous transcript like in [168](https://github.com/mozilla/firefox-voice/issues/168).

![voice 7](https://user-images.githubusercontent.com/54401091/64173212-6c8e7080-ce5f-11e9-9d36-12da70579541.gif)

**Comment by ianb** [comment]
I think this is fixed by our back button fixes.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![76](https://user-images.githubusercontent.com/54401091/65864145-0f141380-e37a-11e9-9f04-55f2b374bc8a.gif)
