### ISSUE TITLE
adjust volume commands always open spotify

### ISSUE THREAD

**Issue by danielamormocea** [mozilla/firefox-voice#1718]
Whenever I say "louder" / "softer" / any other volume adjusting command, without being on a music site, Spotify Web opens and the error: "Internal error: Error: No handler for adjustVolume" appears.

Steps to reproduce:
1. open any website (e. g. New York Times)
2. say "louder"

what should happen?
Maybe display error with "Can't adjust volume of this tab"

**Comment by awallin** [comment]
If you request a volume adjustment and no volume is player we should display a message like "No audio is playing"
