### ISSUE TITLE
“Zap” checkmarks displayed after writing and deleting several commands in “Doorhanger”

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#172]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Write a command, e.g. “Search armadillo” and press “Enter”.
3. Click the “Back” button from the top left side of the “Doorhanger”.
4. Delete the previous command and write a new command, e.g. “Search lion” and press “Enter”.
5. Click the “Back” button from the top left side of the “Doorhanger”.

### Expected result:
The “Doorhanger” doesn’t have display issues.

### Actual result:
There are two “Zap” checkmarks displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Also the following behaviours were observed after performing the above steps:

- The last written command is displayed;
- The “Zap” animation is placed at the bottom of the “Doorhanger”;
- No new vocal command can be made.

Deleting the written command is made sometimes by pressing “Backspace” and sometimes by pressing “fn + Backspace” (so checking both ways is recommended, because the cursor is either in front or at the back of the written terms).

![voice 8](https://user-images.githubusercontent.com/54401091/64174434-f2abb680-ce61-11e9-9677-0d28b2f6a92e.gif)

**Comment by ianb** [comment]
I think this is fixed by the back button fix.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![75](https://user-images.githubusercontent.com/54401091/65863698-50f08a00-e379-11e9-94fc-485ee91bf093.gif)
