### ISSUE TITLE
A vocal command can't be made after pressing the "Back" button from a written or vocal command result in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#174]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a command, e.g. “search armadillo” and have the result in the "Doorhanger".
3. Click the “Back” button from the top left side of the “Doorhanger”.
4. Say a new command, e.g. "Search lion".

### Expected result:
The "Doorhanger" displays the result of the new command, after processing it.

### Actual result:
The vocal command can't be made.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Also the following behaviours were observed after performing the above steps:

- The previous command is displayed, when going back, if the previous command was written;
- The “Zap” animation is placed lower in the “Doorhanger”, when going back;
- The “Zap” checkmark is displayed in the “Doorhanger”, when going back.

Written commands can still be made, by writing and deleting them with “Backspace”, or “fn + Backspace” (so checking both ways is recommended, because the cursor is either in front or at the back of the written terms).
To avoid this issue, the "Doorhanger" needs to be closed and opened again.

![voice 10](https://user-images.githubusercontent.com/54401091/64176354-f6d9d300-ce65-11e9-9cc2-62042129b975.gif)

**Comment by ianb** [comment]
The back button here should effectively be a reload, starting the entire process from scratch with no memory of what it did previously.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![voice 33](https://user-images.githubusercontent.com/54401091/65036192-8c3f9180-d953-11e9-9bd8-53b99a2e00b1.gif)
