### ISSUE TITLE
Vocal and written command result titles are not displayed the same way

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#175]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Perform a vocal command, e.g. "Search armadillo". 
3. Wait for the result information to be displayed and observe the title.
4. Close the "Doorhanger" and click on the mic icon again. 
5. Write a command, e.g. “search armadillo” and press “Enter”.
6. Observe the title from the "Doorhanger".

### Expected result:
The vocal and written command result titles are displayed in the same way.

### Actual result:
The vocal command result title has bold font and the written command result title has normal font.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).

![voice 11](https://user-images.githubusercontent.com/54401091/64177740-c9425900-ce68-11e9-868b-fcc6991e4105.gif)

**Comment by ianb** [comment]
I believed we recently fixed this.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![100](https://user-images.githubusercontent.com/54401091/66296185-adadf080-e8f5-11e9-89c6-ff6ccb6a7063.gif)
