### ISSUE TITLE
Implement settings page

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#177]
We should decide on exactly which settings we want for the betas.

**Comment by awallin** [comment]
For internal my thought is:
* toggle chime on/off
* Link to privacy policy
* Link to feedback

As we gather feedback from internal testing we can add to the settings based on user requests. @ianb @jofish @harraton thoughts?

**Comment by awallin** [comment]
Mockup for settings available in abstract.
https://share.goabstract.com/e41486eb-2b7d-4a91-b9ba-bcfb16cbff93?collectionLayerId=2d569478-c749-4d42-8430-f02b9f829af8&mode=design

**Comment by awallin** [comment]
Adding mockup
![settings](https://user-images.githubusercontent.com/428245/67989764-0f116880-fbf1-11e9-9e38-37a2c972918b.jpg)

**Comment by ianb** [comment]
@jenniferharmon if you were up for another React conversion and styling...?

There's no support for the privacy settings, but if they went in without working then it would be easy to fix that up later. Some of the links would also go nowhere for now (e.g., we don't have a privacy policy written up, or a feedback form).

**Comment by jenniferharmon** [comment]
Hey @ianb ! This looks fun. I will try to get started this weekend. I'm assuming this settings page is a replacement/enhancement for the currently existing page located in extension/options? Please clarify if I'm wrong! Thanks.

**Comment by ianb** [comment]
Yes, all the files can go in `extension/options/`, similar to the popup. `options.js` has a little UI code, and code to get and set the actual settings in the backend.

**Comment by awallin** [comment]
The feedback link is available.
https://qsurvey.mozilla.com/s3/firefoxvoice-feedback

As is the link to what you can say. Although we need to make this a public URL soon.
moz-extension://83d10297-2706-0e4c-8705-4f856f389b20/views/lexicon.html

**Comment by ianb** [comment]
The page should be able to link to the Lexicon with:

`<a href="/views/lexicon.html">The Big List of What You Can Say to Firefox Voice</a>`
