### ISSUE TITLE
Intent-finding intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1771]
Not sure about the phrase, but something like "help about tabs" or "commands for tabs", and it would show examples from intents where the example or intent description included "tab".

**Comment by ianb** [comment]
For implementation: this could open the lexicon, with something like `#query=tabs` and then we'd add some JavaScript to the lexicon page that highlights the search term, and potentially hides portions of the page that don't seem to apply.

**Comment by AbhiVaidya95** [comment]
Hi @ianb I tried creating the help intent and it open the Lexicon page for particular intent as suggested by you.
Thanks.
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/65556960/87857688-4a51f400-c946-11ea-8854-2d28d40acc6a.gif)
