### ISSUE TITLE
"Play trailer" opens spotify

### ISSUE THREAD

**Issue by GowthamPrakaash** [mozilla/firefox-voice#1777]
"Play trailer of something" opens Spotify. Trailer is mostly a video. So, it should open Youtube or similar site.

**Comment by ianb** [comment]
Yes, I see how "trailer" is another term for "video", so this makes sense.

Only detail we want to think about when implementing: we don't want a phrase like `play (trailer | video) (of |) [query]` because we'd lose "trailer" from the query.

**Comment by AbhiVaidya95** [comment]
@ianb I took ur suggestion under conideration and I was able to fix the issue.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/65556960/87148447-06b71480-c2cc-11ea-8568-22258ce70632.gif)
