### ISSUE TITLE
Popup textarea has unfriendly object on display

### ISSUE THREAD

**Issue by PascalUlor** [mozilla/firefox-voice#1781]
### Prerequisites:
Mic permission is enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.
A page that can be translated is opened and made the active tab, e.g. https://en.wikipedia.org/wiki/Lion.

### STR:
Use the shortcut or click on the mic icon from the browser toolbar.

![20200628_040844](https://user-images.githubusercontent.com/32112393/85938280-b622dd00-b903-11ea-9b3a-a334d5f7b4e0.jpg)

## NOTE
This issue was spotted and resolved by me while working my assigned task

**Comment by Simpcyclassy** [comment]
Could you replicate this on master cause I think this works fine on my end? If works fine on your master, probably you may have mistakenly broken it while working

**Comment by PascalUlor** [comment]
> Could you replicate this on master cause I think this works fine on my end? If works fine on your master, probably you may have mistakenly broken it while working

You are right. I'll be closing this issue
