### ISSUE TITLE
Use free text search in tabs.js:getMatchingTabs()

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1789]
The function `getMatchingTabs()` basically does a string search of the URL. That's not a great way to match, especially with voice input.

Instead we should get all tabs that otherwise match the query, and use `query` as a text search of the URL and title of the tabs (it doesn't need to include tab content).

**Comment by PascalUlor** [comment]
Can I work on this?

**Comment by AbhiVaidya95** [comment]
Can I work on this?

**Comment by AbhiVaidya95** [comment]
@ianb I have made changes for the getMatchingTabs() Can you please look into it once?
