### ISSUE TITLE
"Mute" action is made after saying the "Stop" command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#188]
### Prerequisites:
Have the mic permissions enabled.
Have a playing video in a Youtube tab opened.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say the "Stop" vocal command.
3. Observe the Youtube tab browser.

### Expected result:
Youtube video stops playing.

### Actual result:
Youtube video is muted and the action is shown by having a mute icon in the Youtube browser tab.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Video can be unmuted, by saying the "Unmute" vocal command.
After saying the "mute" vocal command, the doorhanger displays information about "mute".

![voice 12](https://user-images.githubusercontent.com/54401091/64255465-1afee800-cf2a-11e9-843e-ad053a34ed00.gif)

**Comment by ianb** [comment]
We should remove `stop` from the mute command. We have #104 to do the right thing for "stop", but muting isn't a good interim solution.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit) and after saying the "Stop" vocal command, I got a different actual result as followed:

**Actual result:** A new tab opens with a Google search result for "Stop".

![41](https://user-images.githubusercontent.com/54401091/65321958-3d416880-dbae-11e9-825d-928c2d5fc9be.gif)

**Comment by ianb** [comment]
I think what's described in https://github.com/mozilla/firefox-voice/issues/188#issuecomment-533507044 is intentional (at least as far as this ticket goes): we removed support for "stop" so it is falling back to a search.

We might re-add stop (maybe as an alias for pause?), but this particular ticket I believe is fixed.
