### ISSUE TITLE
Doorhanger extends after pressing "Enter" multiple times

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#189]
### Prerequisites:
Have mic permissions enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a command, e.g. "Search fox" and wait for the result to appear in the "Doorhanger".
3. Press the "Enter" key several times.

### Expected result:
The "Doorhanger" doesn't have display issues.

### Actual result:
The "Doorhanger" extends. 

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).

![voice 13](https://user-images.githubusercontent.com/54401091/64259763-5dc4be00-cf32-11e9-87cc-c7355d1517a0.gif)

**Comment by ianb** [comment]
This should be fixed by #253

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![27](https://user-images.githubusercontent.com/54401091/65146378-49012380-da24-11e9-8ca7-eb435da1b7a4.gif)
