### ISSUE TITLE
Result of "Look up" command isn't opened in a new tab 

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#190]
### Prerequisites:
Have mic permission enabled.
Have a logged in Gmail account.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command, e.g. "Look up Hamilton on Gmail".

### Expected result:
A new tab opens with "Hamilton" searched results on the user's Gmail.

### Actual result:
From the same tab where the command was made, the user's Gmail loads with results for "Hamilton".

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).

![voice 14](https://user-images.githubusercontent.com/54401091/64262115-4556a280-cf36-11e9-86f8-a5804a4ecff8.gif)

**Comment by ianb** [comment]
For this ticket, we should review all cases of tab opening so it's consistent (e.g., right now "go to amazon" *does* open in a new tab).

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![49](https://user-images.githubusercontent.com/54401091/65323988-83e59180-dbb3-11e9-9912-0b9b0c7a670f.gif)
