### ISSUE TITLE
Record in a background tab

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#191]
As a microphone permission mitigation, I want to try using an extension page/tab, switching to that tab when the popup is opened, calling getUserMedia there, and then switching back to the original page. This should retain the popup UI, but without the permission issues. There will be a noticeable tab switch still.

**Comment by jan-ivar** [comment]
See [bug 1579489 comment 10](https://bugzilla.mozilla.org/show_bug.cgi?id=1579489#c10) regarding planned changes to background access.
