### ISSUE TITLE
Written command search title deleted from the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#192]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Write a command, e.g. "Search fox", press "Enter" and wait for the result to appear in the "Doorhanger".
3. Press "Backspace" several times.

### Expected result:
The "Doorhanger" has a title for the current session.

### Actual result:
The search title is deleted from the "Doorhanger", while still in the current session.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).

![voice 15](https://user-images.githubusercontent.com/54401091/64341955-2cabc280-cff2-11e9-9517-d0cd0d02a201.gif)

**Comment by ianb** [comment]
I think this is fixed by the text input improvements.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![74](https://user-images.githubusercontent.com/54401091/65863515-eccdc600-e378-11e9-8a4e-93514155a2f9.gif)
