### ISSUE TITLE
Previous session displayed when trying to do a blank search 

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#193]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Write a command, e.g. "search fox", press "Enter" and wait for the result to appear in the "Doorhanger".
4. Click the "Back" button.
4. Delete the previous "search fox" command.
5. Press "Enter".

### Expected result:
The "Doorhanger" has a notification that no match is found.

### Actual result:
The "Doorhanger" displays the previous search result.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Reproduced also in the following circumstance, shown in the second gif: 

- after the result appears in the "Doorhanger", the "search fox" command title is deleted while in session, like in [192](https://github.com/mozilla/firefox-voice/issues/192), the "Back" button is clicked, then "Enter" is pressed (blank search).

![voice 17](https://user-images.githubusercontent.com/54401091/64343914-130c7a00-cff6-11e9-9dba-3aabe64ff606.gif)

![voice 16](https://user-images.githubusercontent.com/54401091/64343927-199af180-cff6-11e9-9adb-6364113e60c2.gif)

**Comment by awallin** [comment]
Likely related to #170 and other back button issues.

**Comment by alexandra-martin** [comment]
The bug is still reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![voice 38](https://user-images.githubusercontent.com/54401091/65040948-450ace00-d95e-11e9-9169-afebbce7774a.gif)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![38](https://user-images.githubusercontent.com/54401091/65320680-0fa6f000-dbab-11e9-9192-7abb50093f1e.gif)
