### ISSUE TITLE
"Read this page" doesn't open text to speech mode

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#195]
### Prerequisites:
Mic permissions are enabled.
Have a page opened supporting text to speech, e.g. a [New York Times article](https://www.nytimes.com/2019/09/05/us/hurricane-dorian-updates.html?action=click&module=Top%20Stories&pgtype=Homepage).

### STR:
1. Click on the mic icon from the browser's toolbar.
2. Say or write the "Read this page" command.

### Expected result:
The article opens in the text to speech format and starts reading.

### Actual result:
A "read this page" Google search result is displayed in a new tab.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
The command "Read" opens the article in the text to speech mode, but doesn't starts reading the article content, similar to [114](https://github.com/mozilla/firefox-voice/issues/114) maybe? Other commands like "Play", "Mute", "Unmute", "Stop" are similar with [188](https://github.com/mozilla/firefox-voice/issues/188), [180](https://github.com/mozilla/firefox-voice/issues/180). "Pause" command doesn't work.

![voice 20](https://user-images.githubusercontent.com/54401091/64356309-532a2780-d00b-11e9-9eb7-254ca9a0da15.gif)

**Comment by awallin** [comment]
Hmmm, "Read this page" and "Read" both successfully open reader mode and begin the TTS for me. I might be using an older version of the add-on?

**Comment by ianb** [comment]
This might be an intent parser problem.

**Comment by alexandra-martin** [comment]
It seems now the text to speech mode can be displayed with both "Read this page" and "Read" commands. Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![22](https://user-images.githubusercontent.com/54401091/64702558-6c235480-d4b3-11e9-8d32-fc2aa11b7d74.gif)

**Comment by ianb** [comment]
I think that means this is fixed?

**Comment by alexandra-martin** [comment]
Verified again on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![45](https://user-images.githubusercontent.com/54401091/65322819-7aa6f580-dbb0-11e9-9eeb-883c6babff3f.gif)
