### ISSUE TITLE
Transcription from a vocal command on Gmail displays "1" as "one"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#200]
### Prerequisites:
Have mic permissions enabled.
Have an available mail with the number 1 in its title, e.g. "test 1".

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say the "look up" command for Gmail, e.g. "Look up test 1 on Gmail".

### Expected result:
"Doorhanger" transcript is displayed correctly and a search result in Gmail appears.

### Actual result:
The transcription in the "Doorhanger" is displayed as "look up test one on Gmail" and the mail is not found as a search result.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
The vocal command transcript for a "look up" command in Google Docs, Google Calendar and Google Drive displays correctly "test 1" and search results are found.

![voice 21](https://user-images.githubusercontent.com/54401091/64425027-57aa1b00-d0b3-11e9-8da8-f9a186c50e5f.gif)

![voice 22](https://user-images.githubusercontent.com/54401091/64425035-61cc1980-d0b3-11e9-90a6-9816fae3db4a.gif)

**Comment by ianb** [comment]
I don't think we have a way to control the transcription in this case.
