### ISSUE TITLE
"Look up" command for Coursera adds a space in front of the searched term in the URL

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#201]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command, e.g. "Look up design on Coursera".

### Expected result:
Coursera opens in a new tab displaying results for what was searched.

### Actual result:
Coursera opens in a new tab, but can't find any search results.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
In the URL there is a space in front of "design". Deleting that space will show search results. Maybe this is a regression? Since yesterday this command was running as expected.

![voice 23](https://user-images.githubusercontent.com/54401091/64429866-a52c8500-d0bf-11e9-8e26-eade2a80b159.gif)

**Comment by alexandra-martin** [comment]
It seems sometimes the Coursera website displays results even with the URL space. Now I am not sure what can cause the issue when the website isn't loading the results.

<img width="1280" alt="Screenshot 2019-09-11 at 15 14 04" src="https://user-images.githubusercontent.com/54401091/64696445-18ab0980-d4a7-11e9-9d5b-12ad4e75481d.png">

**Comment by ianb** [comment]
This is a bug with duckduckgo. I have submitted a fix via https://duckduckgo.com/newbang
