### ISSUE TITLE
"Look up" command for Wikipedia, Amazon, Yelp, Reddit, Twitter opens a Google search results tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#202]
### Prerequisites:
Have mic permissions enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say a "Look up" command for one of the following websites: Wikipedia, Amazon, Yelp, Reddit, Twitter, e.g. "Look up PlayStation on Amazon".

### Expected result:
The Amazon webpage opens in a new tab with the content of the command.

### Actual result:
A Google search result tab opens with "playstation on amazon" in the search field.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
The "Look up" command works for Gmail, Google Calendar/Docs/Drive, MDN, Goodreads, Spotify.
The "Look up" commands for Coursera opens the website but doesn't find any results, like in [201](https://github.com/mozilla/firefox-voice/issues/201).

![voice 24](https://user-images.githubusercontent.com/54401091/64432719-c5f7d900-d0c5-11e9-96dc-2029e67e6c3b.gif)

![voice 25](https://user-images.githubusercontent.com/54401091/64432742-cd1ee700-d0c5-11e9-8be7-60909792c15b.gif)

**Comment by ianb** [comment]
I don't think we've added these services to the bang search (service-specific search). And/or we need to make "look up" specifically work.

**Comment by brianpeiris** [comment]
I would like to see search support for youtube, google maps, ddg/google image search and dictionary.com,

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![35](https://user-images.githubusercontent.com/54401091/65243583-40c2ea00-daf1-11e9-87cb-dbf523aa7821.gif)

Found possible issues for Wikipedia and for some new added services, but I will log new specific bug reports after more testing.
