### ISSUE TITLE
"Onboarding" tab has display issues when minimizing browser window

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#215]
### Prerequisites:
Have the add-on installed and mic permissions enabled.

### STR:
1. After installation, click on the mic icon from the browser toolbar and wait a few seconds for the "Onboarding" tab to appear.
2. Minimize the browser window and observe the "Onboarding" tab.

### Expected result:
"Onboarding" tab doesn't have display issues.

### Actual result:
At certain points, text is not visible or is exceeding its violet border.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
When mic permissions are not enabled, the text from the left side can exceed its violet border and the image from the right side can seem distorted at certain minimized window sizes.

![voice 26](https://user-images.githubusercontent.com/54401091/64597615-c4c4f580-d3be-11e9-97c0-f2727947276b.gif)

**Comment by ianb** [comment]
We're going to do a new design of this page, which will be a single column and size down a bit better.

Also, I'm not sure if we're concerned about sizing a window down *quite* that far.
