### ISSUE TITLE
Search result not displayed for a written command in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#222]
### Prerequisites:
Have mic permissions enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Write a command, e.g. "Search lion" and press "Enter".

### Expected result:
Search result for the command is displayed.

### Actual result:
The search result is displayed briefly, then "Sorry, there was an issue" is displayed.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Workaround: wait a few seconds, before pressing the "Enter" key.
Also the following behaviours were observed after performing the above steps:

- "Sorry, there was an issue" is displayed right after the written command is started;
- If a command implies that a new tab opens, then the result is displayed in that tab.

![5](https://user-images.githubusercontent.com/54401091/64683423-e344f280-d48b-11e9-8424-a084145d8468.gif)

![6](https://user-images.githubusercontent.com/54401091/64683441-e9d36a00-d48b-11e9-83ca-5c5bf58a38ef.gif)

**Comment by ianb** [comment]
I think this is the same issue as #229

**Comment by ianb** [comment]
I believe this was fixed by #275

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![46](https://user-images.githubusercontent.com/54401091/65323058-120c4880-dbb1-11e9-9c9d-885cd4c93bfa.gif)
