### ISSUE TITLE
Vocal command transcription isn't displaying all the command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#223]
### Prerequisites:
Have mic permissions enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say a command, e.g. "Look up Design on Coursera".

### Expected result:
Coursera opens with results relating to the searched term.

### Actual result:
Sometimes because the vocal command transcription isn't displaying all the command, an unnecessary command is made.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Mostly reproduced on Windows.

![19](https://user-images.githubusercontent.com/54401091/64697175-e39fb680-d4a8-11e9-955e-27ae203dde94.gif)

**Comment by ianb** [comment]
I think this is just a voice detection issue, it must be cutting off slightly early. It's generally working for me. (Coursera search is broken though, but that's a separate issue with duckduckgo)
