### ISSUE TITLE
[Intermittent] "Zap" animation can displays signs of lagging after clicking the mic icon in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#225]
### Prerequisites:
Have mic permissions enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Observe the "Doorhanger".

### Expected result:
The "Doorhanger" has no display or functional issues.

### Actual result:
Sometimes the "Doorhanger" displays signs of lagging visible in the "Zap" animation.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Mostly reproduced on Windows.

![8](https://user-images.githubusercontent.com/54401091/64702805-e227bb80-d4b3-11e9-84c1-c7f65de7e588.gif)

**Comment by ianb** [comment]
If this turns out to be a frequent problem, then we should escalate the priority.

**Comment by ianb** [comment]
This doesn't seem like it's been a problem, closing for now.
