### ISSUE TITLE
Type input display not visible after a few seconds in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#258]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Write a command, e.g. "search lion". 

### Expected result:
The "Doorhanger" displays the type input.

### Actual result:
The "Doorhanger" displays the "Sorry, there was an issue" text after around 4 seconds and type input is not visible anymore.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
The written command can be continued and results will be shown after pressing "Enter" in both the "Doorhanger" and in new opened tabs, but the continuation of the command will not be visible when it's written.
Sometimes the "Sorry, there was an issue" text is displayed after around 8 seconds after the written command was started.

![voice 36](https://user-images.githubusercontent.com/54401091/65038902-aaa88b80-d959-11e9-8e09-8e3c55bfc2e7.gif)

**Comment by awallin** [comment]
@ianb I assume this is caused when the time out limit is reached. Because we don't need to listen for audio input we should probably just remove the timeout for type input.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![34](https://user-images.githubusercontent.com/54401091/65226067-e6b12d00-dace-11e9-8979-1bcad3106517.gif)
