### ISSUE TITLE
Saying "Read this page" 2 times will disable text to speech mode 

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#260]
### Prerequisites:
Have mic permissions enabled.
Have a opened page supporting text to speech mode, e.g. a [New York Times article](https://www.nytimes.com/2019/09/16/us/politics/trump-saudi-tweet.html).

### STR:
1. Click on the mic icon from the browser's toolbar.
2. Say the "Read this page" command then wait for the action to be made.
3. Repeat steps 1 and 2.

### Expected result:
Page remains in text to speech mode.

### Actual result:
Text to speech mode is disabled.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![24](https://user-images.githubusercontent.com/54401091/65051123-3679e200-d971-11e9-947d-f0f87904a619.gif)

**Comment by ianb** [comment]
We might have a bug for this as well, as it was a known limitation when I reimplemented the read intent and I thought I made a followup (but I'm not able to find it now)

**Comment by alexandra-martin** [comment]
**Update:** 
Text to speech mode is disabled also after saying the "Read" command two times. 
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![48](https://user-images.githubusercontent.com/54401091/65323774-f2761f80-dbb2-11e9-9710-6dd34f5928c7.gif)
