### ISSUE TITLE
calendar tab

### ISSUE THREAD

**Issue by jofish** [mozilla/firefox-voice#265]
"go to my calendar tab" should work. It used to.

**Comment by alexandra-martin** [comment]
@jofish are you referring that the command should find the calendar tab from existing opened tabs or a new calendar tab should open? If it is the former, then yes the calender tab is found only by using "Find my calendar tab". But if it is the latter, I found the issue to be intermittent on both Mac and Win.

**Comment by jofish** [comment]
I meant the former, but it's something we should address, that's for sure. Thanks for the needed clarification.

**Comment by ianb** [comment]
I think this means we should match `go to [query] tab` as a find intent

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 70.0a1 (64-bit).

![50](https://user-images.githubusercontent.com/54401091/65327707-59003b00-dbbd-11e9-8320-a467723c023b.gif)
