### ISSUE TITLE
Support close tab

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#269]
Based on feedback from user testing and early alpha release users are interested in closing a tab with their voice. We should support something like the following:

- Close tab = close active tab
- Close gmail tab = close the gmail tab (we should discuss weather this should close all gmail tabs or not execute if multiple are open)
- Close all tabs = close all open tabs

Related, "undo" or "reopen tab" would be a great companion feature as this is a lightly destructive action.

**Comment by ianb** [comment]
"Close all tabs" seems scary!

I happen to have just done "close tab" so I'm going to add that. I feel like we might want some confirmation for a search-related intent like "close gmail tab".

**Comment by awallin** [comment]
Fair enough, "Close all tabs" and "Close gmail tab" are more destructive. Let's wait to implement those until we hear more user feedback they are desired and we build safety mechanism into it like confirmation or undo.

**Comment by awallin** [comment]
Close tab has been implemented.
