### ISSUE TITLE
Voice interprets the command "google pictures of dogs" incorrectly

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/firefox-voice#271]
For some reason it just opens a google search of "ogle pictures of dogs"

**Comment by ianb** [comment]
Jofish thinks that somehow we are matching "go"

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 70.0a1 (64-bit) and the vocal command opens a Google search result with "pictures of dogs" in the search field. @ianb should this command open Google Images?

![51](https://user-images.githubusercontent.com/54401091/65330627-a8496a00-dbc3-11e9-9da6-d7467c43aace.gif)
