### ISSUE TITLE
"Look up" command for Apple music displays a window to save or open a .txt file

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#277]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command for Apple music, e.g. "Look up Green Day on Apple Music".

### Expected result:
Apple Music page opens in a new tab with a search result for Green Day.

### Actual result:
A window to save or open a .txt file is displayed.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![36](https://user-images.githubusercontent.com/54401091/65253915-1dee0100-db04-11e9-9766-d5c1230b5fdb.gif)

**Comment by ianb** [comment]
Let's just remove Apple Music

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit) and the command now goes to a Google search result. (service removed)

![47](https://user-images.githubusercontent.com/54401091/65323391-e9388300-dbb1-11e9-87ea-f867b40abb06.gif)
