### ISSUE TITLE
Replace mic icon with Firefox Voice icon in about:addons

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#282]
When viewing Firefox Voice in the list of installed extensions the mic icons should be replaced with the Firefox Voice icon to reinforce the brand and create a more compelling visual.

<img width="698" alt="Screen Shot 2019-09-19 at 10 14 46 AM" src="https://user-images.githubusercontent.com/428245/65265796-8e762d00-dac6-11e9-83fa-d0e34bdd516e.png">

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 70.0a1 (64-bit).

<img width="1280" alt="Screenshot 2019-09-20 at 16 08 14" src="https://user-images.githubusercontent.com/54401091/65330970-72f14c00-dbc4-11e9-9e8f-78cffa25aa3c.png">
