### ISSUE TITLE
"Look up" command on Shazam displays blank page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#287]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command, e.g. "Look up Green Day on Shazam".

### Expected result:
Shazam opens in a new tab with search results for Green Day.

### Actual result:
Shazam opens in a new tab and the page is blank.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1.
Reproduced also with the "Search Green Day on Shazam" command.

![52](https://user-images.githubusercontent.com/54401091/65409184-ba0f5500-ddef-11e9-9af3-627520dcfadb.gif)

**Comment by awallin** [comment]
I get the same result. It's unclear what the correct URL construction for a search on Shazam should be as the search functionality is displayed in a popup.

Might want to remove this bang?

**Comment by ianb** [comment]
Yes, let's delete

**Comment by KhushilMistry** [comment]
I am working on this. I will submit a PR in a while.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![7](https://user-images.githubusercontent.com/54401091/66833199-0b7cb100-ef64-11e9-8847-55b8b74fc8ea.gif)
