### ISSUE TITLE
"Look up ... on maps" command will not open Google Maps

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#288]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command for Google Maps, e.g. "Look up Denver on maps".

### Expected result:
Google Maps opens in a new tab with the map of Denver.

### Actual result:
A Google search result for "maps denver" is shown.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Saying or writing "Look up Denver on Google Maps" will open Google Maps in a new tab and the map of Denver is displayed (second gif).
I saw that in the written code, the service "google maps" has the "gmap" alias, while the service "maps" has "google maps" as alias, maybe the bug is reproduced because the services don't have the same alias.

![54](https://user-images.githubusercontent.com/54401091/65420409-c0aac600-de09-11e9-81dd-356347856a53.gif)

![55](https://user-images.githubusercontent.com/54401091/65420380-ab359c00-de09-11e9-97b3-9a2e3a39ed7b.gif)

**Comment by ianb** [comment]
This may be an intent parser error, where we aren't resolving or parsing this as Google Maps.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/66739337-29b9b280-ee79-11e9-95b6-fdea445dde50.gif)
