### ISSUE TITLE
Remove Hulu bang search

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#289]
### Prerequisites:
Mic permissions are enabled.
Have an active Hulu account and be logged in beforehand.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command for Hulu, e.g. "Look up American Horror Story on Hulu".

### Expected result:
Hulu opens in a new tab with search results for "American Horror Story".

### Actual result:
Hulu opens in a new tab and displays the search page, but there is no indication that "American Horror Story" is searched, only in the URL. 

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit). 
Writing "American Horror Story" in the website's search field will display results for the term searched. 

![56](https://user-images.githubusercontent.com/54401091/65424452-43d11980-de14-11e9-88d1-ff2f89ce6a5d.gif)

**Comment by ianb** [comment]
I'm guessing they've changed their URL scheme, and DDG hasn't updated the bang.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![3](https://user-images.githubusercontent.com/54401091/68584600-ae075180-0488-11ea-8d58-7b200e25a147.gif)
