### ISSUE TITLE
"Look up" command for Dictionary.com displays a Google search result

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#290]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command for Dictionary.com, e.g. "Look up lion on dictionary.com".

### Expected result:
The Dictionary website opens in a new tab with a search result for the term searched.

### Actual result:
A Google search result opens in a new tab with "lion on dictionarycom" in the search field.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Saying or writing "Look up lion on dictionary" will display the Dictionary website in a new tab with the seach result for the term searched.

![57](https://user-images.githubusercontent.com/54401091/65425232-2f8e1c00-de16-11e9-8cc1-4d1a41be98bd.gif)

**Comment by ianb** [comment]
We need to add or fix the service name alias for "dictionary.com". It works for "dictionary".

**Comment by KhushilMistry** [comment]
It's not catching up the "dot" from the dictionary.com. You can see that it is also searching for "dictionarycom" on google search. Make the key "dictionarycom" and it is working fine. 
So should I update the key or dug into the code to make it identify the "dot".
I think we should make it identify the "dot". Any thoughts?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/67478601-09ea7180-f665-11e9-8de4-a14064dd4c12.gif)
