### ISSUE TITLE
"Look up" command for Apple TV displays DuckDuckGo search result page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#291]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up command" for Apple TV, e.g. "Look up Suits on Apple TV".

### Expected result:
Apple TV website opens in a new tab with a search result for the term searched.

### Actual result:
A DuckDuckGo search result page opens in a new tab with "suits site:tv.apple.com" in the search field.

### Notes: 
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
It's unclear to me if location or the fact that there is no account logged for the feature, has something to do with the bug. 

![53](https://user-images.githubusercontent.com/54401091/65426307-9f9da180-de18-11e9-9cb6-6fb36b56b78f.gif)

**Comment by awallin** [comment]
I tested with an Apple account and the result was same DuckDuckGo search. The API for this bang! isn't great. Let's remove it @ianb

**Comment by alexandra-martin** [comment]
The bug is still reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![4](https://user-images.githubusercontent.com/54401091/66926965-a2666d80-f037-11e9-884a-fc5632f89f87.gif)
