### ISSUE TITLE
Can't make commands for Pandora website, because of geolocation

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#312]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write a "Look up ... on Pandora" command, e.g. "Look up Green Day on Pandora".

### Expected result:
Pandora.com opens in a new tab with search results for Green Day.

### Actual result:
Can't access the Pandora website, because of geolocation.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![60](https://user-images.githubusercontent.com/54401091/65520807-de9f2600-def0-11e9-9b22-982e0e507bce.gif)

**Comment by awallin** [comment]
This is an issue with Pandora as a service. Firefox Voice will not enable a web service to work in a geolocation it is not currently supported in.

Related #322 will provide better support for music services when they fail due to login, connectivity or geolocation reasons.

**Comment by alexandra-martin** [comment]
@awallin maybe I shouldn't have placed the "bug" label. Wanted you to know that I will not be able to know if certain commands on Pandora will work since I can't access it.

**Comment by awallin** [comment]
Got it. I'm sure we'll have more geolocation issues with other services in the future. Might not need an explicit bug for those. Maybe just include details in daily QA email.
