### ISSUE TITLE
Doorhanger behavior

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#324]
Implement the following doorhanger behavior to create an efficient UX:

* After trigger the doorhanger opens to a "Listen" state showing only a title, the Zap, settings icon, and link to privacy statement.

* After 3 seconds of no audio activity the doorhanger expands to reveal example utterances and feedback for previous requests.

* Note: The first 5 uses of Firefox Voice after installation should override the above behavior and show the fully expanded doorhanger to suggest things that can be said.

* When timeout occurs (6 seconds?) the doorhanger should auto close itself (instead of displaying an error).

![doorhanger-behavior](https://user-images.githubusercontent.com/428245/65537454-176fd880-deba-11e9-97bb-f926cae0c6ff.png)

**Comment by awallin** [comment]
Related to #314

**Comment by ianb** [comment]
Depends on #494

**Comment by ianb** [comment]
I added an `onStartVoice` method in popupController.jsx, though it isn't used yet. We'll need to add some conditionals about displaying the examples, and then use that (setting a timer, and cancelling the timer of they start talking).

**Comment by awallin** [comment]
@jenniferharmon A couple design QA fixes:

- In the listen state (before expansion) can the total height of the doorhanger be reduced? In the mockup it's about ~130px.
- Can there be a smoother transitions to the expanded state? Is there a nice 'expand' animation that can be implemented? Currently it feels like it just pops to the larger size.

**Comment by jenniferharmon** [comment]
@awallin 

- I think I can tighten up the white space a bit, but some of that white space exists as part of the zap animation because in the listening state the animation can be a lot taller than what is depicted in the mockup (when the user is speaking loudly).
- I'll look into adding an animation expand effect.

**Comment by awallin** [comment]
Tighten up the white space as best as possible. Thanks @jenniferharmon!
