### ISSUE TITLE
"Google images of ... " command doesn't display images in Google Images

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#326]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write "Google images of lions".

### Expected result:
A new tab opens with results in Google Images.

### Actual result: 
A new tab opens with results in Google All.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![65](https://user-images.githubusercontent.com/54401091/65578195-fd97c980-df7d-11e9-83d8-7c8f171a5def.gif)

**Comment by ianb** [comment]
We need to put in a special intent and intent matcher for "google images" so that "google [query]" doesn't catch this.

**Comment by lozinska** [comment]
Hello there! I'm new to GitHub and would like to work on this issue

**Comment by ianb** [comment]
@lozinska Oh, I'm sorry, I only noticed your comment when I was putting in a fix for this!

**Comment by ianb** [comment]
I've added these matchers:

```
    google images (of |) [query] [service=images]
    search images (for |) [query] [service=images]
    images of [query] [service=images]
```

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit) for all three matchers.

![117](https://user-images.githubusercontent.com/54401091/66391064-c6d99e80-e9d4-11e9-9147-db5923111ff3.gif)
