### ISSUE TITLE
Youtube tab remains muted for 10 seconds when "Doorhanger" displays text input

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#328]
### Prerequisites:
Mic permissions are enabled.
Have a playing video on a Youtube tab.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar. 
2. Write something to generate the text input in the "Doorhanger".
3. Observe the mute icon from the Youtube tab.

### Expected result:
Since text input is generated, the Youtube tab will not be muted anymore.

### Actual result:
Even though the text input is generated, the Youtube tab stops being muted after around 10 seconds.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Youtube tab is unmuted after a successful vocal or written command (even if command lasts less than 10 seconds). 

![72](https://user-images.githubusercontent.com/54401091/65601858-955fdc80-dfab-11e9-8262-44cc8575848d.gif)

**Comment by awallin** [comment]
Makes sense to unmute when text input begins.

**Comment by ianb** [comment]
I believe I fixed this recently.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![99](https://user-images.githubusercontent.com/54401091/66294679-3591fb80-e8f2-11e9-934a-4535df1c13c5.gif)
