### ISSUE TITLE
"Doorhanger" doesn't close after "Pause" command in a Youtube tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#329]
### Prerequisites:
Mic permissions are enabled.
Have a playing video in a Youtube tab.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Have a successful vocal or written "Pause" command.

### Expected result:
Youtube video is paused and "Doorhanger" closes.

### Actual result:
Youtube video is paused, but the "Doorhanger" isn't closing.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Because the "Doorhanger" is opened, the mute icon is still displayed in the Youtube tab for about 10 seconds, like in [328](https://github.com/mozilla/firefox-voice/issues/328).
On Mac the "Pause" command will display the "Sorry, there was an issue" state, but the video will still be paused.

![70](https://user-images.githubusercontent.com/54401091/65603676-ca216300-dfae-11e9-8c65-889e122f2d4f.gif)

**Comment by ianb** [comment]
I'll reverify this once I've finished refactoring the YouTube code.

**Comment by ianb** [comment]
Will be fixed by #331

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![82](https://user-images.githubusercontent.com/54401091/65960793-ef561b80-e45d-11e9-8fb7-e8525db0b332.gif)
