### ISSUE TITLE
"Pause" and "Mute" commands are not working on a text to speech format page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#330]
### Prerequisites:
Mic permissions are enabled.
Have an opened page supporting text to speech mode, e.g. a [New York Times article](https://www.nytimes.com/2019/09/24/us/politics/democrats-impeachment-trump.html).

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Have a successful vocal or written "Pause" command.

### Expected result:
The reader is paused.

### Actual result:
The reader continues reading text.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
On Win the "Doorhanger" isn't closing, like in [329](https://github.com/mozilla/firefox-voice/issues/329) and the tab remains muted for around 10 seconds like in [328](https://github.com/mozilla/firefox-voice/issues/328).

![69](https://user-images.githubusercontent.com/54401091/65605641-1e7a1200-dfb2-11e9-81a1-69bc522a24ae.gif)

**Comment by ianb** [comment]
#335 should also fix this issue (once that is fixed)

**Comment by alexandra-martin** [comment]
#### Update: 
The bug is reproduced also for the "Mute" command, the reader continues playing and it is not muted. It is reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit). (gif)
On Mac there is an "Internal error:TypeError: intents.read is undefined" message in the "Doorhanger" for the "Mute", "Pause", "Stop" commands. (screenshot)

![90](https://user-images.githubusercontent.com/54401091/66217386-deacdc00-e6cf-11e9-9088-213cbdfa7dec.gif)

<img width="1280" alt="Screenshot 2019-10-04 at 17 03 49" src="https://user-images.githubusercontent.com/54401091/66216142-98ef1400-e6cd-11e9-8c4e-36c9b2a210ea.png">

**Comment by ianb** [comment]
I wonder if there was a build problem causing this? "intents.read is undefined" is a regression I caused temporarily, but has been fixed. @alexandra-martin could you reconfirm this bug?

**Comment by alexandra-martin** [comment]
Verified it today on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
On Mac the message is not appearing anymore in the "Doorhanger" and the "Pause" command is working now, as well as the "Unpause" and "Stop" commands. The "Mute" command is pausing the narration. The "Unmute" command is not working if you pause the tab manually. (1st and 2nd gif)
On Win neither one of the "Mute", "Pause", "Unpause", "Unmute", "Stop" commands are working. (3rd gif)

![new2](https://user-images.githubusercontent.com/54401091/66393686-dc05fb80-e9db-11e9-9254-5fc598fb1e5f.gif)

![new3](https://user-images.githubusercontent.com/54401091/66393696-e2947300-e9db-11e9-8050-62127251b6f9.gif)

![119](https://user-images.githubusercontent.com/54401091/66393708-ea541780-e9db-11e9-8055-979e7a296a9b.gif)

**Comment by ianb** [comment]
I think this is fixed then: "mute" stops the tab from making noise, but doesn't actually make the tab pause. "unmute" undoes this. So pause/play and mute/unmute are a different set of actions.

We might want to change how things work, I made #395 to consider making these work together.
