### ISSUE TITLE
"Look up Spotify on Twitter" will open Spotify tab instead of Twitter

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#344]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command, e.g. "Look up Spotify on Gmail", "Look up Spotify on Twitter", or "Look up Spotify on Instagram".

### Expected result:
Following the examples given, Gmail, Twitter, or Instagram open in a new tab with search results for Spotify.

### Actual result:
Spotify opens in a new tab with search results for "on Gmail", "on Twitter" or "on Instagram".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Similar commands like, "Look up Goodreads on Twitter", "Look up Youtube on Twitter" etc. will open Goodreads and Youtube tabs instead of the Twitter tab.  

![81](https://user-images.githubusercontent.com/54401091/65887764-261d2a80-e3a7-11e9-86ef-cf5fbc7bc77d.gif)

**Comment by ianb** [comment]
The intent that's being matched here is `(do a |) (search | query | look up | lookup | look on | look for) (my |) [service:serviceName] (for | for the |) [query]`

So it's matching `look up [service] [query]`. I'm not sure if this is a good intent match? Maybe we should break that up.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![87](https://user-images.githubusercontent.com/54401091/66207204-d7c79e80-e6ba-11e9-950b-c68e05c2414e.gif)
