### ISSUE TITLE
Do parallel transcription with Deep Speech

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#349]
I believe there's a request flag to do Deep Speech transcription. That is, with just a small tweak we could use Deep Speech.

While I'm not sure we want to switch entirely (though we could make that an option), we could send the request twice, get both responses, and record both transcriptions in Telemetry (and a flag just for equality, which wouldn't require opt-in). This probably doesn't require any server changes.

**Comment by awallin** [comment]
Would be great to collect transcriptions for both during internal Beta and do a comparison to evaluate quality.

**Comment by ianb** [comment]
I'm asking @andrenatal about what we have to change about the request to change the transcription backend.

**Comment by andrenatal** [comment]
@ianb just replace the service endpoint by: `https://dev.speaktome.nonprod.cloudops.mozgcp.net`

This is a backend with deep speech

**Comment by ianb** [comment]
https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/444 contains new Telemetry properties related to this.
