### ISSUE TITLE
"Doorhanger" size remains the same when making commands

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#351]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search" command, e.g. "Search lion".
3. After the result is displayed in the "Doorhanger", click the "Back" button. 

### Expected result:
"Doorhanger" doesn't have display issues.

### Actual result:
The "Doorhanger" stays the same size and it doesn't regains its original size.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![85](https://user-images.githubusercontent.com/54401091/66042381-f300a580-e524-11e9-9df7-21df7b82df87.gif)

**Comment by alexandra-martin** [comment]
#### Update:
Currently the "Doorhanger" remains the same size for other interactions as well, like when making commands, when results are displayed, when the "Doorhanger" is processing the command.

![5](https://user-images.githubusercontent.com/54401091/68950534-0447fd80-07c5-11ea-89e1-6b27266e5a4d.gif)

**Comment by ianb** [comment]
I think this has been fixed with the recent changes.
