### ISSUE TITLE
[music] Allow playlist/album/etc Spotify playing

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#353]
The main Spotify free text search is not that great. E.g., search for "dark side of the moon album" and it will definitely not show you what you intend. But if you search for an album specifically it gives the right response.

We should add intent matching like `play album [query] on spotify` and related things.

**Comment by melvin2016** [comment]
@ianb Can i work on this?

**Comment by ianb** [comment]
@melvin2016 You got it!

You'll need new intents, and then new handlers in the music service. Since it (probably) doesn't make sense to say "play album [query] on youtube" that should probably fall back to just adding "album" to the query and running a normal play.
