### ISSUE TITLE
[Settings] Configuring timeout for listening.

### ISSUE THREAD

**Issue by acwio** [mozilla/firefox-voice#356]
It'd be great to be able to configure how quickly the listener times out. Often times, I'll know what I want, and I'll speak my words quite quickly. Other times, I'll want to take my time in getting my words out.

**Comment by ianb** [comment]
Here's the code that we'd be parameterizing: https://github.com/mozilla/firefox-voice/blob/68d53f0eb0ac9e31bf3aae28139c58f448d4bb95/extension/popup/vad.js#L42-L47

**Comment by ianb** [comment]
I'm now thinking we probably don't want or need this to be configurable, we should just choose a good value. I've increased it to 15 seconds in #613, though we could adjust that further. (@awallin ?)

**Comment by awallin** [comment]
Agreed, at this time we don't need the configuration. 15 seconds is a good place to start, based on user feedback, our own usage, and observations during user testing we can adjust.
