### ISSUE TITLE
View/search voice history

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#357]
Based on a request from a user testing participant an option for view and search voice history should be available.

Possible features include:
* In settings toggle on/off keep voice history. (Also delete history)
* Similar to browser history a running list of voice utterances and actions.
* Ability to rate events and provide feedback.
* History is searchable
* History is sorted by date

**Comment by amandhamija98** [comment]
Hi, I am an outreachy applicant, could I please be assigned this

**Comment by ianb** [comment]
The remaining issues are captured in #1543 and #1785
