### ISSUE TITLE
"Go to New York Times" command displays a Redirect Notice page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#362]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Go to New York Times" command.

### Expected result:
New York Times opens in a new tab.

### Actual result:
A Redirect Notice page is opened in a new tab.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Clicking on the first link from the Redirect Notice page will open the New York Times page in the current tab.

![86](https://user-images.githubusercontent.com/54401091/66130183-f7e35900-e5f9-11e9-970f-859378e800d1.gif)

**Comment by ianb** [comment]
Here's the link that is opened: https://www.google.com/search?q=go+to+new+york+times&btnI – and yes, it somehow turns into a redirect instead of navigating directly. There's a very recent comment about this here: https://support.google.com/websearch/thread/15794018?hl=en – I wonder if Google has changed something?

**Comment by alexandra-martin** [comment]
#### Update:
It seems more sites display a Redirect Notice page, after the "Go to ..." command is made, like Amazon, Goodreads, Coursera, MDN, Wikipedia, Yelp, Twitter, LinkedIn, DuckDuckGo and so on. Google pages, like Gmail, Youtube, Google Drive/Maps/Docs/Slides/Calendar are working.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![116](https://user-images.githubusercontent.com/54401091/66390609-ae1cb900-e9d3-11e9-86f8-b74040156471.gif)
