### ISSUE TITLE
[browser command] Open bookmarks and history

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#373]
"Open bookmarks" or "show bookmarks" should open the bookmarks in the sidebar.

"Open history" or "show history" should open history in the sidebar.

**Comment by awallin** [comment]
Additionally bookmark utterance seen in telemetry "view bookmarks sidebar"

**Comment by richardgreg** [comment]
@ianb can I work on this?

**Comment by ianb** [comment]
@richardgreg I'm not actually sure how this ticket would be implemented, as there are no APIs to open bookmarks or history and it will involve getting into Firefox internals. So I would not recommend this ticket for someone new to the project.

**Comment by farhatcode** [comment]
@ianb can we do this by simulating keypress for the shortcut key of open bookmarks and open history?As a workaround for now. That can work for desktops, I guess.

**Comment by Simpcyclassy** [comment]
I am more confident about how some of these things work now, lemme fix this @ianb . I just tried it out and the API worked, it opens a modal

**Comment by annlinros** [comment]
I think this issue aims to do the same thing as #901 for which I have made a PR.

**Comment by farhatcode** [comment]
@Simpcyclassy Yes sure you can work on it. At that time I didn't knew but now I also know that we can do it by using experiments.voice api. 
But I am in the middle of some other issue, I have not started working on it yet. It's open and you can take it.

**Comment by Simpcyclassy** [comment]
> I think this issue aims to do the same thing as #901 for which I have made a PR.

OK will check the PR out

**Comment by annlinros** [comment]
Its not finished as I am waiting for feedback from Ian..
I have actually run into the commands for Bookmarks and History in serachfox.org like you did.
But I was not sure which way should I go.

May be you could also mention your PR under #901, so that @ianb can look at both.

**Comment by Simpcyclassy** [comment]
Yeah I agree @annlinros but yours looks like it just opens the sidebar, mine opens bookmarks and history specifically

**Comment by Simpcyclassy** [comment]
> Its not finished as I am waiting for feedback from Ian..
> I have actually run into the commands for Bookmarks and History in serachfox.org like you did.
> But I was not sure which way should I go.
> 
> May be you could also mention your PR under #901, so that @ianb can look at both.

Sure I will

**Comment by annlinros** [comment]
Yes I know. I was actually trying to open a sidebar like popup as Ian had asked me to.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-16).

![1](https://user-images.githubusercontent.com/54401091/79469990-899c3c00-8009-11ea-9327-3ce96bf37f8a.gif)
