### ISSUE TITLE
Add traffic intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#374]
Support queries like:

- "What is the traffic like to get to <location>"
- "Look up traffic on <hwy>"
- "How long will it take to get to <location>"

Possibly using card in doorhanger.

**Comment by ianb** [comment]
Right now these default to Google, which returns reasonable results for the queries. Maybe all we need is  #84, which lets us present the Google results better.

**Comment by ianb** [comment]
Fixed with the new search and card interface.
