### ISSUE TITLE
"Open new tab" command opens a Google search result tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#385]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Open new tab" command.

### Expected result:
A new tab opens.

### Actual result:
A Google search result of "Open new tab" is displayed in a new tab.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
The "Open a new tab" works as intended.

![120](https://user-images.githubusercontent.com/54401091/66398053-c0075780-e9e5-11e9-87b2-b545a6853554.gif)

**Comment by ianb** [comment]
This needs a slight intent matcher fix (I think currently "a" is required).
