### ISSUE TITLE
"Play" command for Spotify doesn't start audio autoplay

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#386]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Play" command for Spotify, e.g. "Play Foo". 

### Expected result:
The Spotify tab opens in a new tab and the audio starts playing.

### Actual result:
The Spotify tab opens, but the audio is not playing and there is no information about the artist.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
On Mac an "Internal error: Error: Timeout waiting for .SearchInputBox input" message is displayed in the "Doorhanger".

![121](https://user-images.githubusercontent.com/54401091/66403050-943c9f80-e9ee-11e9-82d8-e0d7bcc75ff9.gif)

<img width="1280" alt="Screenshot 2019-10-08 at 17 15 41" src="https://user-images.githubusercontent.com/54401091/66403647-99e6b500-e9ef-11e9-80c0-ba39a5eac34b.png">

**Comment by ianb** [comment]
I think the timeout on search input is just too low. We should increase it some.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
On Mac the autoplay is working but is not playing the right artist/song, like in [404](https://github.com/mozilla/firefox-voice/issues/404).

![5](https://user-images.githubusercontent.com/54401091/66648538-6c3e7d80-ec34-11e9-922c-45faaf324e4b.gif)
