### ISSUE TITLE
"Look up ... on Spotify" command opens new Spotify tab and music is played in all opened Spotify tabs

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#387]
### Prerequisites:
Mic permissions are enabled.
Have an opened Spotify tab.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Look up" command for Spotify, e.g. "Look up Green Day on Spotify".

### Expected result:
The current opened Spotify tab displays the search results while playing the audio in the background if it is playing.

### Actual result:
Another Spotify tab opens and if one Spotify tab is playing, the audio will play in both tabs.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
If music is stopped from one Spotify tab, it will also stop the music from the second Spotify tab.

![124](https://user-images.githubusercontent.com/54401091/66405995-97865a00-e9f3-11e9-9881-1a0412fd0707.gif)

**Comment by ianb** [comment]
We should remove this from the bang search. 

We should add this phrase to the music service (but it will use only the music service names).

We should check for YouTube as well.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
The Spotify "Look up" command displays the results in the same tab, but the audio starts playing. @ianb Is it intended to do that now?

![12](https://user-images.githubusercontent.com/54401091/66654485-f7267480-ec42-11e9-8881-47abf9ef5a74.gif)
