### ISSUE TITLE
[browser command] Open Settings / Preferences

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#388]
Based on telemetry users want to open the browsers setting and preferences. Implement the following:

"Open settings" or "open preferences" = Load a new about:preferences tab
"Open about debug" or "open debugging" = Load a new about:debugging tab
"Open extensions" or "open add-ons" = Load a new about:addons tab

**Comment by ianb** [comment]
We'll need privileged code to be able to open these pages, as you can't open them just with `browser.tabs.create()`.

**Comment by Simpcyclassy** [comment]
There is an API to open preferences @ianb . If you assign it to me I will add it.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-08) for commands regarding the browser's Settings and Add-ons pages.

![2](https://user-images.githubusercontent.com/54401091/78896467-32cabb80-7a79-11ea-8622-e4eb9cd43397.gif)
