### ISSUE TITLE
Reuse YouTube tab when it's the active tab.

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#397]
We should open a new YouTube tab only when the active tab isn't a YouTube tab. Otherwise we'll reuse the tab.

**Comment by amandhamija98** [comment]
Hi, I would like to work on this issue, could I please be assigned

**Comment by ianb** [comment]
@amandhamija98 You got it!

For this one, if we're about to open a YouTube tab (from `extension/services/youtube/youtube.js`) and the active tab is also a YouTube tab, then we should reuse the active tab.

Note this will require a change to `createTabGoogleLucky()` in `intentRunner.js` to allow it to use an existing tab instead of opening a new tab. I'd recommend changing its signature to:

```js
  async createTabGoogleLucky(query, options) {
    options = options || {};
    const tabId = options.tabId;
    if (tabId !== undefined) {
      ...
    } else {
      ... what it does now ...
    }
```

**Comment by amandhamija98** [comment]
Thank you, I will give this a go, given that I am a beginner, it might take me time.

**Comment by amandhamija98** [comment]
Hi @ianb , so from what I could understand, the current behavior of firefox-voice is that when a youtube tab is active and one says "open youtube", it does not open a new youtube tab, but uses the current one. However if one has an active youtube tab and says "play <song name>", it opens a new youtube tab to play a song.
If I am understanding the problem correctly, I am to fix the problem of opening a new youtube tab when  the active tab is a youtube one and the voice command is "play <song name>" by ensuring that the song is played in the active tab itself.
Could you please clarify this, thank you.

**Comment by amandhamija98** [comment]
Hi @ianb , I have submitted a PR. Kindly review it.
https://github.com/mozilla/firefox-voice/pull/1356

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-14).

![12](https://user-images.githubusercontent.com/54401091/79234260-af430d00-7e72-11ea-8358-39d15e07f1e5.gif)
