### ISSUE TITLE
Add "video" service name for play/etc

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#398]
If you say "play [something] on video" then we should treat that the same as "play [something] on YouTube"

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![11](https://user-images.githubusercontent.com/54401091/66654193-5cc63100-ec42-11e9-8b3f-a45ce48b4fee.gif)
