### ISSUE TITLE
Allow translating a page to different languages

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#403]
In #402 I added a simple translation intent. It can only translate into English.

The primary blocker for other languages is just finding the language names and corresponding language codes for a bunch of languages. E.g., `{german: "de"}`. Given that I can build the appropriate intent matchers (e.g., `translate this page into [language:lang]`), and translate the language into a language code.

**Comment by maloney8** [comment]
Hey! I would like to work on this one.

**Comment by ianb** [comment]
Again thanks @maloney8. The list of languages should go in its own file (and add that file to the list of background scripts in `manifest.json.ejs`), and then in `intentParser.js` it should get added to `ENTITY_TYPES`. Then the existing translation intent can be expanded to support other languages by putting the right value into the `tl` URL query string parameter:

https://github.com/mozilla/firefox-voice/blob/1a831e5670ea639190f99c00f6dec01230569708/extension/intents/navigation/navigation.js#L71-L105

**Comment by maloney8** [comment]
For some reason I cannot run the extension with the npm start command because I get the following error message in Firefox Nightly browser console. I've been trying to resolve this problem for a few days, but without any success. May I ask for your help to get through this problem? 


```
> Warning: unrecognized command line flag -foreground --- BrowserContentHandler.jsm:993

> Error while calling actor 'addons's method 'installTemporaryAddon' 
Could not install add-on at '/mnt/c/Users/Thomas/projects/firefox-voice/extension': [Exception... "Component returned failure code: 0x80520001
 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001
 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://devtools/server/actors/addon/addons.js :: installTemporaryAddon :: line 23"  data: no]

> installTemporaryAddon@resource://devtools/server/actors/addon/addons.js:26:13
> handler@resource://devtools/shared/protocol/Actor.js:154:37
> onPacket@resource://devtools/server/debugger-server-connection.js:378:58
> _onJSONObjectReady/<@resource://devtools/shared/transport/transport.js:464:22
> exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22
> exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22

> Unknown category for SetEventRecordingEnabled: fxmonitor

> NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] 2 network-response-listener.js:84

> No messages returned from https://snippets.cdn.mozilla.net/6/Firefox/72.0a1/2019102121…x86_64-msvc/en-US/nightly/Windows_NT%2010.0/default/default/. ASRouter.jsm:137

> Log warning: The log 'Services.Common.RESTRequest' is configured to use the preference 'services.common.log.logger.rest.request' - you must adjust the level by setting this preference, not by using the level setter Log.jsm:24

> NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] 3 network-response-listener.js:84

> [Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 174"  data: no]
```

**Comment by ianb** [comment]
It looks like something is funny with your paths or filesystem? It looks like the key error here is `/mnt/c/Users/Thomas/projects/firefox-voice/extension (NS_ERROR_FILE_UNRECOGNIZED_PATH)`

The command that it's trying to run is:

```sh
./node_modules/.bin/web-ext run --firefox-profile Profile/ --keep-profile-changes --firefox nightly --source-dir extension/ --browser-console
```

You could try to run that command, maybe removing some of the command line arguments until it works? Or, for instance, try `--source-dir /some/complete/path` if the path it's trying to load is incorrect.

**Comment by maloney8** [comment]
Well, I have the Firefox path defined the same way:
`--firefox \"${FIREFOX:-/mnt/c/program files/firefox nightly/firefox.exe}\"` 
and it works, because every time I use **npm start**, Firefox Nightly opens. I've tried your command too, but still no success.

**Comment by ianb** [comment]
I wonder if there's a problem because of the space in the path? I thought I quoted everything for that, but I might have gotten it wrong

**Comment by maloney8** [comment]
No, it can't be the space. I've tried it with another path that doesn't contain space and had the same issue.

**Comment by maloney8** [comment]
Good news, I succeeded with the installation eventually and I'm already working on the issue.

**Comment by maloney8** [comment]
I'd like to ask for your confirmation @ianb whether I understood the task well. I created the `languages.js` file with the list of languages and codes, then I added it to the `manifest.json.ejs` file and to the `ENTITY_TYPES` as `lang: languages`. Eventually in the `navigation.js` I tried to do the following: 

- created a `language` variable inside the `async run(context)` function of the `nagivation.translate` intent

- at the match field I added instead of **english** the **[language:lang]** 

`match: 
    translate (this |) (page | tab | article | site | this) (to [language:lang] |)`

- then in the URL at the `tl` query string parameter I've added instead of `en` the following value:

`https://translate.google.com/translate?hl=&sl=auto&tl=${language}&u=${encodeURIComponent...`

**Comment by ianb** [comment]
You can't nest slots and alternatives in match strings, so you can't do `(to [language:lang] |)`. Instead you should just make a separate matcher that includes `to [language:lang]`

Otherwise yes, that looks right.

**Comment by maloney8** [comment]
I fixed it in the following way: 

`match: 
    translate (this |) (page | tab | article | site | this) to [language:lang]`

Is that correct? How can I test it whether it works correctly?

**Comment by ianb** [comment]
@maloney8 If you want to make sure that different phrases work correctly, add some `test:` examples to the intent, like:

```js
match: `
...
 translate (this |) (page | tab | article | site | this) to [language:lang]
`,
examples: [
"test:translate this page to Armenian",
"test:translate this to Español", // Of course I don't know if this one works or not...
]
```

Then if you go to the intent viewer (say "show all intents") it will show you if these examples match and how the slot is filled.

**Comment by maloney8** [comment]
For some reason the Intent viewer shows a blank page to me instead of the list of intents. At the console I get the following error: 
> Error: intentParser is not defined

I'm not too sure what may cause the problem here.

**Comment by ianb** [comment]
@maloney8 There's some error loading `intentParser.js` – look back further in the Browser Console and you should see some error message. E.g., when I insert an error into that file I see this:

![image](https://user-images.githubusercontent.com/44390/68420275-9d419d80-0161-11ea-965a-9937d28985a8.png)

**Comment by maloney8** [comment]
The thing is, I don't run it with the **npm start** command, because however I tried - it just didn't want to work like that, but I've found a way to run the extension manually as a temporary add-on, but this way I don't get that initial browser console window with these messages. So when I click on the Intent viewer I get only that short message in the console which I've already mentioned. 
Basically, in the **intentParser.js** file I have changed only one row - (I've added at the ENTITY_TYPES the **lang** property). 
Isn't it possible, that the problem is here? 

```
const ENTITY_TYPES = {
    serviceName: serviceList.allServiceNames(),
    musicServiceName: serviceList.musicServiceNames(),
    lang: languages.allLanguages(),
  };
```

My **languages.js** file looks like this:

```
this.languages = {};

this.languages = (function() {
    const exports = {};

    const languages = {
        czech: "cs",
        danish: "da",
        dutch: "nl",
        english: "en",
        finnish: "fi",
        french: "fr",
        german: "de",
        hungarian: "hu",
        italian: "it",
        norwegian: "no",
        polish: "pl",
        portuguese: "pt",
        romanian: "ro",
        russian: "ru",
        slovak: "sk",
        slovenian: "sl",
        spanish: "es",
        swedish: "sv",
        turkish: "tr",
        ukrainian: "uk",
    };

    exports.allLanguages = function() {
        return Object.keys(languages);
    };
})();
```

**Comment by ianb** [comment]
You can open the console manually with Tools > Web Developer > Browser Console

That one line is presumably the one that is causing the error. Is the languages.js file included in manifest.json.ejs, and does it come before intentParser.js?

**Comment by ianb** [comment]
Hmm... nothing too helpful right there. SessionStore.jsm is not important, and I don't think BrowserElementParent.jsm is important either (I think they come from somewhere else in Firefox), though I'm less sure. But generally the errors will appear right after those manifest warnings.

Another possible option is to use `about:debugging` (enter that in the URL bar) to try to debug the add-on in another way. That gives you a debugger that points at the background page (which is where intentParser.js is loaded).

**Comment by maloney8** [comment]
With the debugger now I got the error messages I needed.

![Screenshot_1](https://user-images.githubusercontent.com/44289095/68499561-c04f7880-0259-11ea-953e-61d6581eed56.png)
I'm not sure why is the `languages` undefined. It is surely added in the `manifest.json.ejs` file.

**Comment by ianb** [comment]
Does it show up in manifest.json? (If not presumably that file didn't get rebuilt)

**Comment by maloney8** [comment]
Yes, it shows up in the manifest.json too.

**Comment by ianb** [comment]
Yes, it should be in `extension/background/languages.js` and then you'd add `background/languages.js` to manifest.json.ejs somewhere around https://github.com/mozilla/firefox-voice/blob/b916925434ec6afa3b4a87b1d8d68caeab471816/extension/manifest.json.ejs#L36

**Comment by maloney8** [comment]
I have it on the right place, still getting the `language is undefined` error. Strange.

![Screenshot_1](https://user-images.githubusercontent.com/44289095/68695091-b5a72300-057a-11ea-96bf-ac96e44848eb.png)

**Comment by ianb** [comment]
Yes, please do

**Comment by maloney8** [comment]
Okay, draft PR created.
