### ISSUE TITLE
Consecutive "Unpause" commands will pause playing on Youtube

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#405]
### Prerequisites:
Have mic permissions enabled.
Have a paused Youtube video in a tab and have that tab active.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Unpause" command.
3. Repeat steps 1 and 2.

### Expected result:
The Youtube video continues playing.

### Actual result:
The Youtube video is paused.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![2](https://user-images.githubusercontent.com/54401091/66650154-93974980-ec38-11e9-8044-844d691f4961.gif)

**Comment by ianb** [comment]
Also fixed by #417

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/66829308-c9e80800-ef5b-11e9-9ff3-1c722c622a93.gif)
