### ISSUE TITLE
Spotify and Youtube tabs will simultaneously play if one tab is playing and one is unpaused

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#408]
### Prerequisites:
Mic permissions are enabled.
Have a playing Youtube tab and a paused Spotify tab and have the paused tab active.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar in the Spotify tab.
2. Say or write an "Unpause" command.

### Expected result:
Spotify tab starts playing and the Youtube tab is paused.

### Actual result:
Both Spotify and Youtube tabs are playing.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Reproduced also for a paused Youtube tab and a playing Spotify tab, or for a paused Youtube tab and a playing Youtube tab.
I think it may be related to [346](https://github.com/mozilla/firefox-voice/issues/346).

![1](https://user-images.githubusercontent.com/54401091/66652961-95b0d680-ec3f-11e9-9367-6da8bdc4b4c9.gif)

**Comment by ianb** [comment]
I'm not able to reproduce. Here's what I'm trying to do:

- Have Spotify open in one tab
- Have a YouTube video in another tab
- Both are pause
- I say "unpause"

When I do this, whichever tab is focused becomes unpaused, and the other remains paused. Am I missing something?

**Comment by alexandra-martin** [comment]
@ianb have the following:
- the Spotify tab playing in a tab
- the Youtube tab paused in another tab
- Say the "Unpause" command while in the Youtube tab

You can do the same thing even if the tabs are switched around, meaning the Youtube tab is playing in a tab and the Spotify tab is paused in another tab. The "Unpause" command is then made in the Spotify tab.
I guess the playing tab can be paused before making the "Unpause" command, but it's an extra step, which can sometimes be forgotten.

**Comment by ianb** [comment]
This might be a little complicated to track down, but you'll want to start in `music.js` and look at the `music.unpause` intent. Which service is selected in this case? Where does the `.unpause()` method go to? Should we be calling `pauseAnyButService` or `pauseAnyButTab` there as well?

**Comment by shreyaa-s** [comment]
Hey! I would like to work on this issue @ianb

**Comment by ianb** [comment]
@shreyaa-s alright, you got it! Check out https://chat.mozilla.org/#/room/#firefox-voice:mozilla.org if you need help

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-13).

![8](https://user-images.githubusercontent.com/54401091/76628022-bd84cd00-6544-11ea-899b-fea1ddc02923.gif)
