### ISSUE TITLE
Spotify commands will not work on one device until it is made the active device

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#409]
### Prerequisites:
Mic permissions are enabled.
Have opened Spotify tabs on Win and Mac.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar on the Win Spotify tab.
2. Say or write a "Pause" or "Mute" command.

### Expected result:
The Spotify tab is paused or muted.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
To make the commands work on Win, the Win device needs to be selected from the bottom right "Connect to a device" Spotify button. 

![10](https://user-images.githubusercontent.com/54401091/66653721-56838500-ec41-11e9-8190-f70ce41831cd.gif)

**Comment by ianb** [comment]
I think this is just how Spotify works and we don't need to override it.
