### ISSUE TITLE
Use bang for "Search [service] for [query]"

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#428]
"Search [service] for [query]" should utilize the bang search if available.

Currently saying "Search Amazon for legos" returns a Google search but should display results directly on Amazon.com.

**Comment by alexandra-martin** [comment]
The bug is still reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).

![4](https://user-images.githubusercontent.com/54401091/66927136-f4a78e80-f037-11e9-8a70-dd9a52221efa.gif)

**Comment by ianb** [comment]
I wonder if this wasn't tested on the most recent version? I just tried the specific queries `search amazon for lego` and got [this](https://www.amazon.com/s?k=lego&tag=duc0c-20) and `search goodreads for harry potter` and got [this](https://www.goodreads.com/search?q=harry+potter)

**Comment by alexandra-martin** [comment]
Usually the latest version is installed each day, don't know why it was not working then. Now I verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit) and it's fine.

![3](https://user-images.githubusercontent.com/54401091/67374539-f6b6a380-f589-11e9-8508-2f97ad1ff9ed.gif)
