### ISSUE TITLE
Shortcut conflicts with 1Password's Addon

### ISSUE THREAD

**Issue by emceeaich** [mozilla/firefox-voice#431]
1 Password for Firefox's activation shortcut is `cntl + .`. 

Since it's a Mozilla recommended tool, should consider not conflicting.

**Comment by ianb** [comment]
I think the answer here will be to make the shortcut configurable in settings.

**Comment by ianb** [comment]
I've opened #560 for making the shortcut configuration, closing this in preference to that solution.
