### ISSUE TITLE
"Doorhanger" error displayed when doing blank search on Mac

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#434]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Press the "Enter" key.

### Expected result:
The "Doorhanger" doesn't have display issues.

### Actual result:
There is an "Internal error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" error displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 71.0a1 (64-bit).
Reproduced also after pressing the "Enter" key while in a blank type input mode. 

![nnnn](https://user-images.githubusercontent.com/54401091/66920669-71347000-f02c-11e9-8c22-ab3b38ce6a32.gif)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. I will submit a PR soon.

**Comment by ianb** [comment]
I'm not seeing this anymore, I believe it's fixed.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 with Firefox Nightly 73.0a1 (64-bit).

![12 13 1](https://user-images.githubusercontent.com/54401091/70805737-5b3ff300-1dc2-11ea-9a0c-ec31cbc72ce1.gif)
