### ISSUE TITLE
"Go to calendar" command opens timeanddate.com website in a new tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#435]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Go to calendar" command.

### Expected result:
Google Calendar opens in a new tab.

### Actual result:
Timeanddate.com website opens in a new tab.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Reproduced intermittently 9/10 or 10/10 times on Mac and Win.

![2](https://user-images.githubusercontent.com/54401091/66926355-9037ff80-f036-11e9-887e-85f95175494c.gif)

**Comment by ianb** [comment]
Another option (that we should discuss) is that "go to" should possibly act like "find". Or, more generally, sometimes we should focus a tab instead of launching a search, especially with an ambiguous term like "go to".

**Comment by ianb** [comment]
Right now this seems to be taking you to Google Calendar, which is OK I guess.
