### ISSUE TITLE
[Search] Eventually close/hide the search tab

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#451]
If you aren't using Firefox Voice, the extra pinned search tab seems funny. Maybe we should close or hide it? (Hiding _might_ be better, @awallin ?)

**Comment by awallin** [comment]
Agreed. What are the trade offs between hiding and closing the pinned tab? What's the experience when a user re-engages with the add-on? What would the criteria be for closing/hiding the pinned tab?

**Comment by ianb** [comment]
Eh, it already opens the tab if the user manually closes it. Probably keeping it simple and closing it is better anyway. I guess I'll do it after... 2 hours?

**Comment by ianb** [comment]
I'm setting it to close after 1 hour.
