### ISSUE TITLE
Opening a Youtube bookmark while another tab is playing allows both tabs to play at the same time

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#455]
### Prerequisites:
Mic permissions and autoplay are enabled.
A Youtube video is bookmarked, like this [one](https://www.youtube.com/watch?v=GCdwKhTtNNw).
A Youtube tab is playing in the background or as an active tab, like this [one](https://www.youtube.com/watch?v=rB6mXBWrPXY).

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write an "Open bookmark" command, e.g. "Open Youtube bookmark" or "Open bookmark sweather weather".

### Expected result:
The Youtube bookmark opens in a new tab and starts playing while the previous Youtube tab is paused.

### Actual result:
Both Youtube tabs are playing at the same time.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced also if a Spotify tab is playing while doing the "Open bookmark" command. (2nd gif)

![4](https://user-images.githubusercontent.com/54401091/67278844-7aad5480-f4d2-11e9-8028-22d3133839c3.gif)

![5](https://user-images.githubusercontent.com/54401091/67279533-db895c80-f4d3-11e9-9dfb-8b0f75ebca0d.gif)

**Comment by ianb** [comment]
We try to make playing through Firefox Voice an exclusive operation, but we can't catch every case where a video opens, only the ones where someone explicitly asks to play something. So I'm going to mark this wontfix.
