### ISSUE TITLE
"Play Youtube" command doesn't unpause Youtube video

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#470]
### Prerequisites:
Mic permissions are enabled.
A Youtube video is opened as the active tab and it is paused.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Play Youtube" command.

### Expected result:
Youtube video is unpaused.

### Actual result:
A new Google tab opens with the "youtube youtube.com" text in the search field.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The "Play video" and "Play music" commands work as intended.

![4](https://user-images.githubusercontent.com/54401091/67395913-69864580-f5af-11e9-8f61-64e8bc803069.gif)

**Comment by ianb** [comment]
Might be the same thing as #471 ?

**Comment by alexandra-martin** [comment]
@ianb It seems the fix for #471 fixed this too.
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![3](https://user-images.githubusercontent.com/54401091/67660974-ae6ffa80-f968-11e9-9ee9-ac93dbc7a765.gif)
