### ISSUE TITLE
[Intermittent] "Unmute" command doesn't unmute active tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#483]
### Prerequisites:
Mic permissions are enabled.
Have two audio/video tabs opened and muted and one tab is active.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write an "Unmute" command.

### Expected result:
The active tab is unmuted.

### Actual result:
The inactive tab is unmuted.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced intermittently on both Mac and Win, either 4, 5, or 6 out of 10 times.
Following the above steps, other intermittent behaviors were observed on Mac and Win:
- 1, 3, or 4 out of 10 times, the command unmuted both muted tabs; (2nd gif) 
- 1 or 2 out of 10 times the "Unmute" command did nothing;
- 0, 1, 2 or 3 out of 10 times the "Unmute" command worked as intended.

![5](https://user-images.githubusercontent.com/54401091/67490447-ef6fc280-f67b-11e9-8a22-7b142ccc66ba.gif)

![9](https://user-images.githubusercontent.com/54401091/67490456-f4347680-f67b-11e9-9641-4853924a4b0b.gif)

**Comment by ianb** [comment]
I'm guessing this is a racy issue between the muting that happens when you activate the microphone, and the muting that happens explicitly when you ask Firefox Voice to mute.

**Comment by vandnakapoor19** [comment]
@ianb I'd like to work on this issue.

**Comment by ianb** [comment]
@vandnakapoor19 You got it

**Comment by vandnakapoor19** [comment]
@ianb I am checking this issue. I'd like to explain the current functionality. Right now when I write an "Unmute/mute" command. It is working on all the tabs.

![unmute](https://user-images.githubusercontent.com/45131874/76920395-c3aade80-68a1-11ea-98cf-c3092bca88c9.gif)


Give me detailed information about how it should work?

**Comment by vandnakapoor19** [comment]
@ianb @awallin Waiting for feedback. Please let me know if this is expected behavior?

**Comment by vandnakapoor19** [comment]
@alexandra-martin  Please check my comment above and let me know in case I've to make any change in the process.

**Comment by alexandra-martin** [comment]
@vandnakapoor19 I think this issue and #1250 might be duplicates. #481 and this issue have the same date and I most probably had muted the active tab manually, before performing the "Unmute" command.
I will close this bug for now.
