### ISSUE TITLE
Several Firefox Voice onboarding page UX issues

### ISSUE THREAD

**Issue by dholbert** [mozilla/firefox-voice#485]
I'm filing this for several UX issues I noticed on the onboarding page (sorry for the grab-bag bug -- I wanted to capture this while the onboarding page was open & screenshot-able).

Here's the onboarding page after I installed the extension:
![image](https://user-images.githubusercontent.com/426803/67504020-849f9680-f63d-11e9-8cbf-fc96f83588d6.png)

The issues I had with it (first four have arrows in the screenshot to highlight the problem):
 (1) There's an `x` close button superimposed with text in the green box, at the top right.

 (2) The green box instructs me to "...revisit this page" in order to change my microphone settings, but it's not at all clear how I would get back to this page.  The URL is `moz-extension://32d99ac7-86b0-4c46-85c6-252f39fbcca7/onboarding/onboard.html` which is not an easy URL to remember. :)

 (3) The `Extension (Voice Fox)` img is awkwardly linewrapped (especially weird: the close-paren after it ends up on a separate line).  This is because the page has CSS that gives this element `display:block`.  The relevant style is in `tailwind.min.css`:
```
audio,
canvas,
embed,
iframe,
img,
object,
svg,
video {
 display:block;
 vertical-align:middle
}
```
We should remove or override that styling so that this img flows more naturally in the paragraph.

(4) The microphone icon used in the page is not the same one that I actually see on my toolbar.

(5) The onboarding page's keyboard combination, `Ctrl` `.`, **does not actually activate Firefox Voice for me**. Instead, it activates the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/) extension's new-tab popup.  It seems that combination is used by multiple addons (at least these two) -- is there a way that we can detect that it's already used, and avoid suggesting it if it is?

**Comment by awallin** [comment]
@dholbert Thanks for flagging these issues. We're actually working on a completely new design for the onboarding page which will address the issues in the green box and the mic icon. As for the shortcut key we've had other reports of conflicts and will look for alternatives or ways to address the conflict. Thanks!

**Comment by ianb** [comment]
I'm going to close this particular ticket, as @awallin is going to make a ticket describing a full redesign of the onboarding page, and it will take these suggestions into account.
