### ISSUE TITLE
Firefox Voice "gear icon" moves to three different positions, making it hard to click

### ISSUE THREAD

**Issue by dholbert** [mozilla/firefox-voice#486]
STR:
 (1) Click the mic icon on your toolbar.
 (2) Watch the gear icon (and try to click it, pretending you're a bit slow with your mouse)

ACTUAL RESULTS:
The gear moves between three different positions, due to the dialog resizing as its content changes.  (There are three phases: "Listening", "One Second", and then "Sorry, there was an issue".  Each phase has a different dialog height and a different position of the gear.)

EXPECTED RESULTS:
The gear should be at a consistent position so that it is easy to click.

**Comment by xlisachan** [comment]
@ianb I am an Outreachy applicant. Can I be assigned to this issue?

**Comment by ianb** [comment]
Unless @awallin feels differently, I think there's nothing left to actually fix on this ticket. It does move around a little bit when the examples open up, but otherwise it's OK. Though if @awallin wanted to move it to a more consistent location (e.g., the top of the popup) then we could reopen.

**Comment by awallin** [comment]
Yea, it's ok to close.
