### ISSUE TITLE
The buttons in firefox voice dialog need hover-styling so you can tell they're clickable

### ISSUE THREAD

**Issue by dholbert** [mozilla/firefox-voice#487]
STR:
 (1) Click the microphone icon in your toolbar.
 (2) Hover the "x" icon at top right, or the gear icon at the bottom left (or the "<" icon that eventually appears at top left on the "Sorry, there was an issue" page, if you don't speak anything out loud)

ACTUAL RESULTS: The buttons don't look any different when hovered.

EXPECTED RESULTS: The buttons should darken (or change look somehow) when hovered, to make it clear that they are indeed buttons and not just decoration.

See the "Firefox Private Network" add-on for reference -- its panel has a gear icon, as well as a "<" icon (inside its "gear" settings panel), and in that extension, both of these buttons change their look when hovered. It'd be great if we could use the same hover-styling as used in Firefox Private Network.

**Comment by ianb** [comment]
We need to add `cursor: pointer` to the styles on these elements.
