### ISSUE TITLE
Firefox Voice still uses Google after I've switched default search engine to Duck Duck Go

### ISSUE THREAD

**Issue by dholbert** [mozilla/firefox-voice#488]
STR:
 (1) Click the mic icon, and say some non-specific command (e.g. "test" or "some search term")
 (2) Observe that this produces a Google search.
 (3) Change your Firefox default search engine to Duck Duck Go, at about:preferences#search
 (4) Repeat step 1.

ACTUAL RESULTS:
Firefox Voice still does a Google search for my voice input.

EXPECTED RESULTS
Firefox Voice should respect my choice of search engine (and in particular, it should respect users' decisions to avoid Google)

**Comment by ianb** [comment]
Right now we're writing code that is very specific to Google, and goes beyond the standard search provider metadata. We could write similar code for duckduckgo, but it would be more custom code for a new search provider. (Or we could do some standard interface, but we're still experimenting with how we make use of search, so we aren't ready to create any abstraction.)

This is all stuff we could do, but aren't ready to do right now.

**Comment by ianb** [comment]
Fixed in #694
