### ISSUE TITLE
Firefox Voice keeps a pinned tab open, with mic persistently activated, even after command has been handled

### ISSUE THREAD

**Issue by dholbert** [mozilla/firefox-voice#489]
STR:
 (1) click the mic icon
  --> A pinned tab appears at the left of my tabstrip, and the Firefox "some tab is using your mic" overlay appears at the top center of my screen.
 (2) Speak some command/term
 (3) Wait.

ACTUAL RESULTS:
Firefox's "some tab is using your mic" overlay sticks around indefinitely, even after the spoken command has been handled.  It's associated with the pinned tab.  This suggests that Firefox Voice is still subtly listening to me (though perhaps not intending to do so), even after it's handled my command.

The "some tab is using your mic" overlay only disappears when I close the Firefox Voice pinned tab at the far-left of my tabstrip.

**Comment by dholbert** [comment]
Screencast (note the overlay appear and then persist at top-center of screen):
https://www.dropbox.com/s/c8x71d9j41sg1sv/firefox-voice-persistent-overlay.ogv?dl=0

**Comment by awallin** [comment]
Thanks for reporting the issue @dholbert. Currently the pinned tab is how the add-on acquires and maintains mic permissions. The mic is only open when triggered and is then paused after processing so it can be re-opened when triggered again.

This is a short term work around to permission issues that exist for add-ons accessing the microphone. We're working with the Firefox team on a long term solution so we don't have to pin a tab.

@ianb For the interim we may want to consider messaging in the pinned tab to clarify.

**Comment by dholbert** [comment]
> @ianb For the interim we may want to consider messaging in the pinned tab to clarify.

FWIW, I didn't even notice the presence of the pinned tab at first, so I'm not sure users will notice it or think to look there.

If we're going to live with this "mic-active" notification, I'd suggest messaging about it somewhere more prominent, like on the firstrun page and/or the popup.  (But I'd much prefer we get rid of the mic-active notification in whatever way we can...)

> Currently the pinned tab is how the add-on acquires and maintains mic permissions. 

Why do we need to "maintain" mic permissions between usages of the addon?  Perhaps after N seconds of no voice commands (where N might be 0 or 10 or something), the addon could close the pinned tab (which gets rid of the overlay) and only reopen it if the user triggers the button again?

Right now the overlay gives a strong indication that Firefox is persistently listening to the user from the point that they click the mic, and that is a really bad look, privacy-wise.

**Comment by dholbert** [comment]
Update: the pinned tab is now gone (or hidden), but the "mic active" popup is still present.

Looks like maybe this will be fixed in #86, though (as mentioned on roughly-dupe-issue #828).

**Comment by ianb** [comment]
FWIW, we're probably going to double-down on the pinned tab because we're trying out a wakeword, which requires keeping the mic open.

**Comment by dholbert** [comment]
Cool. With a wake word, the persistent mic-active indicator is less surprising/ creepy, I think.

**Comment by ianb** [comment]
Fixed in #86/#1064
