### ISSUE TITLE
Add scroll intents

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#492]
For some hands-free operation, `(scroll | page) (down | up)` could be useful.

**Comment by ankiiitraj** [comment]
Hi @ianb, could you please help me, I want to contribute in this.
I didn't get what is to be done.

**Comment by vanekcsi** [comment]
What API should be used for this?

**Comment by ianb** [comment]
Oops, I missed the first comment here. But time has passed. 

@vanekcsi : there's no WebExtension API for this, so you'd have to create a new script and inject it with lazyInject (if you look around there's some examples in the code). To actually scroll call [scrollBy](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy) from the content script.

**Comment by awallin** [comment]
Ideally the action of scrolling (up or down) will move the page far enough to read/see new content but not far enough where the user doesn't have a reference to their previous location.

There's a bit of finesse needed fro scroll speed to ensure the user can track what is happening. Easing the animation in/out would be a nice addition.

**Comment by ianb** [comment]
If we get something working we can tweak it. But `scrollBy` has an option to do an animation, and the scroll amount should probably be `window.innerHeight - overlap` where overlap is... I'm not sure, 10%? 40px?
