### ISSUE TITLE
Wait for sound before timing out

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#494]
Right now the silence timeout starts right away, so you only have a bit of time after activating to speak. We should wait for substantially longer at the beginning to see if the person speaks.

**Comment by awallin** [comment]
Yes, this would be great. Allows the timeout to be shorter and the experience to feel snappy without also reducing the amount of time a user has to begin speaking after the trigger.

**Comment by ianb** [comment]
With the longer timeout I think we're good.
