### ISSUE TITLE
Try hiding the recorder tab

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#503]
I'm not 100% sure we want to do this, but we could [hide](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide) the recorder tab instead of pinning it.

**Comment by ianb** [comment]
Looking at the [docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide) it says: "Tabs that are sharing the screen, microphone or camera cannot be hidden."

So we can't do this.

**Comment by ianb** [comment]
I'll experiment with this a bit more to see if something is possible.

**Comment by PopeRigby** [comment]
Maybe just automatically close it when the user closes the FV popup.

**Comment by ianb** [comment]
With #86 this doesn't seem so important.
