### ISSUE TITLE
Redesign onboarding page

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#505]
Based on user research and existing issues such as #108 a full redesign of the onboarding page seen after installation is warranted.

**Comment by awallin** [comment]
Attaching mockups for onboarding page.

![Onboarding - Beta](https://user-images.githubusercontent.com/428245/68619948-4e597800-0481-11ea-8e73-9466b5bd33a9.jpg)

Also available on Abstract.
https://share.goabstract.com/d17a936c-1bf8-466a-b37f-0db3ede9cc37?mode=design&sha=53c16ac04dd48043963277bfdeb7de18e845d985

**Comment by ianb** [comment]
Fixed in #635
