### ISSUE TITLE
Replace starting chime sound

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#51]
We should decide on another chime sound for when you start audio (replacing https://jcambre.github.io/vf/mic_open_chime.ogg)

**Comment by awallin** [comment]
While we're at it we might want a sound for "success" and "error" events.

**Comment by awallin** [comment]
Let's go with box for the audio chime.

[box.zip](https://github.com/mozilla/firefox-voice/files/3924033/box.zip)
