### ISSUE TITLE
Enable Google sidebar cards

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#514]
When Google returns a sidebar card for a search we should display in the doorhanger (and preference over the main column snippit).

**UI Details**
- Screenshot should scale down to ~310px to fit within the normal 
- Variable height with a max height of 550px.

![sidebar-card](https://user-images.githubusercontent.com/428245/67904856-e758cc80-fb2c-11e9-9847-ab27b9ac29a0.jpg)

Examples utterances:
* Who is Harry Truman
* Who is Barack Obama
* Modest Mouse or who is modest mouse

**Comment by ianb** [comment]
Should be fixed by #518

**Comment by awallin** [comment]
Cards are not/no longer being displayed for sidebar cards.
