### ISSUE TITLE
Snippit Card Design

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#517]
Updated design for cards that display snippit.

**Behavior & Features**
- A click anywhere on the card will open the first result in a new tab
- Screenshot of snippit scaled down to fit standard doorhanger size. Aproximately ~310px
- Utterance displayed at top of doorhanger
- Hint for 'more' functionality displayed at bottom

![snippit-card](https://user-images.githubusercontent.com/428245/67905238-f2f8c300-fb2d-11e9-8780-530f7de8505a.jpg)

**Comment by ianb** [comment]
We'll follow up in better detail in other tickets, maybe with mobile cards instead of screenshots.
