### ISSUE TITLE
Show Google knowledge results when searching

### ISSUE THREAD

**Issue by jcsteh** [mozilla/firefox-voice#520]
With the new search interface, it'd be great if Google knowledge results (which appear before web results, etc.) could be shown as search cards in the pop-up. This way, you possibly wouldn't even have to open the search to see the info you needed. For example:

- [time in California](https://www.google.com/search?client=firefox-b-d&q=time+in+california): Google shows something like:
    > 8:06 pm
    > Thursday, 31 October 2019 (GMT-7)
    > Time in California, USA 
- [1pm brisbane time in california](https://www.google.com/search?client=firefox-b-d&q=1pm+brisbane+time+in+california): Google shows something like:
    > 1:00 pm Friday, in Brisbane QLD is 
    > 8:00 pm Thursday, in California, USA
- [phone number for sushi bar samford](https://www.google.com/search?client=firefox-b-d&q=phone+number+for+sushi+bar+samford): Google shows something like:
    > (07) 3289 5923
    > Sushi Bar Tokyo Roll, Phone
- [51 aud in usd](https://www.google.com/search?client=firefox-b-d&q=51+aud+in+usd): Google shows something like:
    > 51 Australian Dollar equals
    > 35.23 United States Dollar

The tricky thing about these is that they don't necessarily have a useful URL, so "next result" might not work so well.

**Comment by awallin** [comment]
We're with you @jcsteh! In version 0.11 many of the knowledge results appear in the pop-up. Version 0.12 includes additional knowledge results that didn't make it into 0.11 and results that appear in sidebar card (mostly wikipedia entries).

See #500 and #514

**Comment by jcsteh** [comment]
Awesome! To clarify, I'm running from Git master and none of the cards I
mention here are detected yet. I'm not sure whether you were suggesting the
recent changes mean they should be already or not, so just wanted to
clarify.

**Comment by awallin** [comment]
I tested the examples you provided and they all result in cards displayed in the pop-up. What version of the add-on do you have installed? We've had some trouble with auto updating. You could try uninstalling and re-installing to ensure you have the latest version.

**Comment by jcsteh** [comment]
I'm running from Git master; i.e. I cloned from Git, built it and ran it as
a temporary add-on in about:debugging. Even with the official add-on
(currently 0.11.0 on my system), I don't see the cards I expect.

To be clear, if I ask "time in California", I do see a card, but it's a
card for timeanddate.com, not the card showing the actual time as shown as
the first card on Google itself.

**Comment by ianb** [comment]
I just tested these each with master today and they all seem to be working. I made a number of fixes specific to this in #533 (c3dcf395eb5449c4c9c45a920077484bf8c7c1a0) which fit the problems you describe. Please reopen if I mistook something!

**Comment by jcsteh** [comment]
I just tested with latest master (confirming that it included #533 and rebuilding), but I still don't see these cards. For example, I get a card for timeanddate.com when I ask for "time in California", rather than the time as reported on the first card on Google.

Is there something I can provide to help diagnose this?e

**Comment by ianb** [comment]
Here's what I'm getting:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/44390/68411742-a118f400-0150-11ea-806f-953bf27f50f0.png">

The search tab (the pinned Google tab) looks like this:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/44390/68411769-b2fa9700-0150-11ea-9227-cdb7002cc1b7.png">

And the HTML that is being pulled out is:

```html
<div class="vk_c vk_gy vk_sh card-section sL6Rbf">
  <div class="gsrt vk_bk dDoNo" aria-level="3" role="heading">9:20 AM</div>
  <div class="vk_gy vk_sh">  
    Thursday, <span class="KfQeJ">November 7, 2019</span>  
    <span class="KfQeJ"> (PST) </span>  
  </div> 
  <span>  Time in California  </span>      
</div>
```

The conditions for finding this particular card are: it matches the selector `.vk_c` and the element's top (`document.querySelector(".vk_c").getBoundingClientRect().y`) is less than the first search result... which I'm realizing maybe I didn't calculate correctly (it was `document.querySelector("a > h3").getBoundingClientRect().top` but probably should have been `document.querySelector("a > h3").getBoundingClientRect().y`).

Ugh... boxes and heuristics are throwing me here! I don't actually see this problem though, and I don't know why – google.com A/B testing, some locale thing, screen size, ...? Anyway, I can't reproduce, but the code isn't consistent here so it's a reasonable change anyway (and doesn't regress things for me). I made this change in #549 (merged to master), does it help?

**Comment by ianb** [comment]
@jcsteh Did this change help at all? The change is available in the dev version: https://va.allizom.org/releases/dev/firefox-voice.xpi

**Comment by jcsteh** [comment]
I just tried the latest dev version and am still not getting the desired
result here. For example, "time in California" still shows me a card for
www.timeanddate.com, rather than the Google time card.

**Comment by ianb** [comment]
@jcsteh can you add a screenshot of the google.com page that you get from that query?

**Comment by jcsteh** [comment]
Apologies if this isn't right; I'm blind, so can't see the screenshot myself to confirm:
![Screenshot](https://user-images.githubusercontent.com/4166475/68908508-49553b00-0797-11ea-9645-556fb361d017.png)

**Comment by ianb** [comment]
That is perfect, thanks. Your page looks just like mine, so now I'm pretty confused!

**Comment by ianb** [comment]
Putting in backlog because I can't reproduce, and everything _seems_ fine. It may be some interaction with other tools?

**Comment by jcsteh** [comment]
This now works as expected for me. I'm not sure what was going on - it could have been a case of PEBCAK? - but I'm glad that it works now.

**Comment by ianb** [comment]
Oh, good to hear, I don't think it could be a user issue on your part because this shouldn't be user-involved. But there are lots of non-deterministic parts here, and who knows, Google might have been running an A/B test on you. Or maybe we weren't using the same version of the extension (it's been slow to update for reasons I have not determined)
