### ISSUE TITLE
"Search" command result is not always displayed in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#521]
### Prerequisites:
Have 2 Firefox Nightly profiles with the latest add-on installed and mic permissions enabled.
Repeat the below steps for each profile. 

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search" command, e.g. "Search lion", or "Lion".

### Expected result:
The result is displayed in the "Doorhanger".

### Actual result:
The results differ from profile to profile, the "Dorhanger" either displays the result or a new tab opens with the first website found from the pinned Google tab.

### Notes:
Reproduced on Win10x64 with Firefox Nightly 72.0a1 (64-bit).
A few times the "Internal error: Error: communicate is not defined" error was displayed in the "Doorhanger" on Mac. (3rd image)

![7](https://user-images.githubusercontent.com/54401091/68024123-ddaca180-fcb1-11e9-8389-b9e71429c7c4.gif)

![8](https://user-images.githubusercontent.com/54401091/68024128-e1402880-fcb1-11e9-8606-e937288fc7a6.gif)

<img width="1280" alt="Screenshot 2019-11-01 at 15 23 44" src="https://user-images.githubusercontent.com/54401091/68028659-118dc400-fcbe-11e9-87a4-34562a1150fd.png">

**Comment by ianb** [comment]
I think this was fixed with the recent card fixes.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![4](https://user-images.githubusercontent.com/54401091/68584789-371e8880-0489-11ea-8a78-99431ad2a9b7.gif)
