### ISSUE TITLE
The "Back" and "Close" buttons are not working if "Doorhanger" has scrollbar

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#522]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search" command, e.g. "Search lion", or "Lion".
3. Click on the "Back" and "Close" buttons.

### Expected result:
"Doorhanger" either closes or resets.

### Actual result:
The "Doorhanger" information is scrolled down.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced for other commands where the scrollbar is present in the "Doorhanger". (2nd gif)

![4](https://user-images.githubusercontent.com/54401091/68026393-49920880-fcb8-11e9-9901-9ba825fd6c54.gif)

![11](https://user-images.githubusercontent.com/54401091/68026400-4c8cf900-fcb8-11e9-83fd-c94e42b11c24.gif)

**Comment by alexandra-martin** [comment]
It seems the issue no longer applies. Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![8](https://user-images.githubusercontent.com/54401091/69975520-0aadd780-1530-11ea-91f0-77764ea484be.gif)

**Comment by vandnakapoor19** [comment]
@ianb I'd like to work on this issue.

**Comment by ianb** [comment]
@vandnakapoor19 Sure! There's been some design changes that might have effected this, so try to reproduce it first.

**Comment by vandnakapoor19** [comment]
Sure, Thank you!

**Comment by vandnakapoor19** [comment]
@ianb I’m not able to reproduce the above issue and It is working perfectly fine.

System Configuration: -
OS: Windows 10x64
Firefox Nightly: Version 75.0a1
Node: v12.16.1

Back Button

![back](https://user-images.githubusercontent.com/45131874/76789759-d931e280-6793-11ea-8c52-b12cd88518e1.gif)

Close Button

![lion search](https://user-images.githubusercontent.com/45131874/76789802-ef3fa300-6793-11ea-8ac0-95b8199b39ba.gif)

**Comment by alexandra-martin** [comment]
@vandnakapoor19 yes, indeed this might have been resolved a while ago, since this report is so old. But can you try to make these commands again and see if you still get cards in the doorhanger? I currently have problems with that and can't verify.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-27) and the issue is not reproduced anymore.

![2](https://user-images.githubusercontent.com/54401091/77771309-33159080-704f-11ea-87c8-738d72ca31b4.gif)
