### ISSUE TITLE
"A privacy reminder from Google" blocks the Google card to be displayed in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#524]
### Prerequisistes:
Have a new Firefox Nightly profile with the add-on installed and the mic permissions enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Weather" command, e.g. "What's the weather today", or "Weather".

### Expected result:
"Doorhanger" displays the Google weather card without issues.

### Actual result:
 "A privacy reminder from Google" window blocks the Google card to be displayed in the "Doorhanger". 

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced also for other commands, like the "Calculation" command.
After clicking the "Review" and "I Agree" buttons, the Google card is displayed in the "Doorhanger".
If the "Remind me later" button is pressed the card will not be displayed. (2nd gif)

![12](https://user-images.githubusercontent.com/54401091/68030507-51ef4100-fcc2-11e9-85fb-6e25a9049398.gif)

![5](https://user-images.githubusercontent.com/54401091/68030037-418a9680-fcc1-11e9-9c82-c5a47acaaca9.gif)

**Comment by ianb** [comment]
@awallin do you think this is worth fixing? It feels fiddly but also pretty easy for the user to fix for themselves.

**Comment by awallin** [comment]
How would we fix it? Auto click the button?
