### ISSUE TITLE
[Intermittent] "Doorhanger" size is not the same in all sessions

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#525]
### Prerequisites:
Mic permissions are enabled.
Make sure that the Firefox Nightly profile displays the command results in the "Doorhanger" on Win.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search" command, e.g. "Search lion", or "Lion".

### Expected result:
The "Doorhanger" displays the the result without any display issues.

### Actual result:
"Doorhanger" size extends past the 320 x 550 px size.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The size of the two "Doorhanger" versions are approximately around 398 x 603 px, respectively around 506 x 603 px.
Couldn't exactly pinpoint how many times a size is more predominant than the other, because of factors such as, the Firefox Nightly profile, the size of the browser window. (2nd gif)

![10](https://user-images.githubusercontent.com/54401091/68031244-ec03b900-fcc3-11e9-81e8-75aea80c86ed.gif)

![13](https://user-images.githubusercontent.com/54401091/68032079-93cdb680-fcc5-11e9-87bd-1194a91bb40e.gif)

**Comment by ianb** [comment]
This is the result of google.com responding to the smaller window size, and we're just showing an image of what it displays in its tab. I think this is fine.
