### ISSUE TITLE
Put all lexicon phrases in examples

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#527]
Anything in the lexicon should be in an example, at least as a test, so we can confirm they all stay correct. Or maybe we mark up the examples in the HTML (e.g., `data-intent="something"`).

**Comment by annlinros** [comment]
Hi @ianb 
I am an outreachy applicant, Can i please work on this issue ?

**Comment by noi5e** [comment]
@ianb I could work on this issue too, if annlinros is assigned to another one. Just assign me to it if there's no one else.

It sounds like a pretty simple task, but could you give a few more details to help me find what you're talking about in the code?

**Comment by annlinros** [comment]
Hi @ianb Could you please elaborate on the issue ? Much thanks.

**Comment by PrastutiUpadhaya** [comment]
Hi, @ianb can I please work on this?

**Comment by ianb** [comment]
@annlinros @noi5e @PrastutiUpadhaya Looking at this issue I'm afraid it's really not well specified or up to date, so I'm going to close it. Sorry for the confusion!
