### ISSUE TITLE
Card formats not displayed yet in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#539]
Several card formats are not yet supported to be displayed in the "Doorhanger". 
- "What's the cast of Breaking Bad"/"What's the second tallest mountain in the world" commands display cards like:
![2019_11_05_14_15_55_Window](https://user-images.githubusercontent.com/54401091/68207087-ddc0e000-ffd6-11e9-90f6-5cc4ac2622da.jpg)

- "What to do in LA"/"Places to visit in America" commands display cards like:
![2019_11_05_14_18_44_Window](https://user-images.githubusercontent.com/54401091/68207520-c7ffea80-ffd7-11e9-9017-4aac868e9056.jpg)

- "How many Oscars does Tarantino have"/"What's the schedule of the Cluj Opera" commands display cards like:
![2019_11_05_14_27_06_Window](https://user-images.githubusercontent.com/54401091/68207802-6be99600-ffd8-11e9-8dd9-144a5171b69c.jpg)
![2019_11_05_14_26_12_Window](https://user-images.githubusercontent.com/54401091/68207804-6db35980-ffd8-11e9-84d6-498644775b1b.jpg)

- "Recipe for Bok Choy"/"How to make steak" commands display cards like:
![2019_11_05_17_09_01_how_to_make_steak_Google_Search_Firefox_Nightly](https://user-images.githubusercontent.com/54401091/68219680-0d7be200-ffef-11e9-8780-efb5e90c3589.jpg)

**Comment by ianb** [comment]
I think the only ones we actually want to fix here are:

> "How many Oscars does Tarantino have"/"What's the schedule of the Cluj Opera" commands display cards like:

The other ones aren't particularly good cards. E.g., the recipes are fancy links, but they don't contain the recipe in the card itself.

**Comment by ianb** [comment]
Actually, looking at "How many Oscars does Tarantino have" and "What's the schedule of the Cluj Opera", the results are very wide and hard to display in a popup:

![image](https://user-images.githubusercontent.com/44390/72368562-f418a580-36c3-11ea-8e42-35e041de8a25.png)
