### ISSUE TITLE
Come up with some testing system

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#55]
This might even be as simple as a script, but I feel like the surface area is somewhat unclear without some documentation or a process.

Technically Selenium testing should be possible, but ugh.

**Comment by ianb** [comment]
We have some jest tests, though they don't test the startup of the test. A basic Selenium test still might make sense.

**Comment by lelouchB** [comment]
Hey @ianb I wanted to work on this issue
I am going to start on this right away
I will send a PR as soon as I am done

**Comment by ianb** [comment]
Great! Here's an example of how this could work: https://github.com/mozilla-services/screenshots/blob/9df16347d2c88d3973f3d100505f4d918d7edb75/test/test.js

Specifically that is a Selenium test that installs the extension. That test does a few things, but for now I would be very happy with a test that simply builds the extension, installs it with Selenium, and tests that the toolbar button is present. That will catch lots of basic build errors that could otherwise go undetected. You might have to use the Browser Toolbox to figure out some of what is being tested: https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

This is a fairly hard bug, so if you get stuck or part way please open a draft PR for feedback or help.

**Comment by lelouchB** [comment]
@ianb I have started working on this, After going through the test in screenshots, I now have a basic idea to approach this issue
