### ISSUE TITLE
Require Beta participants to opt-in or out of transcript

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#552]
To ensure Beta participants are aware of how their voice transcript will/can be they will have to opt-in or opt-out prior to using the app.

Following installation inform participants and ask for agreement with the following experience:
- Immediately following mic permissions being successfully granted
- Overlay the onboarding page with a request to "Allow Firefox Voice to collect voice transcripts"
- Participant can choose to "Allow" or "Don't Allow"

- If participant closes the tab or attempts to use Firefox Voice before making a selection the mic should not open and no utterance should be captured/recorded.
- The onboarding page is brought to the forefront (or re-opened) with the overlay displayed
- The doorhanger directs the participant to make a selection before they can use the add-on

**Final text for the overlay is still pending legal review**

![Onboarding - Beta B](https://user-images.githubusercontent.com/428245/68506262-17375c80-021e-11ea-94bc-e28c4252fb52.jpg)

**Comment by awallin** [comment]
"Learn more..." link should open in a new tab.

**Comment by awallin** [comment]
Final copy available in this content doc:
https://docs.google.com/document/d/17MnBTuO4Mxl7HZbYF6nxMVtni-MzuYLHkjtauvKiqxs/edit?usp=sharing

**Comment by ianb** [comment]
We want to save the timestamp when the person opted in or out. That timestamp can also be used to determine if the user should see the opt-in/out question. We could make that a setting (using the `settings` module).

But it's ok if the logic isn't all worked out before the initial PR.

**Comment by ianb** [comment]
Oops, I dup'd this in #653. Fixed in #662
