### ISSUE TITLE
Error displayed in "Doorhanger" when "Play" command doesn't find audio to play

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#557]
### Prerequisites:
Mic permissions are enabled.
A Spotify account is signed in and autoplay is enabled beforehand.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a Spotify "Play" command that will not have any results or any audio to play, e.g. "Play Ben Folds in Spotify" or "Play testtesttesttest".

### Expected result:
"Doorhanger" displays a message that audio cannot be played.

### Actual result:
An "Internal error: Error: Timeout waiting for #searchPage button[aria-label='Play'], .tracklist .tracklist-play-pause" error is displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![6](https://user-images.githubusercontent.com/54401091/68588050-3b4ea400-0491-11ea-8fc3-3e38a4d1d99d.gif)

**Comment by ianb** [comment]
This is a bit complicated for a good first issue, but should be doable.

Mostly the content script (`extension/services/spotify/player.js`) should detect this not-found case, and raise an appropriate exception, then `spotify.js` should make that into an error with a `.displayMessage = "No results found"`.

**Comment by JanviMahajan14** [comment]
@ianb I would like to work on this issue

**Comment by noi5e** [comment]
@ianb with Outreachy, i'd like to give this a shot. can you assign this one to me?

**Comment by noi5e** [comment]
@ianb @alexandra-martin I've got the dev environment set up, and I'm reproducing this bug. 

would love to work on it, if it's still a relevant contribution. just let me know!

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win 10x64 with Firefox Nightly 76.0a1 (2020-03-18).

![7](https://user-images.githubusercontent.com/54401091/76971607-12a25380-6936-11ea-83c1-c90747c9254a.gif)
