### ISSUE TITLE
Images are not displayed in "Doorhanger" when making "Search" commands

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#558]
### Prerequisites:
Mic permissions are enabled.
Make sure the "Search" command used in the steps was not used before.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search" command, e.g. "Search lion".

### Expected result:
"Doorhanger" doesn't have display issues.

### Actual result:
Images from the "Search" command are not displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 72.0a1 (64-bit).
When making the "Search Lion" command a second time the images are displayed.
An "Internal error: Error: communicate is not defined" error appeared one time when reproducing the bug. 
Making new "Search" commands, then remaking the "Search Lion" command will reproduce the bug. (2nd gif)

![11 11 (1)](https://user-images.githubusercontent.com/54401091/68590031-36402380-0496-11ea-97e5-f16d03db9ee8.gif)

![11 11 2](https://user-images.githubusercontent.com/54401091/68590037-3b04d780-0496-11ea-91e7-14c9a1a65a1d.gif)

**Comment by alexandra-martin** [comment]
#### Update:
It seems the bug is reproducing intermittently on Win 10, depending on the Firefox Nightly profile and the browser screen size.

![Annotation 2019-11-15 154556](https://user-images.githubusercontent.com/54401091/68947832-1b83ec80-07bf-11ea-9b3a-b6a432bc5093.png)

**Comment by ianb** [comment]
I think this was fixed by #608 (the images were taking a while to load, but now we catch up once they do load)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![4](https://user-images.githubusercontent.com/54401091/69965527-1e037780-151d-11ea-9950-bb06e121e96c.gif)
