### ISSUE TITLE
"Previous result" command makes a new Google search

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#562]
### Prerequisites:
Mic permissions are enabled.
A "Search lion" command is made to have the result in the "Doorhanger" and two "Next result" commands are made consecutively to have the new tab opened with the second website from the Google search list.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Previous result" command.

### Expected result:
The previous website is displayed in the tab regarding lions.

### Actual result:
A new Google search is made for "previous result" and the first website from the search list opens in a new tab.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![3](https://user-images.githubusercontent.com/54401091/68672347-107c5280-055a-11ea-9a45-90c6780e8fc9.gif)

**Comment by ianb** [comment]
Apparently "previous" isn't even implemented (in `search.js`), only next.

**Comment by maitrella** [comment]
@ianb please I need your feedback on this task.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![9](https://user-images.githubusercontent.com/54401091/70809025-a1e51b80-1dc9-11ea-83c4-e109348e65f3.gif)
