### ISSUE TITLE
Youtube "Play" command displays a Google search page for certain queries

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#563]
### Prerequisistes:
Mic permissions and autoplay are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a Youtube "Play" command, e.g. "Play testtesttest on youtube" or "Play 6789 on youtube".

### Expected result:
A Youtube tab opens in a new tab and a query related video starts playing.

### Actual result:
A Google search result page opens in a new tab.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/68673392-4f130c80-055c-11ea-9905-4f477c847f59.gif)

**Comment by ianb** [comment]
You should re-verify this bug if you want to try taking it. If it's fixed please comment here. If it's not fixed... then I think you'll want to add one of these phrases as a test example in `music.toml` and try to debug from there.

**Comment by vinitamaloo** [comment]
Hey @ianb I am Outreachy 2020 applicant. Can you assign this issue to me?

**Comment by LilyLME** [comment]
This issue seems to have been partially fixed. "Play test on youtube" does open youtube for different queries but not on a new tab.

**Comment by Ishakikani9117** [comment]
I think this issue is fixed now and also a new tab opens up for every different queries.

**Comment by Simpcyclassy** [comment]
I will be closing this as this appears to be fixed.
