### ISSUE TITLE
"Play test on youtube" opens Youtube Settings page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#564]
### Prerequisites:
Mic permissions are enabled.
A user is signed in on Youtube.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Play test on youtube" command.

### Expected result:
A new Youtube tab opens and a video related to the query starts playing.

### Actual result:
A new Youtube Settings tab opens in the Playback and performance section.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
If a user is not signed in on Youtube, after making the command, a Google Sign in page opens in the new tab and an "Internal error: TypeError: loadedTab is null" error is displayed in the "Doorhanger". After login the Youtube Settings page is displayed.

![4](https://user-images.githubusercontent.com/54401091/68674276-39064b80-055e-11ea-9936-6b6cc1dad3f7.gif)

**Comment by ianb** [comment]
Apparently "test on youtube" with an "I'm feeling lucky" on Google leads to the account page. Why? Not sure, but in some sense this is the expected behavior (in that we play whatever Google returns).
