### ISSUE TITLE
"Play chime when opening mic" checkmark is not checked after first time installation

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#569]
### Prerequisites:
Add-on is installed for the first time and mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click on the "Settings" button from the bottom left side of the "Doorhanger".

### Expected result:
"Play chime when opening mic" checkmark is checked, as the chime is heard when opening the "Doorhanger".

### Actual result:
"Play chime when opening mic" checkmark is not checked, even though the chime is heard when opening the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
If the "Play chime when opening mic" checkmark is clicked upon two times, then the chime will not be heard when opening the "Doorhanger".

![1](https://user-images.githubusercontent.com/54401091/68761416-ad9fbf80-061c-11ea-81a3-922cf30cf666.gif)

**Comment by alexandra-martin** [comment]
Verified the issue again on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit) and it can be closed. 

![6](https://user-images.githubusercontent.com/54401091/69974640-552e5480-152e-11ea-9ad9-2109c1155f5c.gif)

**Comment by ianb** [comment]
I believe this is fixed
