### ISSUE TITLE
Fix rendering of previous/next messages

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#575]
For example:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/44390/68899959-6b4bb080-06f8-11ea-9341-e7f248000802.png">

If nothing else, www.youtube.com shouldn't be bumped up against the other text. I think it needs a bit of a design review generally (/cc @awallin)

**Comment by awallin** [comment]
#516 should fix this styling.

**Comment by ianb** [comment]
Closed as a dup of #516
