### ISSUE TITLE
[Feedback] Complete designs

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#576]
#573 (77b0be31227ef713d64faec8bdb16d1e3da87ede) added feedback, but the designs aren't really complete:

- [ ] The happy/sad buttons probably should be improved
- [ ] Expanding on hover is a bit crude
- [ ] We don't include intent information everywhere
- [ ] The submit button isn't right
- [ ] General padding and whatnot
- [ ] Make sure the popup is sufficiently tall everwhere

**Comment by awallin** [comment]
@ianb from my initial test of this feature I struggle to even read and click on the icons because the mic timeout period kicks in too quickly.

**Comment by ianb** [comment]
Note the timeout has been increased to 15 seconds (from 6 seconds), so that part has been improved.

**Comment by ianb** [comment]
@awallin Do you have smiley/frowny images we can use here?

**Comment by awallin** [comment]
Attached

[smile-icons.zip](https://github.com/mozilla/firefox-voice/files/3923260/smile-icons.zip)
