### ISSUE TITLE
"Back" button is not available in "Type Input" mode

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#579]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Write a term to display the "Type Input" mode in the "Doorhanger".

### Expected result:
The "Doorhanger" has a "Back" button displayed in the "Type Input" mode.

### Actual result:
There is no "Back" button in the "Type Input" mode.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The "Doorhanger" can only be closed by clicking the "Close" button, the mic icon or by clicking outside the "Doorhanger".

![3](https://user-images.githubusercontent.com/54401091/68951298-69e8b980-07c6-11ea-9015-9ab4e8434ba7.gif)

**Comment by maitrella** [comment]
PR #614 
I'm still reading the popup code so maybe is necessary to modify more things.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
@ianb I think this bug can be closed.

![5](https://user-images.githubusercontent.com/54401091/69965791-ac77f900-151d-11ea-9ce1-9f7f1bc5e084.gif)
