### ISSUE TITLE
Negative feedback "Submit" button resets "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#591]
### Prerequisites:
Mic permissions are enabled.
A command is made beforehand.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click on the sad emoticon from the "How was your last experience" section.
3. Once the "What went wrong?" section is displayed, click on the green "Submit" button.

### Expected result:
A "Thanks for your feedback" message is displayed.

### Actual result:
The "Doorhanger" resets and displays the "Listening" state.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
If text is written in the text box, then the "Submit" button is clicked, a "Thanks for your feedback" message is displayed. (2nd gif)

![1](https://user-images.githubusercontent.com/54401091/69147940-d66ffb00-0adb-11ea-9b59-9b3718e0fd52.gif)

![9](https://user-images.githubusercontent.com/54401091/69548731-8b089180-0fa0-11ea-97a9-d2b1df518a72.gif)

**Comment by jenniferharmon** [comment]
What should happen if the user tries to submit empty feedback?
- Nothing happens?
- Error message?
- Thanks for your feedback view is displayed?

**Comment by ianb** [comment]
Let's go to "thanks" whether or not the user entered text

**Comment by awallin** [comment]
Is it possible to prevent submission if no text has been input? Use 40% opacity on the submit button until text is input to indicate it's inactive?

**Comment by ianb** [comment]
We already accept negative input without text (if you just never fill in this form). Is there a reason to block it here? I feel like it pressures people to say something even if they didn't feel like it, like the mobile rating dark pattern.

**Comment by awallin** [comment]
Good point, users won't understand their frown input has already been accepted. Ok, we should allow empty submissions.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![12](https://user-images.githubusercontent.com/54401091/70711995-7e4ba380-1ceb-11ea-9f69-7a2ea2236060.gif)
