### ISSUE TITLE
Typo in the "Firefox Voice Data Collection and Use" section from the "Settings" page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#594]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click on the "Settings" button from the bottom left side of the "Doorhanger".
3. Inspect the "Firefox Voice Data Collection and Use" section.

### Expected result:
There are no display issues.

### Actual result:
There is a typo on the word "transcripts" from the "Allow Firefox Voice to send anonymized transcipts of your audio request." checkmark from the "Firefox Voice Data Collection and Use" section.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![Annotation 2019-11-19 153000](https://user-images.githubusercontent.com/54401091/69150522-8431d880-0ae1-11ea-867d-d2d83f4c1735.png)

**Comment by maitrella** [comment]
PR #607

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![Annotation 2019-11-25 110236](https://user-images.githubusercontent.com/54401091/69535358-6acad980-0f84-11ea-9cbf-d15da677613f.png)
