### ISSUE TITLE
[Intermittent] An "Internal error: Error: communicate is not defined" error is displayed in "Doorhanger" after making commands

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#600]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search" command, e.g. "Search lion".

### Expected result:
The "Doorhanger" displays the result in the form of a Google card without issues.

### Actual result:
An "Internal error: Error: communicate is not defined" error is displayed in the "Doorhanger" and the result is not displayed.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The issue is reproduced intermittently 0, 1 or 2 out of 10 times. The error was noticed also before but it was rarely seen, but now it seems it is reproducing more frequently but not more than stated above. 
So far the error was displayed after making Google card related commands, like "Search dog", "What is the distance to ...", "How do you say cat in Spanish".

<img width="1280" alt="Screenshot 2019-11-21 at 17 26 28" src="https://user-images.githubusercontent.com/54401091/69358008-cfd5b500-0c8e-11ea-8908-a0b4dba27deb.png">

**Comment by ianb** [comment]
I haven't been able to reproduce this, but maybe it's due to internet speeds. I (or someone) should try this out with some internet-performance-slowdown-tool.

**Comment by ianb** [comment]
I'm still not able to reproduce this. I tried throttling the search page, and the popup waited for the page to load and displayed the card, despite it taking 20 seconds to load. I tried doing overlapping requests (initiating a search, then a new search while the old one was still loading) and it worked fine as well.

**Comment by alexandra-martin** [comment]
I haven't reproduce the issue since returning. You can close the bug report and if I reproduce it again, I will file another bug or reopen this one.
