### ISSUE TITLE
[Intermittent] The blue route line is not displayed in the "Doorhanger" when making a Google Maps card related command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#601]
### Prerequisites:
Mic permissions are enabled.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Map" command, e.g. "What is the distance to Cluj".

### Expected result:
The "Doorhanger" displays the Google map card without issues.

### Actual result:
The blue route line between cities and the destination pin are not displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The issue is reproduced intermittently 2 or 4 out of 10 times on Mac and 1 or 2 out of 10 times on Win.
On Win, the Google map card can also not be displayed at all in the "Doorhanger". I found this issue to be reproducing intermittently 1 or 2 out of 10 times, mostly when the command is made in the pinned Google tab. (2nd gif)
If the command implies a greater distance, another card is displayed and the issue is not reproduced. (3rd gif)
The "Internal error: Error: communicate is not defined" error was also displaying in the "Doorhanger" 0, 1 or 2 out of 10 times, like in #600.

![5](https://user-images.githubusercontent.com/54401091/69359507-61debd00-0c91-11ea-9ba3-be2a7f11e32b.gif)

![4](https://user-images.githubusercontent.com/54401091/69359527-67d49e00-0c91-11ea-9cdf-352bdacddb38.gif)

![6](https://user-images.githubusercontent.com/54401091/69359426-3d82e080-0c91-11ea-9053-18331584febb.gif)

**Comment by ianb** [comment]
The only explanation I have here is that we're capturing the image before the route is displayed. Maybe we should just always do a little follow up image update, since we're already set to do image updates?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The "Doorhanger" can have a 1 second delay when updating the Google Maps card.

![8](https://user-images.githubusercontent.com/54401091/69539371-0102fd80-0f8d-11ea-8f06-a374c8dbc8dd.gif)
