### ISSUE TITLE
Typo in the "Ask a question" section from the "Lexicon" page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#605]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click on the "More things you can say" link from the "Doorhanger".
3. Scroll to the "Ask a question" section and inspect it.

### Expected result:
There are no display issues.

### Actual result:
There is a typo on the word "answer" from the "Displays anwser in a card." text in the "Ask a question" section.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![Annotation 2019-11-22 112227](https://user-images.githubusercontent.com/54401091/69414928-571d3a00-0d1c-11ea-9285-5130a95aa873.png)

**Comment by maitrella** [comment]
PR #606

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![Annotation 2019-11-25 110204](https://user-images.githubusercontent.com/54401091/69535483-bda49100-0f84-11ea-8c9b-74ddef3705a2.png)
