### ISSUE TITLE
Microphone isn't acquired on first start

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#61]
At least in testing (`npm start`) I'm frequently seeing a problem where the microphone isn't acquired in the 2 second time. I haven't seen if it's an indefinite problem or not. Just trying again seems to fix it.

One possible hacky fix: if it's an issue of warming up the mic and/or permission, we could open the onboarding tab on startup, and close it after the mic is acquired. That would be OK for onboarding generally.

**Comment by ianb** [comment]
There might be another error that's making it look like the mic isn't working.

**Comment by jan-ivar** [comment]
I also see the intermittent problem. There shouldn't be any need to warm up the mic or permission.

If I set `media.navigator.permission.disabled` in about:config then it seems to always work for me. In this case the c++ code short-circuits the JS permission code, so maybe that's a clue.

cc @johannhof
