### ISSUE TITLE
Add "Save as pdf" intent

### ISSUE THREAD

**Issue by maitrella** [mozilla/firefox-voice#616]
When someone asks for:

- Save as pdf

Expected result:  Open a dialog asking the user where they want to save the PDF file.

**Comment by maitrella** [comment]
@ianb @awallin  do you think it’s worth it?.

**Comment by awallin** [comment]
Save as pdf is great. A good example of valuable functionality that is buried in menus making it difficult to find. When implemented let's add it to the Lexicon.

**Comment by maitrella** [comment]
Minimal version

```javascript
  this.intentRunner.registerIntent({
    name: "tabs.saveaspdf",
    description: "Saves as pdf the current tab",
    examples: ["save as pdf"],
    match: `
    save (this | current |) (tab |) as pdf (for me |)
    `,
    async run(context) {
      const status = await browser.tabs.saveAsPDF( { } );
    },
  });
```
@awallin @ianb I need some feedback on what to do with the return value.

**Comment by maitrella** [comment]
PR #622
