### ISSUE TITLE
Remove "for internal use only"

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#618]

**Comment by awallin** [comment]
Known locations:
- Onboarding page
- Bottom of the doorhanger

**Comment by maitrella** [comment]
Should the "div" sections be completely removed or just the text?

**Comment by ianb** [comment]
Probably removed? I'd remove them, see if it breaks the layout, and if not then they should be removed. If it does break the layout, then they should not be removed ;)

**Comment by maitrella** [comment]
Ok. I also removed "During the internal pilot..." because I think is related to "internal use" concept.
Correct me if I'm wrong.
