### ISSUE TITLE
Disable circleci for gh-pages branch

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#620]
E.g., [this attempt](https://circleci.com/gh/mozilla/firefox-voice/1057) to build gh-pages failed.

**Comment by ianb** [comment]
Apparently this isn't working.

**Comment by lelouchB** [comment]
@ianb  I would like to work on this

**Comment by ianb** [comment]
@lelouchB I think this is going to be too hard for you to test – I don't know of any better way than committing and pushing gh-pages with different config changes until it stop breaking.

**Comment by lelouchB** [comment]
@ianb okay, will look at another issue

**Comment by lelouchB** [comment]
@ianb Actually i still think I can do it
Can I at least try and spend some time on it before moving ahead

**Comment by lelouchB** [comment]
I think that there was a semi-colon missing in #a6859e6
