### ISSUE TITLE
Only switch to typed input on typeable characters

### ISSUE THREAD

**Issue by jofish** [mozilla/firefox-voice#621]
Right now we start assuming typing on any keypress -- but things like Ctrl are only used to silence screenreaders, and shouldn't be interpreted as typing. We should only switch to typed input mode when someone types a typeable character.

**Comment by ianb** [comment]
@jofish are you using an older version of the extension? This should have been fixed a while ago (and I think is fixed in the latest prod release)

**Comment by jofish** [comment]
I agree, I can’t reproduce on this one. @jteh looks like this one is fixed.
