### ISSUE TITLE
"Translate" commands display "Internal error: TypeError: languages.languageCode is undefined" in "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#623]
### Prerequisistes:
Mic permissions are enabled.
A page in a different language than English is opened and active, like https://ro.wikipedia.org/wiki/Leu.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Translate" command, e.g. "Translate page to English".

### Expected result:
The page is translated in English without issues.

### Actual result:
An "Internal error: TypeError: languages.languageCode is undefined" error is displayed in the "Doorhanger" and the page is not translated.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced also for the "Translate selection" command. (2nd gif)

![1](https://user-images.githubusercontent.com/54401091/69961013-86e5f200-1513-11ea-815d-33a2ea49f598.gif)

![2](https://user-images.githubusercontent.com/54401091/69961019-8a797900-1513-11ea-8451-93f632c33d8d.gif)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
For the "Translate selection" command the bug is still reproduced. 
For the "Translate" command, the tab only translates to English.

![2](https://user-images.githubusercontent.com/54401091/70048038-05a16480-15d2-11ea-85dc-3a1aa6bdd275.gif)

![1](https://user-images.githubusercontent.com/54401091/70048039-089c5500-15d2-11ea-9da2-95b79fc09a8c.gif)

**Comment by maitrella** [comment]
Small change based on @ianb work to fix translate selection intent

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
For the "Translate selection" command, Google Translate opens in a new tab, but no text is displayed and translated in the text boxes. For every new "Translate selection" command a new Google Translate tab opens. 
For the "Translate" command, the tab only translates to English.

![3](https://user-images.githubusercontent.com/54401091/70126022-c41bc280-1680-11ea-86f3-8db9def0087d.gif)

**Comment by maitrella** [comment]
"spanish" is not the same as "Spanish" for the intent.  The second works the first not.

The problem are the keys of languageCodes.

**Comment by maitrella** [comment]
@ianb the PR #647 changes the languageCodes keys. I don´t know if the change breaks something outside translation intents. I'm still reading the codebase.

**Comment by alexandra-martin** [comment]
@maitrella yes it seems it matters if the first character of the language is a small or a capital letter. 

![14](https://user-images.githubusercontent.com/54401091/70141861-99416680-16a0-11ea-91fc-95e0b1ecad9a.gif)

**Comment by maitrella** [comment]
With the PR I think you can forget about firsts characters of the languages.

Point out that English is the default language if nothing is specified in the translate request.

**Comment by ianb** [comment]
I think @maitrella fixed these issues, can you verify @alexandra-martin ?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
On Win everything seems fine, the tab or a text selection can the translated. (1st gif)
On Mac, when the tab is translated, somehow it doesn't detect the language of the text correctly and it doesn't translate the page. (2nd and 3rd gif)

![0n7](https://user-images.githubusercontent.com/54401091/70237570-2a334300-1770-11ea-9354-dd02536a0f6d.gif)

![12 5 1 (2)](https://user-images.githubusercontent.com/54401091/70238489-0bce4700-1772-11ea-9797-9af2c0091269.gif)

![12 5 2](https://user-images.githubusercontent.com/54401091/70238093-4388bf00-1771-11ea-9367-3226f4888989.gif)

**Comment by ianb** [comment]
I guess it's just Google being weird about auto-detection here, I think we're doing the right thing (it also does the right thing for me, so it might be Google getting clever about location). Given that I think we're fine.
