### ISSUE TITLE
"Find tab" can't find more than 2 similar name tabs

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#625]
### Prerequisites:
Mic permissions and autoplay are enabled.
Have several different services tabs open with similar names, e.g several tabs opened with “Best of...” titles, like https://www.esquire.com/best-of-2019/, https://www.nytimes.com/2019/11/19/arts/music/philip-glass-opera-akhnaten.html?searchResultPosition=2, https://www.youtube.com/watch?v=26nsBfLXwSQ  .

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say or write the “Find best tab” command several times.

### Expected result:
All tabs related to the "best" term are found one by one after each command.

### Actual result:
Not all tabs are found after making the command several times.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![5](https://user-images.githubusercontent.com/54401091/69968876-07acea00-1524-11ea-8908-cf35433f0cb7.gif)

**Comment by ianb** [comment]
I thought we should just move through the tabs, but after some thought I think we shouldn't fix this (at least right now). If someone wants to use "find calendar tab" to get to the appropriate tab, then that should keep working consistently, and any simple approach to paging through several matching tabs is likely to exclude repeated (and desired) navigation to a specific tab.
