### ISSUE TITLE
Not all "Supported sites" are displayed in the "Search a specific website" section in the "Lexicon" tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#626]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Lexicon" command, e.g. "Help" or "What can I say".
3. Observe the "Supported sites" from the "Search a specific website" section.

### Expected result:
All supported sites are listed.

### Actual result:
Not all supported sites are listed.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
The supported sites that need to be added to the list: Amazon Maps, DuckDuckGo Images, Google Drive, Google Images, Google Scholar, Google Sheets, Google Translate, OpenStreetMap, TuneIn.
The supported sites that need to be removed from the list: Hulu.

![Annotation 2019-12-02 174837](https://user-images.githubusercontent.com/54401091/69973427-29aa6a80-152c-11ea-848c-a519d625e241.png)

**Comment by maitrella** [comment]
Can I work on it?

**Comment by awallin** [comment]
Go for it @maitrella

**Comment by maitrella** [comment]
@awallin Do you think it would be interesting to reorder all sites in alphabetical order?

**Comment by awallin** [comment]
Alphabetical order would be fine. My only other thought is to try and order by popularity but there's a number of ways we could measure popularity and it might be as good as alpha anyway.

**Comment by jofish** [comment]
Please, please, not alphabetical order. I hate alphabetical order. It’s almost never the right answer. Could we do recency? That might fall out of the data easiest. But please, let’s not alphabetical order.

**Comment by maitrella** [comment]
Sorry I didn't want to create controversy.

**Comment by ianb** [comment]
While it's not clear exactly what order it's in, it's not alphabetical order... we can follow it up later, no worries @maitrella ;)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/70123658-c92a4300-167b-11ea-84a2-978572cf6519.png)
