### ISSUE TITLE
Design privacy policy page

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#630]
The privacy policy text (in privacy-policy.md) comes from legal, but I've just poked it into something based roughly on the lexicon. But it doesn't look good. It should be redesigned.

It should end up being published to https://mozilla.github.io/firefox-voice/privacy-policy.html

**Comment by awallin** [comment]
Design is available on Abstract.
https://share.goabstract.com/17b36726-44b3-4c0e-af1d-34f628689e6d?mode=design&sha=f6999a84ee37324a74f20bfcf1af941e40d8a48a

**Comment by ianb** [comment]
Ideally we'd have a reusable stylesheet that would apply to the Privacy page, the Lexicon, and any other content pages we have. lexicon.css is close already.

**Comment by jenniferharmon** [comment]
@ianb This was merged to master. Can it be closed or are you keeping it open because you have more things you'd like accomplished on it?

**Comment by awallin** [comment]
@jenniferharmon minor design QA issue. Can you reduce the padding between the intro paragraph and 'Voice recordings' by 30px?
