### ISSUE TITLE
Link updates in settings

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#631]
Based on legal review make the following changes to the links in the 'About' section of settings.

* Change the link "How Mozilla Protects Your Voice Privacy (TODO)" to "Firefox Voice Privacy Notice" and link to https://mozilla.github.io/firefox-voice/privacy-policy.html

* Add a new link "About Your Rights" and link to about:rights

**Comment by ianb** [comment]
`about:rights` is not something we can link to or open from the extension (`about:` links are protected). Is there another location where this is hosted?

**Comment by awallin** [comment]
Instead of about:rights link to https://www.mozilla.org/en-US/about/legal/terms/firefox/
