### ISSUE TITLE
"Back" button not available after submitting positive and negative feedbacks

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#637]
### Prerequisites:
Mic permissions are enabled.
Have a command made beforehand.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click on the happy emoticon, to give a positive feedback, from the "How was your last experience" section.
3. Observe the "Doorhanger".

### Expected result:
A "Back" button is displayed at the top left side of the "Doorhanger".

### Actual result:
The "Back" button is not available in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced also when giving a negative feedback, by clicking on the sad emoticon from the "How was your last experience" section and when writing the negative feedback. (2nd gif)

![3](https://user-images.githubusercontent.com/54401091/70051161-2b7e3780-15d9-11ea-9c23-ebace8f5ae19.gif)

![4](https://user-images.githubusercontent.com/54401091/70051163-2e792800-15d9-11ea-92bb-6e74f4aa3ef2.gif)

**Comment by maitrella** [comment]
@ianb too many || ?. Maybe changing the logic and use "listening", "processing" and "success" cases is a better option.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/70125247-2673c380-167f-11ea-9ad4-b73d12f5c74d.gif)

![2](https://user-images.githubusercontent.com/54401091/70125252-28d61d80-167f-11ea-9770-9cf8a14af5a3.gif)
