### ISSUE TITLE
Design QA for settings page

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#642]
To clean up UI and improve the layout make the following fixes.

* Remove build and commit information from version. It should only display the version number.
* Replace the existing logo/wordmark with attached svg in the zip file
* Fix wrapping text for "Allow Firefox Voice to collect your audio recordings...". It should align similar to the previous options not with the checkbox.

[firefox-voice-stacked.svg.zip](https://github.com/mozilla/firefox-voice/files/3917836/firefox-voice-stacked.svg.zip)

**Comment by jenniferharmon** [comment]
Do you also want the "What's New" (changelog) link removed?

**Comment by awallin** [comment]
Leave "What's New", let's people click through to find out the latest features that have been added.
