### ISSUE TITLE
Add React linting

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#644]
I believe we can add eslint plugins for React linting:

* https://www.npmjs.com/package/eslint-plugin-jsx-a11y
* https://www.npmjs.com/package/eslint-plugin-react-hooks (Maybe? I'm not familiar with it)

**Comment by Shubhamchinda** [comment]
Hey, I'd like work on this issue!

**Comment by ianb** [comment]
Great! FYI, I think @jenniferharmon might want to use this for some HTML fixups, so she might beat you to it.
