### ISSUE TITLE
"Thanks for your feedback" title not centered in the "Doorhanger"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#646]
### Prerequisites:
Mic permissions are enabled.
Have a command made beforehand.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click on the happy emoticon, to give a positive feedback, from the "How was your last experience" section.
3. Observe the "Doorhanger".

### Expected result:
The "Doorhanger" doesn't have display issues.

### Actual result:
The "Thanks for your feedback" title is not centered in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Likewise the check mark that needs to be above the title is not displayed.
Reproduced also when giving a negative feedback, by clicking on the sad emoticon from the "How was your last experience" section, writing the negative feedback and clicking the "Submit" green button. (2nd gif)

![4](https://user-images.githubusercontent.com/54401091/70129244-06480280-1687-11ea-8cd2-8470cdb8f4da.gif)

![5](https://user-images.githubusercontent.com/54401091/70129253-0a742000-1687-11ea-852a-996de10f1fa2.gif)

**Comment by awallin** [comment]
"Thanks for your feedback" should be centered aligned. Additionally, a check mark should appear above. See mockup.

![feedback](https://user-images.githubusercontent.com/428245/70168347-810c2000-167d-11ea-8907-8d5ce0498bb6.jpg)

**Comment by alexandra-martin** [comment]
@awallin thank you, I didn't saw this mockup. Will edit the bug then to fit accordingly.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![4](https://user-images.githubusercontent.com/54401091/71095277-f9fa9400-21b4-11ea-9757-700953a85507.gif)
