### ISSUE TITLE
Card rendering needs better design

### ISSUE THREAD

**Issue by jcambre** [mozilla/firefox-voice#65]
Seems the [max height for a popup is 600px](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#Popup_resizing), so we need to work within those constraints even when a card has lots of text, an image, etc. CC @awallin

**Comment by awallin** [comment]
Added a couple reference designs for the cards to Abstract.
https://share.goabstract.com/e41486eb-2b7d-4a91-b9ba-bcfb16cbff93?collectionLayerId=2d569478-c749-4d42-8430-f02b9f829af8&mode=design

**Comment by ianb** [comment]
We've removed these cards in the new search.
