### ISSUE TITLE
[Onboarding] Update permission help image

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#650]
We have this image:

![image](https://user-images.githubusercontent.com/44390/70170682-c850db80-1692-11ea-9625-2dc7013d1da8.png)

I just grabbed it without trying very hard. We should get a new image, with the right name, and cropped a bit better

**Comment by awallin** [comment]
Where is this? In the instruction doc?

**Comment by ianb** [comment]
In onboarding, if you do not give the extension mic permission

**Comment by awallin** [comment]
Name = "Firefox Voice"
How about the logo for the image?

**Comment by ianb** [comment]
It's originally a screenshot, and we could probably just take a fresher and better cropped screenshot

**Comment by awallin** [comment]
I'm confused where/when this shows up?

**Comment by ianb** [comment]
Install the extension on a new profile (e.g., in the repository remove or move `Profile/`), and then when onboarding opens and it asks for mic permissions, deny those permissions.
