### ISSUE TITLE
[Onboarding] Review footer

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#651]
A couple things in the onboarding footer:

- [ ] GitHub should point to this repository
- [ ] Remove installation instructions (they just point back to onboarding)
- [ ] Change link title "lexicon" to "Things you can say"

/cc @awallin

**Comment by awallin** [comment]
Which GitHub repo should the link point to?

**Comment by ianb** [comment]
This repository. I think "GitHub" is specific enough to point them here. We just didn't want users submitting all bug requests directly to our issue tracker, but someone who knows what GitHub is also probably knows the expectations.

**Comment by ianb** [comment]
@awallin did you come up with a label for the lexicon link?

**Comment by awallin** [comment]
Let's go with "Things you can say"
