### ISSUE TITLE
[Onboarding] Design updates

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#652]
(I resolved the PR comments, please just see comment below)

**Comment by awallin** [comment]
Feedback from my design QA pass:

When the page first loads the microphone permission error is shown below the permission doorhanger. This creates a feeling the users has done something wrong. Can that not show? Should just be the onboarding page until after the user clicks to allow mic permissions then the opt-in overlay appears.

*Opt-in/out*
* Missing checkmark and "successfully installed"
* Allow button should have hover state. Darker blue '#003EAA' 
* Make "Allow" button wider (~350px). Should have responsive adjustments.
* Cursor should change to hand pointer when hovering over 'Allow' button
* 'Don't Allow' link color should be blue to match button color
* Learn how Mozilla protects your voice data should be blue link (non bold)
* Font should be Inter

* Onboarding page
* Missing arrow pointing from 'Get started' to icon in upper right of toolbar
* Footer links should underline on hover
* 'Mozilla foundation' in footer links to https://foundation.mozilla.org/en/

**Comment by ianb** [comment]
Note I've noticed some errors in the console about loading the Inter font, so it might be setup but not working (CSP?)

**Comment by ianb** [comment]
If you make the window just the right size, it can imply there's only an "allow" option:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/44390/70252374-f1cb3f00-1746-11ea-9d3f-ea15a42a3e2b.png">

**Comment by ianb** [comment]
The OS test we use elsewhere is just:

```js
  const pasteSymbol = (window.navigator.platform.match(/Mac/i)) ? "\u2318" : "Ctrl";
```

**Comment by awallin** [comment]
We can move the 'Allow' and 'Don't Allow' buttons side by side so they'll both be visible when the viewport cuts off at certain heights.
