### ISSUE TITLE
Hello intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#656]
Because the first interaction a user has is often saying "Hello" this is an opportunity to educate and/or provide a joyful experience.

**Comment by ianb** [comment]
Note that currently we open the lexicon when you say "hello"

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant. Can I take this issue if it is not being worked upon?

**Comment by ianb** [comment]
@Kirti2502 We don't have a design for this, so it's not really ready to be implemented

**Comment by awallin** [comment]
Closing this one as it's covered in #1269
