### ISSUE TITLE
Vocal commands can be made if mic permissions are not granted after page refresh

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#667]
### Prerequisites:
Install the add-on for the first time.
Every time the mic permissions pop-up appears the "Remember this decision" should not be checked.
Mic permissions need to be granted 2 times (when installing add-on and when using the mic icon for the first time).

### STR:
1. After first installation click "Allow" from the mic permissions pop-up, while the "Remember this decision" is not checked.
2. Click "Allow" or "Don't Allow" buttons from the “Allow Firefox Voice to Collect Voice Transcripts” popup.
3. Use the shortcut or click on the mic icon from the browser toolbar.
4. Click "Allow" from the mic permissions pop-up, while the "Remember this decision" is not checked.
5. Refresh page.
6. Click "Don't Allow" from the mic permissions pop-up, while the "Remember this decision" is not checked.
7. Use the shortcut or click on the mic icon from the browser toolbar and make a vocal command.

### Expected result:
Vocal commands can't be made while mic permissions are not allowed.

### Actual result:
Vocal commands can be made even though it is stated in the page that mic permissions are not granted.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![on9](https://user-images.githubusercontent.com/54401091/70241953-9c0f8a80-1778-11ea-86e6-4a8e183dae13.gif)

**Comment by awallin** [comment]
@ianb We should ensure this one if fixed before external beta.

**Comment by ianb** [comment]
I'm not sure this is really a bug, or something we want to try to figure out. Once you reject permission on the onboarding page it shows the error message, but that one page isn't tracking what's happening everywhere. Anyway, it doesn't seem very concerning to me.
