### ISSUE TITLE
"Settings" button and "Feedback?" link not working when "Doorhanger" is opened

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#678]
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click the "Settings" button from the bottom left side of the "Doorhanger".

### Expected result:
"Settings" page is displayed without issues.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced also for the "Feedback?" link when the "Doorhanger" is first opened.
Not reproduced in other "Doorhanger" instances, like "Type Input", "In progress", "Sorry, there was an issue", "Thanks for the feedback". 
"Settings" button and "Feedback?" link work, when the "How was your last experience?" is displayed in the "Doorhanger".  
On Mac the "Feedback?" link can be accessed if the mouse is place on the text underline. (2nd gif)

![ov2](https://user-images.githubusercontent.com/54401091/70305859-14745b00-180e-11ea-8c11-c4504cfd66fd.gif)

![12 6 1](https://user-images.githubusercontent.com/54401091/70305751-d840fa80-180d-11ea-87f6-811d8982fb25.gif)

**Comment by ianb** [comment]
I'm not able to reproduce. @awallin @jenniferharmon can you reproduce this?

**Comment by awallin** [comment]
Unable to reproduce.

**Comment by alexandra-martin** [comment]
Sorry, it seems something was not right from my part, although I don't know what that was. After several attempts where I made new profiles on both Win and Mac, it was reproducing every time. When I tried it again today, the link and button work.

![1](https://user-images.githubusercontent.com/54401091/70424467-21948280-1a78-11ea-96f1-753a64bb1aa3.gif)

**Comment by jenniferharmon** [comment]
The issue with some buttons not being clickable was because of a hidden text input field in the view. Even though it wasn't visible it was overlaying some things and preventing clicks. This has been resolved.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![6](https://user-images.githubusercontent.com/54401091/70912205-24651980-201c-11ea-9478-bbd6019b5218.gif)
