### ISSUE TITLE
"Next" command doesn't open website after a "Search" command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#680]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
A "Search" command is made beforehand, e.g. "Search Lion".

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Next" command.

### Expected result:
The website displayed at the bottom of the "Doorhanger", after the "Search Lion" command was made, opens in a new tab.

### Actual result:
"Spotify is not open" error is displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Using the "Next result" command will open the website in a new tab. (2nd gif)

![ov4](https://user-images.githubusercontent.com/54401091/70309061-505eee80-1815-11ea-96d2-3c082d8ba5ca.gif)

![ov7](https://user-images.githubusercontent.com/54401091/70323502-96c44580-1835-11ea-865c-03fc3a7876e7.gif)

**Comment by awallin** [comment]
I've also experienced this. @ianb we should fix before beta release.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![4](https://user-images.githubusercontent.com/54401091/70433057-5f4dd700-1a89-11ea-97ab-646fd33d489e.gif)
