### ISSUE TITLE
Feedback emoticons don't change color or size on mouse hover

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#689]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
A command is made beforehand.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Mouse hover on the feedback emoticons from the "How was your last experience?" section from the "Doorhanger".

### Expected result:
Emoticons change to blue and change size.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![5](https://user-images.githubusercontent.com/54401091/70435431-81e2ee80-1a8f-11ea-8dc4-8b2cea74294d.gif)

**Comment by ianb** [comment]
The colors do change, but it's so subtle and the lines are so thin that it's hard to tell.

@awallin to give guidance on colors.

**Comment by alexandra-martin** [comment]
@ianb from the mock-up, the emoticons are filled with blue and increased in size after being clicked and I assume this happens also on hover. But @awallin can clarify exactly, if changes also apply when icons are hovered, or only when they are clicked, or both.

![3](https://user-images.githubusercontent.com/54401091/70607964-09536d80-1c08-11ea-8c09-4d4994520315.png)

**Comment by awallin** [comment]
We'll want a slightly different visual for hover than clicked to ensure there change between the two states is obvious.

Attached are SVGs with a hover state for the two icons using a background with a slight opacity.

[smile-icons-with-hover.zip](https://github.com/mozilla/firefox-voice/files/3951739/smile-icons-with-hover.zip)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit). Not sure if there are changes when emoticons are clicked though.

![14](https://user-images.githubusercontent.com/54401091/70712206-eef2c000-1ceb-11ea-826b-d94b73f8c77a.gif)
