### ISSUE TITLE
"Doorhanger" title is not centered if command is too long

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#690]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a long string, e.g. "Search fiction history adventure old books" or "Search fiction history adventure fantasy old books".

### Expected result:
"Doorhanger" doesn't have display issues.

### Actual result:
If command title is too long and will have more than one row, it will not be centered.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![5](https://user-images.githubusercontent.com/54401091/70440011-e86d0a00-1a99-11ea-88fd-be1bf68763bf.png)

![8](https://user-images.githubusercontent.com/54401091/70440010-e4d98300-1a99-11ea-9431-e4ebfa0d5738.png)

**Comment by vandnakapoor19** [comment]
@ianb I'd like to check this issue.

**Comment by awallin** [comment]
Go for it @vandnakapoor19

**Comment by vandnakapoor19** [comment]
Sure! Thanks

**Comment by vandnakapoor19** [comment]
@awallin In current flow when we are trying to say or write a long string, e.g. "Search fiction history adventure old books" or "Search fiction history adventure fantasy old books".

The result is showing on a new tab in google search.

![search_books](https://user-images.githubusercontent.com/45131874/77697906-13666580-6f86-11ea-9949-a65d2c60c4a4.gif)

**Comment by alexandra-martin** [comment]
@vandnakapoor19 the "Search" commands mentioned in step 2 now seem to do Google searches instead of opening any sites. If "fiction history adventure old books" or "fiction history adventure fantasy old books" commands are made, it will open sites in new tabs. 
Currently if the command transcription is too long, it will be shortened. @awallin do you think it should remain like this, or should the whole command transcription be displayed in the doorhanger?

![4](https://user-images.githubusercontent.com/54401091/77770663-4d02a380-704e-11ea-8712-233438abf48e.gif)

**Comment by awallin** [comment]
In the case of displaying at the top of the doorhaner we should shorten if it would wrap onto a second line. The user will have already seen the full transcript displayed in the doorhanger a moment before.

**Comment by vandnakapoor19** [comment]
@awallin @alexandra-martin Should we close this issue? Because this is working exactly the same as @awallin has mentioned.

**Comment by awallin** [comment]
Closing

**Comment by alexandra-martin** [comment]
Verified again on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-31).

![5](https://user-images.githubusercontent.com/54401091/78128168-2366c500-741e-11ea-9b86-be2e24c022e2.gif)
