### ISSUE TITLE
New tab opens every time the mic icon is clicked and permissions are not given

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#701]
### Prerequisites:
Add-on is installed for the first time.
Mic permissions are not enabled.

### STR:
1. Click on the mic icon several times.

### Expected result:
A single "Welcome to Firefox Voice" tab is displayed in the browser.

### Actual result:
Several "Welcome to Firefox Voice" tabs open.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).
Reproduced also if mic permissions are enabled and “Allow Firefox Voice to Collect Voice Transcripts” pop-up is displayed. (2nd gif)

![4](https://user-images.githubusercontent.com/54401091/70539900-fb9cda00-1b6c-11ea-9d28-2f64307acf04.gif)

![6](https://user-images.githubusercontent.com/54401091/70539915-035c7e80-1b6d-11ea-8f5b-737a4393cae3.gif)

**Comment by ianb** [comment]
The fix we'd like is instead of opening new pages, it should activate the existing onboarding page (and maybe reload it to make sure that it's state is up-to-date).

**Comment by alexandra-martin** [comment]
#### Update:
The issue is reproduced also after clicking on the "Things you can say" and "Privacy" links from the "Lexicon" and "Privacy Policy" pages.

![1](https://user-images.githubusercontent.com/54401091/70606622-8fba8000-1c05-11ea-9951-c40bb47f73c4.gif)

![2](https://user-images.githubusercontent.com/54401091/70606504-4833f400-1c05-11ea-81ad-6f4eefe29b07.gif)

**Comment by espertus** [comment]
May I try fixing this issue?

**Comment by ianb** [comment]
@espertus You got it! This is an example of a guarded tab open: https://github.com/mozilla/firefox-voice/blob/master/extension/intents/search/search.js#L22-L55

**Comment by espertus** [comment]
I think this should be closed.
