### ISSUE TITLE
"Submit" negative feedback button not responsive on hover state

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#704]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
A command is made beforehand.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Click on the sad emoticon from the "How was your last experience" section in the "Doorhanger".
3. Mouse hover on the "Submit" green button.

### Expected result:
Button changes color when hovered.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

![8](https://user-images.githubusercontent.com/54401091/70545653-99e16d80-1b76-11ea-93c6-407ff83c443d.gif)

**Comment by ianb** [comment]
Also the frowny face is not centered

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![12](https://user-images.githubusercontent.com/54401091/70711785-f6659980-1cea-11ea-8717-9858bb04c84e.gif)
