### ISSUE TITLE
[browser command] Add save/download screenshot intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#71]
It wouldn't be a huge amount of work to add some simple screenshot-related intents:

* Download a screenshot of this
* Copy a screenshot of this
* Download a screenshot of the entire page
* Copy a screenshot of the entire page

The first two implicitly take a screenshot of the viewport.

This would not use Firefox Screenshots, but would simply make the screenshot (which isn't very hard). Taking a screenshot of just a portion of the page would be out of scope.

**Comment by ianb** [comment]
Note that #782 added copying of screenshots. Downloading could be added to the `saving.js` intent. We should pull the function `createScreenshot` from `extension/intents/clipboard/contentScript.js`

**Comment by awallin** [comment]
Attaching mockup for processing and success/confirmation message.

![screenshot-processing](https://user-images.githubusercontent.com/428245/71107191-7c636380-2175-11ea-8beb-a0b4f462851e.jpg)

![Screenshot](https://user-images.githubusercontent.com/428245/71106860-e4fe1080-2174-11ea-8335-07ba84e81066.jpg)

**Comment by ianb** [comment]
We shouldn't need a progress indicator for this as it's a very fast operation.
