### ISSUE TITLE
Support 'Reload page' intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#713]
Reload the page in the browser when a user says things like:
- Reload this page
- Reload
- Refresh

**Comment by ianb** [comment]
Note this would use [browser.tabs.reload()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/reload)

**Comment by maitrella** [comment]
Can I work on this issue?

**Comment by awallin** [comment]
Yes please @maitrella!

**Comment by ianb** [comment]
It's yours!
