### ISSUE TITLE
Support 'Save page' intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#714]
Save the page to a single HTML page when the users says things like:
- Save this page
- Save
- save to html

**Comment by ianb** [comment]
Instead of invoking the Save As dialog, we might want to use something like [freeze-dry](https://github.com/WebMemex/freeze-dry) to create the HTML, and then the [downloads API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) to download that.

**Comment by vanekcsi** [comment]
Hi,
I would like to work on this issue for a school project.

**Comment by vanekcsi** [comment]
Could you give me some advice please, how to use freeze-dry in this project?

**Comment by ianb** [comment]
Despite the label, I'm not sure if this is a good first issue – or at least, it's an advanced first issue. Good second or third issue?

There's a bunch of steps here:

- [ ] Install freeze-dry
- [ ] Figure out a way to package freeze-dry up as a single file (browserify?)
- [ ] Copy that single file into `extension/js/vendor/`
- [ ] Create the save intent (in `tabs.js`)
- [ ] Use `lazyInject` to inject both freeze-dry and a custom content script into a tab when saving it
- [ ] Also use `pageMetadata.js` to get the "right" title for the page and use that to generate the suggested filename
- [ ] Use [createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to turn the frozen page into a URL
- [ ] Use the download API to download the file (I'm not sure if you can do this from the content script, probably?)
- [ ] Clean up the frozen page after the download has completed
