### ISSUE TITLE
Design feedback into the result

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#715]
Instead of asking for feedback on the next mic click let's try to collect feedback immediately when the result of action occurs.

**Comment by awallin** [comment]
Mockups attached. Note, we should also remove the feedback section from being displayed in the doorhanger immediately after mic click.

[Also available on Abstract.](https://share.goabstract.com/f093ba4c-17bb-4b8e-b7a6-6ae1bab03ba1?mode=design&sha=52cbadbcc454775f8f0a8f1fc60292f21c3bfd29)

@jenniferharmon let me know if you want new smile/frown icons in white or you can make CSS changes to the existing SVGs?

![doorhanger-nav-with-feedback](https://user-images.githubusercontent.com/428245/70740195-7d0b7e00-1ccd-11ea-9e47-44775753a819.jpg)
![doorhanger-with-feedback](https://user-images.githubusercontent.com/428245/70740197-7d0b7e00-1ccd-11ea-9dca-05b974b5b9fb.jpg)

**Comment by awallin** [comment]
Couple minor design QA items:

1. The cursor should change to pointer (hand) on hover
2. It'd be nice to make the hover state more obvious by decreasing the opacity of background for the smile icons on hover. @jenniferharmon can you do in css? Or, I can provide a new SVG?

**Comment by jenniferharmon** [comment]
@awallin Can you provide new svgs for the smile and frown normal and hover states? I'm using masking right now to go from the blue color to white, but it might look better to use new ones that are white.

**Comment by awallin** [comment]
Try these. They also add a bit more personality on hover.
[smile-icons-dark-bkg.zip](https://github.com/mozilla/firefox-voice/files/3963209/smile-icons-dark-bkg.zip)
