### ISSUE TITLE
Add search examples

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#725]
I think amidst the search refactoring we lost any examples of search. We should add some back.

**Comment by awallin** [comment]
Here are examples:

- Search for hiking in Denver
- Look up recipes for fish tacos
- Who created breaking bad?
- Who won the World Series game last night?
- How deep is the Marianas Trench?
- Show me weather in Flagstaff, Arizona
- What's the temperature in San Antonio?
- What time is it?
- What time is it in Berlin?
- Find the nearest sushi on maps
- How long will it take to get to Springfield?
- How do I get to the hardware store?
