### ISSUE TITLE
[browser command] Add pin/unpin tab intents

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#73]
We could add an intent to pin tabs:

* Pin/unpin this tab

We could potentially support other tab movement intents:

* Make this tab first/last

The action implementation is trivial.

**Comment by ankiiitraj** [comment]
Hi @ianb , I want to contribute in this. I will require lil help though. Thanks.

**Comment by ianb** [comment]
@ankiiitraj I wrote up a document about making a new intent: https://github.com/mozilla/firefox-voice/blob/master/docs/writing-an-intent.md

This intent will just need to use `browser.tabs.update` and change the pinned property: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update

**Comment by maitrella** [comment]
@ianb I have implemented the first part (pin/unpin) in order to learn more about intents maybe @ankiiitraj could implement second part (first/last movement).

**Comment by ankiiitraj** [comment]
HI @maitrella Thanks for the help!
