### ISSUE TITLE
"Doorhanger" display not shown from the top

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#733]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Observe the "Doorhanger".

### Expected result:
"Doorhanger" has no display issues.

### Actual result:
"Doorhanger" information is not displayed from the top.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![7](https://user-images.githubusercontent.com/54401091/70710686-67578200-1ce8-11ea-9fd5-3b216ce7d369.gif)

**Comment by ianb** [comment]
I don't have any good ideas here, maybe @jenniferharmon has some thoughts? I wouldn't put too much time into it though.

**Comment by jenniferharmon** [comment]
This issue is resolved as of this morning.

**Comment by alexandra-martin** [comment]
Yeah it seems like it.

![10](https://user-images.githubusercontent.com/54401091/70809536-9fcf8c80-1dca-11ea-808a-b7dd8179e3e4.gif)
