### ISSUE TITLE
'Search' intent should display search result page

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#740]
Intents with "search for ..." should load a search result page instead of going to an I'm feeling luck result.

**Comment by ianb** [comment]
Note I've made these do searches:

```
(do a |) (search | google) (google | the web | the internet |) (for |) [query] (one the web |) (for me|)
```

But stuff like "look up lions" still doesn't open a search page. Here's what we still have going to search.search (the card/search result view):

```
(do a |) (query | find | find me | look up | lookup | look on | look for) (google | the web | the internet |) (for |) [query] (on the web |) (for me |)
```

(I guess "google" is still in there, though now I'm not quite sure what the intended phrase is that it's supposed to capture)
