### ISSUE TITLE
[FEATURE] "Open" as alternative to "Go to"

### ISSUE THREAD

**Issue by RickAndTired** [mozilla/firefox-voice#742]
[FEATURE] "Open" as alternative to "Go to"

Currently saying "Open Gmail" will just search the term "Open Gmail"

I suggest "Open" should be used the same way "Go to" is

In addition I think there should be an Open first result for websites that can be searched

Open "search request" in/on "website"
"Open resume in Google Docs"

**Comment by ianb** [comment]
We should just add "open" to the navigation.navigate intent (it's there, but as an optional additional word, not as a starting keyword)
