### ISSUE TITLE
[Doorhanger] For close (x) Cursor should be pointer

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#745]
When hovering over the x in the doorhanger the cursor changes to the text input. It should change to the pointer (hand) to make it clear click is an available action.

**Comment by alexandra-martin** [comment]
Cursor turns into a pointer in certain angles, similar with #678.

![18](https://user-images.githubusercontent.com/54401091/70798071-ad771900-1dae-11ea-981e-0003d65ba46a.gif)

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![3](https://user-images.githubusercontent.com/54401091/70911749-34c8c480-201b-11ea-839c-a00bf09a8f1b.gif)
