### ISSUE TITLE
Support 'go to my homepage' intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#747]
Based on telemetry users are trying to go to their home page using voice.

'Go to my homepage' or 'Open my homepage' should navigate existing tab to the homepage as defined in about:preferences.

**Comment by maitrella** [comment]
Can I work on this issue?.

**Comment by maitrella** [comment]
@awallin @ianb Are you thinking about a completely new intent in search.js?. Is
 browserSettings.homepageOverride the best option to implement the intent?

**Comment by maitrella** [comment]
@ianb @awallin Working on the intent I have found two problems. First I can't access browserSettings "Internal error: TypeError: browser.browserSettings is undefined", second should I support multiples urls in the homepage settings?.

**Comment by ianb** [comment]
@maitrella I haven't worked with this API before, but my guess is that it's a permission issue. [This page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings) talks about a `"browserSettings"` permission for write, but maybe it's needed for read too.

I wouldn't worry about multiple URLs in that setting (I'm not sure what would cause that?). This would be good for a new intent.

**Comment by maitrella** [comment]
Return value is a string of multiple URLs separated by |.

I'll check permission issue one more time. Thanks !!!
