### ISSUE TITLE
[Intermittent] "Doorhanger" doesn't always expands from the "Listen" state

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#752]
### Prerequisites:
Add-on is installed for the first time.
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Wait a few seconds.

### Expected result:
"Doorhanger" expands from the "Listen" state to show command examples, "Settings" button, "Feedback?" and "More things you can say" links.

### Actual result:
"Doorhanger" doesn't expand  and is showing only the "Listen" state.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).
Reproduced intermittently 5 or 6 out of 10 times on Win and 1 out of 10 times on Mac.
On Win, after installation, the issue will be reproduced 10 out of 10 times after the first unexpanded "Listen" state is displayed in the "Doorhanger". Installing the add-on on a new Firefox Nightly profile restarts the intermittent counting to the number previosuly stated (5 or 6 times).

![6](https://user-images.githubusercontent.com/54401091/70807904-313cff80-1dc7-11ea-9830-295b0ab2b8f6.gif)

![12 13 2](https://user-images.githubusercontent.com/54401091/70807743-d0152c00-1dc6-11ea-9ed1-666c24bf3465.gif)

**Comment by ianb** [comment]
Sometimes the microphone gets some noise, which isn't speech, but we aren't locally able to tell the difference between noise and speaking. As a result I don't think we have an easy or good fix for this.
