### ISSUE TITLE
Native timer

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#76]
Timer intents would support:

* Start timer
* Start timer for [X]
* Pause timer
* Stop timer
* Change timer to [X]

We could implement a timer natively, or attempt some integration. Technically Google supports timers [via search](https://www.google.com/search?client=firefox-b-1-d&q=set+timer+for+10+minutes), but we'd have to leave the page open, and the interface isn't particularly nice.

**Comment by awallin** [comment]
Adding details and mockups to implement a native timer.

* Timer can be set with phrases such as "set a timer for 5 minutes", "10 minute timer", "start a timer for 20 minutes"
* A visual is displayed in the doorhanger when being set
* Only one timer can be set at a time.
* When timer is complete the doorhanger opens with an open mic to allow for follow up commands such as "stop" or "reset." See #962 for details on follow up utterances.
* If a user quits Firefox when a timer is active we should warn them the timer will be lost.

![Timer-doorhanger](https://user-images.githubusercontent.com/428245/76723969-79d9c100-6706-11ea-8a33-5f192594b784.jpg)

[zap-circle.svg.zip](https://github.com/mozilla/firefox-voice/files/4336084/zap-circle.svg.zip)

**Comment by awallin** [comment]
@danielamormocea this one is a bit more advanced. Might be a good fit for you, if you're interested?

**Comment by GangaChatrvedi** [comment]
@awallin I was already working on this if that is alright.

**Comment by danielamormocea** [comment]
@awallin  yes, very; I was actually thinking about it last week

**Comment by GangaChatrvedi** [comment]
@danielamormocea Okay. Please go on.

**Comment by danielamormocea** [comment]
@awallin  I was thinking about making something like this for checking the weather (of the current day as the prompt is fairly small) also? If you consider this a useful feature I could make an issue and work on that too;

**Comment by awallin** [comment]
@danielamormocea Yes, a native weather feature would be nice. I'll put together a mockup and we can see who is available to work on it.

**Comment by danielamormocea** [comment]
@ianb  @awallin  How should I announce that the timer has finished counting? Should I use a jingle? Or a warning?

**Comment by awallin** [comment]
@danielamormocea There's a mockup showing the timer has finished. The one with "It's been 5 minutes"

**Comment by danielamormocea** [comment]
@awallin @ianb Should we allow the user to have more than one timer? 
And if so:
-> the user should be able to see all of the timers? (as in sliding to see the other timers; right-left arrows)
-> and when the user triggers the popup again, down there the user should see multiple timers, or just the last one?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-25).
After making a "Timer" command, the timer display is not shown. If the doorhanger is closed, it will open again in the "Listening" state, when the timer should be done, but a new "Timer" command can't be made afterwards, as the "Only one timer can be active." error text is displayed.
"Pause timer", "Unpause timer", "Stop timer", "Reset timer" commands don't seem to make visible changes. 
After trying to stop the timer, another "Timer" command can't be made afterwards.
Don't know if it was implemented yet, but there is no visible display of the timer when making other commands.

![1](https://user-images.githubusercontent.com/54401091/77629218-d7191200-6f51-11ea-801f-458b4a98fbb4.gif)

![4](https://user-images.githubusercontent.com/54401091/77642755-d9399b80-6f66-11ea-91d0-34cf3e53f715.gif)

![5](https://user-images.githubusercontent.com/54401091/77641929-827f9200-6f65-11ea-8338-bc016fdd78a8.gif)

**Comment by danielamormocea** [comment]
@alexandra-martin did you run npm run build:jsx? from what you described it seems like just the changes in the jsx are not seen, and the ones in the timer.js are

**Comment by alexandra-martin** [comment]
@danielamormocea I initially just did a git pull and a npm start. Now after running npm run build:jsx followed by npm start, I can see the changes.
Issues that I mentioned before and am still experiencing though are that, if the timer is stoped with commands like "Cancel timer" or "Stop timer", the "Only one timer can be active." error text is displayed after trying to make another "Timer" command.
Also the timer display is only visible when the doorhanger is in the "Listening" state, but again I don't know if it was implement for the display to be shown in other instances.
Sorry for not running the step you mentioned before, I didn't know about it. If I find other issues, I will log new bug reports, so this one doesn't get too crowded.

![6](https://user-images.githubusercontent.com/54401091/77646704-ba8ad300-6f6d-11ea-93e6-35bae709ab18.gif)

![8](https://user-images.githubusercontent.com/54401091/77646743-cb3b4900-6f6d-11ea-864d-8c2d69b69cf3.gif)

![7](https://user-images.githubusercontent.com/54401091/77646758-d2faed80-6f6d-11ea-9c10-f7f68e73c043.gif)

**Comment by danielamormocea** [comment]
@alexandra-martin No problem; I fixed the problem you were talking about, in the above PR; Also, I did not implement the timer to be visible in other states, but the listening one; If this should be done, I will get back on it 🙂

@ianb when you have time, take a look at the above PR for the fix;

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-27).

![5](https://user-images.githubusercontent.com/54401091/77769602-bbdefd00-704c-11ea-9b0e-f840c0c5dd94.gif)
