### ISSUE TITLE
Open and go new tab/new window

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#761]
Some examples of utterances we could support:

- "open a new window and go to the Washington Post"
- "open a new window and go to the New York Times"
- "open a new tab to the New York Times"
- "open the New York Times in a new tab/window"

I think these should go in the `navigation.navigate` intent, and add `[where=newtab]` or `[where=newwindow]` as parameters, and adjust the intent as appropriate to make use of those parameters.

**Comment by vanekcsi** [comment]
Can I work on this issue?

**Comment by vanekcsi** [comment]
Do I need to create a createWindow() function in the browserUtils script, that I can use in IntentRunner for the createTabGoogleLucky() function as an additional option using the extra parameter?

**Comment by ianb** [comment]
You might be fine just using `browser.windows` to create the window, and then relying on the new window being the active window. But if you wanted to create a function for creating windows, that would also be reasonable.

**Comment by sabina-rohman** [comment]
Hi @ianb  I'm an outreachy applicant May 2020. Can I please work on this issue, if it's still open?

**Comment by treasurechristain** [comment]
Hi @ianb , am an outrreachy applicant may 2020, please is this issue still open?
would love to work on it

**Comment by PrastutiUpadhaya** [comment]
Hi, can I work on this?

**Comment by JanviMahajan14** [comment]
@ianb  i am struck on how to pass the url of the query created in the new window as **createTabGoogleLucky(query)** creates it for tab only. Can you help me with this. Thanks!

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant. Can I take this issue if it is not being worked upon?

**Comment by JanviMahajan14** [comment]
@Kirti2502 i have already linked a [PR](https://github.com/mozilla/firefox-voice/pull/1165) to solve this issue. You may start with the other good first issues.
