### ISSUE TITLE
Use Gitter?

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#763]
Would other people enjoy using [Gitter](https://gitter.im/) for discussion on this project?

**Comment by maitrella** [comment]
I never heard about Gitter but I want to learn from all of you so I'm in.

**Comment by ianb** [comment]
Since Mozilla finally made a [choice about messaging servers](https://discourse.mozilla.org/t/synchronous-messaging-at-mozilla-the-decision/50620) I'm going to wait for the new Riot servers to be setup and then we'll make a channel there.

**Comment by ianb** [comment]
I've added a section to the README about our new chat service: https://github.com/mozilla/firefox-voice#discussion
