### ISSUE TITLE
Add copy/clipboard intents

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#77]
We might want to support copying some text or pieces of a page:

* Copy link
* Copy title
* Copy title and link
* Copy markdown link (which includes title)
* ~Copy article (Reader Mode view)~
* Copy screenshot
* Copy selection
* ~Copy main image~

What we copy can be HTML or text, but unfortunately we can't have a smart choice of which based on paste (we can _try_ to make the text paste work OK when we copy HTML, but it's limited).

**Comment by awallin** [comment]
@ianb What's the effort involved here? Might be a nice one for the Beta 3 milestone as new functionality to highlight.

**Comment by ianb** [comment]
Some are easy, some are harder. It looks like some of the [more advanced clipboard APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData) are available, which makes things easier.

`pageMetadata.js` makes some of this easier to get (or at least to get slightly nicer versions – e.g., it'll often get the URL without utm parameters).

I'll throw this back into triage for further discussion.
