### ISSUE TITLE
Negative feedback not submitted after pressing "Enter" key

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#772]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.
A command is made beforehand, that can show the feedback section in the "Doorhanger".

### STR:
1. After the command result is displayed in the "Doorhanger", click the sad emoticon from the "Did we get this right?" section.
2. Write something in the negative feedback text box.
3. Press "Enter".

### Expected result:
Negative feedback is submitted.

### Actual result:
Text cursor jumps to a new line.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![7](https://user-images.githubusercontent.com/54401091/70913312-7444e000-201e-11ea-8a08-37d54d8fc6cd.gif)

**Comment by ianb** [comment]
Fixing this will require adding a keypress handler on the textarea, and submitting it when the user presses enter.

**Comment by abahmed** [comment]
I'll start working on this issue
