### ISSUE TITLE
"Type input" text box needs to be resized only vertically

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#773]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Start to write something.
3. Once the "Type your request" section is displayed, click on the bottom right corner of the text box and drag it vertically and horizontally.

### Expected result:
The text box is resized only vertically.

### Actual result:
The text box is resized both vertically and horizontally.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![2](https://user-images.githubusercontent.com/54401091/70913744-44e2a300-201f-11ea-9193-0ce3d0051af6.gif)

**Comment by ianb** [comment]
This was fixed a while back
