### ISSUE TITLE
Text cursor moves in front of first written letter when doing a written command

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#774]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Start to write a command.
3. Observe "Doorhanger".

### Expected result:
There are no display issues in the "Doorhanger".

### Actual result:
After the first letter is written, text cursor goes in front of that letter.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).
The first written letter needs to be deleted or the text cursor needs to be moved to continue the written command.
Probably related to #755.

![1](https://user-images.githubusercontent.com/54401091/70914113-039ec300-2020-11ea-959a-8fe9dbbe969c.gif)

**Comment by awallin** [comment]
This one is driving me nuts. @ianb did you find a fix?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![1](https://user-images.githubusercontent.com/54401091/71177143-f67a1200-2273-11ea-823e-7210492dbb46.gif)
