### ISSUE TITLE
"Search" commands don't always open Google search tabs

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#777]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Search" command, e.g. "Search lion".

### Expected result:
A new Google search tab opens.

### Actual result:
If transcription displays only "lion", a Google card is shown in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![24](https://user-images.githubusercontent.com/54401091/70923695-f0e0ba00-2030-11ea-9f1b-b345f5dda6c9.gif)

![22](https://user-images.githubusercontent.com/54401091/70923710-f50cd780-2030-11ea-9b36-b75a9afebb64.gif)

**Comment by ianb** [comment]
@awallin and I aren't able to reproduce this. I could imagine a problem not catching the first word (and so skipping "search") but the report says it also happens with written commands.

I'm not sure what to do with this as a result, closing until we get other information.
