### ISSUE TITLE
"Launch new tab/window" command not working on Mac

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#786]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Launch new tab" command.

### Expected result:
A new tab open in the browser.

### Actual result:
A Google search is made for "Launch new tab" and a Google card is displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 73.0a1 (64-bit).
Reproduced also for the "Launch new window" command.
"Launch new tab" and "Launch new window" commands work as intended on Win.
"Open new tab" and "Open new window" commands work as intended on both Mac and Win.

![12 17 1](https://user-images.githubusercontent.com/54401091/71001239-88074980-20e5-11ea-81c2-ceaa32abd31e.gif)

**Comment by ianb** [comment]
I did notice a small issue I fixed in #803 – if your active tab is the new/blank tab, then it will be "reused" (which makes sense for opening a page, but not in this case).

However, I did not see a problem interpreting "launch new tab" (or window).

**Comment by alexandra-martin** [comment]
Tried it again today and everything seems fine on both Mac and Win. Tried also to open multiple new tabs while the latest new tab was active and I didn't have problems with the commands.

![12 18 1](https://user-images.githubusercontent.com/54401091/71092572-2e1f8600-21b0-11ea-8ac8-f0975e287e23.gif)
