### ISSUE TITLE
Changes needed for the "Lexicon" page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#788]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Lexicon" command, e.g. "Hello", "Help".
3. Observe the "Lexicon" page.

### Expected result:
The "Lexicon" page displays no issues.

### Actual result:
Current "Lexicon" page present some differences from the mock-up.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).
According to the mock-up the following differences are observed around:
- "Things you can say" and "Privacy" links;
- Missing "Suggest a new action or syntax" link bellow "The big list of what you can say." title;
- Distance variation between "The big list of what you can say." title and the list of command examples.

"Things you can say" link text doesn't need to be changed to "Lexicon" text.
"Things you can say" and "Privacy" links display need to be changed also in the "Privacy" page (accessed by clicking the "Privacy" link).

Mock-up:
![4](https://user-images.githubusercontent.com/54401091/71006726-7a09f680-20ee-11ea-9ccc-e18be4f21b98.png)

![4](https://user-images.githubusercontent.com/54401091/71006837-a7ef3b00-20ee-11ea-82a6-d5677b68714d.gif)

**Comment by awallin** [comment]
The link for suggest new action or syntax should go here:
https://firefox-voice-feedback.herokuapp.com/

**Comment by nash4j** [comment]
Hi @ianb , I'm an outreachy applicant, please let me know if it's fine to pick this issue. Thank you

**Comment by ianb** [comment]
@nash4j You got it!

**Comment by nash4j** [comment]
Hi @ianb , The page is not reloading changes automatically, each time on saving I have to terminate and start again. Am I doing anything wrong please help. Thanks

**Comment by ianb** [comment]
@nash4j Oh yes, that's a bit of a nuisance in how the setup works – whenever you change code the extension restarts, and anytime the extension restarts all the pages that are part of the extension are unloaded. I'm afraid the best suggestion I have is to copy the URL to the lexicon and re-open each time.

**Comment by nash4j** [comment]
sure Thanks. I have the changes for this issue on my local branch, but I can't push it to Github. Can you please confirm if I have push access to the repository. Thanks

**Comment by Simpcyclassy** [comment]
Have you been able to push @nash4j? If not try forking the repository and change origin to the forked repo. Push your code then create a PR. Let me know if this was helpful

**Comment by ianb** [comment]
@nash4j Yes, please fork this repository and push to your fork. From there you can make a pull request. People on the channel can also help you: https://chat.mozilla.org/#/room/#firefox-voice:mozilla.org
