### ISSUE TITLE
Zoom in, out and reset intents

### ISSUE THREAD

**Issue by maitrella** [mozilla/firefox-voice#790]
When someone asks for:

Zoom in
Zoom out
Zoom reset

Expected result: Zoom in, zoom out, reset current tab.

**Comment by awallin** [comment]
I like this one! Would also be nice to enable "Zoom to 150%" or "Zoom to 50%"

**Comment by maitrella** [comment]
@ianb "Zoom to" as another intent?. What is the best way to handle the percentage?.

**Comment by ianb** [comment]
I added `smallNumber` to `intentParser.js` to handle number 1-9 for another intent, I guess the same thing might apply here. You could potentially add percents in the place as a typed parameter. I'm pretty sure you could actually put a regular expression in ENTITY_TYPES, like `ENTITY_TYPES = {...percent: ["\d?\d?\d%?"]}` (but you should confirm using "show all intents" that it compiles into a decent regular expression.

So then there'd be an intent `(zoom | set size) (to |) [level:percent]`

**Comment by maitrella** [comment]
Maybe "zoom to" is a complicated intent for me at the moment but I'll try to study the parser and work on it in the near future.

**Comment by ianb** [comment]
For sure, skipping "zoom to" is fine for this ticket.

**Comment by maitrella** [comment]
If you want I can open a new issue with "Zoom to" intent.
