### ISSUE TITLE
Add progress indicator to Save Page

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#792]
In #791 it adds a Save Page intent, but just putting together the HTML and resources and passing it back to the background page can take a second or two. During that time nothing appears to be happening. We should show some progress in the popup. 

Note that we can't do percentages, as we don't really know how long it will take.

We should probably have some message we send to the popup (by IntentContext) that shows a generic loading throbber, and we can use it other things in the future.

**Comment by awallin** [comment]
We have the Zap processing animation that appears in the doorhanger when attempting to take an action. Can we display that?

**Comment by awallin** [comment]
Attaching mockup.

![processing-save-page](https://user-images.githubusercontent.com/428245/71107236-91d88d80-2175-11ea-9390-7e868995200c.jpg)

**Comment by JanviMahajan14** [comment]
Hey @awallin I am not sure from where I can get this animation .Can you help me with this? Thanks!

**Comment by awallin** [comment]
The animation currently appears after a request has been made. @ianb can probably point you to the specific location in the code.

**Comment by ianb** [comment]
@farhatcode has an open issue so I'll give this one to @JanviMahajan14 

This animation is the "zap" animation. If you look for `class Zap` in `popupView.jsx` you'll find it. We have a single animation, and we use different time periods in the animation to get the different bits.

I think the right way to handle this one is to create another view name, similar to the "feedbackThanks" view, that will show the animation and "Saving page...". Then once the saving is done it should change back to some other view (maybe "success").

You'll have to send messages from `saving.js` through to `popupController.jsx`. Something like "displayFailure" is an example of this.

**Comment by JanviMahajan14** [comment]
Thanks I am working on this.

**Comment by JanviMahajan14** [comment]
@ianb Can you tell me from where we are sending message for "displayFailure" so i could relate it with for sending messages for the new view created through "currentView" prop.

**Comment by ianb** [comment]
@JanviMahajan14 There's three processes involved here: the popup (which is its own page), the invisible background page, and the content page (the tab that is being saved). The background page is where `saving.js` is running (and where `IntentContext` from `intentRunner.js` exists). Actually getting the HTML is happening in the content page, in `saveContentScript.js`. And the popupView and popupController are in the popup page.

So... you'll want `saving.js` to send a message to the popup that saving has started (similar to how `displayFailure` works – IntentContext will send the message, and `popupController.jsx` will receive the message. And then `saving.js` will also send another message when the saving has completed.

**Comment by JanviMahajan14** [comment]
thanks @ianb your explanation really helped me to understand the things clearly.
