### ISSUE TITLE
Add "save page as" intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#799]
Maybe just as another match for the current saving.save intent. There's a parameter to `.download()` that we currently leave unset that will force save as.

We could also do "save page as [name]". I'm a little unsure if that's a reasonable way to give a name, given the unreliability of the transcription, but then if we put it in users might just hate it and tell us, which is OK.

**Comment by awallin** [comment]
Thanks for working on this @maitrella. @ianb is on vacation this week and next so might not get a chance to review the PR until January.

**Comment by maitrella** [comment]
I know. :)
