### ISSUE TITLE
Make a default filename for Save As

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#800]
Right now our filename is `Page_YYYY-MM-DD TITLE.html`

That's probably not the best filename, but I don't know exactly what it should be. I don't think using _just_ the title is great either. And maybe the domain belongs in there too?

**Comment by awallin** [comment]
Do we need 'Page'? What if Domain_YYYY-MM-DD TITLE.html? That feels more descriptive.

**Comment by ianb** [comment]
We can probably skip the underscore too. So it would be `{location.hostname} {date} {title}.html` (with the cleanups that are already in the code). Maybe we'd want to strip `www.` from the hostname too.

**Comment by awallin** [comment]
Agree, strip out "www."
