### ISSUE TITLE
Error displayed in "Doorhanger" when trying to paste a link in a new tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#806]
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
A "Copy link" command is made beforehand.
A new tab is made active.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Paste" command.

### Expected result:
The link is pasted in the tab.

### Actual result:
An "Internal error: Error: Missing host permission for the tab" error is displayed in the "Doorhanger".

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 73.0a1 (64-bit).

![2](https://user-images.githubusercontent.com/54401091/71094657-00d4d700-21b4-11ea-9f57-ddfb171ade8f.gif)

**Comment by awallin** [comment]
I can verify I saw this while testing 'paste' yesterday. It was intermittent.

**Comment by ianb** [comment]
Paste only supports pasting into the page, it can't paste into a URL. The error message is actually about being unable to access about:newtab (because it's an about page). 

We could improve that error message. I'll open that as a separate bug.

**Comment by ianb** [comment]
Pasting into the URL bar is a wontfix, the about:newtab is mentioned in the other ticket.
