### ISSUE TITLE
Improve confirmation for save page and copy

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#807]
To ensure users know how to take next steps after issuing a 'copy' or 'save page' request the confirmation messages should be more descriptive. See attached mockups.

![copied](https://user-images.githubusercontent.com/428245/71114427-9bb5bd00-2184-11ea-9627-e1aa7a2e79f5.jpg)

![Page saved](https://user-images.githubusercontent.com/428245/71106584-73be5d80-2174-11ea-8ca1-58d9f4b7ce61.jpg)

**Comment by ianb** [comment]
I realize we can also do a little followup with downloaded items:

- Open (with default application): not useful here (it would open the static HTML in the browser)
- Show: shows it in the Finder/folder
- Erase (from history): takes it out of the Download Manager (probably not useful?)

**Comment by awallin** [comment]
Can we trigger the file system on the OS with a 'show' command?

**Comment by ianb** [comment]
This is how we display simple messages right now:

<img width="411" alt="image" src="https://user-images.githubusercontent.com/44390/75260595-790cd980-57af-11ea-91b2-adf9577bc69d.png">

It doesn't seem right, but entirely replacing the utterance with a message also doesn't seem right. @awallin thoughts?

**Comment by awallin** [comment]
@ianb Visually it looks good. The only improvements I can see would be adding a link to the 'downloads folder' that would open the file system and/or adding the ability to open the file/folder with an utterance such as 'show' or 'open'

**Comment by ianb** [comment]
We don't actually have an intent to show the downloads, so I guess we don't have anything to do at the moment.
