### ISSUE TITLE
Add tab naming intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#808]
This goes along with the nicknames assigned to intents themselves. I propose:

- `Name (this |) (this | tab | page) [name]`
- `Give (the |) name [name] to (this |) (tab | page)`

Maybe additionally we'd name a site:

- `Name (this |) site [name]`
- `Give (the |) name [name] to (this |) site`

The site would save both the hostname _and_ the specific URL that was matched. A site could be used where a tab was used. (This seems tweaky though... should we just treat everything as both a site and a specific URL?)

We'd then use these names in specific places:

- Open [name]
- Find [name]
- Close [name]
- [name] (would mean the same as "open [name]")

Sites could possibly be handled like:

- Show all [name] (would bring all tabs from that site together)
- ...? I think there's more here.

**Comment by fleur101** [comment]
Hi! May I try to work on this one?

**Comment by ianb** [comment]
@fleur101 Sure, give it a try. There's some open design issues here: what does it mean to name a tab, what intents need be overridden, when do we treat it like a named tab or a named site/url? How do we persist this over restarts? Because I don't have answers for these questions this might be challenging, and I'd recommend starting with the parts that seem clear and then thinking it through from there.

**Comment by fleur101** [comment]
@ianb  Do I understand correctly that I should work in tabs.js and tabs.toml file and use browser.storage.sync for storing tab names (similar to intent names)?

**Comment by ianb** [comment]
@fleur101 it could probably go in `nicknames.js` since it's about naming more than tabs. `browser.storage.sync` would be the right place.

I'm not actually sure where all a named tab would be used, it will require a bit of creativity to think it through. It might require modifying some existing intents. It would be fine to start small with just a couple updated intents.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-13).
Initial testing was made for this intent and most commands are working. So far only #1527 was logged, but will log new reports if other issues are found.

![4](https://user-images.githubusercontent.com/54401091/79131703-b2c28f80-7db1-11ea-8523-a66b01b3f341.gif)
