### ISSUE TITLE
Add weather intents

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#81]
Some ways to ask for weather:

* What is the weather (in [city])
* What’s the temperature (in [city])
* Tell me the forecast (in / for [city])
* [city] temperature
* [city] weather
* What’s it like outside?
* How’s the weather / temperature?
* Is it nice out
* Is it (cold / warm / raining / drizzling / snowing / hailing / windy / chilly / sunny / cloudy / storming / stormy / thunderstorming) out
* Check the weather (in [city])

In almost all cases Google returns an appropriate weather card for its search. Can we simply detect these and display that card in the popup? Google does _not_ display things like [10 day forecast for Keene](https://www.google.com/search?client=firefox-b-1-d&q=10+day+forecast+for+keene) particularly well.

**Comment by espertus** [comment]
All of these seem to work except for "Is it nice out". If you'd like, you can assign that to me.

**Comment by ianb** [comment]
@espertus I don't think we need to put a special case in just for "is it nice out"... I think we can call this ticket fixed.
