### ISSUE TITLE
Ads included in search results

### ISSUE THREAD

**Issue by jofish** [mozilla/firefox-voice#810]
The first link when you search for New York Times is the subscription page, so we're going there right now, which is never the right answer. Let's hard code that query to nytimes.com.

**Comment by ianb** [comment]
What exactly are you saying and where does it go?

If I say "open new york times" it takes me to the homepage, and if I say "new york times" I get a card. If I say "new york times" then "next result" then I do get a subscription page. I do notice this is an ad:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/44390/71127616-0977de00-21b1-11ea-8c89-3ec40598d039.png">

I'm guessing the answer here is to get this code to exclude ads: https://github.com/mozilla/firefox-voice/blob/571ab14adc683387b2684cd2183f5b88028d7d6d/extension/intents/search/queryScript.js#L85-L92

**Comment by awallin** [comment]
If I say "go to the New York Times" it successfully loads nytimes.com

**Comment by jofish** [comment]
It looks like I was saying "take me to the new york times." Can we put "take me to"
 in as an alias for "go to"?
