### ISSUE TITLE
Open in-page links with voice

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#825]
User should be able to use their voice to open a link on the active page.

A couple example of the interaction below:
-  If the New York Times home page is the active page saying "Open <article name>" would result in the relevant article being opened.
- If Facebook is the active page saying "Click on <friends name>" would open your friends profile page.

**Comment by ianb** [comment]
Here's the phrases I catch:

```
  (follow | click | click on) (link |) [query]
  (open | go to) link [query]
```

It only follows links. I add a pinkish highlight to the link for a moment before following it (background-color `rgba(255, 0, 0, 0.3)`). Other styles would be possible, I just made something up.

We might consider supporting `<button>` as well, maybe using two slightly different phrases (I think "follow" shouldn't select buttons, but "click" should do anchors or buttons). Note that elements that are clickable, but aren't anchors or buttons, wouldn't be found at all (unfortunately not uncommon in apps).

**Comment by awallin** [comment]
Great feature. I've had some issues getting the syntax right. Words like 'open' and 'click' seem to have frequent transcription errors. We'll have to keep our eyes on that.

Would be great to use a highlight style that matches the Zap. We could copy the style FPN uses for their navigation.

<img width="760" alt="Screen Shot 2020-02-21 at 9 36 24 AM" src="https://user-images.githubusercontent.com/428245/75057383-bc083d80-548d-11ea-98e5-165fd9ef8036.png">

**Comment by awallin** [comment]
We've also used this css during onboarding for the zap.

`display: block;
content: "";
height: 5px;
background-image: linear-gradient(to right,
#6173ff, #f10366, #ff9100);`
