### ISSUE TITLE
unwanted firefox microphone popup at top of screen after activating

### ISSUE THREAD

**Issue by Maxgy** [mozilla/firefox-voice#828]
![Screenshot_2020-01-07_23-48-22](https://user-images.githubusercontent.com/19353212/71951259-76770600-31a8-11ea-82d5-30606393fb10.png)
This pops up at the top of my screen covering my tabs every time I activate Firefox Voice. I am aware that this is a feature of Firefox (I've seen it in video calls), but I think it is a hindrance to this extension.

**Comment by brierjon** [comment]
Running Pop!_OS 19.10 with default desktop (GNOME) this indicator is persistent on the desktop when all Firefox windows are minimized and is drawn over other application windows.

Desktop screenshot:
![Screenshot from 2020-01-10 17-09-13](https://user-images.githubusercontent.com/717866/72167881-49a33880-33cc-11ea-9327-59eaf5a3b12f.png)

Example is the Pop!_Shop window as screenshot:
![Screenshot from 2020-01-10 17-10-41](https://user-images.githubusercontent.com/717866/72167872-44de8480-33cc-11ea-98a1-0e20c03877ca.png)

**Comment by brierjon** [comment]
Related to #489

**Comment by ianb** [comment]
The fix here will be #86 – this should be possible, but only in Nightly and probably Beta.
