### ISSUE TITLE
Add "find in this page" intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#843]
This would use the [find API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/find/find) to search the current page.

I'm not sure exactly how it would work, so we should flush this out some more before implementation.

**Comment by vibhuti019** [comment]
Please explain about the feature. I want to work on this.

**Comment by awallin** [comment]
@vibhuti019 This feature would allow for a text voice search of the active web page. For example  saying something like:

* "find 'water' on this page"
* "search this page for 'water'"

Would open the find menu (also accessible via Command + F) and search for 'water'

**Comment by ianb** [comment]
If someone wants to try this out: mostly you'll be exposing the find API that is mentioned in the description. So `find [query] on (this |) (page | tab)` or `search (this |) (page | tab) for [query]`

This will be a new intent, I guess in `tabs.js`. The _writing an intent_ document should give some guidance.

**Comment by NoelyMarques** [comment]
Hi @ianb, I am an outreachy applicant and I'd like to have this issue assigned to me. May I?

**Comment by shreyajain25** [comment]
Hi @ianb , May i work on this as my first issue?

**Comment by vibhuti019** [comment]
I will have to work for mobile version only or for pc version too..

**Comment by vibhuti019** [comment]
For mobile version we can give a mic icon so user can tap and perform their queries... 
As I could guess we can extend this too for other options too..

**Comment by ianb** [comment]
I guess I will assign this to the first commenter, but @NoelyMarques please confirm in a comment here that you are working on it so that I can be sure it doesn't get stuck.

**Comment by NoelyMarques** [comment]
Hello @ianb, yes I am!

**Comment by Simpcyclassy** [comment]
I think this issue can be closed with the merged PR for verification
