### ISSUE TITLE
Implement build-controlled URL loading intent runner

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#856]
For demo purposes, we want to be able to let an external app open a URL which will cause Firefox Voice to execute the intent text. (This is not a secure communication channel, so it will only be enabled with a build option used for demo purposes.)

We'll do something like:

```sh
DEMO_INCOMING_URL=https://va.allizom.com/execute.html npm run start-android
```

(or any build-related command – this will modify both manifest.json and buildSettings.js)

Then if the URL `https://va.allizom.com/execute.html?text={text}` is opened, we'll capture that, and execute the text as though the user ran it.

For the first version, we will not open the popup, and so no confirmation will be shown – this is intended for Android, and the popup doesn't work very well there anyway. It requires some WebExperiment code to open the popup without the user clicking on a button, so it's a bit hard.

We could consider signing, but for now we'll avoid that, since it's not obvious how to handle the crypto and keys.

**Comment by espertus** [comment]
I misunderstood and thought this issue was the Android app.
