### ISSUE TITLE
Revert to acquiring microphone in popup

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#86]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

When I launch Firefox via <kbd>npm run once</kbd> (or <kbd>npm start</kbd>), and then click on the toolbar icon, it pops up a modal (yay) but then opens a new tab (ok, sure), prompts to use my microphone (back to yay) but then I lose the modal I was reading and/or the settings dialog (not yay).

Terrible GIF cast ahoy:

![ffvoice](https://user-images.githubusercontent.com/557895/62978298-d32aec00-bdd5-11e9-8792-9c89371236cc.gif)

Even if I click "Allow" in the dialog, it seems to still happen each time I click the toolbar icon... _unless_ I also click "Remember this decision" checkbox.

![Welcome_to_Firefox_Voice](https://user-images.githubusercontent.com/557895/62978384-02d9f400-bdd6-11e9-8b03-ce084bf35c43.png)

![Blank_Skitch_Document](https://user-images.githubusercontent.com/557895/62978407-0ff6e300-bdd6-11e9-963a-618347630716.png)

**Comment by ianb** [comment]
Also related to #61

**Comment by jan-ivar** [comment]
> then opens a new tab (ok, sure), prompts to use my microphone

The extension will need some form of onboarding process that opens a page to hang an initial permission prompt off of. We don't have a better permission story for web extensions at the moment AFAIK.

> Even if I click "Allow" in the dialog, it seems to still happen each time I click the toolbar icon... unless I also click "Remember this decision" checkbox.

Firefox `getUserMedia` permissions are single-use by default (`☐
 Remember this decision` is off), which makes sense for regular content, maybe not so much for extensions.

Maybe we should default `☑ Remember this decision` to on for `moz-extension://` origins?
cc @johannhof

**Comment by johannhof** [comment]
Yeah, we've talked about this last week and I'm going to make a patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1579489

**Comment by johannhof** [comment]
That bug has been resolved now. @ianb you should be able to request permission on an in-content webextension page now and use it in the popup without problems. Would be great if you could give it a try and report any issues.

**Comment by johannhof** [comment]
(In the next Nightly)

**Comment by ianb** [comment]
We need to see if we can remove the recorder page.
