### ISSUE TITLE
Audio is not being captured

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#860]
Several people have reported that when they speak, the audio simply is not being captured and no transcription appears.

**Comment by alexandra-martin** [comment]
While testing on Mac, at some point no audio was captured and then I couldn't make any audio commands. Had to reopen the browser in order for the add-on to work properly again. Managed to get the error from the Browser Console and the telemetry information. What other information should I look at, if I reproduce this again?

![02 21 voice](https://user-images.githubusercontent.com/54401091/75046938-a6ffce80-54ce-11ea-88a7-a851198b0e13.gif)

**Comment by ianb** [comment]
This is some kind of Firefox bug. I've submitted it as [Bug 1621462](https://bugzilla.mozilla.org/show_bug.cgi?id=1621462)

**Comment by awallin** [comment]
Another report from a user. Sounds like the mic works on other apps such as MIcrosoft Word but not in Firefox.
https://github.com/mozilla/firefox_voice_community/issues/323

**Comment by ianb** [comment]
Closing here, as there's no more we can do in Firefox Voice.
