### ISSUE TITLE
The close button in the success instruction box overlaps content at certain page widths

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#87]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

The close button in the success instruction box overlaps content at certain page widths:

![Welcome_to_Firefox_Voice](https://user-images.githubusercontent.com/557895/62978591-7f6cd280-bdd6-11e9-9204-0bce3cbae11f.png)

**Comment by ianb** [comment]
We'll make sure this is fixed in #108
