### ISSUE TITLE
"Web" part of the word "website" constantly missing from file search on Google Drive [BUG]

### ISSUE THREAD

**Issue by VickyEWood** [mozilla/firefox-voice#878]
**Firefox Version**

72.0.1 (64-bit)

**What device are you using?**
 
MacBook Pro (15-inch, Mid 2009)

**Where are you currently based**
 Canada

**Issue Type**

- [X] Doesn't behave as expected
- [ ] Didn't understand me
- [ ] Performance issue or slow
- [ ] Other

**Issue Description**
1. Click Firefox Voice icon in browser
2. Say "Find website work plan on my Google Drive"
3. See Firefox Voice acknowledge "Find website work plan on my Google Drive"
4. Firefox Voice opens up google Drive
5. See "site work plan" filled out in Google Drive search bar

Repeated 3 x and each time with the same result. Also tried searching for multiple documents with the word website in it, but each time "web" was missing from the search bar in Google Drive. 

**What were you hoping/expecting Firefox Voice to do?**
 
I was hoping that Firefox Voice would find the document titled "website work plan" on my Google Drive and display it in the search results. 

**Actual behavior**

Firefox Voice is hearing the sentence correctly. But the "web" part of the word "website" is getting lost when it opens up Google Drive and pre-fills the search bar.  

**Screenshots**

![Screen Shot 2020-01-17 at 2 17 30 PM](https://user-images.githubusercontent.com/59984406/72650352-24b34600-3935-11ea-86f0-e82e45ddb01d.png)
![Screen Shot 2020-01-17 at 2 17 13 PM](https://user-images.githubusercontent.com/59984406/72650354-25e47300-3935-11ea-8ac9-ff3413de8332.png)

**Comment by awallin** [comment]
I've noticed this as well. We should improve the timing between trigger and opening mic.

**Comment by maitrella** [comment]
@awallin maybe is a problem with  substitutions on intent parser.

**Comment by ianb** [comment]
@maitrella you are right, while we have some problems not recording the first word, in this case it's an intent parser problem.

In this case it's a scoring problem: we're scoring slot characters as "bad", so any substitution that shortens a word is preferred. Really we should be scoring non-slot characters as "good".
