### ISSUE TITLE
security-button.png extension img in success instruction block causes line breaks in UI

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#88]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

I think this is because tailwind.min.css seems to set the `<img>` tag to be `display: block;`. We might have to override that for the image to use `display: inline;` or `display: inline-block;`.

### Current

![Welcome_to_Firefox_Voice](https://user-images.githubusercontent.com/557895/62978992-77616280-bdd7-11e9-8473-1cca26d4c05f.png)

---

### Using `display: inline-block`

![Welcome_to_Firefox_Voice](https://user-images.githubusercontent.com/557895/62979038-97912180-bdd7-11e9-83a8-2a6ab1ac809e.png)

**Comment by ianb** [comment]
I put that in in a rush, and didn't even select the rectangle in a reasonable way. Closing this in preference of #108.
