### ISSUE TITLE
Change intents to be more declarative

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#885]
Right now intents register themselves in the extension process. At some point we're going to want to be able to process some of that metadata without the extension loading (e.g., to allow an Android app to read that information).

I would propose that every directory in `intents/` have a JSON file (maybe TOML?) that gives the basic metadata:

- All the match phrases
- All the examples, plus some example metadata
- The name and description of the intent
- Whether the intent can run on desktop, mobile, or (default) both

The runners would then be keyed on ID.

If it's TOML, then we'd probably compile the TOML to JSON and maybe also Javascript (it would be easier to load the metadata as a .js file in the extension, just wrapping the JSON in an assignment).

Note that `bin/substitute-manifest.js` is the script that currently constructs the list of intents and puts that list into `manifest.json` (so that new intents in the `extension/intents/` directory are automatically picked up). Probably these config files should be detected in the same place and used to create the js file that combines all of them. That generated js file would probably look like:

```js
this.intentConfiguration = {
  "search": {
    "search.search": {
      "matches": [
        "some phrase"
      ]
    }
  }
};
```

We could potentially compile match phrases to regular expressions at this stage too, which would make the parser easier to implement in other languages.

**Comment by espertus** [comment]
> Whether the intent can run on desktop, mobile, or (default) both

Would we want to distinguish between mobile launched from the helper app (e.g., Spotify) and mobile passed to the extension running on fenix/fennec?

**Comment by awallin** [comment]
Yes. I added a couple issues for examples on mobile where we'd want different behavior than desktop. #926 #927

**Comment by ianb** [comment]
In retrospect, it also would have been reasonable to just catch a few phrases in the launcher app using any ol' technique, and fall back to the extension. But probably the work on this has progressed and it makes sense to do it – and this ticket would be a useful refactoring for the extension too, so while a more expedient solution here might have been the right choice, the more thorough solution is also reasonable.

One reason that we might want to have the launcher understand all intents is that we do rank the matches, so knowledge of what the extension can do is useful, and we may want to easily reuse some of the phrasing.
