### ISSUE TITLE
Missing href for "How Mozilla protects your voice data"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#89]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

Looks like we're missing the `href=` attribute value, so it just reloads the /onboarding/onboard.html page:

https://github.com/mozilla/firefox-voice/blob/4faedbc04e81ed912b186d8a4fe0241742f6c760/extension/onboarding/onboard.html#L32-L33

We should also make sure we style the link a bit more so it's obvious that it's a link (since it doesn't seem to have a tabindex and I wasn't able to tab to the element), and I didn't realize it was actually a link until I accidentally clicked around on the page.

---

Also missing the `href=` attribute value from /extension/popup/popup.html#L41:

https://github.com/mozilla/firefox-voice/blob/4faedbc04e81ed912b186d8a4fe0241742f6c760/extension/popup/popup.html#L40-L42

**Comment by ianb** [comment]
@harraton is putting together the up-to-date description. For the internal release we may just link to a [Google doc](https://docs.google.com/document/d/1zi8UYgOfcjRnf9kJYXQNuBNhKYf_XUmS50Wj-6Yq4J0/edit), but for the external release we should put a doc on a site and link to that.

**Comment by ianb** [comment]
We'll get a link to our (smaller) privacy policy in our onboarding redesign.
