### ISSUE TITLE
Processing state

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#894]
After the utterance has been displayed a processing state should be visible with the circle animation transitioning to the check mark once the system has confirmed it can accomplish the request.

Ideally this display can remain up for a second while the tab does a bit of loading in the background to create a smooth transition to the display of the active tab (avoiding any display of the previously active tab).

![Processing](https://user-images.githubusercontent.com/428245/72943994-7fc9ac00-3d2c-11ea-92e3-696fb7724406.jpg)

**Comment by espertus** [comment]
@awallin You could help me by letting me know what you want in terms of these states or telling me how I can step through the animation frame by frame:
```

      this.animationSegmentTimes = {
        reveal: [0, 14],
        base: [14, 30],
        low: [30, 46],
        medium: [46, 62],
        high: [62, 78],
        processing: [78, 134],
        waiting: [88, 122],
        error: [134, 153],
        success: [184, 203],
      };
```

**Comment by espertus** [comment]
The events I can detect are:
* app starts
* onReadyForSpeech() [14, 78]
* onBeginningOfSpeech()
* onEndOfSpeech()
* onResults() [184, 203]
* onError() [134, 153]

I put my guesses as to what ranges you want, but I'd like to get your input, @awallin .

**Comment by awallin** [comment]
I'm not familiar with how to step through the animation frame by frame maybe @ianb can provide details?

I'm not sure how to provide guidance for the time ranges? I thought the processing/waiting states would animate until the process in ready to move to the next step?

**Comment by espertus** [comment]
There is a single JSON animation file. I have to specify programmatically which frames should play during which part of the program. I got the labels from the JS code. They aren't part of the animation file itself, as far as I can tell.

**Comment by awallin** [comment]
Is it helpful for me to guess at each state represents? Looking at the names I have a pretty good idea.

**Comment by espertus** [comment]
@awallin Could you please try this candidate APK: https://github.com/espertus/mozilla-assistant/blob/bb2ed110b076ec177053246e3f23e323469c3f9a/app/build/outputs/apk/debug/app-debug.apk?raw=true

**Comment by awallin** [comment]
Looking good. Could the check animation linger on the screen for another .25-.5 seconds to give the user a chance to read the transcription and see the checkmark.

Other than everything is behaving nicely.

**Comment by espertus** [comment]
Thanks for the feedback. I've added that. Here's the new APK. https://github.com/espertus/mozilla-assistant/blob/6610cf27b4ca85811b671475368a6dc997dc2dfb/app/build/outputs/apk/debug/app-debug.apk?raw=true
