### ISSUE TITLE
Activate Firefox Voice when clicking mic icon in Firefox

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#896]
The Android version of Firefox has a mic icon in the url bar which currently launches Google voice services and then routes the request to the configured search provider. For demo purposes we should trigger the FxVoice when clicking on that mic.

A second place a mic appears is on the desktop widget for Firefox. We should also trigger FxVoice in that case.

**Comment by espertus** [comment]
I don't think this is possible (without building our own browser), although I've put out a query to the fennec team.
