### ISSUE TITLE
Onboarding page should have a footer w/ privacy policy and terms of use links

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#90]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

We may want to make sure all the HTML pages have footers with links to legal ToS and Privacy Policy links so user's know how data is handled, etc. It may be the same link(s) as the "How Mozilla protects your voice data" link (ref: #89).

We can also include a link to the GitHub repo for filing issues/feedback, etc.

/onboarding/onboard.html

![Welcome_to_Firefox_Voice](https://user-images.githubusercontent.com/557895/62982033-d7f49d80-bddf-11e9-8bc9-57e6f803d98c.png)

**Comment by ianb** [comment]
We'll do this in #505
