### ISSUE TITLE
[Browser control] add-on manager intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#904]
Based on telemetry users want to open add-ons using utterances such as:

"open add-on manager"
"open extensions"
"manage add-ons"
"manage extensions"
"extensions"

These should open about:addons

**Comment by maitrella** [comment]
@awallin  "about:addons" is an illegal URL. (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create)

``` javascript
  this.intentRunner.registerIntent({
    name: "navigation.openExtensions",
    description: "Opens add-ons/extensions manager",
    match: `
    (open | manage |) (add-on | extensions | add-ons) (manager |)
    `,
    async run(context) {
      await browser.tabs.create({ url: "about:addons" });
    },
  });
```
Maybe in the near future this intent works.

**Comment by Simpcyclassy** [comment]
I fixed this in this PR https://github.com/mozilla/firefox-voice/pull/1413

**Comment by Simpcyclassy** [comment]
Maybe I will add extra examples along the line

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Windows 10x64 with Firefox Nightly 77.0a1 (2020-04-15).

![1](https://user-images.githubusercontent.com/54401091/79350651-66f22080-7f40-11ea-8a09-134158f58ff8.gif)
