### ISSUE TITLE
'Bring up...' utterance

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#908]
Based on telemetry some people are using the phrase 'bring up...' and expect it to open an existing bookmark.

"bring up my calendar"

It could be an alias for bookmarks or just "open..."

**Comment by ianb** [comment]
These are additional phrases for the `navigation.navigate` intent

**Comment by ianb** [comment]
I'm going to actually call this an alias for "find" (we already have "bring me to" for find)
