### ISSUE TITLE
Firefox Voice vs VoiceFox vs Voice Fox

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#91]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

I think I declined the microphone prompt, but we should check this globally.

![Welcome_to_Firefox_Voice](https://user-images.githubusercontent.com/557895/62982602-7f260480-bde1-11e9-8acf-333377543dd1.png)

![Welcome_to_Firefox_Voice](https://user-images.githubusercontent.com/557895/62982702-db892400-bde1-11e9-94fb-89a626a16e41.png)

**Comment by ianb** [comment]
Oops, it was VoiceFox as an internal name for a bit, we haven't removed that everywhere. (Firefox Voice is the correct name)

**Comment by ianb** [comment]
There's still VoiceFox in an image in onboarding I think, but we'll get that fixed in another patch
