### ISSUE TITLE
Support Soundcloud

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#912]
Based on telemetry users were hoping audio controls would work on SoundCloud.

"Play"
"Pause"
"Mute"

**Comment by ianb** [comment]
This might require some guidance, but if someone wants to add Soundcloud support as a new music service, please reply here and I can give pointers.

**Comment by ianb** [comment]
This is a good second issue, slightly harder than some of the other issues. This will involve creating a new service, similar to `extension/services/spotify/` but for SoundCloud.

**Comment by melvin2016** [comment]
@ianb Can i work on this? 
I think along with "Play", "Pause", "Mute", we could add "Next" track and "Previous" track?
Can you guide me on getting started?

**Comment by naima-shk** [comment]
@ianb  can i try this one please ?
