### ISSUE TITLE
Full screen utterance

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#913]
Users want to make videos full screen with utterances like:

"full screen video"
"make full screen"
"full screen"

**Comment by ianb** [comment]
We may have problems implementing this due to this specific functionality having to be launched from a user-initiated event.

**Comment by ianb** [comment]
It looks like the `state` property makes this pretty easy using [windows.update()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update);

**Comment by maitrella** [comment]
@ianb for "make full screen" and "full screen" windows.update works. For "full screen video" maybe Fullscreen API will be an option. [https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API](url)

**Comment by ianb** [comment]
Yeah, full screen video makes sense too, I opened #995 as a followup.
