### ISSUE TITLE
Bookmark page

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#914]
Based on telemetry users are trying to bookmark a page using their voice.

"save this to bookmarks"
"bookmark this"
"bookmark this page"
"add this page to bookmarks"

**Comment by ianb** [comment]
This could be done with the [bookmarks.create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/create)

I think simpler is better, so we can use these phrases to create a simple bookmark placed in no specific location. The `pageMetadata.js` handler can get a good title and URL.

**Comment by paulZhongym** [comment]
@ianb Hi, are there any other features needed in this?

**Comment by ianb** [comment]
I think this is fixed with #967. It would be possible to add some new phrases that set the bookmarks title and such, but I'm not sure that kind of input is accurate enough to work well.
