### ISSUE TITLE
Save to Pocket

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#915]
Based on telemetry users are trying to save the active page to Pocket.

"save this to pocket"
"save page to pocket"
"Pocket this"

**Comment by ianb** [comment]
Maybe the simplest way is to use the same technique that the bookmarklet does:

```js
javascript:(function(){var e=function(t,n,r,i,s){var o=[5671614,6078827,2718634,1042238,4905060,5668005,3048706,3527201,5824429,1550215];var i=i||0,u=0,n=n||[],r=r||0,s=s||0;var a={'a':97,'b':98,'c':99,'d':100,'e':101,'f':102,'g':103,'h':104,'i':105,'j':106,'k':107,'l':108,'m':109,'n':110,'o':111,'p':112,'q':113,'r':114,'s':115,'t':116,'u':117,'v':118,'w':119,'x':120,'y':121,'z':122,'A':65,'B':66,'C':67,'D':68,'E':69,'F':70,'G':71,'H':72,'I':73,'J':74,'K':75,'L':76,'M':77,'N':78,'O':79,'P':80,'Q':81,'R':82,'S':83,'T':84,'U':85,'V':86,'W':87,'X':88,'Y':89,'Z':90,'0':48,'1':49,'2':50,'3':51,'4':52,'5':53,'6':54,'7':55,'8':56,'9':57,'\/':47,':':58,'?':63,'=':61,'-':45,'_':95,'&':38,'$':36,'!':33,'.':46};if(!s||s==0){t=o[0]+t}for(var f=0;f<t.length;f++){var l=function(e,t){return a[e[t]]?a[e[t]]:e.charCodeAt(t)}(t,f);if(!l*1)l=3;var c=l*(o[i]+l*o[u%o.length]);n[r]=(n[r]?n[r]+c:c)+s+u;var p=c%(50*1);if(n[p]){var d=n[r];n[r]=n[p];n[p]=d}u+=c;r=r==50?0:r+1;i=i==o.length-1?0:i+1}if(s==104){var v='';for(var f=0;f<n.length;f++){v+=String.fromCharCode(n[f]%(25*1)+97)}o=function(){};return v+'61799c7020'}else{return e(u+'',n,r,i,s+1)}};var t=document,n=t.location.href,r=t.title;var i=e(n);var s=t.createElement('script');s.type='text/javascript';s.src='https://getpocket.com/b/r4.js?h='+i+'&u='+encodeURIComponent(n)+'&t='+encodeURIComponent(r);e=i=function(){};var o=t.getElementsByTagName('head')[0]||t.documentElement;o.appendChild(s)})()
```

Available on [this page](https://getpocket.com/add/?ep=1) but only if you aren't in Firefox.

Note that code has to be run in the page content as a content script.

**Comment by ellieya** [comment]
Hi, I'm an outreachy intern applicant. Is it ok if I start working on this?

**Comment by annlinros** [comment]
Hi, Can I please work on this issue ? @ianb  @awallin

**Comment by awallin** [comment]
It's all your @annlinros

**Comment by annlinros** [comment]
Hi @awallin 
Could you please elaborate on what we are trying to achieve on this issue ?
I could easily pocket the page that I got from using firefox-voice.
Thanks

**Comment by PrastutiUpadhaya** [comment]
Can I work on this issue?

**Comment by awallin** [comment]
@annlinros Saying something like "save to pocket" should add the current page/url to the users Pocket account and confirm the action (see attached).

You'll also need to handle the case when the user is not logged into their Pocket account (see attached).

![saved-confirm-pocket](https://user-images.githubusercontent.com/428245/76106983-cdbd0b00-5f8c-11ea-865a-26a839286284.jpg)
![login-to-pocket](https://user-images.githubusercontent.com/428245/76106985-ce55a180-5f8c-11ea-9bc3-d44dcc3af033.jpg)

**Comment by ianb** [comment]
@annlinros You'll want to look at https://github.com/mozilla/firefox-voice/blob/master/docs/writing-an-intent.md to learn about writing a new intent. This could be a new intent in a new file in `intents/pocket/pocket.js`

If you look for `content.lazyInject` it'll show you some examples about how an intent can inject code into the running page.

**Comment by annlinros** [comment]
Thanks @ianb  and @awallin. I am working on this.

**Comment by JanviMahajan14** [comment]
@annlinros Can I work on this issue if you are busy with some other issues ?

**Comment by annlinros** [comment]
@JanviMahajan14  I was actually thinking of starting with this issue today.. 
But you could also do a PR if you would like..

**Comment by JanviMahajan14** [comment]
Thanks @annlinros

**Comment by annlinros** [comment]
Hi @awallin 
The user gets feedback from 'Pocket' itself saying the page was saved or the user needs to log in first.

In that case, should we proceed with the UI ?

Response from Pocket: 

<img width="2560" alt="Screenshot 2020-03-21 at 17 22 47" src="https://user-images.githubusercontent.com/42749886/77231120-200b4800-6b99-11ea-819a-4d46f0395c9b.png">

**Comment by awallin** [comment]
In that case no we don't need UI from the popup.
