### ISSUE TITLE
'Paste' dictation error

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#917]
Common issue seen with multiple users in telemetry is STT errors with paste. The following transcriptions have been reported when trying to say 'paste'

* haste
* taste
* pace
* best

**Comment by ianb** [comment]
We could add these to the intentParser subsitutions.

**Comment by awallin** [comment]
Trying to think if that would result in any unintended consequences but not sure anyone is expecting one of those words by itself to take an action?

**Comment by ianb** [comment]
If everything is working properly, the substitutions shouldn't apply unless it's a bare word or a very specific phrase. But this particular case is a bit tricky.

It would be nice to give the STT engine hints for this, but the speaktome API doesn't and probably won't support that.
