### ISSUE TITLE
Close Firefox utterance

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#919]
User wanted to shut down Firefox by saying "close Firefox" or "close the browser"

**Comment by awallin** [comment]
Seeing this same request multiple times in the post action telemetry feedback.

**Comment by maitrella** [comment]
@ianb [window.close](https://developer.mozilla.org/en-US/docs/Web/API/Window/close) "Scripts may not close windows that were not opened by script".  Maybe is impossible to implement a close browser intent.

**Comment by ianb** [comment]
I think this is intended to close the entire program, so there's no easy API to do it.

**Comment by maitrella** [comment]
In my mind: "If you close all the open windows them firefox closes too" XDDDD

**Comment by ianb** [comment]
True, on Windows it probably does – on Mac it just leaves the app open with no windows.

**Comment by awallin** [comment]
Another feature request came in asking for "exit Firefox" / "quit firefox" / "shutdown firefox"

https://github.com/mozilla/firefox_voice_community/issues/292

**Comment by GangaChatrvedi** [comment]
@ianb @awallin as pr is merged for this. should we close this issue?

**Comment by ianb** [comment]
@GangaChatrvedi Good catch, yes

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-04-01) for the current intent.
#1319 is a follow up for possibly having the confirmation window before Firefox is closed.
#1457 is a follow up for adding "(the) browser" in the intent.

![1](https://user-images.githubusercontent.com/54401091/78245359-039fd180-74f0-11ea-960a-bfe50a6b907d.gif)
