### ISSUE TITLE
"ReferenceError: log is not defined" in /popup/vad.js:179:9

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#92]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

I see we've declared `log` as a global in the header (`/* globals util, log */`), but not sure why the add-on isn't finding that method in Browser Console log:

https://github.com/mozilla/firefox-voice/blob/15bfe950a1f7ae957ef11c261068ec75ea488fe2/extension/popup/vad.js#L178-L180

![Browser_Console](https://user-images.githubusercontent.com/557895/62983211-6ae30700-bde3-11e9-86e0-0df126ce8d7a.png)

**Comment by pdehaan** [comment]
I filed the TypeError message as issue #93; **"TypeError: manifest.settings is undefined" in /log.js:9:20**.

**Comment by ianb** [comment]
Oh, I see the problem now – #93 is keeping log.js from loading, which is causing this error. Closing since #93 is the fix
