### ISSUE TITLE
Translate selected text

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#922]
When text is highlighted users ask "translate to Japanese" hoping the text should be translated.

Also tried "translate the selected text to Japanese"

**Comment by ianb** [comment]
Note we have this functionality with these phrases:

```
    translate (this |) selection (to english |) (for me |)
    translate (this |) selection to [language:lang] (for me |)
```

That wouldn't match you example though.

**Comment by maitrella** [comment]
@ianb  are you thinking about a change on intent like "(selection | selected text)" or a change on intentParser "selected text": "selection" ?.

**Comment by maitrella** [comment]
Japanese is not supported in languageCodes at the moment.

We can update languageCodes based on users demand or with the whole list (1)


(1) URLs supported languages by google translate: 

https://translate.google.com/intl/en/about/languages/
https://en.wikipedia.org/wiki/Google_Translate#Supported_languages

What is your opinion?

**Comment by ianb** [comment]
Regarding the phrase, I think we can just extend this one phrase.

For languages, adding the entire language list would be a welcome addition.
