### ISSUE TITLE
[Mobile] Map Intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#927]
On Android requests for directions and mapping locations should launch the default mapping app (not display in the browser).

**Comment by espertus** [comment]
Could you let me know what types of requests you'd like handled, such as:

- Navigate to 345 Spear St.
- What restaurants are nearby?
- How would I get to SFO?

**Comment by awallin** [comment]
Those are all good. These are others we should handle:

* Address only: "331 E Evelyn Ave, Mountain View"
* "Directions to 331 E Evelyn Ave, Mountain View"
* "Map <address/attraction/location/store name>"
* "Where's the nearest sushi restaurant"
* "Where's a good place to get pizza"
* "open maps"
* What's the fastest way to get to Disneyland"
* Might not be possible but if we have access to a 'home' or 'work' location it'd be great to say: "how do I get home?"

**Comment by espertus** [comment]
> Address only: "331 E Evelyn Ave, Mountain View"

@awallin @ianb Any suggestions how to recognize an address?

**Comment by awallin** [comment]
A couple of ideas:

* Try to match an existing set of addresses? Maybe that's contacts on the local phone, maybe an external library or maps API? If match is true pass request to maps app. Maybe we limit to matching to some local area (city, state) for faster/more accuracy?

* Look for city or zip code matches or use of "street", "avenue", "boulevard"

**Comment by espertus** [comment]
I don't think matching a raw address is very practical. Using an API would take time and/or cost money. I don't know how likely it is that an address would be in contacts and how long it would take to search for it, but that would really slow things down. 

There are regular expressions that would catch most addresses. I'll add one of @ianb thinks it's a good idea. 

FWIW, even Google Voice Assistant doesn't open Google Maps when given a raw address.

This explains some of the issues. https://stackoverflow.com/questions/11160192/how-to-parse-freeform-street-postal-address-out-of-text-and-into-components

**Comment by awallin** [comment]
If we could catch most addresses that'd be great. Doesn't have to be 100%.

FWIW, Siri does a pretty good job with just a number and a street name. 

![IMG_3C8FF3837A78-1](https://user-images.githubusercontent.com/428245/74986726-806a6680-53ee-11ea-983b-a0f95a34c8b9.jpeg)

**Comment by espertus** [comment]
There's a first version that should do everything except for a raw address. It has not been extensively tested. https://github.com/espertus/mozilla-assistant/blob/issue927/app/build/outputs/apk/debug/app-debug.apk?raw=true

The phrases can be seen in this file https://github.com/espertus/mozilla-assistant/blob/issue927/app/src/main/java/mozilla/voice/assistant/intents/maps/Maps.kt

More later.

**Comment by ianb** [comment]
Detecting addresses is just too hard for us at this time, it's like its own sub-language. If we send bare addresses to search/google.com, then Google will detect the address and show a map, and you can click that to get through to the Maps app. This seems like fairly good behavior to me.

**Comment by espertus** [comment]
I've merged these changes into master. As always, the APK can be found at https://github.com/espertus/mozilla-assistant/blob/master/app/build/outputs/apk/debug/app-debug.apk?raw=true

You can see the intents here: https://github.com/espertus/mozilla-assistant/blob/master/app/src/main/java/mozilla/voice/assistant/intents/maps/Maps.kt

**Comment by awallin** [comment]
Tested it out. Works great. I like how you support biking and walking directions.

Can you add support for the phrase "directions to <address>"?

**Comment by espertus** [comment]
That would be an easy addition. Hang on.

**Comment by espertus** [comment]
Done.
