### ISSUE TITLE
[mobile] Fix to listening UI

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#929]
A couple minor visual fixes listening mode when the zap and examples are being displayed but no audio is being captured.

- Do not repeat the 'burst' every few seconds. The line should continue to undulate without the burst repeating.
- the zap line should not extend the full width of the screen. Add margin of 40px on either side.

**Comment by espertus** [comment]
Thanks for calling these to my attention. Please test this APK when you get a chance: https://github.com/espertus/mozilla-assistant/blob/34f6c54cb59059aec76d854e35a85360e1a43b17/app/build/outputs/apk/debug/app-debug.apk?raw=true

**Comment by awallin** [comment]
Visual are looking good.
