### ISSUE TITLE
[FEATURE] Add more music services

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#931]
I would like choosing other music services, like Amazon Music or Deezer (and there are others: SoundCloud, iTunes, Google Play Music, YouTube)

**Comment by ianb** [comment]
We're going to survey everyone on what music services they are interested in. We have some tickets for specific services (e.g., #912), but we'll make more tickets for the other services when those results come in.

Contributions will also be welcome.

I think it will be easier to track these tickets individually, so I'm going to close this ticket.
