### ISSUE TITLE
Close tab alias

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#937]
Add an alias for tab when users says "close this website"

**Comment by maitrella** [comment]
@ianb I don't know whether to change intent or intentParser. Maybe the second option is more aggressive.

**Comment by ianb** [comment]
@maitrella I think changing the intent is probably the better way to go – the intentParser substitutions could get really out of hand if we add too many. Ideally I'd want to use them mostly for commonly-misheard words, and words that can be removed entirely.

**Comment by maitrella** [comment]
@ianb ok.
