### ISSUE TITLE
Scroll all the way down intent

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#938]
Add "scroll all the way down" intent which would scroll the active website to the bottom of the page.

Aliases:
- "Scroll to bottom"
- "Scroll to end"

At the same time we'd probably want to add "scroll all the way up" with aliases like:
- "Scroll to top"
- "Scroll back to beginning"

**Comment by maitrella** [comment]
@awallin  "Scroll to botton", "Scroll to top" are already supported.

**Comment by awallin** [comment]
@maitrella Can you add "scroll all the way down" looks like that was the intent a user tried recently.

**Comment by maitrella** [comment]
@awallin let me double check tomorrow but I think is already supported.

**Comment by awallin** [comment]
Yup. Looks like it works already.
