### ISSUE TITLE
Audit files in addons.xpi

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#94]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

```sh
$ tree

.
├── assets
│   ├── animations
│   │   ├── Done.json
│   │   ├── Error.json
│   │   ├── Spinning.json
│   │   └── Start.json
│   └── images
│       ├── alexa_logo.svg
│       ├── feedback.svg
│       ├── ff-logo.png
│       ├── googleAssistant_logo.svg
│       ├── icon\ settings.svg
│       ├── icon-48.png
│       ├── icon-96.png
│       ├── icon-close.svg
│       ├── icon-done-rtl.svg
│       ├── icon-done.svg
│       ├── icon-mic.svg
│       ├── icon-redo.svg
│       ├── mic.svg
│       ├── onboarding
│       │   ├── supergraphic-large.svg
│       │   ├── toolbar-arrow-2.png
│       │   ├── toolbar-arrow-3.png
│       │   └── zap.svg
│       └── smileface.svg
├── background
│   ├── intentParser.js
│   ├── intentRunner.js
│   └── main.js
├── css
│   ├── main.css
│   ├── options.css
│   └── vendor
│       └── tailwind.min.css
├── intents
│   ├── find
│   │   └── find.js
│   ├── muting
│   │   └── muting.js
│   ├── navigation
│   │   └── navigation.js
│   ├── playing
│   │   ├── pauseMedia.js
│   │   ├── playMedia.js
│   │   └── playing.js
│   └── read
│       ├── read.js
│       └── startNarration.js
├── js
│   ├── display-history.js
│   ├── languages.json
│   ├── options.js
│   └── vendor
│       ├── browser-polyfill.min.js
│       ├── fuse.js
│       ├── lottie.min.js
│       ├── moment.min.js
│       ├── webrtc_vad.js
│       └── webrtc_vad.wasm
├── log.js
├── main.css
├── manifest.json
├── manifest.json.ejs
├── onboarding
│   ├── onboard.html
│   ├── onboarding.css
│   ├── onboarding.js
│   ├── security-button.png
│   ├── security-panel.png
│   └── security-popup.png
├── popup
│   ├── animations
│   │   └── Firefox_Voice_Full.json
│   ├── popup.css
│   ├── popup.html
│   ├── popup.js
│   ├── ui.js
│   ├── vad.js
│   └── voice.js
├── searching.js
├── util.js
└── views
    ├── CHANGELOG.html
    └── options.html

19 directories, 66 files
```

Looks like the current XPI filesize (via <kbd>npm run package</kbd>) is 413 KB.

```sh
$ ls -lash addon.xpi # 413K
$ ls -lshR | grep -v "drwxr" | grep -v "total "
```
 
| SIZE | FILE | NOTES |
|-----:|:-----|:------|
| 966B | log.js
| 0B | main.css | Empty file?
| 1.7K | manifest.json
| 1.6K | manifest.json.ejs | ~~Should try and omit this file since we only need the generated .json file.~~ Ref #102
| 679B | searching.js
| 629B | util.js
| **120K** | ./assets/animations/Done.json | Not minified.
| 23K | ./assets/animations/Error.json | Minified. 👍 
| 120K | ./assets/animations/Spinning.json | Not minified.
| 120K | ./assets/animations/Start.json | Not minified.
| 3.0K | ./assets/images/alexa_logo.svg | Not minified. Ref #95 PR
| 649B | ./assets/images/feedback.svg | Minified. 👍 
| 9.4K | ./assets/images/ff-logo.png
| 856B | ./assets/images/googleAssistant_logo.svg | Minified. 👍 
| 1.1K | ./assets/images/icon settings.svg | Space in filename? Not minified.
| 1.0K | ./assets/images/icon-48.png
| 2.2K | ./assets/images/icon-96.png
| 741B | ./assets/images/icon-close.svg | Not minified. Ref #95 PR
| 808B | ./assets/images/icon-done-rtl.svg | Not minified. Ref #95 PR
| 773B | ./assets/images/icon-done.svg | Not minified. Ref #95 PR
| 1.5K | ./assets/images/icon-mic.svg | Not minified. Ref #95 PR
| 1.0K | ./assets/images/icon-redo.svg | Not minified. Ref #95 PR
| 413B | ./assets/images/mic.svg | Minified. 👍 
| 7.2K | ./assets/images/smileface.svg | Not minified. Ref #95 PR
| 2.8K | ./assets/images/onboarding/supergraphic-large.svg | Minified. 👍 
|  19K | ./assets/images/onboarding/toolbar-arrow-2.png
| 9.2K | ./assets/images/onboarding/toolbar-arrow-3.png
| 664B | ./assets/images/onboarding/zap.svg | Minified. 👍 
| 2.7K | ./background/intentParser.js
| 541B | ./background/intentRunner.js
| 437B | ./background/main.js
| 9.0K | ./css/main.css
| 165B | ./css/options.css
| **537K** | ./css/vendor/tailwind.min.css | ~~Seems huge for minified CSS, we may need to investigate our build.~~ Filed #113
| 1.4K | ./intents/find/find.js
| 1.3K | ./intents/muting/muting.js
| 598B | ./intents/navigation/navigation.js
| 564B | ./intents/playing/pauseMedia.js
| 562B | ./intents/playing/playMedia.js
| 1.1K | ./intents/playing/playing.js
| 585B | ./intents/read/read.js
| 204B | ./intents/read/startNarration.js
| 874B | ./js/display-history.js
| 4.6K | ./js/languages.json
| 2.7K | ./js/options.js
| 9.8K | ./js/vendor/browser-polyfill.min.js | Minified. 👍 
|  11K | ./js/vendor/fuse.js | Minified. 👍 
| **244K** | ./js/vendor/lottie.min.js | Minified. 👍 
| **52K** | ./js/vendor/moment.min.js | Minified. 👍 
| **67K** | ./js/vendor/webrtc_vad.js | Not minified.
| **29K** | ./js/vendor/webrtc_vad.wasm | ~~Do we need .js and .wasm?~~ (Yes, see https://github.com/mozilla/firefox-voice/issues/94#issuecomment-521278558 below)
| 5.9K | ./onboarding/onboard.html
| 932B | ./onboarding/onboarding.css
| 2.2K | ./onboarding/onboarding.js
|  10K | ./onboarding/security-button.png
| **51K** | ./onboarding/security-panel.png
| **55K** | ./onboarding/security-popup.png
| 3.0K | ./popup/popup.css
| 4.3K | ./popup/popup.html
| 2.7K | ./popup/popup.js
| 5.2K | ./popup/ui.js
| 7.2K | ./popup/vad.js
| 4.5K | ./popup/voice.js
| **60K** | ./popup/animations/Firefox_Voice_Full.json | Minified. 👍 
| 612B | ./views/CHANGELOG.html | Do we need to include a CHANGELOG.html?
| 491B | ./views/options.html

**Comment by pdehaan** [comment]
svg files minified in pending PR #95; **"Minify the SVGs using svgo"**.

**Comment by ianb** [comment]
I made manifest.json.ejs a ticket in #102

The wasm and js files for webrtc_vad do go together (one loads the other). #45 is a ticket to make these part of the build instead of copying them in, but at the moment I don't know exactly where they come from. I'll make a note about minimizing at the same time.

**Comment by pdehaan** [comment]
> but at the moment I don't know exactly where they come from

I had one theory in https://github.com/mozilla/firefox-voice/issues/45#issuecomment-521068040. My superficial looking at the headers made them almost seem similar. But I think the upstream https://github.com/mozilla/webrtcvad_js webrtc_vad.js file only had 4 revisions, so it should hopefully be fairly trivial for me to do some diffing and see if the files are in sync and that is indeed their heroic origin story.

**Comment by ianb** [comment]
We're working with @andrenatal and he can clear up the webrtcvad stuff, he just happened to be out on vacation.

What do you recommend for minimizing the JSON files? I think that's the only major thing left on the list.

**Comment by pdehaan** [comment]
> What do you recommend for minimizing the JSON files? I think that's the only major thing left on the list.

I don't think it's a thing anymore. I was just browsing the epic #117 and it looks like @jcambre nuked a bunch of the orphaned files and the offending JSON offending files were ✂️.

Here's an updated list (via <kbd>npm run package</kbd> then extracting the addon.xpi into tmp/ and running the following filesizer.js) and sorted by filesize:

```sh
$ ls -lh *.xpi
-rw-r--r--  1 pdehaan  staff   374K Aug 15 12:48 addon.xpi
```

SIZE | FILE | NOTES
----:|:-----|:-----
536.52 KB | css/vendor/tailwind.min.css | 
244.28 KB | js/vendor/lottie.min.js | 
67.5 KB | js/vendor/webrtc_vad.js | 
60.1 KB | popup/animations/Firefox_Voice_Full.json | 
55.06 KB | onboarding/security-popup.png | 
52.07 KB | js/vendor/moment.min.js | 
50.88 KB | onboarding/security-panel.png | 
28.5 KB | js/vendor/webrtc_vad.wasm | 
19.24 KB | onboarding/images/toolbar-arrow-2.png | 
11.21 KB | js/vendor/fuse.js | 
10.5 KB | onboarding/security-button.png | 
9.76 KB | js/vendor/browser-polyfill.min.js | 
9.23 KB | onboarding/images/toolbar-arrow-3.png | 
7.37 KB | popup/vad.js | 
5.82 KB | onboarding/onboard.html | 
5.76 KB | popup/ui.js | 
4.96 KB | popup/popup.html | 
4.62 KB | js/languages.json | 
4.5 KB | popup/popup.css | 
4.47 KB | popup/voice.js | 
4.45 KB | popup/images/dax-logo.svg | 
3.1 KB | popup/popup.js | 
2.95 KB | background/intentParser.js | 
2.64 KB | js/options.js | 
2.3 KB | onboarding/images/supergraphic-large.svg | 
2.21 KB | onboarding/onboarding.js | 
2.19 KB | assets/images/icon-96.png | 
1.89 KB | searching.js | 
1.74 KB | manifest.json | 
1.71 KB | intents/navigation/navigation.js | 
1.66 KB | manifest.json.ejs | 
1.51 KB | intents/muting/muting.js | 
1.44 KB | intents/find/find.js | 
1.24 KB | intents/playing/playing.js | 
1.03 KB | assets/images/icon-48.png | 
966 B | log.js | 
932 B | onboarding/onboarding.css | 
874 B | js/display-history.js | 
673 B | intents/read/read.js | 
629 B | util.js | 
612 B | views/CHANGELOG.html | 
564 B | intents/playing/pauseMedia.js | 
562 B | intents/playing/playMedia.js | 
541 B | background/intentRunner.js | 
540 B | onboarding/images/zap.svg | 
491 B | views/options.html | 
455 B | background/main.js | 
358 B | popup/images/mic.svg | 
204 B | intents/read/startNarration.js | 
165 B | css/options.css | 
0 B | main.css |

<details>
<summary>filesizer.js</summary>

```js
const fs = require("fs");

const filesize = require("filesize");
const glob = require("glob");

main();

async function main(dir="tmp/") {
  const re = new RegExp(`^${dir}`);
  const files = glob.sync(`${dir}**`);
  const res = files.map(file => {
    return {
      file: file.replace(re, ""),
      stats: fs.statSync(file),
    };
  })
  .filter(file => !file.stats.isDirectory())
  .sort(fileSizeDesc);

  console.log("SIZE | FILE | NOTES");
  console.log("----:|:-----|:-----");
  for (const file of res) {
    console.log(`${filesize(file.stats.size)} | ${file.file} | `);
  }
}

function fileSizeDesc(fileA, fileB) {
  return fileB.stats.size - fileA.stats.size;
}
```
</details>

**Comment by ianb** [comment]
I think things are OK now, or good enough
