### ISSUE TITLE
[wakeword] Don't enable wakeword when there's no specific word

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#943]
If you turn on the wakeword but have no words specified, it shouldn't try to start the detector. Should be a simple change to wakeword.js (`updateWakeword()`)

**Comment by awallin** [comment]
Is the wakeword enabled on the settings screen? Can we prevent it from being enabled without the selection of a specific word?

**Comment by ianb** [comment]
The logic gets a little complicated and annoying if we try to keep people from getting into this particular state. Adding a default wakeword (#942) will keep this from happening too often.

**Comment by ianb** [comment]
This was fixed in #1121
