### ISSUE TITLE
Review Ubiquity commands

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#957]
The page [Labs/Ubiquity/Commands In The Wild - MozillaWiki](https://wiki.mozilla.org/Labs/Ubiquity/Commands_In_The_Wild) links to lots of commands for Ubiquity (see also [UbiquityWE](https://gchristensen.github.io/ubiquitywe/)).

I think we should read through them for ideas. A bunch are wonky or niche, or wouldn't translate well to speech (Ubiquity was typing-based), but some will. We can probably skip custom searches. The command collections look interesting, as they are bundles of things deemed to small to enable individually, which might be just the right size for an intent.

**Comment by jofish** [comment]
Yeah, cbeard was really excited about that stuff and sent me that page last all hands. I think command line interface stuff is going to be really interesting for power users.

**Comment by ianb** [comment]
From the wiki list. Links were lost in my copying, but almost all links are dead. I tried to be inclusive...

> Feeling-lucky is a simple command that looks up the first result and displays it on the preview, and upon hitting enter, it executes by opening that particular web-page. 

Interesting as it has a slightly different flow than what we do.

> Link-to-feeling-lucky is a command that is similar to link-to-wikipedia: upon execution it injects a link to google's first result on the rich text-editing field. Quite handy when linking to companies websites while blogging.

Similar to #955 (which I think I thought of after reading this item)

> lazylink: Replaces the selected text with a link to its first hit in Google. 

> resurrect - try to resurrect a dead page with internet archiving services such as Internet Wayback Machine on web.archive.org or some other.

> What is being played on Radio Paradise? (rp) - Displays the artist and name of the song that Radio Paradise is playing right now.

Very specific of course, but "what is playing?" seems like a valid question that we could answer.

> get-all-links - Creates a (filtered) list of all links from webpages opened in tabs/windows 

> Turn down the lights: change the background colour of the page to dark grey 

> Table parser - convert an html table into semicolon-seperated values

> Mailinator.com http://gist.github.com/16415 Opens the mailinator inbox of the typed name. 

> Cite - create a well-formatted {{cite:web citation of the current page

This would be a simple addition to the clipboard stuff we have already.

> shorturl: Replaces the selected URL with a Rev-Canonicalized URL of less than 44 characters or else a TinyUrl.

We do try to get a canonical URL already, but a tiny fallback could also make sense. Or maybe the world has moved on...

Not a command, but a reference to https://shortexts.com/ which could be interesting functionality.

> expand-short-url Uses the LongURL service to expand URLs shortened with any shortening service (TinyURL.com, Bit.ly, etc.) 

> backtype: Starts a search of BackType, which allows you to do a search for a person's comments on blogs and other sites.

Access to a defunct service, [BackType - Wikipedia](https://en.wikipedia.org/wiki/BackType)

> Emulates the Delicious.com bookmarklet. Highlight some text on the page for notes, activate Ubiquity, enter command delicious. It will pop up a new window where you can select tags other people have used for the URL. 

> Looks up (On HowJSay.com), how to pronounce a english word correctly. gist.github.com/220600 

> NYTimes recent Headlines: autosuggest recent headlines when you are typing; and if no matching, just hit enter, you will go to NYTimes.com search page. 

> get-news: Enables you to search Google News for news titles. 

> Gmail Status Message Update your Google Talk status message in Gmail 

Status updating seems interesting generally, often nice to be able to do without switching to the service

> rtm-* - Commands to manage your Remember The Milk task lists. Add, postpone, prioritise, complete, move and view commands are available. 

> mite-* - Track your working hours: add new time entries to your mite.account or start/stop a timer. 

> summon command - look up a link representing the keywords or phrase you enter, and inserts it into the page. Good for quickly inserting links into emails, blog, blog comments, twitter, etc.

> images (shows only the images on a page) - http://kloudsolutions.com 

I've thought about slideshow views on pages...

> lorem: Allows you to copy any given number of words or paragraphs of the "Lorem Ipsum" placeholder text onto your Clipboard, useful if you want to paste it in some other application afterward. Use: lorem [num] nice [words||paragraphs] 

> open-all-bookmarks-in-tabs - opens all bookmarks filed under the given folder in new tabs. It is also possible to open bookmarks with a specific tag. 

> printwyl - opens current page in PrintWhayYouLike.com so you can create a better print out of the information you need. 

Unlike most of these, the service still exists!

> qr_code - Generates QR Code images. 

> Insert words using a keyword: insert and learn-to-insert 

I think this is like dictation, but with custom shortcuts

> mzzt.net commands: remove/replace selection, detach tab to new window, open chromeless window

**Comment by ianb** [comment]
From UbiquityWE:

> https://github.com/GChristensen/ubiquitywe/blob/master/commands/feedsub.js Subscribe to a RSS feed in Feedly

> https://github.com/GChristensen/ubiquitywe/blob/master/commands/builtin.js#L135 Closes all open tabs that have the given word in common

**Comment by ianb** [comment]
In summary: there might be some interesting things to pull out of here, but I'm a little surprised at how limited the Ubiquity commands I've found are. Tons of simple site integrations (mostly a reminder of how few of the sites from that era remain!) and strangely few general-purpose or composable commands.

**Comment by ianb** [comment]
Some items roughly inspired from this:

- #955
- #1101 and #1086 
- #1109
- #1110
- #1111
- I wanted to do something with "copy all links", but I couldn't decide which links. Just all links isn't helpful, e.g., I wouldn't want to copy the Pricing, API, Training etc links from this page.
- #1112
- #1114
- #1115
