### ISSUE TITLE
Add "find [query] in tabs" intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#961]
I experimented with this before, doing a text search across all open tabs. It seemed a bit interesting. There's no particularly obvious way to display the results though. A series of screenshots around the selected text...?

**Comment by IkkyOdufade** [comment]
Hi @ianb can I work this? What if a new tab was opened with the results or a modal?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-09).

![4](https://user-images.githubusercontent.com/54401091/78901663-55f96900-7a81-11ea-92cd-8a7d2bc29c4b.gif)
