### ISSUE TITLE
Allow followup questions

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#962]
In some cases we want to ask for followup from the user (usually "yes" or "no", but maybe "next" or some other phrase). Right now they'd have to start the intent all over.

For this ticket we'd allow an intent to specify that it would like to receive another response from the user, and that would get fed back in. If the user closes the popup then it's cancelled.

**Comment by JM-Mendez** [comment]
@ianb I'd like to work on this issue. Do you have any intents in mind? I've been working in the `intents/search.js` part of the codebase the last few days, and it might be a good place for this feature depending on your requirements.

Questions off the top of my head:
1. Does the doorhanger stay open? (I would assume yes)
2. Do we prompt the user with follow up questions? (also yes)
3. What if the user is typing, do we display buttons? (not sure)

**Comment by ianb** [comment]
@JM-Mendez Sure, you got it; this is not a very easy bug but you've done some harder bugs already.

The obvious one is to allow someone to say "next results", so that would fit with search results.

The idea is while the popup was open, and if the intent asked for it, we would keep listening. Probably we'd only listen for a fixed number of things. So you could search for something and say "next results", but you couldn't search for something and then say "open tab". So the intent would ask for more results (`context.listenForFollowup()`), and if you say something it would call some method on the intent (say, `.runFollowup(context)` where the context has a `.followupUtterance` attribute or something).

The rest of the work is in `popupController.jsx` to get that message about listening for a followup, and start the `recorder` up again. We should probably show a microphone in the popup when it's listening, but that could be in a followup, or @awallin might have thoughts. It would be the responsibility of `.runFollowup()` to actually tell the user what it does. It should probably ignore things it doesn't understand, since the user might not be paying attention to the fact that it's listening.

**Comment by awallin** [comment]
Let's try these two use cases for follow up questions.

1. Next result
2. What music providers do you support > Set default by saying provider (see #1268)

Mock ups attached showing both uses cases along with a microphone in the popup to indicate it's listening.

![follow-up](https://user-images.githubusercontent.com/428245/76590462-68947880-64aa-11ea-8e09-a9ebd1ced5b6.jpg)

**Comment by JM-Mendez** [comment]
@awallin Thanks for the mockups. They've clarified the direction I should take. A few questions:

1. As far as UX, do you think the popup should auto close after a certain time (maybe configurable)?

I haven't tested the other intents, but the popup for the search intent closes shortly after confirming a successful command. I was thinking to set it longer to about 5-10 secs, although I'd need to feel out the waiting period. I'm torn between each intent deciding its own waiting period, or defaulting to a common time for UX.

If I do keep the card open waiting for a follow up, should I add a count down timer so the user isn't surprised when it closes before saying their next command?

___
2. How to display multiple options?

The search intent allows navigating to the previous and next result. Do I vertically stack each option, or would you like to mock up how to display multiple commands? 

___
3. Do I strive for a common layout

Originally I thought to configure a common layout, but I'm leaning towards passing the available commands and descriptions as children to a React component. That way each intent can decide the best text layout according to its functional use, while maintaining the parent's layout consistent.

___
4. Can you send me the mic assets?

You can email me or send them however you want. 
john.manuel.mendez@gmail.com

**Comment by awallin** [comment]
@JM-Mendez Great questions.

1. Yes, the popup should close after a certain time. Probably a few seconds but we'll have to experiment to know the exact timing. Maybe start with a standard of 5 seconds but as we add more we may find that it needs to be configure per intent, depending on the number of results or complexity of options.

 I really like your visible countdown timer idea to indicate how much time the user has to respond. I can mockup something up for that. I'm thinking similar to how YouTube video shows the time remaining for an add.

2. I don't think we need to display both 'previous' and 'next' in the navigation case. The mockup I attached shows 'next' as a hint and I'm assuming 'previous' will be intuitive to be who use that feature.

3. @ianb can comment on the Recat component. As for design I imagine keeping intent that need to display multiple options consistent with a vertical layout of <image> <utterance>

4. Mic and arrow asset attached. Green hex color is #30E60B.

[follow-up.zip](https://github.com/mozilla/firefox-voice/files/4331537/follow-up.zip)

**Comment by JM-Mendez** [comment]
@awallin awesome, thanks. This is more than enough to get me started. 

I do believe you meant to attach a photo after

>As for design I imagine keeping intent that need to display multiple options consistent with a vertical layout of

It shows as a broken link in my email, and doesn't show up at all in the browser.

**Comment by JM-Mendez** [comment]
@awallin sorry forgot to add one question:

You said the mockup showed a hint. Does that mean the search result on the bottom shouldn't be an actual link? And if it is an actual link, then should I switch to "say previous to view" when I reach the last link?

**Comment by awallin** [comment]
By 'hint' I was referring to the black section with text that says "Say 'next' to view". Yea, I guess switching to "Say 'previous' to view" makes sense on the last link? Not sure how often that occurs since links are based on the Google search results which is practically infinite?

The broken image link might be left over from me trying to attach an SVG for the icons. You got those right?

**Comment by JM-Mendez** [comment]
Actually the way the search intent is currently implemented is by scraping the results from the page, which is usually around 6-10 depending on the engine. This means that there is no way to know the next results without the user navigating to them (each search engine displays them differently).

And yes, I have received both the mic and arrow svg assets.

**Comment by awallin** [comment]
@JM-Mendez #1311 is another possible use for follow up questions.
