### ISSUE TITLE
"Read title" intent

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#968]
This intent seems a bit weird and overly minimal, but I've wanted it a few times lately. Often the title of the page is not clear, especially when it is scrolled down. This happens most often when I'm returning to a tab that is scrolled down. That includes issue numbers in GitHub, or a comment thread where the title indicates what the comments are about.

Of course we'd need to figure out our speech generation in order to do this.

Possible phrases:

* Read title
* What is the title
* What's the name of this page
* Read page title/name

**Comment by maitrella** [comment]
Just for fun
``` javascript
this.intentRunner.registerIntent({
  name: "speak.speak",
  description: "Speaks",
  examples: ["Speak"],
  match: `
  speak
`,
  async run(context) {
    const synth = window.speechSynthesis;
    const utterThis = new SpeechSynthesisUtterance("Hello Ian Bicking");
    utterThis.lang = "en-US";
    synth.speak(utterThis);
  },
});
```
