### ISSUE TITLE
*ding* Play chime sound preference is not saved *ding*

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#97]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

### Steps to reproduce

1. CLick the toolbar icon.
1. Authorize the microphone and do a search for something.
1. Note that there is some weird ding sound when you're done.
1. Click the toolbar icon again and go to the gear icon.
1. The "Play chime sound" checkbox was deselected for me, but I still hear dings on each search.
1. Select the checkbox and go back (or close popup).
1. Click the toolbar icon again and return to the gear menu.

![](https://user-images.githubusercontent.com/557895/62986181-2f4e3a00-bdef-11e9-9321-2229b27e385d.png)

### Actual results

I always hear a ding, regardless of that setting.
Even if I select the checkbox, reopening the settings shows the checkbox as deselected.
\*ding\*

### Expected results
Be able to turn off ding.

**Comment by ianb** [comment]
This was fixed
