### ISSUE TITLE
Add voice command "Open Firefox Settings"

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#975]
Now, if you say "Open settings" it opens "Firefox Voice settings".
If you say "Open Firefox Settings" it opens webpage result -> it should open Firefox Settings

**Comment by ianb** [comment]
We'll have to work out the permissions for this. It should just open `about:preferences` but that will have to happen in `api.js`

**Comment by amandhamija98** [comment]
Hi, I would like to work on this issue, could I please be assigned

**Comment by ianb** [comment]
@amandhamija98 This one isn't ready to be implemented yet, opening settings is not as easy as it would seem and I have to talk with Firefox people to figure out the best way to do this.

**Comment by Simpcyclassy** [comment]
I believe this PR https://github.com/mozilla/firefox-voice/pull/1413 covers this intent

**Comment by Simpcyclassy** [comment]
I will be closing as it has been fixed
