### ISSUE TITLE
Add "Search NAME on addons"

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#977]
Add the command voice "Search NAME on Addons" to search the addon specified on Firefox Addons website easily.

**Comment by ianb** [comment]
Right now we're deferring to duckduckgo to setup site-specific searches, but we should also handle some ourselves.

"addons" (and "addons.mozilla.org", "extensions", "firefox extensions", "amo") should go in `serviceList.js` in `SERVICE_BANG_ALIASES` and then we'll need another list of our own search providers. E.g., addons would use `https://addons.mozilla.org/en-US/firefox/search/?q=%s`

This involves touching a few files and making some new objects, but shouldn't be too hard for a newcomer.

**Comment by sabina-rohman** [comment]
Hi, @ianb  I'm an outreachy applicant May 2020. Can I please work on this issue, if it's still open?

**Comment by SaumyaSinghal** [comment]
Hello, @ianb I'm an outreachy applicant. Can I please work on this?

**Comment by ianb** [comment]
I believe @sabina-rohman and @farhatcode both have issues assigned, so I'll assign this one to @SaumyaSinghal

**Comment by SaumyaSinghal** [comment]
Sir @ianb I only need to make changes in searchServices.toml right? Please guide me if I am wrong.

**Comment by ianb** [comment]
@SaumyaSinghal Yes, that's right

**Comment by SaumyaSinghal** [comment]
@ianb after making changes in searchServices.toml, on giving the voice command "open  NAME on add-ons" it directly opens the mozilla website and if the voice command is "Search NAME on add-ons" then it shows a Yahoo search result. Is this the desired result after fixing the issue?

**Comment by ianb** [comment]
@SaumyaSinghal No, neither seems right. I would recommend adding the phrase to `navigation.toml` as a `[[navigation.bangSearch.example]]` and using `npm run jest` to make sure it matches the way you are expecting.

It's possible that the service name doesn't match what it thinks you said.

**Comment by SaumyaSinghal** [comment]
@ianb, sir can you please tell me what is the expected result after making changes.

**Comment by SaumyaSinghal** [comment]
Sir, I have made changes in navigation.toml and now it searches the NAME of the addon on the Firefox addon website. Is this correct, please help if I am making some mistake.

**Comment by ianb** [comment]
@SaumyaSinghal If you say "search bookmarks on add-ons" or "search add-ons for bookmarks" it should take you to https://addons.mozilla.org/en-US/firefox/search/?q=bookmarks

**Comment by SaumyaSinghal** [comment]
Yes sir I am getting that result.

**Comment by ianb** [comment]
OK, then maybe it's working?

**Comment by SaumyaSinghal** [comment]
Yes sir
