### ISSUE TITLE
Able to get multiple "listening" waves if you go to settings and back

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#98]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

### Steps to reproduce
1. Click toolbar icon.
1. Click the gear/settings icon in the lower left corner.
1. Click the back button in the top left corner.
1. Click the gear/settings icon in the lower left corner.
1. Click the back button in the top left corner.

### Actual results:
line party!

![](https://user-images.githubusercontent.com/557895/62986296-bac7cb00-bdef-11e9-8a85-03707047b080.png)

### Expected results:
One wavy line per customer.

**Comment by pdehaan** [comment]
Related: #99 (where you get a `500 <unavailable>` error from the server. But what's interesting is that even though I have 3 little wavy lines, I was unable to do a voice search.

**Comment by ianb** [comment]
I'm going to move settings with #127, and that will fix this bug implicitly.
