### ISSUE TITLE
[Mobile] (Feature request) Icon background colour

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/firefox-voice#981]
To help "fit in" with the style of Fenix, Send and Lockwise, recommend changing the background of the app icon as displayed on the Android home screen from white to black.

**Comment by awallin** [comment]
@espertus Can you change the background color to #202340 to match the app icon Firefox.

**Comment by awallin** [comment]
@espertus That looks good.

**Comment by espertus** [comment]
I did not properly merge this branch before moving my files into the firefox-voice repo. I am in the process of fixing this.
