### ISSUE TITLE
[Settings] Design for keyboard shortcut

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#987]
Implement cleaned up Keyboard shortcut configuration in settings.

Changing keys should involve the following steps
1. Clicking into the input box
2. Pressing desired keys to change
3. Setting auto saved when un-focus occurs.

![settings](https://user-images.githubusercontent.com/428245/74279942-ad24cc80-4cd0-11ea-880d-02d4e6a21683.jpg)

**Comment by IkkyOdufade** [comment]
Hi @awallin . I'm an intern from Outreachy. Can I work on this?

**Comment by awallin** [comment]
@IkkyOdufade This one is not quite ready yet. I should have an updated design in a day or so.

**Comment by IkkyOdufade** [comment]
Ok.

**Comment by awallin** [comment]
Closing as this is a dup of #1224
