### ISSUE TITLE
"Got error: Error: Failed response from server: 500 <unavailable>" in /popup/popup.js:94:15

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-voice#99]
```sh
git rev-parse --short HEAD # 15bfe95
npm run once
```

Not sure this is exactly related to #98, but that was how I was able to reproduce it consistently.

### Steps to reproduce

1. Open Browser Console (Tools > Web Developer > Browser Console). You can clear any existing output if it's noisy.
1. Click toolbar icon
1. Wait for the wavy line but don't say anything.
1. Wait for ~8-10 seconds.
1. Watch Browser Console.

### Actual results

![Browser_Console](https://user-images.githubusercontent.com/557895/62986439-7c7edb80-bdf0-11e9-80f2-10f2ddb30afe.png)

https://github.com/mozilla/firefox-voice/blob/15bfe950a1f7ae957ef11c261068ec75ea488fe2/extension/popup/popup.js#L93-L96

Not sure why we'd get a 500 response from a server, but maybe we can more elegantly capture searches with no audio. I did see a "goCloud, why: Raise novoice" in the console output (via vad.js:156), so maybe we already know there was no voice search and we can fail better.

**Comment by pdehaan** [comment]
Also note that once you get that ominous `500 <unavailable>` error, you're unable to perform a search, even though the UI still says "Listening".

**Comment by ianb** [comment]
Somewhat related to #103 (which at least will keep the UI consistent, but the 500 error is another issue)

**Comment by ianb** [comment]
#161 fixes #103 and gives a generic error message. We should talk to @andrenatal about why there are (somewhat frequent) 500 errors.

**Comment by ianb** [comment]
Error messages for this case removed in #1063
