### ISSUE TITLE
Play/pause video on active page

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#997]
Saying "play" or "pause" should control the video on any active page if there is a video available.

If more than one video is available the first visible video should be played.

**Comment by ianb** [comment]
Note that this doesn't have to work on any site but YouTube (at least for now).

This change will probably go in `music.js` and will be about how we select the service.

We should probably make a followup to try to get this working on non-YouTube pages, or pages where there is a YouTube video embedded.

**Comment by danielamormocea** [comment]
Is it alright if I start working on this issue? :)

**Comment by ianb** [comment]
@danielamormocea You got it!

**Comment by danielamormocea** [comment]
I have some questions regarding this issue @ianb @awallin  . At this moment, saying pause stops every service that is audible. Should I pause only the active tab? And maybe introduce something like 'Pause all' in the toml for pausing every service? Also, the 'Play' command works, but the user should interact with the website first (otherwise there is a warning saying 'Autoplay is only allowed when approved by the user'). I'm not exactly sure, if this is the expected behavior or not.

**Comment by ianb** [comment]
@danielamormocea The autoplay issue is one I should probably look into, but it's somewhat involved to fix it. So for this issue I'd recommend not worrying about it, and we can open a followup issue. So I believe it should work _after_ the user first plays something, but on the first play it will require user interaction, or they'll have to allow autoplay on the site.

As for pausing things in the background, I'll defer to @awallin. It's possible if the current tab is pausible, then we should pause only the current tab. But if I try to think through realistic scenarios, I can't come up with many reasons to have multiple tabs playing at all, and in most cases where multiple things are playing it would be better to just pause everything so you can get rid of the nuisance.

**Comment by awallin** [comment]
Agree with @ianb. 'Pause' should apply to all active tabs. An important use case is being able to pause the music/video on the non-active tab and I don't think many people will intuitively say "Pause all" (education around what to say is always a challenge). Intuitively, users are likely to believe 'pause' will control any audio playing on any tab.

**Comment by danielamormocea** [comment]
Ok, so if I'm undersanding correctly, this issue should be closed?

**Comment by ianb** [comment]
Yes, I think so. I think there was another idea that was badly explained here about playing embedded YouTube videos, but we'll open a new ticket for that.
